/* AND THEN THERE WERE NONE - datos nivel A2 (easy retelling)
   Formato compartido por attwn-data-a2.js / -b1.js / -c1.js:
   window.ATTWN_DATA = {level, lead, CHAPTERS, READINGS, EVENTS}
   El audio se regenera con: python gen_attwn_audio.py <nivel> */
window.ATTWN_DATA = (function(){
const CHAPTERS = [
  { n:1, title:"Soldier Island",
    sum:"Eight people travel to a small island near Devon. A letter from Mr Owen invited each of them, but nobody knows him. In the house they find an old rhyme about ten soldier boys and ten china figures on the table.",
    vocab:[
      ["ISLAND","land with water all around it"],
      ["GUEST","a person invited to a house"],
      ["HOST","the person who invites the guests"],
      ["LETTER","a message you write and send to somebody"],
      ["BOAT","a small ship for short journeys on water"],
      ["SERVANT","a person who works in another person’s house"],
      ["RHYME","a short poem with sounds that repeat"],
      ["SOLDIER","a person in an army"],
      ["DINNER","the big meal in the evening"],
      ["CHINA","a fine white material for cups and figures"],
      ["HOUSE","a building where people live"],
      ["STRANGER","a person you do not know"]
    ],
    comp:[
      ["How many people travelled to Soldier Island?",["Six","Eight","Ten","Twelve"],1,"Eight guests received letters and travelled to the island."],
      ["Who took the guests to the island?",["Fred Narracott, a boatman","Mr Owen","A taxi driver","A policeman"],0,"Fred Narracott took them across the water in his boat."],
      ["Who opened the door of the house?",["Mr Owen","Vera","The servants, Mr and Mrs Rogers","Anthony Marston"],2,"Thomas Rogers and his wife Ethel worked at the house."],
      ["Where were Mr and Mrs Owen?",["In the kitchen","Not on the island yet","On the boat","In the garden"],1,"Rogers said they were going to arrive the next day."],
      ["What was on the wall of every bedroom?",["A photo","A mirror","A map","An old rhyme in a frame"],3,"Every room had the old rhyme about ten little soldier boys."],
      ["What happens in the rhyme?",["Ten soldier boys die one by one","Ten boys find gold","Ten boys go home","Ten boys sing songs"],0,"In the poem the boys die until there are none left."],
      ["What stood on the dinner table?",["Ten candles","Ten flowers","Ten china soldiers","Ten glasses"],2,"Ten small china figures stood on a glass plate."],
      ["Why did Vera come to the island?",["For a holiday","To work as a secretary","To buy the house","To see her family"],1,"A letter offered her work as a secretary."]
    ],
    tf:[
      ["The guests knew Mr Owen well.",false,"Nobody had ever met the host."],
      ["The guests went to the island by boat.",true,"Fred Narracott took them in his boat."],
      ["The house was old and broken.",false,"It was a white, modern house on top of the rock."],
      ["Mr and Mrs Rogers were servants.",true,"They opened the door and worked at the house."],
      ["There was a rhyme in every bedroom.",true,"The old rhyme hung on the wall in a frame."],
      ["There were nine china figures on the table.",false,"There were ten figures, one for each little soldier."]
    ],
    writing:[
      {task:"You are a guest. Write a postcard to a friend about your first day on Soldier Island.",
       target:"30–50 words",
       tips:["Use the past simple: I arrived, I saw.","Use two adjectives for the island and the house.","End your postcard with a short goodbye."],
       starters:["Dear Ana,","Today I arrived at…","The house is…","See you soon,"]},
      {task:"Describe the house on the island. Write about the rooms, the table and the strange rhyme.",
       target:"30–50 words",
       tips:["Use there is / there are.","Write short, clear sentences.","Add one sentence about how you feel."],
       starters:["The house is big and…","In every bedroom there is…","On the table there are…","I feel a little…"]}
    ]},
  { n:2, title:"The voice",
    sum:"After dinner, a cold voice speaks from nowhere. It accuses all ten people in the house of causing a death. The voice was only a record on a gramophone, and Rogers played it because a letter told him to.",
    vocab:[
      ["VOICE","the sound of a person speaking"],
      ["COFFEE","a hot brown drink"],
      ["RECORD","a flat disc with sound on it"],
      ["FAINT","to fall down because you suddenly feel weak"],
      ["SILENCE","no sound at all"],
      ["MACHINE","a thing with parts that does a job"],
      ["BRANDY","a strong alcoholic drink"],
      ["MUSIC","sounds that people sing or play"],
      ["DEATH","the end of a life"],
      ["ORDER","something you tell a person to do"],
      ["ACCUSE","to say that somebody did a bad thing"],
      ["AFRAID","feeling fear"]
    ],
    comp:[
      ["When did the voice speak?",["Before breakfast","During dinner","After dinner","At midnight"],2,"The guests were drinking coffee after dinner."],
      ["What did the voice say about the people?",["They stole money","They each caused a death","They told lies","They must leave the island"],1,"It said every person in the house caused a death in the past."],
      ["How many people did the voice name?",["Eight","Nine","Ten","Seven"],2,"It named the eight guests and the two servants."],
      ["Who fainted?",["Vera","Mrs Rogers","Emily Brent","The doctor"],1,"Mrs Rogers fell to the floor in a faint."],
      ["Where did the voice really come from?",["A radio","A man behind the door","The garden","A gramophone record"],3,"Lombard and Blore found a gramophone in the next room."],
      ["Who put the record on the machine?",["Rogers","Mr Owen himself","Blore","Nobody"],0,"Rogers played it because a letter told him to."],
      ["Did Rogers know what was on the record?",["Yes, he wrote it","Yes, he heard it before","No, he thought it was music","No, he cannot hear"],2,"He never heard it before and thought it was only music."],
      ["What did the doctor give Mrs Rogers?",["Water","Brandy","Coffee","Nothing"],1,"Dr Armstrong gave her some brandy to help her."]
    ],
    tf:[
      ["The voice spoke during the dinner.",false,"It spoke after dinner, when the guests were drinking coffee."],
      ["The voice accused the servants too.",true,"It named all ten people, including Rogers and his wife."],
      ["The voice came from a real person in the room.",false,"It was a recording on a gramophone record."],
      ["Rogers played the record because of a letter.",true,"His orders said: play the record after dinner."],
      ["Mrs Rogers laughed at the voice.",false,"She fainted and needed the doctor’s help."],
      ["Nobody felt safe that night.",true,"The guests were shocked and afraid."]
    ],
    writing:[
      {task:"Write a short diary note about the night of the voice. What happened? How did you feel?",
       target:"30–50 words",
       tips:["Use the past simple: the voice said…","Use feeling words: afraid, surprised, cold.","Finish with a question."],
       starters:["Tonight a strange thing happened.","After dinner, a voice…","I felt very…","Who is…?"]},
      {task:"Write the short note from Mr Owen to Rogers with his orders for the evening.",
       target:"30–50 words",
       tips:["Use the imperative: play, bring, open.","Say the exact time for each order.","Do not explain why — keep it a secret."],
       starters:["Dear Rogers,","Please serve dinner at…","After dinner, play…","Do not open…"]}
    ]},
  { n:3, title:"Accusations",
    sum:"The guests say they are innocent and talk about their host. The judge sees that the name U. N. Owen means ‘unknown’. Then young Marston drinks whisky with poison in it and dies, and one china soldier disappears.",
    vocab:[
      ["INNOCENT","not guilty of a bad action"],
      ["NAME","the word people call you by"],
      ["DETECTIVE","a person whose job is to find criminals"],
      ["UNKNOWN","not known by anybody"],
      ["WHISKY","a strong alcoholic drink"],
      ["GLASS","a container you drink from"],
      ["POISON","something that can kill you if you drink or eat it"],
      ["DEAD","not living any more"],
      ["JUDGE","the person who decides things in a court"],
      ["TRUTH","the real facts, not a lie"],
      ["DRINK","liquid that you put in your mouth"],
      ["BREATHE","to take air in and out of your body"]
    ],
    comp:[
      ["What did most guests say about the accusations?",["‘We are guilty’","‘We are innocent’","‘We did not hear the voice’","Nothing"],1,"Almost everyone said the same thing: I am innocent."],
      ["What was Blore’s false name?",["Owen","Marston","Davis","Narracott"],2,"He arrived with the name Davis, but that was not true."],
      ["What was Blore’s real job?",["A doctor","A judge","A soldier","A detective"],3,"He was a policeman before, and now he was a detective."],
      ["What does the name U. N. Owen sound like?",["Unknown","Union","Uncle","Unlucky"],0,"Judge Wargrave heard the word ‘unknown’ in the name."],
      ["What did Anthony Marston drink?",["Wine","Whisky","Coffee","Water"],1,"He put whisky in his glass and drank it fast."],
      ["Why did Marston die?",["He was shot","He fell","There was poison in his glass","He was ill"],2,"The whisky had cyanide, a very strong poison."],
      ["Who smelled the glass?",["Dr Armstrong","Blore","Vera","Rogers"],0,"The doctor smelled the glass and found the poison."],
      ["How many china soldiers were on the plate at night?",["Ten","Eight","Seven","Nine"],3,"Rogers counted them twice: only nine were left."]
    ],
    tf:[
      ["Blore’s real name was Davis.",false,"Davis was a false name; his real name was Blore."],
      ["Lombard was ashamed of his story.",false,"He smiled and told his story without shame."],
      ["The guests never met their host.",true,"Nobody knew Mr Owen; the name means ‘unknown’."],
      ["Marston died in seconds.",true,"He could not breathe and fell to the floor, dead."],
      ["The poison in the whisky was cyanide.",true,"Cyanide is the very strong poison that killed Marston."],
      ["All ten china soldiers were still on the table.",false,"One figure was gone; only nine stood there."]
    ],
    writing:[
      {task:"You are a guest. Write a short message to explain why you are innocent.",
       target:"30–50 words",
       tips:["Say who you are first.","Use the past simple to tell your story.","Use because to give a reason."],
       starters:["My name is…","The voice said that I…","But I am innocent because…","Please believe me."]},
      {task:"Write a short news text about the death of Anthony Marston.",
       target:"30–50 words",
       tips:["Say who, where and when.","Use short sentences like a newspaper.","Do not give your opinion."],
       starters:["A young man died last night.","His name was…","He drank…","The police do not know…"]}
    ]},
  { n:4, title:"Death in the night",
    sum:"In the morning, Mrs Rogers is dead in her bed. The boat never comes, so the guests cannot leave. The men search the island and the house, but they find nobody.",
    vocab:[
      ["MORNING","the first part of the day"],
      ["SLEEP","to rest with your eyes closed"],
      ["MEDICINE","something you take when you are ill"],
      ["BREAKFAST","the first meal of the day"],
      ["BOAT","a small ship that travels on water"],
      ["SEARCH","to look everywhere for something"],
      ["CAVE","a big hole in a rock"],
      ["STONE","a small piece of rock"],
      ["ROOF","the top part of a building"],
      ["FEAR","the feeling when you are afraid"],
      ["EMPTY","with nothing or nobody inside"],
      ["ALONE","without other people"]
    ],
    comp:[
      ["Who died during the night?",["Ethel Rogers","Vera","Emily Brent","Blore"],0,"Rogers found his wife dead in her bed in the morning."],
      ["How did she die?",["She fell","Too much sleeping medicine","Poison in her tea","A gun"],1,"The doctor thought she had too much sleeping medicine."],
      ["How many china figures were left at breakfast?",["Nine","Seven","Eight","Ten"],2,"Vera counted only eight figures on the plate."],
      ["What did the guests wait for?",["A plane","A letter","The police","The boat"],3,"They waited for the boat, but it never came."],
      ["What did the men do?",["They searched the island","They swam to the coast","They slept all day","They made a fire"],0,"They looked in every cave and behind every stone."],
      ["What did they find on the island?",["A stranger","A boat","Nobody","Food"],2,"There was no other person on the island."],
      ["What was in the house?",["A secret room","A hidden person","A radio","No secret room and no hidden person"],3,"They searched everywhere and found nothing strange."],
      ["What did General Macarthur say?",["‘The boat is coming’","‘Nobody will leave this island’","‘I know the killer’","‘I am hungry’"],1,"His words frightened Vera very much."]
    ],
    tf:[
      ["Ethel Rogers died in her sleep.",true,"She died quietly during the night."],
      ["The boat came in the morning as usual.",false,"The boat never came, so nobody could leave."],
      ["The island had many trees.",false,"It was only rock and grass, with no trees."],
      ["The men found a stranger in a cave.",false,"They found nobody at all."],
      ["Only the guests were on the island.",true,"The search showed there was no hidden person."],
      ["General Macarthur helped with the search.",false,"He sat alone by the sea all morning."]
    ],
    writing:[
      {task:"You cannot leave the island. Write a message for a bottle. Ask for help.",
       target:"30–50 words",
       tips:["Say where you are.","Say what the problem is.","Ask for help clearly."],
       starters:["Help us, please!","We are on…","Two people are dead and…","Please send…"]},
      {task:"Write a diary note about the search of the island. What did the men look for? What did they find?",
       target:"30–50 words",
       tips:["Use the past simple: we looked, we found.","Name two places you searched.","Say how you feel at the end."],
       starters:["Today we searched…","We looked in…","We found…","Now I am afraid because…"]}
    ]},
  { n:5, title:"A killer’s game",
    sum:"General Macarthur is found dead by the sea. Judge Wargrave tells the others a terrible fact: the killer is one of them. The deaths follow the old rhyme, and nobody trusts anybody now.",
    vocab:[
      ["KILLER","a person who kills somebody"],
      ["MURDERER","a person who kills another person on purpose"],
      ["HEAD","the top part of your body"],
      ["BODY","a dead person"],
      ["COURT","the place where a judge works"],
      ["WIND","air that moves fast"],
      ["GAME","an activity with rules that you play"],
      ["MESSAGE","words that you send to somebody"],
      ["DEATH","the end of a life"],
      ["SAFE","not in danger"],
      ["JUDGE","the person who decides things in a court"],
      ["RHYME","a short poem with sounds that repeat"]
    ],
    comp:[
      ["Where was the general found dead?",["In his bed","By the sea","In the kitchen","On the roof"],1,"He still sat by the water when the doctor found him."],
      ["How did he die?",["Somebody hit him on the head","Poison","He drowned","A gun"],0,"Somebody came behind him and hit him hard on the head."],
      ["Who spoke to the guests like in a court?",["Blore","Vera","Judge Wargrave","Lombard"],2,"The old judge asked everyone to sit down and listen."],
      ["What did the judge say?",["A stranger is hiding","The killer is one of us","The boat is coming","The game is over"],1,"There was no stranger, so the killer was in the room."],
      ["How many people were dead now?",["Two","Four","Five","Three"],3,"Marston, Mrs Rogers and the general were dead."],
      ["What did the deaths follow?",["The weather","A map","The rhyme","The clock"],2,"The deaths followed the rhyme, line by line."],
      ["What happened after every death?",["A figure disappeared from the plate","A bell rang","A letter arrived","A door opened"],0,"Somebody took the china figures away, one by one."],
      ["How did the guests feel about each other now?",["They trusted everybody","They felt safe","They were happy","Nobody trusted anybody"],3,"They locked their doors and watched each other."]
    ],
    tf:[
      ["The general died from poison.",false,"Somebody hit him hard on the head."],
      ["The killer was somebody in the house.",true,"The judge said: the killer is one of us."],
      ["A stranger was hiding on the island.",false,"The search found nobody on the island."],
      ["The deaths followed the old rhyme.",true,"Vera saw that each death matched a line of the poem."],
      ["The china figures stayed on the plate.",false,"After every death, one figure disappeared."],
      ["The guests locked their doors at night.",true,"They were afraid and did not trust anybody."]
    ],
    writing:[
      {task:"You are Judge Wargrave. Write the short speech: tell the guests the killer is one of them.",
       target:"30–50 words",
       tips:["Speak slowly and clearly: first…, then…","Use must: the killer must be…","End with a warning."],
       starters:["Please listen to me.","We searched the island and…","So the killer must be…","From now on, we must…"]},
      {task:"Who do you think the killer is? Write your idea and give one reason.",
       target:"30–50 words",
       tips:["Name one person.","Give a reason with because.","Use maybe or perhaps."],
       starters:["I think the killer is…","I think this because…","Maybe he or she…","But I am not sure."]}
    ]},
  { n:6, title:"The storm",
    sum:"A big storm cuts the island off from the world. A china figure disappears, but nobody died that day, and Lombard’s revolver is gone too. In the morning, Rogers is missing.",
    vocab:[
      ["STORM","very bad weather with wind and rain"],
      ["RAIN","water that falls from the sky"],
      ["WAVE","a line of water that moves on the sea"],
      ["GUN","a weapon that shoots"],
      ["REVOLVER","a small gun you hold in one hand"],
      ["KEY","a small metal thing that opens a lock"],
      ["KITCHEN","the room where people cook"],
      ["AWAKE","not sleeping"],
      ["PLAN","an idea about what to do"],
      ["SEVEN","the number after six"],
      ["FOOTSTEP","the sound of a foot on the floor"],
      ["SUPPER","a meal in the evening"]
    ],
    comp:[
      ["What came to the island that evening?",["A boat","A storm","A plane","The police"],1,"A big storm arrived with wind, rain and huge waves."],
      ["Why was the storm important?",["It broke the windows","It stopped the electricity","No boat could come now","It was cold"],2,"The survivors were cut off from the world."],
      ["How many china figures did Rogers count?",["Seven","Eight","Six","Nine"],0,"He counted only seven figures on the table."],
      ["Why was that strange?",["He counted badly","The plate was empty","The table was new","Nobody died that day"],3,"Somebody took a figure before the next death."],
      ["What did the survivors lock away?",["Medicines, knives and matches","Their money","Their letters","The food"],0,"They collected all the dangerous things in the house."],
      ["Who kept the keys?",["Vera and the judge","Blore and Lombard","Rogers","The doctor"],1,"The two men kept the keys of the cupboard."],
      ["What was gone from Lombard’s room?",["His revolver","His money","His shoes","His letters"],0,"Somebody stole his gun during the night."],
      ["Who was missing in the morning?",["The doctor","Vera","Blore","Rogers"],3,"The kitchen was cold and empty, and Rogers was not there."]
    ],
    tf:[
      ["A boat could still come in the storm.",false,"The sea was too wild; no boat could come."],
      ["The guests slept very well that night.",false,"They lay awake behind locked doors."],
      ["A figure disappeared, but nobody died that day.",true,"The killer was already planning the next death."],
      ["Somebody stole Lombard’s revolver.",true,"The gun was gone from his room."],
      ["Blore heard footsteps in the corridor.",true,"He heard soft footsteps in the dark house."],
      ["Rogers made tea in the morning as usual.",false,"There was no tea, and Rogers was missing."]
    ],
    writing:[
      {task:"Describe the storm on the island. What can you see and hear?",
       target:"30–50 words",
       tips:["Use the present simple or past simple.","Use sound words: scream, crash, hit.","Say how the people feel."],
       starters:["The wind is very…","The rain hits…","The sea…","Inside the house, everybody…"]},
      {task:"You are one of the survivors. Write a short note about your plan for a safe night.",
       target:"30–50 words",
       tips:["Use will for plans: I will lock…","Write two or three actions.","Say what you are afraid of."],
       starters:["Tonight I will…","First, I will lock…","I will not open…","I am afraid of…"]}
    ]},
  { n:7, title:"Six little soldiers",
    sum:"Rogers is found dead in the washhouse with an axe. Now six people are left, and they make breakfast themselves. Emily Brent talks about Beatrice Taylor and feels no guilt, then stays alone by the window.",
    vocab:[
      ["AXE","a tool for cutting wood"],
      ["WOOD","the material that comes from trees"],
      ["FIRE","the hot bright thing that burns"],
      ["LAUGH","to make happy sounds with your voice"],
      ["BREAKFAST","the first meal of the day"],
      ["MEAT","food that comes from animals"],
      ["BISCUIT","a small dry cake"],
      ["GIRL","a young woman or female child"],
      ["GUILT","the bad feeling after you do something wrong"],
      ["WINDOW","the glass part of a wall you can see through"],
      ["CHAIR","a seat for one person"],
      ["RIVER","water that moves across the land"]
    ],
    comp:[
      ["Where did they find Rogers?",["In the washhouse","In his bedroom","On the beach","In the dining room"],0,"He was in the small washhouse behind the kitchen."],
      ["What was he doing there?",["Making tea","Cutting wood for the fire","Washing clothes","Sleeping"],1,"He went there early to cut wood."],
      ["What killed him?",["A gun","Poison","An axe","A rope"],2,"Somebody hit him from behind with an axe."],
      ["How many china figures were left?",["Seven","Five","Four","Six"],3,"Only six figures stood on the plate now."],
      ["Who made breakfast now?",["The guests themselves","Mrs Rogers","A cook from the village","Nobody ate"],0,"The servants were dead, so the guests cooked."],
      ["Who was Beatrice Taylor?",["Vera’s sister","Emily Brent’s servant","A guest","A teacher"],1,"She was a young girl who worked for Miss Brent."],
      ["How did Miss Brent feel about the girl’s death?",["Very sad","Angry","Afraid","She felt no guilt"],3,"She said the girl did a bad thing, so it was not her fault."],
      ["Where did Emily Brent stay after breakfast?",["In the kitchen","In the garden","In her chair by the window","In her bedroom"],2,"She stayed alone in the dining room, by the window."]
    ],
    tf:[
      ["Rogers died inside the house.",false,"He died in the small washhouse behind the kitchen."],
      ["The killer used an axe.",true,"Rogers was cutting wood, and the axe killed him."],
      ["Vera laughed and could not stop.",true,"Lombard had to stop her."],
      ["Seven people were still alive.",false,"Only six people were alive now."],
      ["Miss Brent sent Beatrice Taylor away.",true,"The girl worked for her, and Miss Brent sent her away."],
      ["Emily Brent felt very sorry about the girl.",false,"She felt no guilt at all."]
    ],
    writing:[
      {task:"You are Blore. Write short police notes about the death of Rogers.",
       target:"30–50 words",
       tips:["Write short facts, like a list.","Say the place, the time and the weapon.","End with the name of a suspect."],
       starters:["Time: early morning.","Place:…","The weapon was…","I suspect…"]},
      {task:"Was Emily Brent right to send Beatrice away? Write your opinion.",
       target:"30–50 words",
       tips:["Start with I think.","Give one reason with because.","Write a short last sentence."],
       starters:["I think Emily Brent was…","She sent the girl away because…","In my opinion, that was…","The girl needed…"]}
    ]},
  { n:8, title:"The bee and the seaweed",
    sum:"Emily Brent dies from an injection, and a bee flies at the window. In the evening, cold seaweed frightens Vera in her dark room. When everybody runs to her, the judge is shot — they find him dressed like a judge, with a bullet hole in his forehead.",
    vocab:[
      ["BEE","a yellow and black insect that makes honey"],
      ["NEEDLE","a thin sharp metal point"],
      ["NECK","the part of the body between head and shoulders"],
      ["SEAWEED","a plant that grows in the sea"],
      ["SCREAM","a loud high cry of fear"],
      ["TRICK","something you do to fool a person"],
      ["CURTAIN","cloth that hangs in front of a window"],
      ["WIG","false hair that you wear on your head"],
      ["FOREHEAD","the part of the face above the eyes"],
      ["BULLET","the small metal thing that a gun shoots"],
      ["CEILING","the top part of a room, above your head"],
      ["MARK","a small spot or sign on something"]
    ],
    comp:[
      ["Where was Emily Brent when she died?",["In her chair","In her bed","In the garden","On the stairs"],0,"She still sat in her chair by the window."],
      ["What was on her neck?",["A cut","A small red mark","A bee","Nothing"],1,"There was a small red mark, like an insect sting."],
      ["What really killed her?",["A bee sting","Old age","An injection of poison","A fall"],2,"Somebody put poison into her neck with a needle."],
      ["Why did the killer bring a bee?",["To match the rhyme","By accident","To make honey","To scare the doctor"],0,"The killer wanted the death to look like the rhyme."],
      ["What came back to Lombard’s room?",["His money","His revolver","His keys","His coat"],1,"The gun was suddenly back, like before."],
      ["What touched Vera in her dark room?",["A hand","A rope","A curtain","Cold, wet seaweed"],3,"Seaweed hung from the ceiling and touched her neck."],
      ["Why did somebody hang the seaweed there?",["To clean it","To dry it","To frighten Vera and trick everybody","To decorate the room"],2,"The trick took everybody upstairs at the same time."],
      ["How was Judge Wargrave found?",["Dressed like a judge, shot in the forehead","Asleep in his chair","In the garden","Missing"],0,"He wore a red curtain and a wig, with a bullet hole in his forehead."]
    ],
    tf:[
      ["A bee killed Emily Brent.",false,"Somebody put poison in her neck with a needle."],
      ["They found the syringe in the grass.",true,"The killer threw it out of the window."],
      ["Five people were left after her death.",true,"The judge, the doctor, Lombard, Blore and Vera remained."],
      ["The seaweed in Vera’s room was dangerous.",false,"It was only a trick to frighten her."],
      ["The men ran upstairs when Vera screamed.",true,"They heard her scream and ran to her room."],
      ["The judge was found in his bed.",false,"He sat downstairs, dressed like a judge, with a bullet hole in his forehead."]
    ],
    writing:[
      {task:"Describe the moment when Vera enters her dark room. Make it scary.",
       target:"30–50 words",
       tips:["Use short sentences.","Use the words dark, cold and wet.","Put the scream at the end."],
       starters:["Vera opened the door.","The room was dark.","Something cold touched…","She…"]},
      {task:"You are Dr Armstrong. Write a short note about the deaths of Miss Brent and the judge.",
       target:"30–50 words",
       tips:["Write like a doctor: short and clear.","Say how each person died.","Add one thing you cannot explain."],
       starters:["Two more people are dead.","Miss Brent died from…","The judge died from…","I cannot explain…"]}
    ]},
  { n:9, title:"And now there are four",
    sum:"Four survivors watch each other all night. In the morning, Dr Armstrong is gone, and only three china soldiers stand on the plate. The three others stay outside, but Blore goes for food alone and dies under a marble clock shaped like a bear.",
    vocab:[
      ["FOUR","the number after three"],
      ["LAMP","a thing that gives light in a room"],
      ["NOISE","a sound, often loud or strange"],
      ["CORRIDOR","a long narrow space inside a building"],
      ["CLIFF","a high wall of rock next to the sea"],
      ["SUNSHINE","the light and heat of the sun"],
      ["HUNGRY","wanting to eat"],
      ["FOOD","things that people eat"],
      ["CRASH","a loud noise when something falls or breaks"],
      ["MARBLE","a hard, heavy stone"],
      ["CLOCK","a machine that shows the time"],
      ["BEAR","a big, strong wild animal"]
    ],
    comp:[
      ["How many people were alive at the start?",["Three","Five","Four","Two"],2,"Dr Armstrong, Blore, Lombard and Vera were left."],
      ["How did they spend the night?",["Together with the lamps on","In their own rooms","Outside","On the boat"],0,"They stayed together and did not go to bed."],
      ["Who was missing in the morning?",["Blore","Dr Armstrong","Vera","Lombard"],1,"His bed was empty and his coat was gone."],
      ["How many china soldiers were on the plate?",["Four","Two","One","Three"],3,"Only three figures stood on the plate now."],
      ["Where did the three survivors stay all day?",["In the kitchen","In the sitting room","Outside on the rocks","In the caves"],2,"Outside, everybody could see everybody."],
      ["Why did Blore go back to the house?",["To sleep","To find the doctor","To close the windows","To get food"],3,"He was very hungry, and the others said no."],
      ["What fell on Blore?",["A big marble clock","A tree","A stone from the roof","A window"],0,"The heavy clock fell from a window above him."],
      ["What shape did the clock have?",["A lion","A bear","A soldier","A ship"],1,"In the rhyme, a big bear hugged one little soldier."]
    ],
    tf:[
      ["The four survivors slept in their own rooms.",false,"They stayed together all night with the lamps on."],
      ["Dr Armstrong left in the night and disappeared.",true,"In the morning he was not in the house."],
      ["The survivors found Armstrong on the cliffs.",false,"They searched the house and the island but found nothing."],
      ["They felt safer outside than inside the house.",true,"Outside, everybody could see everybody."],
      ["Vera went with Blore to the house.",false,"Blore walked up alone."],
      ["Blore’s death matched the rhyme about a bear.",true,"A marble clock shaped like a bear fell on him."]
    ],
    writing:[
      {task:"You are Vera. Write a diary note about the long night and the morning.",
       target:"30–50 words",
       tips:["Use the past simple.","Say what you heard in the night.","Say how you feel now."],
       starters:["I did not sleep.","In the night I heard…","In the morning…","Now only…"]},
      {task:"Only three people are left. Write a short conversation between two of them.",
       target:"30–50 words",
       tips:["Write short questions and answers.","Use words like you, me, who.","Show that they are afraid."],
       starters:["‘Where is the doctor?’","‘I don’t know.’","‘Maybe it is you!’","‘No! It is not me.’"]}
    ]},
  { n:10, title:"A message in a bottle",
    sum:"Vera and Lombard find the doctor’s body in the sea, and Vera shoots Lombard with his own gun. In her room a rope waits for her, and she hangs herself. Weeks later, a bottle from the sea explains everything: Judge Wargrave was the killer.",
    vocab:[
      ["BOTTLE","a glass container for drinks"],
      ["CONFESSION","words that say: I did it"],
      ["POLICE","the people whose job is to stop crime"],
      ["ROPE","very thick, strong string"],
      ["HOOK","a curved piece of metal for hanging things"],
      ["POCKET","a small bag inside your clothes"],
      ["BATH","washing your whole body in hot water"],
      ["CASE","a crime that the police try to solve"],
      ["REVOLVER","a small gun you hold in one hand"],
      ["GUN","a weapon that shoots"],
      ["CHAIR","a seat for one person"],
      ["STAIRS","steps that go up inside a building"]
    ],
    comp:[
      ["What did Vera and Lombard find in the water?",["A boat","A bottle","Dr Armstrong’s body","A china soldier"],2,"The sea brought the doctor’s body back to the island."],
      ["What did Vera take from Lombard?",["His revolver","His keys","His money","His coat"],0,"She took the gun from his pocket while he bent over the body."],
      ["What did Vera do with the gun?",["She threw it into the sea","She shot Lombard","She gave it back","She hid it"],1,"She fired, and Lombard fell down dead."],
      ["What waited in Vera’s room?",["A letter","A meal","The police","A rope and a chair"],3,"A rope hung from the ceiling, with a chair under it."],
      ["How did Vera die?",["She hanged herself","She was shot","She drowned","She fell"],0,"She put the rope around her neck and kicked the chair away."],
      ["Where was the confession found?",["Under a bed","In the house","In a bottle in the sea","At the police station"],2,"A fishing boat found the bottle in the sea."],
      ["Who was the killer?",["Dr Armstrong","Lombard","Blore","Judge Wargrave"],3,"The judge confessed everything in his letter."],
      ["How did the judge trick everybody?",["He faked his death with the doctor’s help","He hid in a cave","He left the island","He wore a mask all the time"],0,"The doctor helped him look dead, and then the judge killed him too."]
    ],
    tf:[
      ["Vera shot Lombard with his own revolver.",true,"She took the gun from his pocket and fired."],
      ["Vera left the island alive.",false,"She hanged herself in her room, like the rhyme says."],
      ["The police understood the case quickly.",false,"Ten people were dead, and no killer was there."],
      ["A fishing boat found the bottle.",true,"The bottle was in the sea, with a letter inside."],
      ["Judge Wargrave wrote the confession.",true,"He explained that he was the killer."],
      ["The doctor stayed safe because he helped the judge.",false,"The doctor helped him, but the judge killed him too."]
    ],
    writing:[
      {task:"You are the killer. Write the first lines of your confession for the bottle.",
       target:"30–50 words",
       tips:["Write in the first person: I did…","Say why you did it.","Use the past simple."],
       starters:["My name is…","I brought ten people to…","I did it because…","Nobody could…"]},
      {task:"Write a short news text about the mystery of Soldier Island for a newspaper.",
       target:"30–50 words",
       tips:["Say what the police found.","Use numbers: ten people, one island.","End with the bottle and the letter."],
       starters:["Ten people died on a small island.","The police found…","Nobody could explain…","Then a fishing boat…"]}
    ]}
];

const READINGS = {
1:["It was a hot day in August. Eight people were on their way to a small island near the coast of Devon. Its name was Soldier Island. Each person had a letter. The letters invited them to stay at a big house there. But nobody knew the host, Mr Owen.",
"The guests were very different. Vera Claythorne came to work as a secretary. Philip Lombard came because a man paid him money. Emily Brent was an old, strict lady. There was also a judge, a doctor, an old general, and a policeman with a false name. Young Anthony Marston drove there in his fast car.",
"At the sea, a boatman waited for them. His name was Fred Narracott. He took the eight guests to the island in his boat. From the water they saw the island for the first time. It was a big rock with a white, modern house on top. Nobody talked much.",
"At the house, two servants opened the door. They were Thomas Rogers and his wife Ethel. Rogers said that Mr and Mrs Owen were not there yet. They were going to arrive the next day. The rooms were ready, and a good dinner waited for the guests.",
"In every bedroom there was a strange thing on the wall. It was an old rhyme for children, in a frame. It told the story of ten little soldier boys. In the rhyme, the boys die one by one. At the end of the poem, there are none left.",
"On the dinner table there was a glass plate. On it stood ten small china figures. They were little soldiers, like the boys in the rhyme. Vera counted them. Then dinner started. The food was good, but everyone asked the same question. Who was Mr Owen?"],
2:["Dinner was very good that evening. The guests ate well and drank wine. After dinner, they went to the sitting room. Rogers brought coffee for everyone. The guests talked quietly. They felt happy and relaxed. Outside, the sea was calm and dark.",
"Then a loud voice spoke. It came from nowhere. It was cold and slow, like a machine. ‘Ladies and gentlemen! Silence, please,’ it said. Everybody stopped. Nobody moved. The voice began to say their names, one by one. It knew every person in the house.",
"The voice told a terrible story about each person. It said that every one of them caused a death in the past. It accused the eight guests. It also accused Rogers and his wife. Ten names, ten deaths. Then the voice stopped, and the room was silent.",
"Suddenly there was a noise. Mrs Rogers fell to the floor in a faint. Dr Armstrong ran to help her. He gave her some brandy. Lombard and Blore ran out of the room. They wanted to find the voice. Where did it come from?",
"In the next room they found the answer. There was a gramophone behind the wall. On it there was a record. The voice was only a recording. But who made it? And why? The guests came in and looked at the machine in silence.",
"Rogers was white and afraid. He explained everything. His orders came in a letter from Mr Owen. The letter said: play the record after dinner. Rogers thought it was only music. He never heard it before. That night, nobody in the house felt safe."],
3:["Nobody went to bed. The guests stayed in the sitting room and talked. Each person answered the voice. Almost everyone said the same thing: ‘I am innocent.’ The doctor talked about bad luck. Vera said she tried to save the boy in the sea.",
"One man told the truth about his name. His real name was not Davis. It was Blore. He was a policeman before, and now he was a detective. Somebody paid him to watch the guests. Lombard smiled and told his story too, without shame.",
"Then the judge, Mr Wargrave, looked at the letters. Every invitation came from ‘U. N. Owen’. He said the name slowly. It sounded like one English word: unknown. So their host had no real name. A stranger brought them all to the island. But why?",
"Anthony Marston was young and bored. He wanted a drink. He put whisky in his glass and drank it fast. Then something terrible happened. His face changed. He could not breathe. He fell from his chair to the floor. In seconds, he was dead.",
"Dr Armstrong ran to him, but it was too late. The doctor smelled the glass carefully. There was poison in the whisky. It was cyanide, a very strong poison. Did Marston kill himself? The doctor said maybe. But nobody in the room believed that.",
"Late that night, Rogers went to the dining room. He looked at the glass plate on the table. Something was wrong. He counted the china soldiers. He counted them again. Ten little figures stood there before dinner. Now there were only nine."],
4:["In the morning, Rogers took tea to his wife’s room. He knocked, but there was no answer. Dr Armstrong came quickly. It was too late. Ethel Rogers died in her sleep during the night. The doctor thought she had too much sleeping medicine.",
"At breakfast, Vera looked at the table. She counted the china soldiers with cold hands. There were only eight. Another figure was gone. Nobody wanted to talk about it. But everyone was thinking the same thing. Two people were dead, and the figures knew it.",
"The guests waited for the boat from the village. It never came. They walked down to the sea and watched the water. They shouted and waved their arms. Nobody answered from the coast. Slowly they understood a terrible fact. They could not leave the island.",
"The men decided to search the island. Maybe a stranger was hiding there. The search was short. The island was only rock and grass. There were no trees and no empty houses. They looked in every cave and behind every stone. They found nobody.",
"Then they searched the big house. They opened every door and every cupboard. They looked under the beds and up on the roof. There was no secret room. There was no hidden person. Only the guests were on the island. The fear grew and grew.",
"Old General Macarthur did not help with the search. He sat alone by the sea all morning. He looked calm and very tired. Vera spoke to him. His answer frightened her. ‘Nobody will leave this island,’ he said. ‘This is the end.’"],
5:["At lunchtime, the general did not come to the house. Dr Armstrong went down to the sea to call him. The old man still sat by the water. But he was dead. Somebody came behind him and hit him hard on the head.",
"The men carried the body to the house. Now three people were dead. Judge Wargrave asked everyone to sit down. He spoke slowly, like in a court. ‘We searched the island,’ he said. ‘There is no stranger here. So the killer is one of us.’",
"Nobody spoke. Vera looked at the faces around her. One of these people was a murderer. But which one? The judge? The doctor? The quiet old lady? There was no way to know. Outside, the wind started to blow across the sea.",
"Vera saw something else, too. She talked about the rhyme on the bedroom walls. The deaths followed the rhyme, line by line. Marston died from his drink. Mrs Rogers did not wake up. And the third soldier in the poem stayed there for ever.",
"And there was the strange game with the china figures. After every death, one figure disappeared from the plate. Somebody took them away, one by one. It was like a message from the killer: I am here, and I am counting.",
"From that day, life in the house changed. Nobody trusted anybody. The guests locked their doors at night. They watched each other’s eyes and hands. They did not want to be alone. But together they were not safe. The killer was always in the room."],
6:["That evening, a big storm came. The wind screamed around the house. Heavy rain hit the windows. The sea was wild and white. Big waves crashed against the rocks. Now no boat could come to the island. The seven survivors were cut off from the world.",
"They ate a cold supper together. Then they sat in the sitting room and listened to the storm. Every small sound was frightening. Blore watched Lombard. Lombard watched the doctor. Vera watched them all. Nobody wanted to go upstairs first. Nobody wanted to stay alone.",
"Before bed, Rogers came in with a grey face. He counted the china soldiers on the table, he said. There were only seven figures. But nobody died that day. Somebody took a figure early. The killer was already planning the next death.",
"The survivors made a plan. They collected all the dangerous things in the house. They took the doctor’s medicines, the kitchen knives and the matches. They locked everything away. Blore and Lombard kept the keys. It was a good plan. It did not work.",
"That night, Lombard got a bad surprise. His revolver was not in his room. He searched everywhere. The gun was gone. Somebody stole it. This was terrible news. Now the killer maybe had a gun. Lombard said nothing to the others until morning.",
"It was a long, dark night. The guests lay awake behind locked doors. They listened to the wind and the rain. Blore heard soft footsteps in the corridor. In the morning, the kitchen was cold and empty. There was no tea. Rogers was not there."],
7:["They found Rogers behind the kitchen, in the small washhouse. He went there early to cut wood for the fire. Now he lay dead next to the wood. Somebody killed him from behind with an axe. He never saw the person coming.",
"Vera started to laugh. She could not stop. Lombard hit her face softly, and she was quiet again. Everyone thought about the rhyme. One soldier boy cut himself in two with an axe. In the dining room, only six china figures stood on the plate.",
"Six people were still alive: the judge, the doctor, Lombard, Blore, Vera and Miss Brent. The servants were dead, so the guests made breakfast themselves. Vera boiled water and opened some tins. It was a strange meal. They ate cold meat and biscuits in silence.",
"At the table, the talk was all about the killer. Blore did not believe the doctor’s words. Lombard said quiet people are often dangerous. The judge listened carefully and said very little. Under the polite words, everyone had one question: is it you?",
"Vera asked Emily Brent about Beatrice Taylor. The old lady answered with a cold voice. Beatrice was her servant, she said. The girl did a bad thing, so Miss Brent sent her away. Later, the girl jumped into a river and died. Miss Brent felt no guilt at all.",
"After breakfast, the others took the plates to the kitchen. Emily Brent stayed in the dining room. She said she felt a little strange. She sat very straight in her chair by the window. Her hands rested in her lap. She was alone."],
8:["The others came back from the kitchen. Emily Brent still sat in her chair. But she was dead. Her lips were blue. There was a small red mark on her neck. And at the window, a bee flew against the glass, buzzing loudly.",
"Dr Armstrong looked at the mark. A bee did not do this, he said. Somebody used a needle. Somebody put poison into her neck with an injection. Later they found the syringe in the grass outside. The killer brought the bee only for the rhyme.",
"Five people were left. They stopped playing polite games. They searched each other and every room. They locked all dangerous things in a cupboard. Then came a strange surprise. Lombard’s revolver was back in his room. It lay there like before, quiet and ready.",
"In the evening, Vera went up to her bedroom. The room was dark. She put out her hand to find the light. Then something touched her neck. It was cold and wet. It hung from the ceiling and moved on her skin. Vera screamed and screamed.",
"The men heard her scream. They ran up the stairs and turned on the light. The cold, wet thing was only seaweed from the sea. Somebody hung it there to frighten Vera. It was a trick. And the trick took everybody upstairs at the same time.",
"Then they went downstairs together. In the sitting room, Judge Wargrave sat in a high chair. He wore a red curtain like a judge’s robe. On his head was a grey wig of wool. In the middle of his forehead there was a dark bullet hole."],
9:["Now only four people were alive: Dr Armstrong, Blore, Lombard and Vera. They carried the judge’s body upstairs. Then they sat together in the sitting room. They looked at each other in silence. Each person thought the same thing: the killer is here.",
"They did not go to bed that night. They stayed together with all the lamps on. The hours passed very slowly. Vera slept a little in her chair. Blore heard a soft noise, like footsteps in the corridor. He looked out. The corridor was dark and empty.",
"In the morning, Dr Armstrong was not in the house. His bed was empty and his coat was gone. The three others searched the house and the island. They walked along the cliffs and looked into the sea. Nothing. On the plate stood only three china soldiers.",
"Vera, Lombard and Blore made a decision. The house was too dangerous. They stayed outside on the open rocks all day. There, everybody could see everybody. They sat in the sunshine and watched each other. They spoke very little. The hours went slowly by.",
"In the afternoon, Blore was very hungry. He wanted food from the house. He asked the others to come with him. They said no. Vera did not want to enter that house again. So Blore walked up alone. Vera and Lombard watched him go inside.",
"Then they heard a great crash. They ran to the house. Blore lay near the door, dead. A big marble clock fell on him from a window above. The clock had the shape of a bear. In the rhyme, a big bear hugged one little soldier."],
10:["Vera and Lombard did not go back to the house. They walked down to the sea. At the bottom of the cliff they saw something in the water. It was a body. The sea brought Dr Armstrong back. He was dead, drowned in the cold water.",
"They pulled the body out of the sea. Lombard bent over the dead doctor. In that second, Vera moved fast. She took the revolver from Lombard’s pocket. She stepped back and pointed the gun at him. He jumped at her. She fired. Lombard fell down, dead.",
"Vera was alone on the island. She felt strange and light, almost happy. It was over, she thought. She was safe now. She walked slowly up to the house. She wanted a bath, dry clothes and a long sleep. She climbed the stairs to her room.",
"Her bedroom door was open. From the hook in the ceiling hung a rope. Under the rope stood a chair. On the little table she saw one small china soldier. The last figure waited for her. The room smelled of the sea.",
"Vera was very tired. A voice inside her head spoke to her. It said: this is the end of the rhyme, and you know it. She stood on the chair. She put the rope around her neck. Then she kicked the chair away.",
"Weeks later, the police studied the case. Ten people died on the island, but no killer was there. Then a fishing boat found a bottle in the sea. Inside was a confession from Judge Wargrave. He was the killer. The doctor helped him fake his death. Then he killed the doctor too, and at the end he shot himself."]
};

const EVENTS={
1:{ev:["Eight people get letters and travel to Soldier Island.",
      "Fred Narracott takes the guests across the water in his boat.",
      "The servants say that Mr and Mrs Owen are not there.",
      "The guests find an old rhyme about ten soldier boys in their bedrooms.",
      "Vera counts ten china figures on the dinner table.",
      "The guests have dinner and ask who Mr Owen is."],
   keys:["island","letter","boat","Rogers","rhyme","china"]},
2:{ev:["After dinner the guests drink coffee in the sitting room.",
      "A cold voice speaks and says all their names.",
      "The voice accuses ten people of causing a death.",
      "Mrs Rogers falls to the floor in a faint.",
      "Lombard and Blore find a gramophone with a record.",
      "Rogers explains that a letter told him to play it."],
   keys:["coffee","voice","accused","faint","gramophone","record"]},
3:{ev:["The guests answer the voice and say they are innocent.",
      "Blore says that Davis is not his real name.",
      "The judge sees that U. N. Owen sounds like ‘unknown’.",
      "Marston drinks his whisky very fast.",
      "He falls down dead — there was poison in the glass.",
      "Rogers counts the china soldiers: only nine are left."],
   keys:["innocent","Davis","unknown","whisky","poison","nine"]},
4:{ev:["Ethel Rogers dies in her sleep during the night.",
      "Vera counts only eight china soldiers at breakfast.",
      "The guests wait for the boat, but it never comes.",
      "The men search the island and find nobody.",
      "They search the house too: there is no hidden person.",
      "General Macarthur says nobody will leave the island."],
   keys:["sleep","eight","boat","search","nobody","Macarthur"]},
5:{ev:["The general does not come to the house at lunchtime.",
      "Dr Armstrong finds him dead by the sea.",
      "Judge Wargrave says the killer is one of them.",
      "Vera sees that the deaths follow the rhyme.",
      "After every death, one china figure disappears.",
      "Nobody in the house trusts anybody now."],
   keys:["dead","killer","judge","rhyme","figure","trust"]},
6:{ev:["A big storm cuts the island off from the world.",
      "Rogers counts only seven china figures on the table.",
      "The survivors lock away the medicines, knives and matches.",
      "Lombard’s revolver disappears from his room.",
      "Blore hears footsteps in the dark corridor.",
      "In the morning, Rogers is not in the kitchen."],
   keys:["storm","seven","plan","revolver","gun","Rogers"]},
7:{ev:["The guests find Rogers dead in the washhouse.",
      "Somebody killed him from behind with an axe.",
      "Vera starts to laugh and cannot stop.",
      "The six survivors make a strange breakfast themselves.",
      "Emily Brent talks about Beatrice Taylor and feels no guilt.",
      "Miss Brent stays alone in her chair by the window."],
   keys:["axe","laugh","breakfast","Beatrice","guilt","window"]},
8:{ev:["Emily Brent is found dead with a mark on her neck.",
      "The doctor says somebody used a needle, not the bee.",
      "Lombard’s revolver comes back to his room.",
      "Cold seaweed touches Vera in her dark bedroom.",
      "The men hear her scream and run upstairs.",
      "Downstairs, the judge sits dead with a bullet hole in his forehead."],
   keys:["bee","needle","revolver","seaweed","scream","bullet"]},
9:{ev:["The four survivors stay together all night with the lamps on.",
      "In the morning, Dr Armstrong is gone.",
      "Only three china soldiers stand on the plate.",
      "The three survivors stay outside on the rocks.",
      "Blore goes back to the house alone for food.",
      "A marble clock in the shape of a bear falls on him."],
   keys:["night","Armstrong","three","outside","food","bear"]},
10:{ev:["Vera and Lombard find Dr Armstrong’s body in the water.",
      "Vera takes the revolver from Lombard’s pocket and shoots him.",
      "She walks back to the house alone.",
      "In her room she finds a rope and one china soldier.",
      "Vera puts the rope around her neck and kicks the chair away.",
      "Weeks later, a fishing boat finds the judge’s confession in a bottle."],
   keys:["Armstrong","revolver","rope","soldier","bottle","confession"]}
};

return {level:'A2', lead:'Agatha Christie · easy retelling · <b>A2 elementary</b> (≈600 headwords)',
  CHAPTERS:CHAPTERS, READINGS:READINGS, EVENTS:EVENTS};
})();
