/* AND THEN THERE WERE NONE - datos nivel B2 (upper-intermediate retelling)
   Formato compartido por attwn-data-a2.js / -b1.js / -b2.js / -c1.js:
   window.ATTWN_DATA = {level, lead, CHAPTERS, READINGS, EVENTS}
   El audio se regenera con: python gen_attwn_audio.py <nivel> */
window.ATTWN_DATA = (function(){
const CHAPTERS = [
  { n:1, title:"Soldier Island",
    sum:"Eight strangers, each tempted by a personally tailored invitation, travel to a lonely island off the Devon coast to stay with a host nobody has ever met. The butler and cook, Thomas and Ethel Rogers, explain that the Owens have been delayed. In every bedroom hangs a framed rhyme about ten little soldiers, and ten china figures stand on the dining table.",
    vocab:[
      ["INVITATION","a written or spoken request asking someone to come somewhere"],
      ["RETIRED","having stopped working, usually because of age"],
      ["EMPLOYER","the person or company that pays someone to work"],
      ["WEALTHY","having a great deal of money"],
      ["ISOLATED","far away from other places or people; cut off"],
      ["LUXURY","great comfort provided by expensive and beautiful things"],
      ["ORNAMENT","an object displayed because it is attractive, not useful"],
      ["COINCIDENCE","two things happening together by chance in a surprising way"],
      ["ANONYMOUS","from a person whose name is not known or given"],
      ["GENUINE","real and exactly what it appears to be"],
      ["SUSPICIOUS","feeling that something is wrong or someone cannot be trusted"],
      ["HESITATE","to pause before doing something because you are not sure"]
    ],
    comp:[
      ["Why does Judge Wargrave accept the invitation to Soldier Island?",["He is an old friend of the Owens","The chance to stay on the famous island outweighs his doubts","He has been sent there by the police","He wants to buy the island"],1,"He can barely remember the lady who signed the letter, but the island itself is tempting enough to silence his doubts."],
      ["What has Vera Claythorne been offered?",["A permanent teaching post","A job as a cook","Temporary work as a holiday secretary","A share in the island"],2,"She believes an employer she has never met has engaged her as a holiday secretary."],
      ["Why has Philip Lombard travelled to the island?",["He has been paid to come and stay alert in case of trouble","He is investigating the Owens","He wants a quiet holiday","He is a friend of Marston’s"],0,"He accepted a hundred guineas simply to be ready if difficulties arose, and asked no questions."],
      ["What do the guests learn from the servants when they arrive?",["The Owens are waiting upstairs","The Owens have sold the house","The Owens never existed","The Owens have been delayed and will come the next day"],3,"Rogers apologises smoothly and says his employers will join the party the following day."],
      ["What is unusual about the servants’ relationship with their employer?",["They have worked for him for many years","They dislike him","They, too, have never met him","They are secretly related to him"],2,"Like the guests, the Rogerses were engaged by letter and admit they have never seen Mr Owen."],
      ["How do most guests react to the framed rhyme in their rooms?",["They are frightened at once","They ask Rogers to remove it","They treat it as a joke and forget it","They discuss it together all evening"],2,"Most smile at their host’s odd sense of humour; only Wargrave reads the final line twice."],
      ["Why does Vera feel a shiver when she counts the china soldiers?",["The dining room is cold","The number matches the rhyme and the people in the house exactly","She has accidentally broken one","She is afraid of Rogers"],1,"Ten figures, ten verses and ten people seem too neat a coincidence to be entirely comfortable."],
      ["What does every guest privately wonder during dinner?",["Who their invisible host really is","When the boat will return","Whether the food is safe to eat","Why the house is so old-fashioned"],0,"The strangers eat and laugh together while each of them puzzles over the absent Mr Owen."]
    ],
    tf:[
      ["Every guest received exactly the same invitation.",false,"Each invitation was different, carefully designed to attract that particular person."],
      ["Fred Narracott takes the party across to the island by boat.",true,"He is waiting for them at the tiny harbour of Sticklehaven."],
      ["Anthony Marston travels down to Devon by train with the others.",false,"He arrives last of all, roaring up in an enormous sports car."],
      ["The house on the island is modern and extremely comfortable.",true,"Soft carpets, modern bathrooms and excellent wine make it pure luxury."],
      ["Judge Wargrave pays more attention to the rhyme than the other guests do.",true,"He alone reads the final line twice and wonders whether the decoration is entirely innocent."],
      ["By the end of dinner the guests know exactly who their host is.",false,"Nobody has ever met the Owens, and everyone is still wondering about them."]
    ],
    writing:[
      {task:"You are Vera Claythorne. Write an informal email to a good friend describing your journey to Soldier Island, the people you have met and one detail that puzzles you.",
       target:"100–140 words",
       tips:["Open and close like a real informal email: Hi…, Anyway, write back soon!","Organise your ideas: the journey, the house, the people, the strange detail.","Use natural B2 language: it turns out, a bit odd, you’ll never guess…"],
       starters:["Hi Lucy,","You’ll never guess where I’m writing from.","The house itself is stunning, but…","Write back soon — Vera"]},
      {task:"Write an article for a travel magazine called ‘The mystery of Soldier Island’, describing the island, the modern house and the rumours about its invisible owner.",
       target:"100–140 words",
       tips:["Hook the reader with a question or striking image in the first line.","Describe the facts first, then move on to rumour and atmosphere.","End with a sentence that leaves the reader curious."],
       starters:["Everyone in Devon is talking about it.","Seen from the mainland, the island looks tiny and harmless…","Nobody, however, has ever met the owner.","Perhaps some islands prefer to keep their secrets."]}
    ]},
  { n:2, title:"The voice",
    sum:"Over after-dinner coffee, a cold recorded voice accuses every one of the ten people in the house of having caused a death. Mrs Rogers faints from the shock, and the sound is traced to a gramophone record that Rogers played under sealed written instructions. Nobody seriously believes it is a joke any longer.",
    vocab:[
      ["ATMOSPHERE","the general feeling or mood in a place"],
      ["DELIBERATE","done on purpose, not by accident"],
      ["ACCUSATION","a statement saying that someone has done something wrong"],
      ["OPERATION","a medical procedure in which a surgeon cuts the body"],
      ["HORRIFIED","extremely shocked and frightened"],
      ["TREMBLE","to shake slightly because of fear or weakness"],
      ["GRAMOPHONE","an old machine for playing recorded sound from discs"],
      ["RECORDING","sounds that have been stored so they can be played again"],
      ["INSTRUCTIONS","written or spoken information telling you what to do"],
      ["REMORSE","a deep feeling of guilt about something you have done"],
      ["WITNESS","a person who sees an event and can describe it"],
      ["HOAX","a trick that makes people believe something false"]
    ],
    comp:[
      ["When exactly does the mysterious voice interrupt the party?",["During dinner","While the guests are having coffee after dinner","At breakfast","While everyone is asleep"],1,"The party has moved to the drawing room for coffee when the voice cuts through the room."],
      ["How many people does the voice accuse?",["The eight guests only","Only the two servants","All ten people in the house","Nobody by name"],2,"It reads out ten names, guests and servants alike, and lays a charge against each one."],
      ["What makes the accusations especially frightening?",["They are shouted angrily","They are written on the walls","They are spoken in a foreign language","They are precise, complete with names, dates and places"],3,"Each charge is detailed and exact, which suggests long and careful research by an unseen enemy."],
      ["What happens to Ethel Rogers when the voice stops?",["She runs out of the house","She attacks her husband","She starts laughing","She faints"],3,"The dreadful silence is broken by a crash as she collapses to the floor in shock."],
      ["Where was the gramophone hidden?",["In the room next door, with its horn against a hole in the wall","In the cellar","Under the dining table","In Rogers’s bedroom"],0,"Lombard and Blore trace the sound to the neighbouring room and find the machine there."],
      ["What is significant about the record’s title, ‘Swan Song’?",["It is a popular dance tune","A swan song means a final performance before death","It was Mrs Rogers’s favourite record","It refers to the seabirds on the island"],1,"The title is a grim joke: a ‘swan song’ is a person’s last act before dying."],
      ["Why did Rogers play the record?",["He was following written instructions from Mr Owen","He wanted to frighten the guests","Mrs Rogers asked him to play it","He thought the guests had requested music"],0,"His sealed orders told him to start the machine at that exact hour; he believed the record was music."],
      ["How do the guests feel about the ‘practical joke’ theory by the end of the evening?",["They find it very convincing","They think Marston invented the voice","Nobody seriously believes it any more","They are sure Rogers is joking"],2,"Any hope that the evening was an elaborate joke is quietly dying in every face."]
    ],
    tf:[
      ["The voice speaks while the guests are still sitting at the dinner table.",false,"It interrupts them later, over coffee in the drawing room."],
      ["The servants are accused as well as the guests.",true,"The Rogerses are named as the killers of a helpless former employer."],
      ["Dr Armstrong is accused of causing a death during an operation.",true,"The voice claims he operated on a patient while drunk and killed her."],
      ["Rogers admits that he knew what was on the record.",false,"He swears he thought it was music and only followed his written instructions."],
      ["The gramophone was played from inside the drawing room itself.",false,"It stood in the next room, its sound passing through a hole in the wall."],
      ["By bedtime most guests still believe the evening was a harmless joke.",false,"The joke theory is dying; the atmosphere has turned serious and fearful."]
    ],
    writing:[
      {task:"Continue the story from the moment the voice stops speaking. Write the scene through the eyes of one guest, describing the silence, the panic and your character’s secret thoughts.",
       target:"100–140 words",
       tips:["Choose one clear point of view and stay inside it.","Mix short, tense sentences with longer descriptive ones.","Show the character’s guilt or fear through small physical details."],
       starters:["For a moment nobody breathed.","The cup was still shaking in my hand.","Somebody in this house knew everything.","I forced myself to look up at the others."]},
      {task:"You are one of the guests. Write a formal letter to the police, to be posted as soon as possible, reporting the recorded accusations and the strange situation on the island.",
       target:"100–140 words",
       tips:["Use a formal opening and closing: Dear Sir or Madam… Yours faithfully.","Report events in clear chronological order, using the past simple and passive.","Keep your tone factual; avoid emotional language."],
       starters:["Dear Sir or Madam,","I am writing to report a deeply disturbing incident.","At approximately nine o’clock…","I would be grateful if officers could be sent without delay."]}
    ]},  { n:3, title:"Accusations",
    sum:"The accused defend themselves with varying degrees of honesty, and Blore admits that his name is not really Davis. Wargrave shows that the host’s name, U. N. Owen, simply spells ‘unknown’. Moments later Anthony Marston chokes to death on cyanide in his whisky, and one china soldier disappears from the table.",
    vocab:[
      ["VERSION","one person’s description of events, which may differ from others"],
      ["CONSCIENCE","the inner sense that tells you whether your actions are right or wrong"],
      ["IDENTITY","who a person really is"],
      ["DETECTIVE","a person whose job is to investigate crimes"],
      ["SIGNATURE","a person’s name written in their own characteristic way"],
      ["REGRET","a feeling of sadness about something you did or failed to do"],
      ["RECKLESS","done without thinking about the dangerous consequences"],
      ["CYANIDE","an extremely powerful poison that kills within minutes"],
      ["SUICIDE","the act of deliberately ending your own life"],
      ["JUSTIFY","to give an acceptable reason for something questionable"],
      ["MOTIVE","the hidden reason that makes someone do something"],
      ["DISTRESS","a state of extreme worry, sadness or pain"]
    ],
    comp:[
      ["How does Emily Brent respond to the accusation against her?",["She says her conscience is clear and refuses to explain anything","She cries and apologises","She blames Vera","She threatens to leave the island"],0,"She announces that her conscience is perfectly clear and will not discuss the matter further."],
      ["What is revealed about the man who called himself Davis?",["He is really Mr Owen","He is a journalist","He is William Blore, an ex-inspector working as a private detective","He is Marston’s cousin"],2,"Blore confesses his real identity and says he was hired to protect jewels that probably never existed."],
      ["What does Lombard admit about the story of the tribesmen?",["It is completely false","It is true — he abandoned them and took the food","He was never in Africa","He went back and rescued them"],1,"He admits it openly and argues that survival mattered more than fine feelings."],
      ["What does Judge Wargrave discover when he compares the letters?",["They are all signed by the same hand","They were all posted from abroad","They are forgeries written by Blore","Each is different, and the host’s name U. N. Owen simply spells ‘unknown’"],3,"Every signature is different, and the initials, said quickly, make one mocking word: unknown."],
      ["How does Marston treat the deaths of the two children he ran over?",["With deep regret","He denies driving that day","He blames the children’s parents","As pure bad luck that could happen to anyone"],3,"He shows so little regret that the room goes cold around him."],
      ["What kills Anthony Marston?",["A heart attack","A fall down the stairs","Cyanide in his whisky","Poisoned food at dinner"],2,"Armstrong catches the unmistakable smell of cyanide in the empty glass."],
      ["Why does nobody accept the suicide explanation?",["Marston left no note","Healthy young men in love with their own lives do not kill themselves at a stranger’s party","Armstrong proves the glass was switched","The whisky bottle had disappeared"],1,"The doctor suggests suicide without much conviction, and not one person in the room believes it."],
      ["What does Rogers discover when clearing up much later?",["A second gramophone","The front door standing open","That one china soldier has disappeared","A letter signed by Mr Owen"],2,"He counts the figures twice, because the first answer seems impossible: there are only nine."]
    ],
    tf:[
      ["Blore came to the island under a false name.",true,"He travelled as ‘Davis’ and only admits his real identity after the accusations."],
      ["Lombard denies the accusation against him.",false,"He admits it openly and says his own life mattered more than the tribesmen’s."],
      ["All the invitation letters carry identical signatures.",false,"Every signature is different — one of the details that alarms Wargrave."],
      ["Wargrave concludes that the guests were gathered for a hidden purpose.",true,"He says that somebody has brought them all to the island under a false name and with a plan."],
      ["Marston dies slowly, several hours after drinking.",false,"He chokes and is dead within a minute of swallowing the whisky."],
      ["After Marston’s death only nine china soldiers remain on the stand.",true,"Ten stood there at dinner; now there are nine."]
    ],
    writing:[
      {task:"You are a journalist. Write a short news article about the sudden death of a wealthy young man at a private house party on Soldier Island.",
       target:"100–140 words",
       tips:["Start with a headline in capital letters and a strong first sentence answering who, what, where, when.","Use the passive where natural: was found, is believed, has not been confirmed.","Include one short quotation from an unnamed guest."],
       starters:["TRAGEDY STRIKES ISLAND HOUSE PARTY","A promising young motorist died suddenly last night…","One guest, who asked not to be named, told us…","Police have not yet been able to reach the island."]},
      {task:"‘Lombard’s honesty is more respectable than the excuses of the others.’ Write an essay saying how far you agree with this statement.",
       target:"100–140 words",
       tips:["State your position clearly in the introduction.","Compare Lombard’s open confession with one or two other characters’ excuses.","Use linkers of contrast and conclusion: whereas, on the other hand, all things considered."],
       starters:["At first sight, Lombard’s frankness seems almost admirable.","Whereas the others hide behind excuses,…","On the other hand, honesty about a crime does not excuse it.","All things considered,…"]}
    ]},
  { n:4, title:"Death in the night",
    sum:"Ethel Rogers never wakes up: an overdose of her sleeping draught has killed her during the night. The boat from the mainland never comes, and a thorough search of the bare island proves that no stranger is hiding anywhere. General Macarthur calmly tells Vera that none of them will ever leave.",
    vocab:[
      ["OVERDOSE","an amount of a drug or medicine that is dangerously too large"],
      ["SIGNAL","a movement, light or sound used to send a message"],
      ["OPTIMISTIC","expecting good things to happen"],
      ["THOROUGH","done completely, with attention to every detail"],
      ["INVISIBLE","impossible to see"],
      ["ARCHITECT","a person who designs buildings"],
      ["CELLAR","an underground room, often used for storage"],
      ["ATTIC","a room at the top of a house, under the roof"],
      ["LOGIC","clear, step-by-step reasoning"],
      ["HOLLOW","an empty space or small valley in a surface"],
      ["ISOLATION","the state of being completely separated from others"],
      ["DREAD","a strong fear of something that is going to happen"]
    ],
    comp:[
      ["What is Dr Armstrong’s conclusion about Ethel Rogers’s death?",["Heart failure caused by old age","A massive overdose of her sleeping draught","Poison hidden in her food","Suffocation during the night"],1,"There is no mark of violence, but her sleeping draught tells its own story."],
      ["Which detail suggests her death was probably murder?",["She had been ill for years","She was found outside her room","Somebody had most likely measured out the fatal dose for her","She left a farewell note"],2,"Armstrong thinks it far more likely that someone gave her the overdose than that she took it herself."],
      ["Who finally mentions the china soldiers at breakfast?",["Vera","Blore","Wargrave","Lombard"],0,"It is Vera who says aloud that there are now only eight figures on the stand."],
      ["What do the guests try in order to contact the mainland?",["A radio message","Lighting a bonfire","Sending a message with a gull","Shouting, waving towels and flashing mirrors"],3,"They try every kind of signal, but no answer ever comes from the shore."],
      ["Why is the search of the island so quickly finished?",["The men give up early","The weather stops them","The island is bare rock with almost nowhere to hide","They only examine the beach"],2,"There are no trees, no bushes and hardly a hollow deep enough to hide a dog."],
      ["What is the terrifying logic of the empty search?",["A boat must be hidden somewhere","The killer must be one of the eight people still alive","The killer must come at night from the sea","Narracott must be the murderer"],1,"If no stranger is on the island, the danger stands somewhere among their own faces."],
      ["How does General Macarthur behave while the others search?",["He sits by the sea, strangely at peace","He directs the search parties","He locks himself in his room","He tries to swim to the mainland"],0,"He takes no part at all, watching the waves while fear spreads through the others."],
      ["What does Macarthur tell Vera?",["That he knows who the killer is","That help will arrive soon","That none of them will ever leave the island","That she should hide in the caves"],2,"He speaks gently, like a man saying goodbye, and says he has stopped being afraid of the end."]
    ],
    tf:[
      ["Ethel Rogers dies violently.",false,"There is no mark on her; she simply drifted deeper into a drugged sleep until her heart stopped."],
      ["The boat from the mainland arrives late but does arrive.",false,"It never comes at all, and by noon the guests know they are cut off."],
      ["People on the coast respond to the guests’ signals.",false,"Shouting, waving and flashing mirrors bring no answer from the shore."],
      ["The searchers find a hidden cave where someone has been living.",false,"Every cave and shadow is checked and holds nothing but gulls and wet stone."],
      ["The search of the house includes measuring the walls for secret rooms.",true,"They tap panels and measure walls from the cellar to the attic and find nothing."],
      ["General Macarthur seems terrified by the idea of dying on the island.",false,"He is strangely calm and tells Vera he has stopped being afraid."]
    ],
    writing:[
      {task:"Write the official report that the survivors agree to prepare for the police, describing the search of the island and its conclusions.",
       target:"100–140 words",
       tips:["Use headings or clear paragraphs: purpose, method, findings, conclusion.","Write impersonally: the island was searched, no trace was found.","Finish with a clear, factual conclusion."],
       starters:["Report on the search of Soldier Island","The search was carried out by three of the guests…","Particular attention was paid to the caves and the cliffs.","It must therefore be concluded that…"]},
      {task:"‘People show their true character in a crisis.’ Write an essay discussing this idea, using two characters from the story as examples.",
       target:"100–140 words",
       tips:["Introduce the statement and say broadly whether you agree.","Dedicate one short paragraph to each chosen character.","End with a balanced conclusion in your own words."],
       starters:["A crisis strips away good manners and leaves the truth.","General Macarthur, for example,…","Lombard, by contrast,…","In conclusion, danger does not change people — it reveals them."]}
    ]},  { n:5, title:"A killer’s game",
    sum:"General Macarthur is found by the sea with his skull crushed from behind. Wargrave, taking charge like a judge in court, demonstrates that the murderer must be one of the seven people left alive. Vera realises the deaths are copying the soldier rhyme verse by verse, and trust dies completely.",
    vocab:[
      ["SKULL","the bone structure of the head"],
      ["PRECAUTIONS","actions taken in advance to avoid danger"],
      ["MERCILESS","showing no pity at all"],
      ["OUTSIDER","a person who does not belong to a particular group or place"],
      ["SUSPICION","a feeling that someone may be guilty, without proof"],
      ["EXECUTIONER","a person whose job is to put condemned people to death"],
      ["PROCESSION","a line of people moving slowly and formally"],
      ["THREAT","a sign that something dangerous may happen"],
      ["VERSE","one section of a poem or song"],
      ["DEDUCTION","a conclusion reached by reasoning from facts"],
      ["RUTHLESS","willing to do anything to get what you want, without pity"],
      ["VIGILANT","watching carefully for signs of danger"]
    ],
    comp:[
      ["How is General Macarthur killed?",["He is drowned in the sea","His skull is crushed by a single blow from behind","He is shot on the cliff path","He is poisoned at lunch"],1,"Somebody came up silently behind him, struck once, and walked away unseen."],
      ["What does the manner of the attack suggest?",["The General fought hard against his attacker","The killer approached without being heard and struck only once","Several people attacked him together","His death was a simple accident"],1,"There is no sign of a struggle: one silent approach, one heavy blow."],
      ["What role does Wargrave take at the meeting?",["A judge conducting his own court once again","A frightened old man","A defence lawyer","A silent observer"],0,"He places himself in the tallest chair and the years seem to fall away from him."],
      ["What is the key point of Wargrave’s argument?",["The killer arrived by boat at night","The killer is hiding in a cave","The killer is Fred Narracott","The killer must be one of the people in the room"],3,"Since no outsider exists and no boat can approach unseen, the murderer is among them."],
      ["What pattern does Vera identify?",["The victims die in alphabetical order","Each death copies a verse of the soldier rhyme","Only the servants are being killed","Every death happens at midnight"],1,"Marston choked, Mrs Rogers overslept for ever, and the General stayed in Devon — verse by verse."],
      ["Which earlier event now fits the third verse of the rhyme?",["Marston’s choking at dinner","Mrs Rogers’s endless sleep","Macarthur staying in Devon for ever","The disappearance of the boat"],2,"The third verse promises that one soldier will stay in Devon — exactly what the General predicted for himself."],
      ["What happens to the china figures after each death?",["One quietly disappears","They are all broken","Rogers hides them for safety","They are moved to the kitchen"],0,"Someone removes a figure every time, as if keeping score."],
      ["How does life in the house change after the meeting?",["Everyone relaxes now the truth is known","The guests move out of the house","They elect a leader to protect them","Suspicion poisons everything and nobody trusts anyone"],3,"They lock their doors, watch each other’s hands and drink nothing they have not opened themselves."]
    ],
    tf:[
      ["Macarthur is found exactly where he had been sitting all morning.",true,"He is still on his seat facing the sea, but he will never watch it again."],
      ["The judge believes an outsider may still be hiding on the island.",false,"His whole argument is that the search proved no outsider exists."],
      ["Vera is the one who points out the link with the rhyme.",true,"She forces herself to say aloud that the deaths are copying the nursery rhyme."],
      ["Three people have died by the end of this chapter.",true,"Marston, Mrs Rogers and Macarthur are dead, leaving seven alive."],
      ["The guests agree to stop locking their doors in order to show trust.",false,"They do exactly the opposite: locked doors and constant watchfulness."],
      ["Wargrave delivers his conclusions in a voice full of panic.",false,"He speaks with terrible politeness — short, calm and merciless."]
    ],
    writing:[
      {task:"Wargrave asks for a written record of the facts. Write the formal report summarising the three deaths and the results of the search, ending with the logical conclusion.",
       target:"100–140 words",
       tips:["Number the deaths and give one factual sentence about each.","Keep opinions out until the final section, labelled ‘Conclusion’.","Use modal verbs of deduction: must, cannot, may."],
       starters:["Record of events on Soldier Island, day three.","Death one: Anthony Marston,…","The island and the house have been searched twice.","Conclusion: the person responsible must be…"]},
      {task:"Continue the story from the end of the meeting. Write about the first night after Wargrave’s announcement from Vera’s point of view.",
       target:"100–140 words",
       tips:["Create tension through sounds, shadows and small movements.","Use a mix of narrative tenses: past simple, past continuous, past perfect.","End your scene on a moment of doubt or fear, not a resolution."],
       starters:["Vera turned the key twice and stood listening.","Somewhere below, a floorboard sighed.","She had trusted these people only yesterday.","Towards dawn, she finally understood what frightened her most."]}
    ]},
  { n:6, title:"The storm",
    sum:"A violent storm seals the island off from the world. Rogers reports that a china soldier has vanished although nobody new has died, dangerous items are locked away, and Lombard’s revolver is stolen from his room. In the morning the stove is cold and Rogers himself is missing.",
    vocab:[
      ["FURIOUS","extremely violent or extremely angry"],
      ["VESSEL","a ship or large boat"],
      ["RATIONAL","based on clear thinking and reason"],
      ["ILLUSION","a false idea or belief; something that seems real but is not"],
      ["CONCLUSION","the judgement you reach after considering the facts"],
      ["REVOLVER","a small handgun with a rotating cylinder of bullets"],
      ["RIGID","stiff and unmoving"],
      ["MEASURES","official actions taken to achieve a purpose"],
      ["UNTHINKABLE","too shocking or unlikely even to be considered"],
      ["TENSION","nervous anxiety felt when something dangerous may happen"],
      ["DESPERATION","the feeling of having almost no hope left"],
      ["GALE","an extremely strong wind"]
    ],
    comp:[
      ["What effect does the storm have on the survivors’ situation?",["It floods the ground floor","It makes any rescue or escape impossible for days","It destroys the landing place","It cuts off the electricity"],1,"No lifeboat, fishing vessel or swimmer could survive that crossing."],
      ["Why does staying together bring no comfort?",["The drawing room is too small","They keep arguing about food","Every remark and glance now feels like a hint or an accusation","Emily Brent insists on reading aloud"],2,"Company cannot help when each person is secretly studying the others."],
      ["What alarming discovery does Rogers report?",["The front door is standing open","A window has been forced","The whisky has been poisoned","Only seven china soldiers remain, though nobody new has died"],3,"He counts the figures while laying the breakfast table and finds one missing in advance."],
      ["What does the missing figure imply?",["Rogers has simply miscounted","The murderer has already prepared the next death","A guest is collecting souvenirs","There were only seven figures from the start"],1,"Someone has collected the figure for a death that has not yet happened."],
      ["What safety measures do the survivors take?",["They lock drugs, knives and other dangerous items away, with two men holding separate keys","They all sleep in one room","They throw every weapon into the sea","They take turns guarding the kitchen"],0,"Neither key-holder can open the cupboard alone — a rational plan that proves useless."],
      ["What does Lombard discover before going to bed?",["A note pushed under his door","That his money has gone","That his loaded revolver has been stolen","That his door will not lock"],2,"He searches his room twice, but only a careful, patient thief could have found the gun."],
      ["Why is the theft of the revolver so serious?",["It was extremely valuable","Lombard cannot sleep without it","Blore will certainly be blamed","The murderer is now armed with six bullets"],3,"Whoever holds the gun can now kill quickly, silently and from a distance."],
      ["What do the survivors find when they come down in the morning?",["Breakfast laid as usual","Rogers dead in the kitchen","A cold stove, an unlaid table and no sign of Rogers","A message pinned to the door"],2,"Rogers, who has never once failed in his duties, is nowhere to be found."]
    ],
    tf:[
      ["The storm makes the sea impossible to cross.",true,"The waves rise into white, furious walls of water against the rocks."],
      ["Rogers now counts the china soldiers every evening.",true,"Checking the figures has become his nightly habit, which is how he notices the loss."],
      ["A figure disappears only after someone has died.",false,"This time a figure vanishes before any new death — the next murder is already planned."],
      ["The locked-cupboard plan makes the survivors genuinely safe.",false,"It gives them only a false feeling of safety, as the stolen revolver soon proves."],
      ["Lombard finds his revolver after searching his room twice.",false,"He turns the room upside down twice, and the gun is definitely gone."],
      ["This is the first morning Rogers has ever failed to prepare breakfast.",true,"The stove is cold and the table unlaid — something that has never happened before."]
    ],
    writing:[
      {task:"Write the story of the storm night as experienced inside the house, from the first thunder to the empty kitchen at dawn.",
       target:"100–140 words",
       tips:["Appeal to the senses: what can be heard, seen and felt in the dark house.","Use dramatic verbs: hurl, scream, pound, creep.","Let the weather outside mirror the fear inside."],
       starters:["The first gust hit the house like a fist.","Behind every locked door, someone lay listening.","Once, past two o’clock, a floorboard creaked.","Dawn came grey and dripping — and the kitchen was silent."]},
      {task:"‘In real danger, it is always better to face things in a group than alone.’ Write an essay discussing this statement, referring to the survivors’ situation.",
       target:"100–140 words",
       tips:["Present one argument for the statement and one against it.","Use the island as your main example: does the group protect anyone?","Give your own final opinion clearly in the conclusion."],
       starters:["Human beings naturally look for safety in numbers.","On the island, however, the group itself contains the danger.","Being watched is not the same as being protected.","On balance, I would argue that…"]}
    ]},  { n:7, title:"Six little soldiers",
    sum:"Rogers is found in the washhouse, killed with his own axe while chopping firewood. The six survivors prepare a strange breakfast from tins and trade open suspicions across the table. Emily Brent declares she feels no guilt over the girl Beatrice Taylor, and stays alone by the dining-room window.",
    vocab:[
      ["COMPREHEND","to fully understand something difficult"],
      ["HYSTERICAL","unable to control laughter, tears or fear"],
      ["SPINSTER","an older unmarried woman (old-fashioned word)"],
      ["GUILT","the unhappy feeling of having done something wrong"],
      ["VIRTUE","morally good behaviour; a good quality"],
      ["GIDDY","feeling slightly dizzy, as if about to lose your balance"],
      ["CRUELTY","behaviour that deliberately causes pain or suffering"],
      ["TERRIFIED","extremely frightened"],
      ["STERN","serious, strict and unsmiling"],
      ["PRAYER","words spoken to God, often silently"],
      ["DISMISS","to order someone to leave their job"],
      ["RESPECTABLE","considered socially acceptable, proper and correct"]
    ],
    comp:[
      ["Where and how is Rogers found?",["In his bed, poisoned","On the cliff path, where he had fallen","In the kitchen, stabbed","In the washhouse, struck down with his own axe"],3,"He lies beside the firewood with the axe he had been using buried in the back of his neck."],
      ["What was Rogers doing when he was attacked?",["Serving early tea","Counting the china figures","Chopping firewood for the stove","Locking the silver cupboard"],2,"He had risen early to chop sticks, as he did every morning, and his back was turned."],
      ["How does Vera react to the discovery?",["She faints on the spot","She becomes coldly practical","She bursts into wild, hysterical laughter","She runs to lock herself in her room"],2,"Her laughter goes on and on until Lombard slaps her sharply across the face."],
      ["Who stops Vera’s hysteria, and how?",["Armstrong, with an injection","Lombard, by slapping her face","Wargrave, with calm words","Blore, by shouting at her"],1,"The slap silences her, and she apologises at once."],
      ["How do the six survivors manage meals now?",["Emily Brent cooks for everyone","They refuse to eat anything","They prepare simple food themselves, from tins","Lombard shoots seabirds for the table"],2,"With both servants dead, they open tins of tongue and biscuits and fend for themselves."],
      ["Whom does Blore openly distrust at breakfast?",["Dr Armstrong","Vera","Emily Brent","Wargrave"],0,"He declares bluntly that a medical man could kill in a dozen quiet ways."],
      ["What is Emily Brent’s attitude to Beatrice Taylor’s death?",["She feels deep, hidden guilt","She cannot remember the girl at all","She blames Vera for mentioning it","She believes the girl’s death was the result of the girl’s own sin"],3,"She insists she only did her duty in dismissing the girl, and her conscience is spotless."],
      ["Why is Emily Brent left alone after breakfast?",["The others want to punish her","She feels giddy and stays to rest while the others clear away","She insists on praying alone","She has offered to guard the china figures"],1,"She says she feels slightly giddy and will sit quietly until it passes."]
    ],
    tf:[
      ["Rogers was killed while his back was turned.",true,"Somebody walked up behind him while his hands were busy with the firewood."],
      ["Vera immediately connects the death with the fourth verse of the rhyme.",true,"She says aloud what her laughter had been screaming: the fourth soldier chopped himself in halves."],
      ["The survivors still eat meals prepared by the servants.",false,"Both servants are dead; the six survivors open tins and look after themselves."],
      ["Wargrave talks more than anyone else at breakfast.",false,"He listens from behind half-closed eyes, like an old grey spider, and offers no opinion."],
      ["Emily Brent expresses regret about dismissing Beatrice Taylor.",false,"She feels no guilt whatsoever; the girl’s fate, she says, proved the depth of her sin."],
      ["Emily Brent is alive when the others leave the dining room.",true,"She sits upright by the window — but nobody in the house will ever speak with her again."]
    ],
    writing:[
      {task:"You are William Blore. Write your professional notes on the death of Thomas Rogers: time, place, weapon, opportunities and your current suspicions.",
       target:"100–140 words",
       tips:["Write like a detective: short, numbered, factual points.","Use the passive voice for findings: the body was discovered, no witnesses were present.","Finish with the names you cannot eliminate and one line of reasoning."],
       starters:["Case notes, fourth day. Subject: T. Rogers, butler.","The body was discovered at approximately 7.50 a.m.","Every survivor claims to have been alone at the time.","Persons I am unable to eliminate:"]},
      {task:"‘A clear conscience is not the same as an innocent life.’ Write an essay discussing this idea with reference to Emily Brent.",
       target:"100–140 words",
       tips:["Explain briefly what Emily Brent did and how she justifies it.","Contrast what she feels with what the reader is meant to feel.","Move from her case to a general conclusion about conscience and responsibility."],
       starters:["Emily Brent sleeps soundly, and that is precisely the problem.","In her own eyes she merely did her duty.","The rhyme’s judge, however, sees her differently.","Perhaps a conscience can be too comfortable to be trusted."]}
    ]},
  { n:8, title:"The bee and the seaweed",
    sum:"Emily Brent is found dead from an injection, with a bee left buzzing at the window as grim decoration. After a fruitless search, Lombard’s revolver mysteriously returns. That evening Vera’s scream at cold seaweed in her dark room draws the men upstairs — and below, Wargrave is found dressed as a judge with a bullet hole in his forehead.",
    vocab:[
      ["PUNCTURE","a small hole made by a sharp point"],
      ["DECORATION","something added only to make a thing look a certain way"],
      ["MOCKERY","behaviour that makes someone or something look ridiculous"],
      ["IMITATION","a copy of something real"],
      ["SCARLET","a brilliant red colour"],
      ["NIGHTMARE","a terrifying dream, or an experience that feels like one"],
      ["GRADUALLY","slowly, over a period of time"],
      ["SWOLLEN","larger than normal because of injury or illness"],
      ["DUSK","the time in the evening when the light is fading"],
      ["INJECT","to force liquid into the body through a needle"],
      ["THEATRICAL","exaggerated and dramatic, as if performed on a stage"],
      ["VULNERABLE","easy to attack or hurt; unprotected"]
    ],
    comp:[
      ["What do the survivors find when they return to the dining room?",["Emily Brent dead in her chair, with a tiny mark on her neck","Emily Brent gone from the house","Emily Brent writing a confession","The china figures smashed on the floor"],0,"She has not moved from her chair, and she will never move again."],
      ["Why does Armstrong reject the idea that a bee killed her?",["Bees cannot get into the house","She was immune to stings","The bee was found dead on the windowsill","The mark was made by a needle, not a sting"],3,"The puncture came from a needle, and a syringe is later found in the bushes below the window."],
      ["Why did the killer bring a bee at all?",["To frighten Vera","Purely as decoration, so the death would match its verse of the rhyme","Completely by accident","To distract the doctor’s attention"],1,"The insect is stage-dressing: the killer is not merely murdering his victims but staging them."],
      ["What strange thing happens to Lombard’s revolver?",["It is found in Vera’s room","It is thrown into the sea","It reappears in his drawer after being missing","It is discovered with the bullets removed"],2,"After staying missing all afternoon, it returns with quiet mockery to exactly where it had always lived."],
      ["What does the revolver’s return demonstrate?",["The killer has left the island","Blore stole it as a joke","Locks and searches mean nothing to the murderer","Lombard had simply mislaid it"],2,"Someone is showing the survivors that their precautions are useless."],
      ["What actually touched Vera’s throat in the dark?",["Wet seaweed hanging from the ceiling hook","A rope","A cold hand","The curtain blowing in the wind"],0,"The light reveals a long ribbon of damp seaweed placed there to terrify her."],
      ["What is the real purpose of the seaweed trick?",["To kill Vera silently","To draw everyone upstairs and leave one victim alone below","To remind Vera of the sea","To hide the stolen syringe"],1,"While the men race up to Vera, the judge is left alone downstairs — and dies."],
      ["How is Wargrave found?",["In his bed, apparently asleep","Hanging in the hall","In a chair, dressed like a judge, with a bullet hole in his forehead","Missing from the house entirely"],2,"A scarlet curtain serves as his robe and grey wool as his wig — a judge, judged."]
    ],
    tf:[
      ["Emily Brent dies from a natural bee sting.",false,"No bee made that wound: poison was injected with a needle."],
      ["A syringe is later found outside, beneath the window.",true,"It had been tossed into the bushes below."],
      ["The survivors search one another as well as the rooms.",true,"The last barriers of politeness collapse and everyone is searched."],
      ["Vera is physically injured in her bedroom.",false,"She is terrified but unhurt; the seaweed was placed there only to frighten her."],
      ["All four men run upstairs when Vera screams.",false,"Only three come — Wargrave stays below, and that is when he apparently dies."],
      ["After this evening, four people appear to be left alive.",true,"Vera, Lombard, Blore and Armstrong remain — with the judge seemingly dead."]
    ],
    writing:[
      {task:"Write the scene in Vera’s dark bedroom as a piece of atmospheric story-telling, from the moment she reaches for the light switch to the moment the men arrive.",
       target:"100–140 words",
       tips:["Slow time down: describe each second in detail.","Use the senses — cold, wet, darkness, the smell of the sea.","Keep the explanation back until the very end of the scene."],
       starters:["The switch was by the door; her fingers never reached it.","Something touched her throat in the darkness.","Every nightmare of the past three days poured into one second.","Then the room was full of light and shouting men."]},
      {task:"Write Dr Armstrong’s formal report on the deaths of Emily Brent and Judge Wargrave, stating the apparent cause of each and noting what cannot yet be explained.",
       target:"100–140 words",
       tips:["Use precise, clinical language and short paragraphs.","Give the apparent cause of death for each victim separately.","End with the unanswered questions a doctor would honestly record."],
       starters:["Medical report: fifth day on Soldier Island.","Miss Brent: death consistent with the injection of a poison.","Mr Justice Wargrave: a single bullet wound to the forehead.","The following points remain unexplained:"]}
    ]},  { n:9, title:"And now there are four",
    sum:"The four remaining survivors keep an open vigil all night, but by dawn Dr Armstrong has vanished and only three china soldiers remain. Blore, Lombard and Vera spend the day in the open, where nobody can approach unseen. When Blore returns to the house alone for food, a marble clock shaped like a bear crushes him.",
    vocab:[
      ["VIGIL","a period of staying awake to watch or guard"],
      ["EXHAUSTION","the state of being completely tired"],
      ["STEALTHY","quiet and secret, so as not to be noticed"],
      ["VANISH","to disappear suddenly and completely"],
      ["HORIZON","the distant line where the sky seems to meet the sea or land"],
      ["GROTESQUE","strange and unpleasant in a shocking, twisted way"],
      ["TERRACE","a flat paved area beside a house"],
      ["UNGUARDED","left without protection or supervision"],
      ["FURY","violent, uncontrolled energy or anger"],
      ["DAWN","the first light of the morning"],
      ["SURVIVOR","a person who remains alive after a dangerous event"],
      ["INSTINCT","a natural feeling that makes you act without thinking"]
    ],
    comp:[
      ["How do the four survivors spend the night?",["Each locked in a separate room","Outside on the rocks","Searching the house for clues","Together in the drawing room, keeping open watch on one another"],3,"Politeness is finished: they sit facing each other with every lamp burning."],
      ["What does Blore think he hears in the night?",["Breaking glass","The gramophone playing again","A door closing and stealthy footsteps","A boat’s engine offshore"],2,"When he forces himself to look out, the passage lies empty in the lamplight."],
      ["What is discovered at dawn?",["Armstrong has disappeared","Blore has disappeared","The revolver is missing again","A fifth body lies in the hall"],0,"His bed is empty, his door open, his coat gone — the doctor has vanished."],
      ["What detail suggests Armstrong left the house deliberately?",["His window was broken","His coat was gone from its hook","His room had been searched","He left a farewell note"],1,"A man dragged away by force does not stop to collect his coat."],
      ["Why do the three survivors decide to stay outside?",["The house has been locked against them","They are waiting for the boat","The weather is too warm for indoors","In the open, nobody can approach unseen"],3,"Indoors means hidden corners; on the open rock nobody can come within fifty metres unobserved."],
      ["Why does Blore return to the house alone?",["To fetch the revolver","To search Armstrong’s room","To get food","To signal to the mainland"],2,"By mid-afternoon hunger has become impossible to ignore, and the others refuse to go with him."],
      ["What kills Blore?",["A falling marble clock shaped like a bear","A shot from the revolver","A blow from the axe","A fall from the cliff"],0,"A great block of white marble is pushed from a window above and crushes his head."],
      ["Where did the marble bear fall from?",["The kitchen roof","The drawing-room mantelpiece","A window above the terrace — Vera’s own room","The cellar steps"],2,"The clock had stood on the window sill of Vera’s room, one floor above the terrace."]
    ],
    tf:[
      ["The survivors keep every lamp burning through the night.",true,"They light the whole drawing room and sit facing one another until dawn."],
      ["When Blore checks the corridor, he sees a figure disappearing.",false,"The passage lies empty; he never sees anyone at all."],
      ["Three china soldiers remain after Armstrong vanishes.",true,"With horrible simplicity, three figures stand where four had been."],
      ["The three survivors go indoors together for lunch.",false,"They stay on the open rock all day; only Blore goes in, alone, for food."],
      ["Vera and Lombard watch Blore enter the house.",true,"They follow his broad back with their eyes until the house swallows him."],
      ["Blore’s death does not match the nursery rhyme.",false,"The marble bear ‘hugged’ its soldier, exactly as the verse demands."]
    ],
    writing:[
      {task:"Write the story of the night vigil from Blore’s point of view, ending at the moment he discovers Armstrong’s empty room.",
       target:"100–140 words",
       tips:["Show the narrator’s professional, suspicious way of thinking.","Build the night hour by hour: small sounds, small doubts.","End on the discovery — do not explain it."],
       starters:["Twenty years in the police teach a man to stay awake.","I watched their hands, all three of them.","Past two o’clock, I heard it: a door, then footsteps.","The doctor’s bed was empty, and his coat was gone."]},
      {task:"‘There is safety in numbers.’ Write an essay saying how far the events on Soldier Island support or contradict this saying.",
       target:"100–140 words",
       tips:["Define briefly what the saying normally means.","Use at least two concrete events from the story as evidence.","Reach a clear personal conclusion in the final paragraph."],
       starters:["We are taught from childhood to stay with the group.","On Soldier Island, however, the group is precisely where the danger lives.","Blore dies the moment he leaves the others — yet staying had not saved the judge.","My own conclusion is that numbers protect us only when…"]}
    ]},
  { n:10, title:"A message in a bottle",
    sum:"Armstrong’s drowned body is returned by the tide, and Vera, certain that Lombard is the killer, shoots him with his own revolver. In her room a noose and one china soldier are waiting, and she hangs herself. Months later a bottle from the sea delivers Wargrave’s confession: he faked his death with Armstrong’s help, drowned the doctor, and finally shot himself.",
    vocab:[
      ["PREDATOR","an animal or person that hunts others"],
      ["BARREL","the metal tube of a gun that the bullet travels through"],
      ["TRIUMPH","a feeling of great satisfaction after a victory"],
      ["RELIEF","the good feeling when something unpleasant ends"],
      ["OVERWHELMING","so strong that it is impossible to resist"],
      ["NOOSE","a loop of rope that tightens when pulled, used for hanging"],
      ["INEVITABLE","certain to happen; impossible to avoid"],
      ["SEQUENCE","a series of events that follow one another in order"],
      ["MURMUR","to speak very softly and quietly"],
      ["CONFESSION","a statement admitting that you are guilty"],
      ["INCURABLE","impossible to cure"],
      ["VERDICT","the official decision about guilt at the end of a trial"]
    ],
    comp:[
      ["What do Vera and Lombard find at the tide line?",["A message in a bottle","An empty boat","Dr Armstrong’s drowned body","Blore’s coat"],2,"The sea has kept the doctor for a night and a day and then returned him."],
      ["Why does finding the body change everything between them?",["It proves Armstrong was the murderer","With Armstrong dead, each is now certain the other is the killer","It shows that the police are on their way","It means the rhyme has been broken"],1,"Each of the two survivors now knows, beyond argument, what the other is thinking."],
      ["How does Vera get the revolver?",["She slips it from Lombard’s pocket while he bends over the body","Lombard hands it to her freely","She finds it lying on the rocks","She has been hiding it all along"],0,"When Lombard straightens up, she is several paces away with the barrel level at his chest."],
      ["What does Vera feel after shooting Lombard?",["Immediate horror and regret","Nothing at all","Fear of being arrested","An overwhelming, guilty relief"],3,"She believes she has faced the murderer and survived him — it is finished."],
      ["What is waiting in Vera’s room?",["A noosed rope, a chair and one china soldier","A written confession","The murderer himself","A packed suitcase"],0,"The hook that held the seaweed now holds a rope, and a chair stands ready beneath it."],
      ["Whose voice seems to urge Vera towards the rope?",["Wargrave’s","Cyril’s","Hugo’s","Her mother’s"],2,"A voice very like Hugo’s murmurs that this is what the whole island was arranged to produce."],
      ["Why is Scotland Yard defeated by the case?",["No bodies are ever found","Ten people are dead and no killer is left alive on the island","The confession is destroyed by the sea","Narracott refuses to talk"],1,"Ten carefully arranged deaths remain, with nobody left alive who could have arranged them."],
      ["How had Wargrave managed to appear dead in Chapter 8?",["He hid in the cellar for a day","He used a wax model of himself","Armstrong helped him fake the wound, believing it was a trick to trap the killer","Rogers helped him before dying"],2,"The doctor’s innocent help made the fake bullet wound convincing — and cost him his life."]
    ],
    tf:[
      ["Lombard is shot with his own revolver.",true,"Vera takes it from his pocket and fires as he springs at her."],
      ["Vera walks calmly into the trap prepared in her room.",true,"Exhausted and half dreaming, she accepts the rope as if it were the last line of a song."],
      ["Vera hesitates and tries to escape the island before dying.",false,"She feels the ending is inevitable and does what the rhyme demands."],
      ["The confession is discovered within days of the deaths.",false,"It surfaces months later, when a fishing boat hauls the bottle up from the sea."],
      ["Wargrave was dying of an incurable illness when he planned the murders.",true,"Knowing his own death was near, he appointed himself executioner of ten unpunished killers."],
      ["Armstrong knew all along that he was helping the real murderer.",false,"He believed the faked death was a trick to catch the killer — and paid for his trust."]
    ],
    writing:[
      {task:"Write a review of ‘And Then There Were None’ for your school’s English magazine. Describe the situation and atmosphere, evaluate the story, and recommend it — without giving away the ending.",
       target:"100–140 words",
       tips:["Organise the review: hook, brief situation, strengths, recommendation.","Use evaluative B2 language: gripping, ingenious, unbearably tense.","Tease the ending without revealing it."],
       starters:["Ten strangers, one island, and no way off.","Christie builds the tension chapter by chapter.","What impressed me most was…","If you think you can guess the ending — you can’t."]},
      {task:"‘Nobody has the right to act as judge and executioner.’ Write an essay discussing this statement with reference to Wargrave’s confession.",
       target:"100–140 words",
       tips:["Present Wargrave’s own justification fairly before you judge it.","Weigh the guilt of his victims against the horror of his method.","Finish with your own reasoned verdict on private justice."],
       starters:["Wargrave saw himself as justice perfected, not as a criminal.","His victims, it is true, had all escaped the law.","Yet a court of one is no court at all.","My own verdict is that…"]}
    ]}
];
const READINGS = {
1:["On a blazing August afternoon, eight strangers were making their way towards the Devon coast, and every one of them carried an invitation to Soldier Island. In a first-class railway carriage, Mr Justice Wargrave, a retired judge with a dry, careful mind, examined his letter yet again. It was signed by a lady he could barely remember, yet the offer of a few days on the famous island was tempting enough to silence his doubts.",
"The others had equally convincing reasons for the journey. Vera Claythorne believed she had been engaged as a holiday secretary by an employer she had never met. Philip Lombard had accepted a hundred guineas to come and stay alert in case of trouble. Emily Brent trusted a signature she could not read, Dr Armstrong expected a wealthy patient, General Macarthur hoped to meet old comrades, and a heavy man calling himself Davis claimed he was simply on holiday.",
"At the tiny harbour of Sticklehaven, a boatman called Fred Narracott was waiting to take them across. As the boat cut through the calm water, Soldier Island rose ahead of them: a bare rock crowned by a low, modern white house. It was beautiful, yet strangely isolated, cut off from every sound of ordinary life. Anthony Marston arrived last of all, roaring up in an enormous sports car, and then the little party was complete.",
"At the front door they were welcomed by Thomas Rogers, the butler, and his wife Ethel, the cook. Rogers apologised smoothly: Mr and Mrs Owen had been delayed on the mainland and would join their guests the next day. Meanwhile, nothing had been forgotten. The house was pure luxury — soft carpets, modern bathrooms, excellent wine — and yet the servants admitted that they, too, had never actually met their mysterious employer.",
"Upstairs, every guest discovered the same curious ornament hanging in a neat frame above the fireplace: an old nursery rhyme about ten little soldier boys who die one by one until none are left. Most of them read it, smiled at their host’s odd sense of humour, and forgot it at once. Only Judge Wargrave read the final line twice, wondering, just for a moment, whether such a decoration was entirely innocent.",
"Down in the dining room the long table had been laid for eight, and in its centre, on a circular glass stand, stood ten small china soldiers. Vera counted them and felt an odd little shiver at the coincidence: ten figures, ten verses, ten people in the house. Then dinner was served, the conversation flowed, and the eight strangers ate and laughed together — each one privately wondering who their invisible host could possibly be."],
2:["By the end of dinner the atmosphere had grown almost cheerful. The food was superb, the wine flowed generously, and even Emily Brent unbent far enough to discuss knitting with Vera. When the party moved into the drawing room for coffee, Anthony Marston was entertaining everybody with stories about his cars. For a little while the eight guests forgot that they were strangers, and that not one of them had ever set eyes on their host.",
"Then, without the slightest warning, a voice cut through the room. It was inhuman in its coldness, and it seemed to come from the walls themselves. ‘Ladies and gentlemen! Silence, please,’ it commanded. Cups froze halfway to lips. The voice then began, slowly and precisely, to read out all ten of their names — guests and servants alike — and against each name it laid a deliberate accusation of murder, complete with names, dates and places.",
"Dr Armstrong, it declared, had operated on a patient while drunk and killed her. Vera Claythorne had let a little boy drown; Lombard had abandoned twenty-one men in the African bush; Blore’s false evidence had destroyed an innocent prisoner; Emily Brent’s harshness had driven her servant girl to suicide. Macarthur had sent his wife’s lover to certain death, Marston had run down two children, Wargrave had hanged an innocent man, and the Rogerses had let a helpless employer die.",
"When the voice finally stopped, the silence was dreadful. Then came a crash: Ethel Rogers had fainted. Dr Armstrong pushed through the horrified guests to help her, while her husband stood by, his hands beginning to tremble, unable to produce a single word. Brandy was fetched, the poor woman was carried to a sofa, and slowly the colour returned to her face. Every person in the room was silently asking the same question: who had spoken?",
"Lombard and Blore traced the sound to the room next door, where they discovered a gramophone pushed against the wall, its horn fitted neatly into a hole drilled through to the drawing room. On the turntable lay the recording that had accused them all; its label carried a bitter little joke, for the record was called ‘Swan Song’. Whoever had prepared it had planned the whole evening with remarkable care, down to the last cruel detail.",
"Rogers, grey-faced, swore that he had known nothing. His written instructions, signed by Mr Owen, had simply told him to start the machine at that exact hour; he had assumed the record was music for the guests. Armstrong gave Mrs Rogers something to help her sleep and sent her to bed. Downstairs, the guests stared at one another, and any hope that the evening was an elaborate joke was quietly dying in every face."],
3:["Sleep was out of the question. One by one, the accused gave their own version of events. Armstrong blamed bad luck for the failed operation, saying nothing about the drink. Vera, close to tears, described swimming after little Cyril and failing to reach him. Emily Brent announced that her conscience was perfectly clear and refused to explain anything at all, while General Macarthur said stiffly that the story about his wife was a wicked lie.",
"The man called Davis then made a confession of his own. His real identity was William Blore, a former police inspector who now worked as a private detective; he had been hired, by letter, to protect the jewels of Mrs Owen — jewels, he now suspected, that had never existed. Lombard laughed openly and admitted that his accusation was true: he had taken the food and left the tribesmen behind. Survival, he said, mattered more than fine feelings.",
"Judge Wargrave took charge like a man returning to his own courtroom. He collected the letters and compared them: every signature was different, every story slightly wrong, and not one guest had ever actually met the Owens. Then he pointed out the detail that chilled them all. Written quickly, the host’s name — U. N. Owen — became a single mocking word: unknown. Somebody, he concluded, had gathered them here under a false name, for a hidden purpose.",
"Anthony Marston found all this talk exhausting. He had already dismissed his own charge — two children knocked down through reckless driving — as pure bad luck, showing so little regret that the room had gone cold around him. Now, announcing that the whole affair was a splendid mystery, he poured himself a large whisky and swallowed it in one go. A second later the glass dropped from his hand, his face twisted, and he was choking.",
"Armstrong knelt beside the young man, but nothing could be done: he was dead within a minute. Bending over the fallen glass, the doctor caught the unmistakable smell of cyanide. He suggested, without much conviction, that Marston might have taken the poison himself, yet nobody in the room believed in that suicide for a moment. Healthy, wealthy young men in love with their own lives do not choose to die at a stranger’s dinner party.",
"It was Rogers who noticed the other thing, much later, when he came in to clear away. He stopped in the dining-room doorway, staring at the glass stand, and counted the little china figures under his breath. Then he counted them again, because the first answer seemed impossible. There was no mistake, however. Ten soldiers had stood there at dinner; now, gleaming quietly in the lamplight, there were only nine."],
4:["Rogers carried up his wife’s morning tea and came down the stairs a changed man. Ethel had not woken; she would never wake again. Dr Armstrong examined the body and found no mark of violence, but her sleeping draught told its own story. In his opinion she had swallowed a massive overdose — or, far more likely, somebody had measured it out for her. She had simply drifted deeper and deeper into sleep until her heart stopped.",
"Breakfast was a grim performance. The survivors passed the toast and poured the coffee, discussing the weather while carefully avoiding the only subject that mattered. It was Vera who finally said it aloud: on the glass stand in the dining room there were now only eight china soldiers. Two deaths, two missing figures. Nobody offered an innocent explanation, because nobody could think of one, and the meal ended in a watchful silence that no one dared to break.",
"All morning they waited for Fred Narracott’s boat, and the boat did not come. They stood at the landing place, staring across the strip of water at the mainland, where ordinary life continued without them. They shouted, waved towels and flashed mirrors, but no answering signal came from the shore. The village, it seemed, had been told to ignore whatever came from the island, and by noon even the most optimistic guest understood that they were cut off.",
"Lombard, Blore and Armstrong then organised a thorough search of the island. It was quickly done, for Soldier Island was little more than a bare rock in the sea: no trees, no bushes, hardly a hollow deep enough to hide a dog. They climbed down to every cave, checked every shadow under the cliffs, and found seagulls, wet stone and nothing else. If a mad killer was hiding on the island, he had made himself invisible.",
"The house came next. They measured walls, tapped panels, and opened every wardrobe and trunk from the cellar to the attic, hunting for the secret room that a modern architect had never built. The result was the same, and its logic was terrifying. There was no stranger on Soldier Island. Apart from the dead, the only human beings on that rock were the eight of them — which meant that the killer wore one of their own faces.",
"Only General Macarthur had taken no part in the search. He sat on a seat at the island’s far end, watching the waves, strangely at peace while fear spread through the others. When Vera came to fetch him, he spoke to her gently, like a man already saying goodbye. None of them would ever leave the island, he told her; this was the end, and he, for one, had stopped being afraid of it."],
5:["When lunch was ready, General Macarthur did not appear, and Armstrong walked down to the shore to fetch him. The old soldier was still sitting on his seat, facing the sea he had watched all morning — but he would never watch it again. The back of his skull had been crushed by a single heavy blow. Whoever had delivered it had come up silently behind him, struck once, and walked away unseen.",
"They carried the General’s body up to the house and laid it beside the others, and something in that slow little procession made the truth impossible to avoid any longer. Three deaths in two days could not be coincidence, accident or illness. When they gathered afterwards in the drawing room, Judge Wargrave placed himself in the tallest chair, and the years seemed to fall away from him. Once again he was a judge — and this was his court.",
"His argument was short and merciless. The island had been searched from end to end, so no outsider was hiding on it. No boat could approach without being seen. Therefore the person who had murdered three people was not some stranger prowling outside in the dark. The murderer was sitting in that very room, drinking tea and wearing an expression of innocent horror like everybody else. He advised them all, with terrible politeness, to take precautions.",
"Nobody spoke for a long moment. Outside, the wind was strengthening and the sea had begun to pound the rocks. Vera looked around the circle of familiar faces — the doctor, the detective, the adventurer, the judge, the spinster — and felt her sense of reality slipping. One of these polite, frightened people had crushed an old man’s skull only hours earlier. That knowledge turned every glance and every quiet word into a possible threat.",
"Then Vera forced herself to say what she had noticed. The deaths were copying the nursery rhyme, verse by verse. Marston had choked at dinner, like the first little soldier; Mrs Rogers had overslept for ever, like the second; and the third verse promised that one soldier would stay in Devon — exactly what the General had calmly predicted for himself. It was not madness to see the pattern, she insisted. The madness belonged to their invisible enemy.",
"And each time death visited the house, a china figure was quietly removed from the dining table, as if some bookkeeper of murder were keeping score. From that afternoon, suspicion poisoned everything. They locked their bedroom doors and drank nothing they had not opened themselves. They moved in pairs, watched each other’s hands, and lay awake behind locked doors — knowing that whichever face they trusted might be the mask of their executioner."],
6:["The storm broke over Soldier Island that evening with astonishing violence. The wind howled around the house, hurling rain against the glass, while below the cliffs the sea rose into white, furious walls of water. Any faint hope of rescue was finished for days: no lifeboat, no fishing vessel, no swimmer could survive that crossing. The island had become a prison, and the prisoners sat inside it, listening to the weather scream.",
"Supper was cold ham eaten in near silence. Afterwards the survivors stayed together in the drawing room, since being alone was unthinkable, yet company brought no comfort at all. Every remark sounded like a hint and every look like an accusation. Blore studied Lombard’s pockets; Lombard studied the doctor’s steady hands; Vera studied them all. Emily Brent read her Bible and observed, to nobody in particular, that the guilty could never hope to escape punishment.",
"Just before ten, Rogers appeared at the door with a face the colour of ash. He had been laying the breakfast table, he explained, and he had counted the china soldiers as he now did every evening. There were seven. Yet nobody had died since the General. The meaning sank in slowly and horribly: somewhere in the house, the murderer had already collected the figure for a death that had not yet happened.",
"Wargrave proposed sensible measures, and for once everyone agreed. The doctor’s case of drugs, the kitchen knives and everything else with an obvious deadly purpose was gathered up and locked in the silver cupboard, with two men keeping separate keys so that neither could open it alone. It was a rational plan, carried out with great seriousness, and it gave them all a small feeling of safety that was entirely false.",
"The illusion did not survive the night. Searching through his suitcase before bed, Philip Lombard went suddenly still: his revolver was missing. He had brought it loaded, he had kept it hidden, and only a careful, patient thief could have found it. He turned the room upside down twice and then sat on the bed in the dark, facing the obvious conclusion. Somewhere in the house, the murderer now had six bullets.",
"Nobody truly slept. They lay rigid behind locked doors while the storm gradually blew itself out, and the old house produced a hundred small, unexplainable sounds. Blore could have sworn that soft footsteps passed his door after two o’clock. When morning came, grey and dripping, the survivors gathered downstairs to a cold stove, an unlaid table and a silent kitchen. Rogers, who had never once failed in his duties, was nowhere to be found."],
7:["The search was short. Behind the kitchen, in the little washhouse, Thomas Rogers lay dead beside a pile of firewood, the axe he had been using buried in the back of his neck. He had risen early to chop sticks for the stove, as he did every morning, and somebody had walked up behind him while his back was turned. Even now, with five people dead, that quiet, practical cruelty was hard to comprehend.",
"Vera began to laugh — high, wild, hysterical laughter that went on and on until Lombard slapped her sharply across the face. She fell silent, apologised, and then said aloud what her laughter had been screaming: the fourth little soldier had chopped himself in halves, and the rhyme was working through them like a machine. Back in the dining room, six china figures stood on the glass stand. Nobody bothered to pretend surprise any more.",
"There were six of them left: the judge, the doctor, the detective, the soldier of fortune, the games teacher and the stern religious spinster. With both servants dead, they fended for themselves. Lombard and Blore fetched water, Vera opened tins of tongue and biscuits, and they sat down to the strangest breakfast of their lives — polite, hungry and terrified, passing one another plates that any of them might have poisoned.",
"The conversation circled endlessly around a single question. Blore declared bluntly that he distrusted the doctor: a medical man could kill in a dozen quiet ways. Lombard observed that respectable-looking people made the best criminals, and looked at nobody in particular. Wargrave listened to everything from behind half-closed eyes, like an old grey spider, and offered no opinion at all. Under the talk ran a current of pure fear that no logic could calm.",
"Emily Brent alone seemed untouched by the atmosphere. When Vera, needing to talk, asked about the girl Beatrice Taylor, the answer came flat and cold. Beatrice had been her servant; the girl had behaved immorally, and Miss Brent had naturally dismissed her at once. That the girl had then thrown herself into a river proved only the depth of her sin. Her mistress felt no guilt whatsoever — her own conscience, she repeated, was spotless.",
"After the meal the others carried out the plates, glad of any small task with a purpose. Emily Brent remained behind, saying she felt slightly giddy and would sit quietly until it passed. Vera glanced back once from the doorway. The old lady sat perfectly upright in her chair by the window, hands folded in her lap, lips moving as if in prayer — a picture of stern virtue that nobody in the house was ever to speak with again."],
8:["When they came back from the kitchen she was still in her chair, and she was dead. Her lips were blue, her face strangely swollen, and on the side of her neck there was a tiny puncture, like the sting of an insect. Against the window, as if arranged by a theatre director, a single bee buzzed angrily up and down the glass. Nobody needed reminding that the next verse of the rhyme mentioned a bee.",
"Armstrong needed only a minute to reject the obvious explanation. No bee on earth had made that wound: the mark had been made by a needle, and the poison it delivered was confirmed when they found a syringe tossed into the bushes beneath the window. The insect was pure decoration, brought along so that the death would obey its verse of the rhyme. The killer, they realised, was not merely murdering them — he was staging them.",
"Five now remained, and the last barriers of politeness collapsed. At Wargrave’s suggestion they searched one another, then every room, and locked away all the drugs and anything resembling a weapon. The one thing they most wanted was not found: Lombard’s revolver stayed missing all afternoon — and then, with quiet mockery, it reappeared that evening in his drawer, exactly where it had always lived. Someone was demonstrating that locks and searches meant nothing at all.",
"At dusk Vera went up alone to her room. The switch was by the door, but before her fingers could reach it, something touched her throat in the darkness — something cold, wet and soft that swung gently against her skin. Every nightmare of the past three days poured into that single second. She thought of drowned Cyril, of dead men’s hands reaching for her, and she screamed as she had never screamed in her life.",
"The others came pounding up the stairs — Lombard first with his revolver, then Blore, then Armstrong. The light revealed the horror to be a long ribbon of damp seaweed hanging from the ceiling hook, placed there to terrify her. Somebody produced brandy; Vera sat shaking on the bed, half laughing, half crying. Only gradually, as their heartbeats slowed, did the men count themselves and understand the trick. They were three — and the judge was not with them.",
"They found Mr Justice Wargrave downstairs in the drawing room, arranged in a high-backed chair like an exhibit. A scarlet bathroom curtain hung from his shoulders in imitation of a judge’s robe, and a wig of grey wool sat upon his head. In the centre of his forehead was a small, neat bullet hole. Armstrong examined him and pronounced him dead, his voice barely steady. The mock judge had been judged, and four china soldiers stood on the glass stand."],
9:["Four people were left, and none of them intended to close an eye. They gathered in the drawing room, lit every lamp, and settled down to an open, undisguised vigil, each with a chair against the wall and each facing the other three. Politeness was finished. Armstrong looked grey with exhaustion; Blore chewed an unlit pipe; Lombard smiled his wolfish smile; and Vera sat wrapped in a rug, listening to the sea breathe below the windows.",
"The night crawled past. Somewhere towards two in the morning Blore heard — or dreamed he heard — a door closing softly, and then stealthy footsteps in the corridor; but when he forced himself to look out, the passage lay empty in the lamplight. Vera dozed and woke and dozed again, haunted by the smell of the sea. When dawn finally arrived, cold and colourless, it felt to all four of them like a personal victory.",
"The victory lasted minutes. Armstrong’s bed was empty, his door open, his coat gone from its hook; the doctor had walked out into the darkness, apparently to vanish from the earth. They hunted for him along the cliffs and among the rocks with a fury born of terror, and found nothing but gulls and spray. In the dining room, with a horrible simplicity, three china soldiers stood where four had been. The rhyme had swallowed the doctor as well.",
"Blore, Lombard and Vera reasoned it out on the open rock. Indoors meant hidden corners, unlocked doors and death waiting behind panels; outside, in plain daylight, nobody could come within fifty metres of them unobserved. So they carried out rugs and stayed on the cliff top through the morning, three small figures under an enormous sky, scanning the horizon for a boat that never came — and, always, keeping watch on one another.",
"By mid-afternoon hunger had become impossible to ignore. Blore announced that he was going up to the house for food, and asked the others to come with him; Vera refused flatly to set foot inside again, and Lombard refused to leave Vera unguarded — or unwatched. So Blore went alone. They followed his broad back with their eyes until the house swallowed him, and the island returned to its silence of wind and gulls.",
"The crash reached them clearly across the rock. Racing back, they found Blore on the terrace beneath Vera’s window, his head crushed by a great block of white marble that lay beside him — a clock carved in the shape of a bear. Neither of them had ever heard anything so sudden, or seen anything so grotesque. The bear had hugged its little soldier, exactly as the verse demanded, and now there were two."],
10:["Neither of them would enter the house again, so Vera and Lombard drifted down to the rocks, keeping a careful space between themselves and saying very little. It was there, rolling gently at the tide line, that they found Dr Armstrong. The sea had kept him for a night and a day and had then returned him, as if to complete the count. Now each of the two survivors knew, beyond argument, exactly what the other was thinking.",
"As Lombard bent to drag the body clear of the water, Vera acted. Her hand slipped the revolver from his pocket, and when he straightened up she was several paces away with the barrel level at his chest. Lombard weighed his chances like the predator he had always been — and sprang. The shot met him in mid-air. He fell heavily across the dead man, and Vera stood over them both, shaking, the smoke drifting away over the water.",
"What she felt then was not horror but an overwhelming, guilty relief. It was finished; she had faced the murderer and outlived him. Light-headed with exhaustion and triumph, she climbed the path to the silent house, dreaming of hot food, a bath and a long, safe sleep, hardly noticing how naturally her feet carried her up the staircase towards her own room. The front door had been standing open, as if the house had expected her.",
"Her bedroom door was open too, and the smell of the sea was in the room. From the hook in the ceiling, where the seaweed had hung the night before, there now hung a rope, its noose tied with professional neatness, and a chair stood ready beneath it. On the bedside table, catching the last of the evening light, waited one small china soldier. Vera looked at it for a long time, without any feeling of surprise.",
"She was so tired, and the sequence felt so inevitable, like the last line of a song she had always known. A voice very like Hugo’s seemed to murmur that this was what he had wanted from her, what the whole island had been arranged to produce. She let the revolver fall to the floor, climbed onto the chair and settled the noose around her neck. Then she kicked the chair away — and the tenth little soldier was gone.",
"The puzzle defeated Scotland Yard completely: ten corpses on an island, and no killer left alive to accuse. The answer arrived months later inside a bottle hauled up by a fishing boat — a signed confession from Judge Wargrave. Dying of an incurable illness, he had appointed himself executioner of ten people whom the law could not touch, faked his own death with Armstrong’s innocent help, drowned the doctor that same night, and finally, when Vera was dead, shot himself in earnest."]
};

const EVENTS={
1:{ev:["Eight strangers travel down to Devon, each holding a personal invitation to Soldier Island.",
      "Fred Narracott ferries the party across the water to the island.",
      "Thomas and Ethel Rogers explain that the Owens have been delayed.",
      "Every guest finds the soldier rhyme framed in their bedroom.",
      "Vera counts ten china soldiers on the dining table.",
      "The guests dine together, still wondering who their host really is."],
   keys:["island","invitation","Narracott","Rogers","rhyme","china"]},
2:{ev:["After dinner the guests settle in the drawing room for coffee.",
      "A cold, inhuman voice suddenly demands silence.",
      "The voice accuses all ten people of murder, with names, dates and places.",
      "Ethel Rogers faints and is helped by Dr Armstrong.",
      "Lombard and Blore find the gramophone in the next room.",
      "Rogers explains that written instructions told him to play the record."],
   keys:["coffee","voice","accusation","fainted","gramophone","instructions"]},
3:{ev:["The guests give their own versions of the deaths they are accused of.",
      "Blore admits that Davis is a false name and that he is a private detective.",
      "Wargrave shows that U. N. Owen spells the word ‘unknown’.",
      "Marston swallows his whisky in one go and collapses.",
      "Armstrong smells cyanide in the dead man’s glass.",
      "Rogers counts the china soldiers and finds only nine."],
   keys:["letters","Davis","unknown","whisky","cyanide","nine"]},
4:{ev:["Ethel Rogers is found dead after an overdose of her sleeping draught.",
      "At breakfast Vera points out that only eight china soldiers remain.",
      "The guests signal to the mainland, but no boat ever comes.",
      "The men make a thorough search of the whole island.",
      "They conclude that no stranger is hiding anywhere on the rock.",
      "General Macarthur tells Vera that none of them will ever leave."],
   keys:["overdose","eight","boat","search","stranger","Macarthur"]},
5:{ev:["Macarthur fails to appear for lunch.",
      "Armstrong finds the General dead, his skull crushed from behind.",
      "Wargrave gathers everyone and reasons like a judge in court.",
      "He proves that the murderer must be one of the people in the room.",
      "Vera shows that the deaths are copying the nursery rhyme.",
      "Suspicion destroys the last of the trust among the survivors."],
   keys:["lunch","skull","Wargrave","murderer","rhyme","suspicion"]},
6:{ev:["A violent storm cuts the island off completely.",
      "Rogers reports that only seven china soldiers are left.",
      "The survivors lock drugs, knives and other dangerous things away.",
      "Lombard discovers that his revolver has been stolen.",
      "Blore hears footsteps in the corridor during the sleepless night.",
      "In the morning Rogers is nowhere to be found."],
   keys:["storm","seven","locked","revolver","footsteps","Rogers"]},
7:{ev:["Rogers is found in the washhouse, killed with his own axe.",
      "Vera breaks into hysterical laughter until Lombard slaps her.",
      "The six survivors make themselves a breakfast from tins.",
      "Open suspicion is traded across the breakfast table.",
      "Emily Brent insists she feels no guilt about Beatrice Taylor.",
      "Miss Brent stays behind, alone in her chair by the window."],
   keys:["axe","hysterical","breakfast","Beatrice","conscience","window"]},
8:{ev:["Emily Brent is found dead with a tiny puncture on her neck.",
      "Armstrong proves that a needle, not the bee, caused her death.",
      "The survivors search everyone and everything — and the revolver returns.",
      "Vera screams when wet seaweed touches her in the dark.",
      "Three men race upstairs and discover the trick.",
      "Wargrave is found below, dressed as a judge and shot through the forehead."],
   keys:["bee","needle","revolver","seaweed","judge","forehead"]},
9:{ev:["The four survivors keep watch together through the night.",
      "Blore hears a door and soft footsteps in the corridor.",
      "By morning Armstrong has vanished and only three figures remain.",
      "Blore, Lombard and Vera spend the day out in the open.",
      "Blore goes back to the house alone to fetch food.",
      "A marble clock shaped like a bear crushes him on the terrace."],
   keys:["night","footsteps","Armstrong","three","food","bear"]},
10:{ev:["The tide returns Dr Armstrong’s drowned body to the island.",
      "Vera slips the revolver from Lombard’s pocket and shoots him.",
      "Feeling strangely relieved, she walks back to the empty house.",
      "In her room she finds a noose, a chair and one china soldier.",
      "Vera hangs herself, completing the rhyme.",
      "Months later a bottle gives the police Wargrave’s confession."],
   keys:["tide","revolver","rope","soldier","confession","bottle"]}
};

return {level:'B2', lead:'Agatha Christie · retelling · <b>B2 upper-intermediate</b> (≈2,000 headwords)',
  CHAPTERS:CHAPTERS, READINGS:READINGS, EVENTS:EVENTS};
})();
