/* AND THEN THERE WERE NONE - datos nivel B1 (Black Cat Step Three)
   Formato compartido por attwn-data-a2.js / -b1.js / -c1.js:
   window.ATTWN_DATA = {level, lead, CHAPTERS, READINGS, EVENTS}
   El audio se regenera con: python gen_attwn_audio.py <nivel> */
window.ATTWN_DATA = (function(){
const CHAPTERS = [
  { n:1, title:"Soldier Island",
    sum:"Eight strangers travel down to Devon, each one invited to Soldier Island by a host they have never actually met. A local boatman takes them across to a beautiful modern house, where the servants, Mr and Mrs Rogers, explain that Mr and Mrs Owen have not arrived yet. In every bedroom hangs an old children’s rhyme about ten little soldiers, and on the dining table stand ten small china figures.",
    vocab:[
      ["ISLAND","a piece of land with water all around it"],
      ["GUEST","a person who is invited to a house"],
      ["HOST","the person who invites guests and receives them"],
      ["BOAT","a small vessel for travelling on water"],
      ["CLIFF","a high steep rock face beside the sea"],
      ["SERVANT","a person paid to work in someone’s house"],
      ["LUGGAGE","the bags and cases you take on a journey"],
      ["RHYME","a short poem with words that sound the same"],
      ["CHINA","fine white material used for cups and small figures"],
      ["STRANGER","a person you do not know"],
      ["SECRETARY","a person employed to write letters and organise work"],
      ["MYSTERY","something strange that you cannot explain"]
    ],
    comp:[
      ["Where is Soldier Island?",["Off the coast of Devon","Near Scotland","In the Thames","Off the coast of Wales"],0,"The island lies just off the Devon coast, near the little village of Sticklehaven."],
      ["How do the guests reach the island?",["By plane","By boat","By bridge","They swim"],1,"A local boatman, Fred Narracott, takes them across from the mainland."],
      ["Who welcomes the guests at the house?",["Mr and Mrs Owen","Mr and Mrs Rogers","Judge Wargrave","Vera Claythorne"],1,"The servants, Thomas and Ethel Rogers, receive them; the Owens have not arrived."],
      ["Why has Vera Claythorne come to the island?",["For a holiday","To work as a secretary","To buy the house","To visit her family"],1,"Vera believes she has been hired as a holiday secretary for Mrs Owen."],
      ["What has Philip Lombard been paid to do?",["Cook the meals","Come and be ready for trouble","Drive a car","Repair the house"],1,"Lombard was offered a hundred guineas simply to come and be useful if there was danger."],
      ["What name does Mr Blore use when he arrives?",["Davis","Owen","Marston","Narracott"],0,"Blore is a former policeman and travels under the false name of Davis."],
      ["What hangs framed in every bedroom?",["A map of Devon","An old rhyme about ten little soldiers","A photograph of the host","A list of rules"],1,"A framed copy of the old nursery rhyme hangs on the wall of each bedroom."],
      ["What stands on the dining-room table?",["Ten candles","Ten china soldier figures","Ten glasses","Ten letters"],1,"Ten small china soldiers are arranged in the middle of the table."]
    ],
    tf:[
      ["All the guests know their host personally.",false,"Not one of them has ever met Mr or Mrs Owen."],
      ["The guests travel to the island by boat.",true,"Fred Narracott takes them across from Sticklehaven."],
      ["Mr and Mrs Rogers are the servants of the house.",true,"Rogers is the butler and his wife is the cook."],
      ["The house on the island is old and ruined.",false,"It is a beautiful, modern and very comfortable house."],
      ["Mr Blore gives his real name when he arrives.",false,"He introduces himself as Davis."],
      ["There are ten little china figures on the dining table.",true,"They stand in a row in the middle of the table."]
    ],
    writing:[
      {task:"You are Vera Claythorne. Write a short letter to a friend describing your journey to Soldier Island and your first impressions of the house.",
       target:"50–70 words",
       tips:["Use the past simple to tell what happened.","Add two or three adjectives to describe the island and the house.","Open and close a friendly letter correctly."],
       starters:["Dear Anna,","I arrived on the island this afternoon…","The house is…","Write soon, Vera"]},
      {task:"Write the invitation letter that Mr Owen might have sent to one of the guests. Invite them to the island and give a reason.",
       target:"40–60 words",
       tips:["Use polite invitation language: I would be delighted if…","Give a date and say how they will travel.","Do not give too much information — keep it mysterious."],
       starters:["Dear Mr…,","I would be delighted if you could…","A boat will meet you at…","Yours sincerely,"]}
    ]},
  { n:2, title:"The voice",
    sum:"After an excellent dinner, the guests are relaxing with their coffee when a loud, cold voice suddenly fills the room. It calls out all ten names, one by one, and accuses every person in the house — including the two servants — of causing someone’s death. Mrs Rogers faints, and the guests discover that the voice came from a gramophone record hidden in the next room.",
    vocab:[
      ["VOICE","the sound a person makes when speaking"],
      ["ACCUSE","to say that someone has done something wrong"],
      ["MURDER","the crime of killing a person on purpose"],
      ["SILENCE","complete absence of sound"],
      ["RECORD","a flat black disc that plays recorded sound"],
      ["DINNER","the main meal of the day, eaten in the evening"],
      ["COFFEE","a hot dark drink made from roasted beans"],
      ["FAINT","to lose consciousness for a short time"],
      ["CHARGE","a formal statement that someone has broken the law"],
      ["SHOCK","a sudden strong and unpleasant surprise"],
      ["MACHINE","a device with moving parts that does a job"],
      ["BRANDY","a strong alcoholic drink made from wine"]
    ],
    comp:[
      ["When does the voice speak?",["Before dinner","After dinner, during coffee","At breakfast","In the middle of the night"],1,"The guests have just finished dinner and are drinking coffee in the sitting room."],
      ["What does the voice do?",["It welcomes the guests","It accuses each person of causing a death","It reads a poem","It asks for money"],1,"It names all ten people and charges each of them with a death."],
      ["How many people does the voice accuse?",["Eight","Nine","Ten","Six"],2,"All ten: the eight guests and the two servants."],
      ["Where does the sound really come from?",["The garden","A gramophone in the next room","The radio","A person on the stairs"],1,"Rogers had been told to play a record called ‘Swan Song’ at that exact moment."],
      ["Who had put on the record?",["Judge Wargrave","Rogers, following his instructions","Vera","Nobody"],1,"Rogers was simply obeying written orders from his employer."],
      ["What happens to Mrs Rogers?",["She runs away","She faints","She laughs","She telephones the police"],1,"She collapses on the floor and Dr Armstrong looks after her."],
      ["What does Dr Armstrong give Mrs Rogers?",["Water only","Something to help her sleep","Coffee","Nothing at all"],1,"He gives her a drink of brandy and later something to make her sleep."],
      ["How do the guests feel after the voice stops?",["Amused","Shocked and frightened","Bored","Sleepy"],1,"There is a long, terrible silence before anybody can speak."]
    ],
    tf:[
      ["The voice speaks before the guests have dinner.",false,"It speaks after dinner, while they are drinking coffee."],
      ["The voice accuses only the eight guests.",false,"It also accuses the two servants, Mr and Mrs Rogers."],
      ["The sound comes from a gramophone record.",true,"The record was hidden in the room next door."],
      ["Rogers played the record because he was told to.",true,"He had written instructions from his employer to play it at that moment."],
      ["Mrs Rogers is not affected by the accusation.",false,"She faints and has to be helped by Dr Armstrong."],
      ["Everybody laughs at the voice.",false,"Nobody laughs: the guests are shocked and afraid."]
    ],
    writing:[
      {task:"Write the short speech that the mysterious voice makes to three of the guests. Accuse each of them of causing a death.",
       target:"50–70 words",
       tips:["Use full names and a very formal, cold tone.","Repeat the same sentence pattern for each person.","Use the past simple: on such a date, you caused the death of…"],
       starters:["Ladies and gentlemen, silence please.","You are charged with…","On the 14th of…","Prisoners at the bar, have you anything to say?"]},
      {task:"You are one of the guests. Write a diary entry about the evening when you heard the voice. Describe what you heard and how you felt.",
       target:"60–80 words",
       tips:["Use the past simple and past continuous.","Include feelings: shocked, afraid, angry, confused.","Finish with a question you cannot answer."],
       starters:["Tonight something terrible happened.","While we were drinking our coffee…","I felt…","Who could…?"]}
    ]},
  { n:3, title:"Accusations",
    sum:"One after another, the guests try to explain the accusations against them. They also compare their invitations and realise that nobody has ever seen their host: the initials U. N. Owen simply mean ‘Unknown’. Then the youngest guest, Anthony Marston, drinks his whisky, chokes and falls dead — and one of the ten china soldiers has disappeared.",
    vocab:[
      ["INNOCENT","not guilty of a crime"],
      ["GUILTY","responsible for doing something wrong"],
      ["DEFEND","to speak or act in support of yourself or others"],
      ["EVIDENCE","facts that show whether something is true"],
      ["POISON","a substance that can kill you if you swallow it"],
      ["GLASS","a container you drink from"],
      ["CHOKE","to be unable to breathe because of something in the throat"],
      ["INITIAL","the first letter of a name"],
      ["UNKNOWN","not known or identified"],
      ["VICTIM","a person who is hurt or killed"],
      ["DRIVER","a person who drives a vehicle"],
      ["JUSTICE","fair treatment according to the law"]
    ],
    comp:[
      ["What do the guests do after the record has finished?",["They go to bed at once","They explain and defend themselves","They call the police","They leave the island"],1,"Each of them gives their own version of the events the voice described."],
      ["What do the initials U. N. Owen really mean?",["A famous family","‘Unknown’","United Nations","Nothing at all"],1,"Judge Wargrave notices that ‘U. N. Owen’ sounds exactly like ‘unknown’."],
      ["Who works out the meaning of the name?",["Vera","Judge Wargrave","Blore","Armstrong"],1,"The old judge is the first to see the joke hidden in the name."],
      ["How did Anthony Marston cause two deaths?",["In a fire","He ran over two people with his car","In a fight","At sea"],1,"He knocked down and killed John and Lucy Combes while driving too fast."],
      ["How does Marston feel about the accident?",["Very sorry","He calls it bad luck and blames the road","He denies it","He cries"],1,"He shows almost no regret, which shocks the others."],
      ["How does Anthony Marston die?",["He is shot","He drinks poisoned whisky and chokes","He falls from the cliff","He is hit on the head"],1,"There is cyanide in his glass and he dies within seconds."],
      ["What does Dr Armstrong find in the glass?",["Water","Cyanide","Sugar","Medicine"],1,"The doctor recognises the smell and effects of cyanide poisoning."],
      ["What has happened to the china figures?",["One has broken","One has disappeared","They have moved","Nothing"],1,"Only nine are left on the table after Marston’s death."]
    ],
    tf:[
      ["All the guests admit that they are guilty.",false,"Almost all of them say they are innocent and give an explanation."],
      ["‘U. N. Owen’ is a way of writing ‘unknown’.",true,"Judge Wargrave points this out to the others."],
      ["Anthony Marston killed two people with his car.",true,"He ran over John and Lucy Combes while driving fast."],
      ["Marston is very sorry about the accident.",false,"He speaks about it lightly, as if it were only bad luck."],
      ["Marston dies because of poison in his drink.",true,"There was cyanide in his whisky."],
      ["After Marston’s death there are still ten china figures.",false,"Only nine remain: one has vanished."]
    ],
    writing:[
      {task:"You are a newspaper reporter. Write a short news item about the death of Anthony Marston on Soldier Island.",
       target:"60–80 words",
       tips:["Begin with a short headline in capital letters.","Answer who, what, where and when in the first sentence.","Use the past simple and the passive: was found, was taken."],
       starters:["DEATH ON SOLDIER ISLAND","A young man died last night…","Guests at the house said…","The police have been informed…"]},
      {task:"Choose one guest and write the explanation they give to defend themselves against the accusation. Do you believe them? Say why.",
       target:"60–80 words",
       tips:["First give the character’s own version of events.","Then add one sentence with your own opinion.","Use linkers: however, because, in my opinion."],
       starters:["…says that…","According to him/her…","However, I think…","In my opinion,…"]}
    ]},
  { n:4, title:"Death in the night",
    sum:"In the morning Mrs Rogers does not wake up: she has died in her sleep, and now only eight china figures remain. The boat from the mainland never comes, and the guests slowly understand that they cannot leave. They search every rock and cave on the island — and find that there is absolutely nobody else there.",
    vocab:[
      ["MORNING","the early part of the day"],
      ["BREAKFAST","the first meal of the day"],
      ["ASLEEP","sleeping"],
      ["OVERDOSE","too much of a medicine or drug"],
      ["SLEEPING","resting with your eyes closed and mind at rest"],
      ["SEARCH","to look carefully for something"],
      ["CAVE","a large hole in a cliff or under the ground"],
      ["TRAPPED","unable to escape from a place"],
      ["SIGNAL","a sign or sound used to send a message"],
      ["MAINLAND","the main area of land, not the islands"],
      ["EMPTY","with nothing or nobody inside"],
      ["FEAR","the feeling you have when you are afraid"]
    ],
    comp:[
      ["What happens to Mrs Rogers?",["She leaves the island","She dies in her sleep","She is arrested","She hides"],1,"She never wakes up: she has died during the night."],
      ["What caused Mrs Rogers’s death?",["A heart attack from old age","Too much sleeping medicine","Drowning","A fall"],1,"Dr Armstrong believes she was given an overdose of a sleeping draught."],
      ["How many china figures are left now?",["Nine","Eight","Seven","Ten"],1,"Another figure has gone: only eight remain."],
      ["Why does nobody come from the mainland?",["The boat has broken down","No boat comes at all","The boatman is ill","There is fog"],1,"Fred Narracott simply does not appear, and the guests begin to feel trapped."],
      ["What do the guests do to try to get help?",["They swim to the coast","They try to signal to the mainland","They telephone the police","They light a lamp in the window"],1,"They try to make signals, but nobody on the coast takes any notice."],
      ["What do the men do after breakfast?",["They go fishing","They search the whole island","They play cards","They sleep"],1,"They examine every part of the island and the house."],
      ["What do they find during the search?",["A hidden room","Nobody else on the island","A boat","A radio"],1,"There is no other living person: the island is bare rock with nowhere to hide."],
      ["What does General Macarthur say by the sea?",["That he wants to go home","That he will never leave the island","That he knows the killer","That he is hungry"],1,"He sits quietly by the water and says he does not expect to leave."]
    ],
    tf:[
      ["Mrs Rogers dies during the night.",true,"She is found dead in her bed the next morning."],
      ["Dr Armstrong thinks she was given too much sleeping medicine.",true,"He believes it was an overdose of a sleeping draught."],
      ["The boat comes as usual in the morning.",false,"No boat comes, and the guests cannot leave the island."],
      ["The guests find another person hiding in a cave.",false,"They search everywhere and find nobody at all."],
      ["The island is covered with thick woods.",false,"It is bare rock, with no trees and nowhere to hide."],
      ["General Macarthur believes he will leave the island alive.",false,"He calmly says that none of them will ever leave."]
    ],
    writing:[
      {task:"Write the page of Dr Armstrong’s notebook for this morning. Record the death of Mrs Rogers and your medical opinion.",
       target:"50–70 words",
       tips:["Use short, factual sentences and give the time.","Use medical language: cause of death, dose, examination.","Do not add emotion — a doctor’s notes are cold and clear."],
       starters:["8.15 a.m. Called to the room of…","On examination…","In my opinion the cause of death was…","No other marks were found."]},
      {task:"Imagine you are trapped on a small island with no way to leave. Write about what you would do first and how you would feel.",
       target:"60–80 words",
       tips:["Use the second conditional: If I were…, I would…","Give at least two practical actions.","Finish with your feelings."],
       starters:["If I were trapped on an island,…","The first thing I would do is…","After that, I would…","I would probably feel…"]}
    ]},
  { n:5, title:"A killer’s game",
    sum:"General Macarthur is found dead on the shore, killed by a heavy blow on the back of the head. Judge Wargrave then says out loud what everybody is thinking: the murderer is not a stranger hiding on the island — the murderer is one of the seven people still alive. From this moment nobody trusts anybody, and each death follows a line of the old rhyme.",
    vocab:[
      ["MURDERER","a person who kills another person on purpose"],
      ["SUSPECT","a person who may have committed a crime"],
      ["TRUST","to believe that someone is honest and safe"],
      ["BLOW","a hard hit"],
      ["SHORE","the land at the edge of the sea"],
      ["JUDGE","the official who controls a court of law"],
      ["MADNESS","the state of having a very disturbed mind"],
      ["THEORY","an idea that explains how something happens"],
      ["PATTERN","a regular way in which something is repeated"],
      ["WEAPON","an object used to hurt or kill"],
      ["DANGER","the possibility of being harmed"],
      ["ALIBI","proof that you were somewhere else when a crime happened"]
    ],
    comp:[
      ["Where is General Macarthur found?",["In his bedroom","By the sea, on the shore","In the kitchen","On the cliff path"],1,"He is sitting in the same place by the water where he had spent the morning."],
      ["How did General Macarthur die?",["Poison","A heavy blow on the back of the head","Drowning","A fall"],1,"Somebody came up behind him and struck him with something heavy."],
      ["What does Judge Wargrave tell the others?",["That help is coming","That the murderer is one of them","That it was an accident","That they should swim"],1,"He explains calmly that no outsider can be on the island."],
      ["Why can the murderer not be a stranger?",["The island has been searched completely","The boat has gone","The doors are locked","There is a storm"],0,"Their search proved that nobody else is hiding on the island."],
      ["How many people are alive after Macarthur’s death?",["Eight","Seven","Six","Five"],1,"Marston, Mrs Rogers and Macarthur are dead, so seven remain."],
      ["What connects the deaths to the rhyme?",["Nothing","Each death follows a line of the rhyme","The rhyme is sung each time","The rhyme is written on the bodies"],1,"The way each victim dies matches a verse about the ten little soldiers."],
      ["What happens to the china figures after each death?",["They are cleaned","One disappears","They are counted","They are broken"],1,"Somebody removes one figure from the table for every person who dies."],
      ["How do the survivors behave now?",["They relax","They suspect one another","They go to bed","They leave together"],1,"Nobody can trust anybody, and they watch each other constantly."]
    ],
    tf:[
      ["General Macarthur is killed with a knife.",false,"He is killed by a heavy blow on the back of the head."],
      ["Judge Wargrave believes the murderer is one of the guests.",true,"He states it clearly: the killer is one of the people in the house."],
      ["Somebody else is hiding on the island.",false,"The search showed that nobody else is there."],
      ["Seven people are still alive after this chapter.",true,"Three of the ten are already dead."],
      ["Each death matches a line of the old rhyme.",true,"The murderer is following the rhyme exactly."],
      ["After Wargrave’s speech the guests trust each other completely.",false,"From now on every person suspects everybody else."]
    ],
    writing:[
      {task:"You are Judge Wargrave. Write the short speech in which you explain to the others that the murderer is one of them.",
       target:"60–80 words",
       tips:["Use a calm, logical order: first…, secondly…, therefore…","Use modal verbs of deduction: must be, cannot be.","End with a warning or an instruction."],
       starters:["Ladies and gentlemen, let us look at the facts.","We have searched the island, and therefore…","The murderer must be…","From now on we must…"]},
      {task:"Write a short paragraph explaining who you suspect at this point in the story and why.",
       target:"50–70 words",
       tips:["Name one character and give two reasons.","Use language of possibility: might, could, probably.","Mention one fact from the story as evidence."],
       starters:["At this point I suspect…","The first reason is that…","Secondly,…","However, I am not sure because…"]}
    ]},
  { n:6, title:"The storm",
    sum:"A violent storm breaks over the island and cuts it off completely from the coast. Locked in the house with the rain and the wind, the survivors watch each other and hardly dare to sleep. Rogers reports that another china figure has disappeared from the table, although nobody has died — and in the morning Rogers himself cannot be found.",
    vocab:[
      ["STORM","very bad weather with strong wind and rain"],
      ["THUNDER","the loud noise you hear during a storm"],
      ["WIND","air moving quickly"],
      ["CANDLE","a stick of wax that gives light when it burns"],
      ["LOCKED","closed with a key so that nobody can enter"],
      ["NERVES","the feeling of being anxious and tense"],
      ["WHISPER","to speak very quietly"],
      ["SHADOW","a dark shape made when light is blocked"],
      ["MISSING","not in the place where it should be"],
      ["COUNTED","added up to find the total number"],
      ["AWAKE","not sleeping"],
      ["TERROR","very great fear"]
    ],
    comp:[
      ["What happens to the weather?",["It becomes sunny","A violent storm breaks","It snows","There is fog only"],1,"Wind and heavy rain hit the island and the sea becomes dangerous."],
      ["Why is the storm important?",["It cools the house","It makes escape and rescue impossible","It brings a boat","It puts out the lights"],1,"No boat can cross, so the survivors are completely cut off."],
      ["How do the survivors spend the night?",["Sleeping deeply","Awake and watching one another","Playing games","Searching the cliffs"],1,"They are too frightened to sleep and lock their doors."],
      ["What does Rogers notice on the table?",["A broken plate","Another china figure has gone","A letter","A knife"],1,"A figure has disappeared although nobody has died yet."],
      ["Why does this frighten Rogers so much?",["He thinks a ghost took it","It suggests he may be the next victim","He must pay for it","He cannot count"],1,"Somebody has already prepared the next death."],
      ["What do the survivors do with the drugs and weapons?",["Throw them into the sea","Try to lock them away safely","Share them","Hide them separately"],1,"They agree to keep dangerous things locked up, but the plan does not work."],
      ["What is missing from Lombard’s room?",["His money","His revolver","His shoes","His notebook"],1,"Somebody has taken Philip Lombard’s gun."],
      ["Where is Rogers in the morning?",["In the kitchen","He cannot be found","On the shore","In his room"],1,"He does not appear with the morning tea, and the others go to look for him."]
    ],
    tf:[
      ["The storm makes it impossible for any boat to come.",true,"The island is completely cut off from the mainland."],
      ["The survivors sleep well that night.",false,"They lie awake, listening and watching."],
      ["A china figure disappears even though nobody has died.",true,"This shows that the murderer is already planning the next death."],
      ["Lombard’s revolver is stolen.",true,"It disappears from his room and nobody knows who took it."],
      ["The survivors decide to lock away the medicines.",true,"They try to make dangerous things safe, but it is not enough."],
      ["Rogers appears as usual with the morning tea.",false,"He is missing, and the others go to search for him."]
    ],
    writing:[
      {task:"Describe the storm on Soldier Island. Use your senses: what can you see, hear and feel?",
       target:"60–80 words",
       tips:["Use strong adjectives and verbs: crashing, roaring, freezing.","Use the past continuous for background description.","Add one sentence about how the storm made the people feel."],
       starters:["All night the wind was…","Rain crashed against…","Somewhere below, the sea…","Inside the house, nobody…"]},
      {task:"You are one of the survivors. Write the note you leave in your locked room in case you do not survive the night.",
       target:"50–70 words",
       tips:["Say the date and who you are.","List the facts you are sure about.","Say who you suspect and why."],
       starters:["To whoever finds this,","My name is…","These are the facts as I know them:","If I die tonight, look for…"]}
    ]},
  { n:7, title:"Six little soldiers",
    sum:"Rogers is found dead in the small washhouse, killed with an axe while he was chopping wood for the fire. Six people are left, and the atmosphere in the house becomes unbearable. They eat together, move together and refuse to be alone — but Emily Brent stays behind in the dining room after breakfast, sitting very still in her chair.",
    vocab:[
      ["WOOD","material from trees, used for fires and furniture"],
      ["CHOPPING","cutting something with an axe or knife"],
      ["BLOOD","the red liquid inside the body"],
      ["KITCHEN","the room where food is cooked"],
      ["TONGUE","the soft part inside your mouth used for speaking"],
      ["SILENT","making no sound"],
      ["PANIC","a sudden strong feeling of fear"],
      ["HUNGRY","needing to eat"],
      ["ACCUSE","to say that someone has done something wrong"],
      ["GOVERNESS","a woman employed to teach children in their home"],
      ["DROWNED","died under water"],
      ["PROUD","feeling that you are better or more important"]
    ],
    comp:[
      ["Where is Rogers found?",["In his bed","In the washhouse outside","On the cliff","In the sitting room"],1,"He is found in the little washhouse where he had gone to cut wood."],
      ["What was Rogers doing when he was killed?",["Sleeping","Chopping wood","Making tea","Cleaning shoes"],1,"He had gone out early to cut sticks for the kitchen fire."],
      ["What was used to kill him?",["A gun","An axe","Poison","A rope"],1,"The axe he was using was turned against him."],
      ["Which line of the rhyme does his death follow?",["A bee stings one","One chopped himself in halves","One overslept","One got frizzled up"],1,"The verse about chopping sticks matches the way he died."],
      ["How many people are still alive?",["Seven","Six","Five","Four"],1,"Wargrave, Armstrong, Lombard, Blore, Vera and Emily Brent remain."],
      ["Who cooks the breakfast now?",["Nobody eats","The survivors prepare it themselves","Emily Brent","Dr Armstrong"],1,"With both servants dead, the guests must look after themselves."],
      ["Who was Beatrice Taylor?",["Emily Brent’s young servant","A guest","A nurse","Vera’s sister"],0,"Emily Brent dismissed her young servant, who then drowned herself."],
      ["How does Emily Brent feel about Beatrice Taylor?",["Very guilty","She believes she did the right thing","She does not remember","She never knew her"],1,"She is convinced her behaviour was correct and feels no guilt at all."]
    ],
    tf:[
      ["Rogers is killed with an axe.",true,"He was chopping wood when the murderer struck him."],
      ["Rogers dies inside his bedroom.",false,"He is found in the washhouse outside the main building."],
      ["Six people are alive at the beginning of this chapter’s end.",true,"Four of the ten are now dead."],
      ["The survivors now have to prepare their own food.",true,"Both servants are dead, so they cook and serve for themselves."],
      ["Emily Brent feels very guilty about Beatrice Taylor.",false,"She insists that she only did her duty."],
      ["The survivors want to be alone in their rooms during the day.",false,"They are frightened and try to stay together."]
    ],
    writing:[
      {task:"You are William Blore. Write your notes about the death of Rogers: the facts, the time and your suspicions.",
       target:"60–80 words",
       tips:["Write like a police officer: short, numbered facts.","Use the passive: the body was found, the axe was left.","End with the name of the person you suspect most."],
       starters:["Time of discovery:","The body was found…","The weapon used was…","My conclusion at present:"]},
      {task:"Emily Brent believes she was right to dismiss her servant. Do you agree with her? Give your opinion with reasons.",
       target:"70–90 words",
       tips:["State your opinion in the first sentence.","Give two reasons and one example from the story.","Use linkers: firstly, moreover, on the other hand, in conclusion."],
       starters:["In my opinion, Emily Brent was…","Firstly,…","On the other hand, some people would say…","In conclusion,…"]}
    ]},
  { n:8, title:"The bee and the seaweed",
    sum:"Emily Brent is found dead in her chair with a tiny mark on her neck, while a bee buzzes at the window — a perfect copy of another line of the rhyme. The five survivors search each other and lock away everything dangerous, but that evening Vera screams: something cold and wet is hanging in her dark bedroom. Everyone runs upstairs, and downstairs Judge Wargrave is discovered dressed as a judge, with a bullet wound in his forehead.",
    vocab:[
      ["SEAWEED","a plant that grows in the sea"],
      ["NEEDLE","a thin sharp metal point, used for injections"],
      ["SYRINGE","an instrument used to inject liquid into the body"],
      ["SCREAM","to give a loud high cry of fear"],
      ["BULLET","the small piece of metal fired from a gun"],
      ["CURTAIN","cloth hung in front of a window"],
      ["FOREHEAD","the part of the face above the eyes"],
      ["ROBE","a long loose piece of clothing worn for ceremonies"],
      ["CEILING","the surface above you in a room"],
      ["SEARCH","to look carefully for something"],
      ["CORPSE","a dead body"],
      ["DARKNESS","the absence of light"]
    ],
    comp:[
      ["Where is Emily Brent found dead?",["In her bedroom","In her chair in the dining room","On the shore","In the kitchen"],1,"She had stayed behind after breakfast and never moved again."],
      ["What mark is on her neck?",["A cut","A small mark like a sting","A bruise","Nothing"],1,"There is a tiny mark, and a syringe was used to inject poison."],
      ["What is buzzing in the room?",["A fly","A bee","A wasp nest","Nothing"],1,"The murderer put a bee there so the death would match the rhyme."],
      ["Why did the murderer bring a bee?",["To sting her","To copy the line of the rhyme","By accident","To frighten the others"],1,"The killer wants each death to imitate the verse exactly."],
      ["What do the five survivors decide to do?",["Sleep separately","Search each other and lock up everything dangerous","Swim to the coast","Stop eating"],1,"They search one another’s rooms and lock away drugs, knives and matches."],
      ["What does Vera find hanging in her dark room?",["A rope","Wet seaweed","A coat","A curtain"],1,"Cold, wet seaweed touches her face in the dark and she screams."],
      ["Where is Judge Wargrave found?",["Upstairs","Downstairs, sitting in a chair","On the shore","In the garden"],1,"While everyone ran up to Vera, he was left alone below."],
      ["How is Judge Wargrave dressed?",["In pyjamas","In a red curtain and a grey wool wig, like a judge","In a coat","In a raincoat"],1,"The murderer has dressed the body as a judge in court."]
    ],
    tf:[
      ["Emily Brent is killed with a syringe.",true,"Poison was injected into her neck, leaving a tiny mark."],
      ["The bee at the window arrived by accident.",false,"The murderer put it there so the death would match the rhyme."],
      ["After Emily Brent’s death five people are alive.",true,"Wargrave, Armstrong, Lombard, Blore and Vera remain."],
      ["Vera finds seaweed hanging in her bedroom.",true,"It is cold and wet, and it makes her scream."],
      ["The seaweed was left there to frighten Vera.",true,"It is a trick, and it takes everybody upstairs at the same time."],
      ["Judge Wargrave is found dead in his bed.",false,"He is found downstairs, dressed as a judge, with a wound in his forehead."]
    ],
    writing:[
      {task:"Describe the moment when Vera enters her dark bedroom and touches the seaweed. Build the tension step by step.",
       target:"70–90 words",
       tips:["Use short sentences to create tension.","Use the senses: cold, wet, smell, darkness.","Delay the explanation until the last line."],
       starters:["Vera opened the door.","The room was completely dark.","Something cold and wet touched…","She screamed."]},
      {task:"Write the report Dr Armstrong might make about the deaths of Emily Brent and Judge Wargrave.",
       target:"60–80 words",
       tips:["Keep a formal, medical tone.","Give the apparent cause of death for each person.","Add one sentence saying what still cannot be explained."],
       starters:["Report on two further deaths.","Miss Brent: apparent cause of death…","Mr Justice Wargrave: apparent cause of death…","One point remains unexplained:"]}
    ]},
  { n:9, title:"And now there are four",
    sum:"Four people are left, and none of them dares to close their eyes. In the middle of the night Dr Armstrong leaves the house and never comes back, so in the morning only Vera, Lombard and Blore remain. They stay outside all day, but when Blore returns alone to the house to get food, a heavy marble clock in the shape of a bear falls from a window above him.",
    vocab:[
      ["FOOTSTEP","the sound of a foot touching the ground"],
      ["CORRIDOR","a long passage inside a building"],
      ["MARBLE","a hard stone used for statues and floors"],
      ["CLOCK","a machine that shows the time"],
      ["WINDOW","an opening in a wall with glass in it"],
      ["HUNGER","the feeling of needing food"],
      ["BISCUIT","a small hard sweet or dry cake"],
      ["SUNSHINE","the light and heat from the sun"],
      ["REVOLVER","a small gun with a turning cylinder"],
      ["ESCAPE","to get away from a dangerous place"],
      ["SUSPECT","a person who may have committed a crime"],
      ["VANISH","to disappear suddenly and completely"]
    ],
    comp:[
      ["How many people are alive at the start of this chapter?",["Five","Four","Three","Two"],1,"Armstrong, Blore, Lombard and Vera are the only survivors."],
      ["How do they spend the night?",["Sleeping in their rooms","Sitting together, awake and armed","Searching the island","Outside on the rocks"],1,"They stay in one room together, too frightened to sleep."],
      ["Who leaves the house during the night?",["Blore","Dr Armstrong","Vera","Lombard"],1,"Armstrong goes out and is never seen alive again."],
      ["What does Blore hear in the night?",["Music","Footsteps in the corridor","A boat","Nothing"],1,"He hears someone moving quietly outside the rooms."],
      ["Who is missing in the morning?",["Vera","Dr Armstrong","Lombard","Blore"],1,"His bed is empty and he is nowhere on the island."],
      ["Why does Blore go back to the house alone?",["To sleep","To get some food","To find the boat","To hide"],1,"He is very hungry and decides to fetch something to eat."],
      ["What kills Blore?",["A gun","A heavy marble clock shaped like a bear","A knife","The sea"],1,"The clock is pushed from a window above and crushes him."],
      ["Which line of the rhyme does Blore’s death match?",["A bumblebee stung one","A big bear hugged one","One overslept","A red herring swallowed one"],1,"The marble bear makes the death match the verse about the zoo."]
    ],
    tf:[
      ["Four people are alive at the beginning of this chapter.",true,"Armstrong, Blore, Lombard and Vera."],
      ["The four survivors sleep in separate rooms that night.",false,"They stay together, awake, because they are too frightened."],
      ["Dr Armstrong disappears during the night.",true,"He leaves the house and is not seen alive again."],
      ["Vera goes back to the house alone to find food.",false,"It is Blore who goes back alone."],
      ["Blore is killed by a falling marble clock.",true,"The clock is shaped like a bear, matching the rhyme."],
      ["After Blore’s death three people are still alive.",false,"Only Vera and Lombard remain."]
    ],
    writing:[
      {task:"Write Vera’s diary entry for this terrible night and morning. Describe what happened and how her feelings changed.",
       target:"70–90 words",
       tips:["Use the past simple and past perfect: I had never…","Show the change from fear to exhaustion.","Include one short sentence of direct thought."],
       starters:["I have not slept.","During the night…","When morning came,…","Now there are only…"]},
      {task:"Two people are left and each believes the other is the murderer. Write their short conversation.",
       target:"60–80 words",
       tips:["Write it as a dialogue with names and dashes or quotation marks.","Use accusations and denials: You must be…, It wasn’t me.","Keep the sentences short and tense."],
       starters:["‘There is nobody else left,’ said…","‘Then it must be you.’","‘I swear it wasn’t me.’","Neither of them moved."]}
    ]},
  { n:10, title:"A message in a bottle",
    sum:"Vera and Lombard find Dr Armstrong’s body washed up on the shore, and Vera, certain that Lombard is the killer, takes his revolver and shoots him. Alone at last, she walks up to the house in a dream and finds a rope already waiting in her room. Weeks later the police can explain nothing — until a fishing boat pulls a bottle out of the sea containing the murderer’s full confession.",
    vocab:[
      ["BOTTLE","a glass container for liquids"],
      ["CONFESS","to admit that you have done something wrong"],
      ["DOCUMENT","an official paper with written information"],
      ["FISHERMAN","a person who catches fish"],
      ["POLICE","the official force that keeps public order"],
      ["PUZZLE","something difficult to understand or solve"],
      ["ILLNESS","a disease or period of bad health"],
      ["PLAN","an arrangement for doing something in the future"],
      ["ROPE","a very thick strong string"],
      ["SOLUTION","the answer to a problem"],
      ["CORPSE","a dead body"],
      ["SURVIVE","to continue to live after a dangerous event"]
    ],
    comp:[
      ["Whose body do Vera and Lombard find on the shore?",["Blore’s","Dr Armstrong’s","Rogers’s","Nobody’s"],1,"Armstrong’s body has been washed up by the sea."],
      ["What does Vera do to Lombard?",["She helps him","She shoots him with his own revolver","She locks him in","She runs away"],1,"She takes the gun while he is bending over the body and shoots him."],
      ["What does Vera find waiting in her bedroom?",["A letter","A rope and a chair","Food","A china figure"],1,"Everything is prepared for the last line of the rhyme."],
      ["How does Vera die?",["She is shot","She hangs herself","She drowns","She is poisoned"],1,"In a strange, dreamlike state she does exactly what the rhyme says."],
      ["Why can the police not solve the case?",["There are no bodies","Everyone on the island is dead and no killer is found","They never go to the island","The bodies disappear"],1,"All ten people are dead and there is no possible survivor to be the murderer."],
      ["Who wrote the confession in the bottle?",["Dr Armstrong","Judge Wargrave","Philip Lombard","Vera Claythorne"],1,"The judge explains the whole plan in a document thrown into the sea."],
      ["How did the murderer pretend to be dead?",["He hid in a cave","Dr Armstrong helped him fake his death","He used a mask","He swam away"],1,"He persuaded Armstrong to help him, then killed him too."],
      ["Why did the murderer choose these ten people?",["They were rich","The law could not punish them for the deaths they caused","They were his family","By accident"],1,"He wanted to punish crimes that no court could touch."]
    ],
    tf:[
      ["Vera shoots Philip Lombard with his own revolver.",true,"She takes the gun while he is looking at Armstrong’s body."],
      ["Vera escapes from the island alive.",false,"She hangs herself in her bedroom, exactly as the rhyme says."],
      ["The police quickly understand what happened on the island.",false,"The case seems impossible: everyone is dead and nobody could be the killer."],
      ["The truth is discovered in a message inside a bottle.",true,"A fishing boat finds the bottle with the confession inside."],
      ["The murderer was Judge Wargrave.",true,"He explains everything in his written confession."],
      ["The murderer chose his victims by chance.",false,"He chose people who had caused a death but could not be punished by law."]
    ],
    writing:[
      {task:"Write the last part of the murderer’s confession: explain in your own words why he did it and how he tricked the others.",
       target:"80–100 words",
       tips:["Write in the first person and use a calm, logical tone.","Explain the motive first, then one trick in detail.","Use the past perfect for things done before: I had already…"],
       starters:["I have always had two things in my nature:","I chose ten people who…","My greatest difficulty was…","And so, at the end,…"]},
      {task:"‘Justice should always be done by the law, never by a private person.’ Do you agree? Give your opinion about the murderer’s idea of justice.",
       target:"80–100 words",
       tips:["State your opinion clearly in the first sentence.","Give two arguments and one example from the novel.","Use linkers: firstly, furthermore, however, to sum up."],
       starters:["I strongly agree/disagree that…","Firstly,…","Furthermore, in the novel…","To sum up,…"]}
    ]}
];

const READINGS = {
1:["In the hot August sunshine, eight people were travelling towards the same small village on the coast of Devon. In the corner of a first-class railway carriage, old Mr Justice Wargrave, a retired judge, was smoking and thinking about the letter in his pocket. It came from a lady he could not quite remember, and it invited him to spend a few days on Soldier Island.",
"The others were travelling too. Vera Claythorne, a young games mistress, had been offered work as a holiday secretary. Philip Lombard had been given a hundred guineas simply to come to the island and be ready for trouble. Emily Brent, a strict old lady, had accepted an invitation from a friend whose signature she could not read. Dr Armstrong had been asked to examine a lady who was unwell, General Macarthur had been promised a meeting with old army friends, and a big square man who called himself Davis had come, he said, for a holiday. Last of all came Anthony Marston, driving his enormous car far too fast along the narrow roads.",
"At Sticklehaven a boatman named Fred Narracott was waiting for them. He took them across the water, and for the first time they saw Soldier Island properly: a rock rising out of the sea, with a low white modern house on top of it. Nobody spoke much. The sea was calm, but the island looked strangely lonely.",
"At the door they were received by a servant, Thomas Rogers, and his wife Ethel, who was the cook. Rogers explained politely that Mr and Mrs Owen had been delayed and would arrive the following day. Everything, however, had been prepared for the guests: excellent rooms, excellent food, everything new and comfortable.",
"Upstairs, each guest found the same thing hanging on the bedroom wall in a neat frame: an old children’s rhyme about ten little soldier boys who disappear, one after another, until there are none left. Most of the guests read it, smiled, and thought no more about it.",
"Downstairs in the dining room the table had been laid for eight. In the very centre, on a round glass plate, stood ten little china soldiers. Vera counted them without knowing why. Then dinner was served, the wine was poured, and the strangers began to talk, each one still wondering exactly who their host was."],
2:["Dinner was a success. The food was good, the wine was better, and the eight guests began to relax. Anthony Marston talked and laughed the loudest. Even Emily Brent, sitting very straight in her chair, allowed herself a small smile. Afterwards they moved into the sitting room, where Rogers brought in the coffee.",
"And then, suddenly, a voice spoke. It was loud, clear and terribly cold, and it seemed to come from nowhere at all. ‘Ladies and gentlemen,’ it said. ‘Silence, please.’ Everyone stopped moving. Cups stayed in the air. The voice went on, and it began to call out their names.",
"One by one, it accused them. Edward George Armstrong, it said, had caused the death of a woman during an operation. Emily Caroline Brent was responsible for the death of Beatrice Taylor. William Henry Blore had sent an innocent man to prison, where he died. Vera Elizabeth Claythorne had killed a little boy called Cyril Hamilton. Philip Lombard had left twenty-one men to die in Africa. John Gordon Macarthur had sent his wife’s lover to certain death. Anthony James Marston had run over and killed John and Lucy Combes. Thomas and Ethel Rogers had allowed an old lady to die. And Lawrence John Wargrave had murdered Edward Seton.",
"Then the voice asked, in the calm tone of a judge in court, whether any of the prisoners had anything to say in their defence. After that there was silence — a silence so complete that they could hear the sea outside.",
"There was a crash as Mrs Rogers fell to the floor. Dr Armstrong hurried to help her while Lombard and Blore ran out of the room to find the source of the voice. In a small room next door they found a gramophone, still turning, with its horn against the wall. The record on it was called ‘Swan Song’.",
"Rogers, white and shaking, explained everything. His written instructions had told him to put on that record at exactly that moment. He had never heard it before; he had thought it was music. Dr Armstrong helped Mrs Rogers to her feet and gave her something to make her sleep. Nobody, that night, felt like laughing."],
3:["Nobody could go to bed. In the sitting room the eight of them began, one after another, to answer the accusations. Dr Armstrong said the operation had been unlucky. General Macarthur said very little at all. Emily Brent said only that she had done her duty and that she had nothing whatever to explain. Vera said that she had swum after the little boy and had not been able to reach him.",
"Blore admitted that his real name was not Davis: he was a former police inspector, now a private detective, and he had been paid to come and watch the other guests. Philip Lombard, smiling, admitted quite openly that he had left the twenty-one men in the bush and taken the food. ‘It was my life or theirs,’ he said.",
"Then they compared their invitations. Each letter was signed differently, and none of them had ever met their host. Judge Wargrave took the letters, read them carefully, and pointed out something strange. The name of the host was written as U. N. Owen. Said aloud, quickly, those initials made one word: unknown.",
"‘Somebody,’ said the judge quietly, ‘has brought us all here for a purpose.’ Anthony Marston, who was tired of the conversation, said that he needed a drink. He filled his glass with whisky, lifted it, and drank it down.",
"A moment later his face changed colour. He tried to breathe, put his hands to his throat, and fell forward out of his chair. Dr Armstrong knelt beside him, smelled the glass, and looked up with a strange expression. ‘Cyanide,’ he said. ‘He must have taken it himself.’ But nobody in that room believed it.",
"Much later, when Rogers came to clear the sitting room, he stopped in the doorway of the dining room and stared at the little glass plate in the middle of the table. He counted the china soldiers twice. There were nine."],
4:["Rogers knocked at his wife’s door in the morning with a cup of tea, and she did not answer. Dr Armstrong was called at once, but there was nothing to be done: Ethel Rogers had died quietly in her sleep, some time during the night. The doctor said that in his opinion she had been given far too large a dose of a sleeping draught.",
"At breakfast, Vera looked at the glass plate and said, in a voice that did not sound like her own, that there were only eight soldiers now. Nobody replied.",
"They waited for the boat. It did not come. At ten o’clock, at eleven, at midday, they walked down to the little landing place and looked across at the mainland, where they could clearly see houses and the smoke of a train. They waved and shouted; nothing happened. Fred Narracott, they learned later, had been told that whatever signals came from the island were only part of a game.",
"Now real fear entered the house. The men decided to search Soldier Island from end to end. It did not take long, because there was almost nothing there: bare rock, short grass, a few gulls, no trees, no buildings except the house itself. They looked into every cave and behind every stone. There was no boat, no hiding place and no other living person.",
"They searched the house as well, from the cellar to the roof. Every cupboard was opened, every wall was measured. There was no secret room, no visitor, nobody at all beyond the seven people who were still alive.",
"General Macarthur did not join the search. He sat down on a stone seat at the far end of the island, looking out at the water, and stayed there all morning. When Vera passed and spoke to him, he smiled at her gently and said that he was very glad it would soon be over. None of them, he told her, would ever leave the island. Then he turned back to the sea and did not speak again."],
5:["At lunchtime General Macarthur did not come in. Dr Armstrong walked down to the stone seat to call him and found the old man still sitting there, facing the sea. He was dead. Somebody had come quietly up behind him and struck him a heavy blow on the back of the head.",
"They carried the body up to the house and laid it in a bedroom, next to the others. Then Judge Wargrave asked everybody to come into the sitting room, and he spoke to them as he had once spoken to juries.",
"‘Let us be clear about the facts,’ he said. ‘Three of us are dead. The island has been searched and there is nobody hiding on it. No boat can land without being seen. Therefore the person who has killed three people is not a stranger. He — or she — is in this room now.’",
"Nobody moved. Outside, the wind was beginning to rise. Vera looked at the six faces around her and understood that one of them belonged to a murderer, and that there was no possible way of knowing which.",
"There was something else, too. Vera said it out loud, because she could not keep it inside any longer: the deaths were following the rhyme on the bedroom walls. Marston had choked over his drink. Mrs Rogers had gone to sleep and never woken up. And the third little soldier, said the rhyme, had stayed in Devon for ever — exactly as the General had said he would.",
"And every time a person died, one small china figure disappeared from the plate in the dining room. From that moment nobody in the house trusted anybody. They locked their doors, they watched each other’s hands, and they tried not to be alone in any room — with the terrible knowledge that being together was no safer at all."],
6:["The storm arrived that evening. The wind rose until it screamed around the corners of the house, and the rain hit the windows like handfuls of stones. Down below, the sea turned white and threw itself against the rocks. Whatever else happened now, no boat could reach Soldier Island.",
"They ate a cold supper and sat together in the sitting room, listening. Every sound seemed enormous. Blore watched Lombard; Lombard watched Armstrong; Vera watched them all. When Emily Brent said calmly that the guilty would be punished, nobody was quite sure whether she was talking about the others or about herself.",
"Before he went upstairs, Rogers came in with a strange, grey face. He had been laying the table for breakfast, he said, and he had counted the little china soldiers. There were only seven. Yet nobody had died since the General. Somebody, then, had already taken away the figure for the next death.",
"The survivors agreed to be sensible. They collected everything that could be dangerous — the doctor’s case of drugs, the kitchen knives, the matches — and locked them away, and Blore and Lombard kept the keys. It was a good plan, and it was completely useless.",
"During the night, Philip Lombard discovered that his revolver had gone. He searched his room twice and swore quietly in the darkness. Now the murderer had a gun.",
"Nobody slept properly. They lay awake behind locked doors, listening to the storm and to the sounds of the old house. Once, Blore was certain he heard footsteps in the corridor. Once, Vera heard a door open very softly and close again. And in the morning, when the storm had dropped and the survivors came down for breakfast, there was no fire in the kitchen, no tea on the table and no sign of Rogers anywhere."],
7:["They found him in the little washhouse behind the kitchen. He had gone out early to chop sticks for the fire, and he was lying beside the wood with the axe still in the wound. He had been killed from behind, while his hands were busy and his back was turned.",
"Vera began to laugh, and could not stop, and Lombard slapped her face until she was quiet. Then somebody said the words that were in everybody’s mind: the fourth little soldier in the rhyme had chopped himself in halves. In the dining room, six china figures now stood on the glass plate.",
"Six people were left: Judge Wargrave, Dr Armstrong, Philip Lombard, William Blore, Vera Claythorne and Emily Brent. With both servants dead, they had to look after themselves. Vera and Emily Brent boiled water and opened tins, and the four of them who could still eat sat down to a strange breakfast of tongue and biscuits.",
"They talked while they ate, and the talk was all suspicion. Blore said openly that he did not believe in Dr Armstrong’s medical explanations. Lombard suggested that the quietest person in the room was often the most dangerous. Wargrave listened to everything and said almost nothing.",
"Emily Brent hardly spoke at all. When Vera asked her about Beatrice Taylor, the old lady answered in a hard, flat voice. The girl had been her servant, she said, and had got into trouble, so she had of course sent her away. When the girl drowned herself, that was the girl’s own sin, not hers. Emily Brent had done her duty, and her conscience was perfectly clear.",
"After breakfast the others carried the dishes out and went to wash them. Miss Brent said that she felt a little strange, and that she would sit quietly for a moment. When Vera looked back from the door, the old lady was sitting very upright in her chair by the window, with her hands folded in her lap, exactly as usual."],
8:["When they came back she was still sitting there, and she was dead. Her face had gone a curious colour and her lips were blue. On the right side of her neck there was a mark, small and round, like the sting of an insect. And on the window, buzzing loudly against the glass, there was a bee.",
"Dr Armstrong looked at the mark for a long time. It was not the work of a bee, he said; something had been injected into her neck. Later they found the syringe, thrown out of the window into the grass below. The murderer had brought the bee simply so that the death would match its line of the rhyme.",
"Five people were left, and now they were completely honest with one another about their fear. They searched each other, and each other’s rooms, and everything that could kill was locked away in a cupboard, with Lombard and Blore each keeping a key. Even so, when the search was finished, Lombard’s revolver was suddenly back in his room, exactly where it had been.",
"That evening Vera went upstairs to have a bath. Her room was dark. She reached for the light, and as she did so something cold and wet touched her throat — something soft that hung down from the ceiling and moved against her skin. She screamed, and went on screaming.",
"Every one of them came running: Lombard first, then Blore, then Armstrong, and they turned on the light and found her holding a long, dripping strand of seaweed that somebody had hung from the ceiling hook. Vera sat down on the bed and laughed weakly at herself while the men stared at each other.",
"Then, slowly, the four of them realised that they were four. They went down the stairs together. In the sitting room, Mr Justice Wargrave was sitting in a high chair at the end of the room. Round his shoulders somebody had draped the scarlet curtain from the bathroom, and on his grey hair somebody had placed a wig of grey wool. He looked exactly like a judge in court. In the middle of his forehead there was a round dark hole where a bullet had gone in."],
9:["Four were left: Dr Armstrong, William Blore, Philip Lombard and Vera Claythorne. They carried the judge’s body upstairs, they came down again, and they sat in the sitting room and looked at one another, and none of them said what they were all thinking.",
"They did not go to bed. They sat together with the lamps burning, and the night went slowly by. At some point Vera slept a little in her chair. At some point Blore was sure he heard a door and then soft footsteps going along the corridor. He got up and looked out, and the corridor was empty and dark, and he went back and locked himself in again.",
"In the morning Dr Armstrong was missing. His bed had been slept in and then left; his door was open; his coat had gone. They searched the house and then the island, walking along the cliffs and looking down into the water, and they found nothing at all. Three little china soldiers stood on the glass plate in the dining room.",
"After that the three survivors made a decision: they would not go inside again. They stayed out in the sunshine on the open rock, where nobody could come near them without being seen, and they sat and watched each other, hour after hour, and said very little.",
"By the afternoon Blore was extremely hungry. He said he was going up to the house to fetch some food, and he asked the others to come with him. They refused: nothing, said Vera, would make her go back inside that house. So Blore went alone, walking quickly, and they watched him disappear through the door.",
"They heard the crash from where they sat. When they ran up, they found him lying on the terrace at the back of the house with his head crushed. Beside him on the stones lay a great block of white marble, a clock in the shape of a bear that had stood on the window sill of Vera’s room, one floor above. In the rhyme, a big bear had hugged one of the little soldiers. Now there were two."],
10:["Vera and Lombard did not go back into the house. They walked down to the edge of the sea instead, saying nothing, keeping a careful distance from each other, and it was there, at the bottom of the cliff, that they saw something rolling in the water at the tide line. It was Dr Armstrong. The sea had brought him back.",
"They pulled the body up out of the water together. And as Lombard bent over it, Vera stepped back, and her hand went into his pocket, and when he stood up again she was three metres away and his own revolver was pointing at his chest. He understood at once, and he was fast — but she fired first, and Philip Lombard fell across the body of the doctor.",
"Vera was alone. She stood on the rocks with the gun in her hand and felt an enormous, wonderful sense of peace. It was over. She had won. Slowly she climbed the path to the house, went in through the open door, and started up the stairs to her room, thinking about a bath, and dry clothes, and sleep.",
"Her bedroom door was open. There was a smell of the sea in the room. And from the hook in the ceiling, where the seaweed had hung, there now hung a rope with a noose ready at the end of it, and underneath it somebody had placed a chair. On the little table by the bed stood one small china soldier.",
"Vera looked at it for a long time. She was very tired. Somewhere in her mind a voice that sounded like Hugo’s told her that this was what she must do now, and that she had always known it, and she found that she agreed. She stepped up onto the chair, put the rope round her neck and kicked the chair away.",
"Weeks later, at Scotland Yard, two police officers went through the case again and gave it up. Ten people were dead on Soldier Island; ten deaths had been carefully arranged; and there was nobody left alive who could possibly have arranged them. Then a fishing boat off the Devon coast pulled up a bottle with a paper inside, and the paper was a confession signed by Mr Justice Wargrave. All his life, he wrote, he had felt two things at the same time: a passion for justice and a secret desire to kill. He was old and mortally ill, so he had chosen ten people who had caused a death that no court could punish, and he had brought them together to be judged. He had persuaded Dr Armstrong to help him ‘pretend’ to be dead — the red mark on his forehead was only mud and red curtain material — and then he had pushed the doctor into the sea. And when the last of the others was gone, he had lain down on his bed and arranged the revolver so that, when he fired, his body would fall exactly as it should. Nobody would ever solve it, he wrote. He simply could not bear the thought that nobody would ever know how clever he had been."
]
};

const EVENTS={
1:{ev:["Eight strangers receive invitations to Soldier Island from a host they have never met.",
      "Fred Narracott takes the guests across the water by boat.",
      "The servants, Mr and Mrs Rogers, explain that the Owens have not arrived.",
      "Each guest finds an old rhyme about ten little soldiers framed in their bedroom.",
      "Vera counts ten china soldiers on the dining-room table.",
      "The strangers have dinner together, still wondering who their host is."],
   keys:["island","invitation","boat","Rogers","rhyme","china soldiers"]},
2:{ev:["The guests enjoy an excellent dinner and move to the sitting room for coffee.",
      "A cold, loud voice suddenly speaks from nowhere.",
      "The voice accuses all ten people in the house of causing a death.",
      "Mrs Rogers faints and Dr Armstrong looks after her.",
      "Lombard and Blore find a gramophone in the next room.",
      "Rogers explains he only followed written instructions to play the record."],
   keys:["dinner","voice","accuses","faints","gramophone","record"]},
3:{ev:["One by one, the guests answer the accusations against them.",
      "Blore admits that his real name is not Davis.",
      "Judge Wargrave works out that U. N. Owen means ‘unknown’.",
      "Anthony Marston fills his glass with whisky and drinks it.",
      "Marston chokes and falls dead — there was cyanide in his glass.",
      "Rogers counts the china soldiers: there are only nine."],
   keys:["accusations","Davis","unknown","whisky","cyanide","nine"]},
4:{ev:["In the morning, Mrs Rogers does not wake up: she has died in her sleep.",
      "Vera notices there are only eight china soldiers left.",
      "The guests wait for the boat, but it never comes.",
      "The men search every rock and cave on the island.",
      "They find nobody: there is no other person on Soldier Island.",
      "General Macarthur says that none of them will ever leave the island."],
   keys:["sleep","eight","boat","search","nobody","Macarthur"]},
5:{ev:["General Macarthur does not come in for lunch.",
      "Dr Armstrong finds the General dead by the stone seat.",
      "Judge Wargrave gathers everyone in the sitting room.",
      "The judge explains that the murderer must be one of them.",
      "Vera realises the deaths are following the soldier rhyme.",
      "From that moment, nobody in the house trusts anybody."],
   keys:["lunch","dead","Wargrave","murderer","rhyme","trust"]},
6:{ev:["A violent storm reaches the island: no boat can arrive now.",
      "Rogers reports that only seven china soldiers are left.",
      "The survivors lock away the drugs, the knives and the matches.",
      "During the night, Lombard discovers that his revolver has gone.",
      "Blore and Vera hear footsteps and doors in the dark house.",
      "In the morning there is no fire, no tea and no sign of Rogers."],
   keys:["storm","seven","locked","revolver","footsteps","Rogers"]},
7:{ev:["The guests find Rogers dead in the washhouse, killed with an axe.",
      "Vera laughs hysterically until Lombard stops her.",
      "Six survivors prepare a strange breakfast for themselves.",
      "During the meal, everyone talks about who they suspect.",
      "Emily Brent says her conscience is perfectly clear about Beatrice Taylor.",
      "Miss Brent stays alone in her chair by the window."],
   keys:["axe","laughs","breakfast","suspicion","Beatrice","window"]},
8:{ev:["Emily Brent is found dead in her chair, with a mark on her neck.",
      "Dr Armstrong explains that something was injected — the bee was only decoration.",
      "The five survivors search each other and lock everything dangerous away.",
      "Lombard’s revolver mysteriously returns to his room.",
      "Vera screams when cold seaweed touches her in the dark.",
      "The others find Judge Wargrave dressed as a judge — shot in the forehead."],
   keys:["bee","injected","search","revolver","seaweed","judge"]},
9:{ev:["The four survivors sit together all night with the lamps burning.",
      "In the morning, Dr Armstrong has disappeared.",
      "Only three china soldiers stand on the glass plate.",
      "The three survivors decide to stay outside, in the open.",
      "Blore goes back to the house alone to fetch some food.",
      "A marble clock in the shape of a bear crushes Blore on the terrace."],
   keys:["night","Armstrong","three","outside","food","bear"]},
10:{ev:["Vera and Lombard find Dr Armstrong’s body at the tide line.",
      "Vera takes Lombard’s revolver and shoots him.",
      "Feeling strangely peaceful, Vera walks back to the house.",
      "In her room she finds a rope and one china soldier.",
      "Vera hangs herself, exactly as the rhyme says.",
      "Weeks later, a fishing boat finds Wargrave’s confession in a bottle."],
   keys:["Armstrong","revolver","peace","rope","rhyme","confession"]}
};

return {level:'B1', lead:'Agatha Christie · retelling · <b>B1 intermediate</b> (≈1,000 headwords)',
  CHAPTERS:CHAPTERS, READINGS:READINGS, EVENTS:EVENTS};
})();
