/* BEING EARNEST - datos nivel B1 (extraidos de being-earnest.html).
   Mismo formato que attwn-data-*.js; EVENTS los completa el agente. */
window.ATTWN_DATA = (function(){
const CHAPTERS = [
  { n:1, title:"The silver case",
    sum:"In Algernon Moncrieff's London flat, his friend Jack — known in town as 'Ernest' — comes to propose to Gwendolen. But Algernon has found Jack's silver cigarette case, inscribed 'from little Cecily'. The gift forces Jack to confess his double life, and Algernon reveals his own trick: an imaginary friend called Bunbury.",
    vocab:[
      ["CASE","a small flat container, e.g. for cigarettes"],
      ["SILVER","a shiny grey-white precious metal"],
      ["BUTLER","the chief male servant of a house"],
      ["PIANO","a large musical instrument with black and white keys"],
      ["GUARDIAN","an adult legally responsible for a young person"],
      ["BACHELOR","a man who is not married"],
      ["INVENT","to create something that is not real"],
      ["CONFESS","to admit that you did something"],
      ["WICKED","very bad; behaving badly"],
      ["EXCUSE","a reason you give to explain or avoid something"],
      ["IDENTITY","who a person really is"],
      ["INSCRIPTION","words written or engraved on an object"]
    ],
    comp:[
      ["Where does Chapter 1 take place?",["Jack's country house","Algernon's flat in London","Victoria Station","A church"],1,"The play opens in Algernon Moncrieff's fashionable London flat."],
      ["What is Lane's job in the house?",["Cook","Butler (servant)","Gardener","Driver"],1,"Lane is Algernon's butler."],
      ["Which object reveals Jack's secret?",["A letter","A silver cigarette case","A photograph","A ring"],1,"Algernon has kept Jack's silver cigarette case, which carries a telling inscription."],
      ["What name does Jack use when he is in town?",["Algernon","Bunbury","Ernest","Thomas"],2,"In London Jack calls himself Ernest."],
      ["Who gave Jack the cigarette case?",["Gwendolen","Lady Bracknell","Cecily","Miss Prism"],2,"It is inscribed 'From little Cecily, with her fondest love'."],
      ["Who is Cecily to Jack?",["His sister","His ward (he is her guardian)","His cousin","His daughter"],1,"Jack is the legal guardian of young Cecily in the country."],
      ["What does Algernon call his invented excuse-friend?",["Ernest","Bunbury","Cardew","Chasuble"],1,"Algernon invented an invalid friend, Bunbury, to escape social duties."],
      ["Why has Jack come to town?",["To sell his house","To propose to Gwendolen","To find his parents","To study"],1,"Jack has come to London hoping to propose to Gwendolen Fairfax."]
    ],
    tf:[
      ["The story begins in Jack's country house.",false,"It begins in Algernon's flat in London."],
      ["The cigarette case is made of silver.",true,"It is a silver case with an inscription from Cecily."],
      ["Jack is called Ernest in the countryside.",false,"He is Jack in the country and Ernest in town."],
      ["Cecily gave Jack the cigarette case.",true,"The inscription is from 'little Cecily' to her 'dear Uncle Jack'."],
      ["Algernon invented a sick friend called Bunbury.",true,"'Bunburying' is his word for using an invented excuse."],
      ["Jack wants to marry Cecily.",false,"Jack wants to marry Gwendolen."]
    ],
    writing:[
      {task:"Write a short note as Cecily to her Uncle Jack. Thank him for a present and ask when he will come home.",
       target:"40–60 words",
       tips:["Open and close a friendly note correctly.","Use the past simple for the gift and 'will' for the future.","Keep the tone warm and polite."],
       starters:["Dear Uncle Jack,","Thank you so much for…","I hope you will…","With fondest love, Cecily"]},
      {task:"Explain in your own words what 'Bunburying' means and give one example from your own life.",
       target:"50–70 words",
       tips:["Define the idea first, then give your example.","Use linking words: for example, because, so.","Use the present simple to explain a general idea."],
       starters:["'Bunburying' means…","People do this because…","For example, I once…"]}
    ]},
  { n:2, title:"No cucumber sandwiches",
    sum:"Lady Bracknell and Gwendolen come to tea. Algernon has ordered cucumber sandwiches specially for his aunt — then eats them all himself, so the butler pretends there were no cucumbers. While Algernon distracts Lady Bracknell, Jack proposes to Gwendolen, who accepts him — because she has always dreamed of loving a man called Ernest.",
    vocab:[
      ["CUCUMBER","a long green salad vegetable"],
      ["SANDWICH","two pieces of bread with a filling"],
      ["TEA","a hot drink; also a light afternoon meal"],
      ["AUNT","the sister of your mother or father"],
      ["PROPOSAL","when you ask someone to marry you"],
      ["ACCEPT","to say yes to something"],
      ["ADORE","to love and admire very much"],
      ["IDEAL","the best or most perfect example"],
      ["NERVOUS","worried and slightly afraid"],
      ["DELIGHT","great pleasure"],
      ["DECLARE","to say something firmly and openly"],
      ["CHARM","the power to please and attract people"]
    ],
    comp:[
      ["Who is coming to tea at Algernon's flat?",["Cecily and Miss Prism","Lady Bracknell and Gwendolen","Dr. Chasuble","Mr. Cardew"],1,"Algernon expects his aunt, Lady Bracknell, and his cousin Gwendolen."],
      ["What special food had Algernon ordered?",["Cake","Cucumber sandwiches","Bread and butter","Fruit"],1,"He ordered cucumber sandwiches especially for Lady Bracknell."],
      ["What happens to the cucumber sandwiches?",["The dog eats them","Algernon eats them all himself","They are burnt","Gwendolen takes them"],1,"Algernon nervously eats every one before his aunt arrives."],
      ["What excuse does the butler give for the missing sandwiches?",["They fell","There were no cucumbers in the market","The cook forgot","A guest ate them"],1,"Lane says there were no cucumbers, 'not even for ready money'."],
      ["Who does Jack propose to in this chapter?",["Cecily","Gwendolen","Lady Bracknell","Miss Prism"],1,"Jack seizes his chance to propose to Gwendolen."],
      ["Does Gwendolen accept Jack's proposal?",["No","Yes","She asks her mother first","She runs away"],1,"Gwendolen happily accepts him."],
      ["Why does Gwendolen say she loves Jack?",["He is rich","Because his name is Ernest","He is handsome","He lives in town"],1,"She declares that her ideal has always been to love a man named Ernest."],
      ["What is Gwendolen's 'ideal'?",["To live in the country","To love a man called Ernest","To marry a lord","To travel"],1,"The name Ernest, she says, 'inspires absolute confidence'."]
    ],
    tf:[
      ["Lady Bracknell is Gwendolen's aunt.",false,"Lady Bracknell is Gwendolen's mother; she is Algernon's aunt."],
      ["Algernon eats all the cucumber sandwiches himself.",true,"He finishes them before his aunt even arrives."],
      ["The butler says there were no cucumbers.",true,"Lane provides the excuse to cover Algernon."],
      ["Gwendolen refuses Jack's proposal.",false,"She accepts him enthusiastically."],
      ["Gwendolen loves the name Ernest.",true,"Her whole 'ideal' depends on the name Ernest."],
      ["Jack feels nervous about proposing.",true,"He is anxious and awkward as he proposes."]
    ],
    writing:[
      {task:"Write a short note of apology as Algernon for eating all the cucumber sandwiches before your aunt arrived.",
       target:"40–60 words",
       tips:["Say sorry and give a (funny) excuse.","Use 'I'm sorry that…' and 'I promise…'.","Keep it light and polite."],
       starters:["Dear Aunt Augusta,","I'm terribly sorry that…","I promise that next time…","Yours, Algernon"]},
      {task:"Do you think a person's name can make you like or dislike them? Give your opinion with reasons.",
       target:"60–80 words",
       tips:["State your opinion at the start.","Give at least one reason with 'because'.","Add an example from real life."],
       starters:["In my opinion, a name…","This is because…","For example,…"]}
    ]},
  { n:3, title:"Lady Bracknell interviews Jack",
    sum:"Before she will consider Jack as a husband for Gwendolen, Lady Bracknell interviews him about his income, his property and — above all — his family. Jack must admit that he has no parents: as a baby he was found in a handbag at Victoria Station. Horrified, Lady Bracknell refuses the marriage until he can produce some relatives.",
    vocab:[
      ["INTERVIEW","a formal meeting with questions"],
      ["INCOME","the money a person earns or receives"],
      ["PROPERTY","land and buildings that someone owns"],
      ["FORTUNE","a very large amount of money"],
      ["HANDBAG","a bag carried by hand for personal things"],
      ["STATION","a place where trains stop"],
      ["ORPHAN","a child whose parents are dead"],
      ["SOCIETY","fashionable, upper-class people"],
      ["APPROVE","to agree that something is good"],
      ["REFUSE","to say no to something"],
      ["ASTONISHED","very surprised"],
      ["SUITABLE","right or acceptable for a situation"]
    ],
    comp:[
      ["Who interviews Jack about the marriage?",["Gwendolen","Lady Bracknell","Algernon","Dr. Chasuble"],1,"Lady Bracknell questions Jack to judge if he is a suitable husband."],
      ["Why does she interview him?",["To offer him a job","To see if he is a suitable husband for Gwendolen","To sell him a house","To ask for money"],1,"She will only allow the marriage if he passes her examination."],
      ["What things does Lady Bracknell mainly ask about?",["His hobbies","His income, property and family","His friends","His holidays"],1,"She interrogates him about money, property and, above all, his relations."],
      ["Where was Jack found as a baby?",["In a church","In a handbag at Victoria Station","On a ship","In the countryside"],1,"He was discovered in a handbag in the cloakroom at Victoria Station."],
      ["Who found the baby Jack?",["Lady Bracknell","Miss Prism","Mr. Thomas Cardew","A policeman"],2,"The wealthy Mr. Thomas Cardew found and adopted him."],
      ["How does Lady Bracknell react to Jack's story?",["She laughs kindly","She is astonished and refuses","She agrees at once","She cries with joy"],1,"She is horrified that he has no known family."],
      ["What does Lady Bracknell advise Jack to do?",["Earn more money","Acquire some relatives (parents)","Change his name","Move abroad"],1,"She tells him to 'acquire some relations' as soon as possible."],
      ["Does Lady Bracknell allow the marriage?",["Yes","No","Only in a year","She lets Gwendolen decide"],1,"She refuses her consent because of Jack's unknown origins."]
    ],
    tf:[
      ["Lady Bracknell thinks Jack is immediately suitable.",false,"She refuses him because of his unknown family."],
      ["Jack owns property in town and in the country.",true,"He has houses in both, which pleases her at first."],
      ["Jack knows who his real parents are.",false,"He is an orphan and does not know his origins."],
      ["Jack was found in a handbag.",true,"He was found in a black leather handbag at the station."],
      ["Mr. Thomas Cardew found the baby Jack.",true,"Mr. Cardew found and adopted him."],
      ["Lady Bracknell allows the marriage at once.",false,"She refuses until Jack can produce relatives."]
    ],
    writing:[
      {task:"Imagine you are Lady Bracknell. Write five questions you would ask a person who wants to marry your child.",
       target:"50–70 words",
       tips:["Use correct question forms (Do you…? How much…? Where…?).","Number your questions.","Think about money, family and character."],
       starters:["1. How much…?","2. Do you have…?","3. Where were you…?","4. What is your…?","5. Who are your…?"]},
      {task:"Should who a person's family is matter when you choose a partner? Give your opinion with reasons.",
       target:"60–80 words",
       tips:["State your opinion clearly, then justify it.","Use linkers: firstly, however, in conclusion.","Consider both sides before finishing."],
       starters:["In my opinion,…","On the one hand,…","On the other hand,…","To conclude,…"]}
    ]},
  { n:4, title:"The Manor House",
    sum:"The action moves to the garden of Jack's country house. Cecily avoids her German lesson with Miss Prism, who secretly admires the rector, Dr. Chasuble. Then Algernon arrives pretending to be Jack's 'wicked brother Ernest' — and Cecily, who has long dreamed of that romantic brother, is delighted to meet him.",
    vocab:[
      ["GARDEN","the ground with plants next to a house"],
      ["GOVERNESS","a woman who teaches children in their home"],
      ["LESSON","a period of teaching"],
      ["DIARY","a book where you write daily events"],
      ["RECTOR","a priest in charge of a parish"],
      ["PRETEND","to act as if something false were true"],
      ["CHARMING","very pleasant and attractive"],
      ["IMAGINATION","the ability to form ideas in your mind"],
      ["DELIGHTED","very pleased and happy"],
      ["MANOR","a large country house"],
      ["ADMIRE","to like and respect someone"],
      ["ROMANTIC","connected with love and strong feelings"]
    ],
    comp:[
      ["Where does Chapter 4 take place?",["Algernon's flat","The garden of Jack's Manor House","A London club","Victoria Station"],1,"The second part of the story moves to Jack's country house."],
      ["Who is Cecily's governess?",["Gwendolen","Lady Bracknell","Miss Prism","Miss Fairfax"],2,"Miss Prism is Cecily's strict governess."],
      ["What does Miss Prism want Cecily to study?",["French","German","Piano","History"],1,"Miss Prism insists on the German lesson, which Cecily dislikes."],
      ["Who is Dr. Chasuble?",["A doctor of medicine","The local rector (priest)","Jack's lawyer","Cecily's uncle"],1,"Dr. Chasuble is the rector of the parish."],
      ["Who does Miss Prism secretly admire?",["Jack","Algernon","Dr. Chasuble","Mr. Cardew"],2,"There is a comic romance hinted at between Miss Prism and Dr. Chasuble."],
      ["Who arrives pretending to be 'Ernest'?",["Jack","Algernon","Dr. Chasuble","A stranger"],1,"Algernon comes disguised as Jack's wicked brother Ernest."],
      ["How does Cecily feel about the 'wicked' Ernest?",["Afraid","Delighted and already fascinated","Angry","Bored"],1,"She has romanticised him for months and is thrilled to meet him."],
      ["How do we know Cecily has thought about Ernest before?",["She has his photo","She has written about him in her diary","Her uncle told her","She met him in town"],1,"Cecily's diary records a whole imaginary romance with Ernest."]
    ],
    tf:[
      ["Miss Prism is Cecily's mother.",false,"She is Cecily's governess, not a relative."],
      ["Cecily loves studying German.",false,"She tries hard to avoid the German lesson."],
      ["Algernon pretends to be Jack's brother Ernest.",true,"He uses the false identity to meet Cecily."],
      ["Cecily has already imagined a romance with Ernest.",true,"She invented it in her diary before meeting him."],
      ["Dr. Chasuble is a doctor of medicine.",false,"He is the parish rector (a priest)."],
      ["Miss Prism has warm feelings for Dr. Chasuble.",true,"Their scenes hint at a shy mutual attraction."]
    ],
    writing:[
      {task:"Write a diary entry as Cecily about meeting 'Ernest' for the first time.",
       target:"60–80 words",
       tips:["Use the past simple to tell what happened.","Add feelings: I felt…, I was so…","Start with the date, as in a real diary."],
       starters:["Today, at last, I met…","He was even more … than I imagined.","I felt…"]},
      {task:"Describe a person you imagined before you actually met them. Were they how you expected?",
       target:"60–80 words",
       tips:["Contrast expectation and reality: I thought… but in fact…","Use past tenses.","Finish with how you felt afterwards."],
       starters:["Before I met …, I imagined…","When I finally met them,…","In the end,…"]}
    ]},
  { n:5, title:"In mourning",
    sum:"Jack returns to the Manor House dressed in deep black, announcing that his 'brother Ernest' has died in Paris. But at that very moment Algernon is in the house, alive and still pretending to be Ernest! In the confusion, both men secretly ask Dr. Chasuble to christen them 'Ernest' that same afternoon.",
    vocab:[
      ["MOURNING","black clothes worn to show grief after a death"],
      ["FUNERAL","a ceremony for a dead person"],
      ["CHRISTEN","to give someone a name in a church ceremony"],
      ["GRIEF","very great sadness"],
      ["CEREMONY","a formal set of actions for an occasion"],
      ["CONFUSION","a situation that is unclear or mixed up"],
      ["ANNOUNCE","to tell people something officially"],
      ["DECEASED","dead"],
      ["CHILL","a slight illness caused by cold"],
      ["REQUEST","to ask for something formally"],
      ["SUDDEN","happening quickly and unexpectedly"],
      ["SORROW","a feeling of deep sadness"]
    ],
    comp:[
      ["How does Jack arrive at the Manor House?",["In bright clothes","Dressed in black mourning","On a horse","In a hurry to leave"],1,"Jack appears in deep mourning to 'bury' his invented brother."],
      ["Why is Jack in mourning?",["His aunt died","He says his brother Ernest has died","He lost his money","His dog died"],1,"He has decided to kill off the fictional Ernest."],
      ["Where did 'Ernest' supposedly die?",["London","Paris","Rome","The country"],1,"Jack claims his brother died in Paris."],
      ["What did 'Ernest' supposedly die of?",["An accident","A severe chill","Old age","Hunger"],1,"Jack says his brother died of a chill."],
      ["What problem appears when Jack announces the death?",["Nobody listens","Algernon is there, alive, pretending to be Ernest","Lady Bracknell arrives","Cecily faints"],1,"The 'dead' brother is standing in the house as Algernon's disguise."],
      ["Who introduces the living 'Ernest' to Jack?",["Miss Prism","Cecily","Dr. Chasuble","Lane"],1,"Cecily proudly presents Jack's 'brother'."],
      ["What do both men secretly ask Dr. Chasuble to do?",["Hold a funeral","Christen them with the name Ernest","Marry them at once","Keep a secret"],1,"Each man privately arranges to be re-christened Ernest."],
      ["When do the men want to be christened?",["Next year","That same afternoon","On Sunday","Never"],1,"They both ask for the christening that afternoon."]
    ],
    tf:[
      ["Jack announces that his brother is getting married.",false,"He announces that his brother Ernest has died."],
      ["Jack wears black to show he is in mourning.",true,"He dresses in deep mourning for the 'dead' Ernest."],
      ["Algernon is pretending to be the dead brother Ernest.",true,"He is very much alive at the house as 'Ernest'."],
      ["'Ernest' supposedly died in London.",false,"Jack says he died in Paris, of a chill."],
      ["Both men decide they want to be christened Ernest.",true,"Each wants the name to please the woman he loves."],
      ["Dr. Chasuble refuses to christen anyone.",false,"He agrees to perform the christenings."]
    ],
    writing:[
      {task:"Write Jack's short announcement to the household that his brother Ernest has died. Make it sound sad and serious.",
       target:"50–70 words",
       tips:["Use formal, serious language.","Use the past simple: died, caught, passed away.","Show grief with adjectives: terrible, sudden, sad."],
       starters:["I have very sad news…","My poor brother Ernest…","He died suddenly in…","We will all miss him."]},
      {task:"Write about a time there was a funny misunderstanding, or when you (or someone) pretended to be someone else.",
       target:"60–80 words",
       tips:["Use past tenses to narrate.","Sequence events: first, then, suddenly, in the end.","End with what happened or what you learned."],
       starters:["One day,…","At first everyone thought…","But then…","In the end,…"]}
    ]},
  { n:6, title:"The engagement",
    sum:"Alone with Cecily, Algernon (still 'Ernest') declares his love. To his surprise, Cecily tells him they have already been engaged for three months — she has invented the whole romance in her diary, complete with love letters and a quarrel. She, too, could only love a man named Ernest, so Algernon rushes off to be christened.",
    vocab:[
      ["ENGAGEMENT","the agreement between two people to marry"],
      ["DIARY","a daily record of your thoughts and events"],
      ["RING","a circle of metal worn on the finger"],
      ["LETTER","a written message sent to someone"],
      ["DECLARE","to say something openly and firmly"],
      ["DEVOTED","very loving and loyal"],
      ["BELOVED","a person who is deeply loved"],
      ["INVENT","to make up something that is not real"],
      ["SINCERE","honest and truly meant"],
      ["BLUSH","to become red in the face from emotion"],
      ["ROMANCE","a love relationship"],
      ["DARLING","a person you love very much"]
    ],
    comp:[
      ["Who declares his love to Cecily?",["Jack","Algernon (as Ernest)","Dr. Chasuble","Mr. Cardew"],1,"Algernon, still pretending to be Ernest, proposes to Cecily."],
      ["How long does Cecily say they have been engaged?",["One day","About three months","Two years","They are not engaged"],1,"To his shock, she says their engagement is already three months old."],
      ["Where did Cecily record their romance?",["In letters to Jack","In her diary","In a newspaper","In a photo album"],1,"Cecily's diary contains the entire imaginary relationship."],
      ["What did Cecily invent about the romance?",["Nothing","Love letters, the engagement and even a quarrel","A wedding date","A journey abroad"],1,"She wrote his love letters herself and invented a break-up and reconciliation."],
      ["How does Algernon feel about Cecily's diary romance?",["Angry","Delighted and charmed","Bored","Frightened"],1,"He is enchanted by her imagination."],
      ["What name must Cecily's true love have?",["Jack","Algernon","Ernest","Any name"],2,"Like Gwendolen, Cecily says she could only love a man called Ernest."],
      ["What does Algernon hurry off to arrange?",["A wedding","To be christened Ernest","A trip to Paris","A party"],1,"He rushes to Dr. Chasuble to get the name Ernest."],
      ["Is Algernon's real name Ernest?",["Yes","No","It is his middle name","Nobody knows"],1,"His real name is Algernon; 'Ernest' is a disguise."]
    ],
    tf:[
      ["Cecily says she has only just met Ernest.",false,"She says they have been engaged for three months — in her imagination."],
      ["Cecily kept a diary about their romance.",true,"The whole relationship is written in her diary."],
      ["Cecily wrote love letters to herself as if from Ernest.",true,"She invented his letters and even a quarrel."],
      ["Cecily could happily love a man of any name.",false,"She insists her love must be called Ernest."],
      ["Algernon decides to be christened Ernest.",true,"He hurries off to arrange it with Dr. Chasuble."],
      ["Algernon's real name is Ernest.",false,"His real name is Algernon Moncrieff."]
    ],
    writing:[
      {task:"Write a romantic diary entry as Cecily inventing a special moment with 'Ernest'.",
       target:"60–80 words",
       tips:["Use the past simple and lots of feeling words.","Describe the place and what 'Ernest' said.","Make it dramatic and romantic, like Cecily would."],
       starters:["This afternoon, my dear Ernest…","He looked at me and said…","My heart…","I shall never forget…"]},
      {task:"Is it good or bad to imagine things that have not really happened? Give your opinion with reasons.",
       target:"60–80 words",
       tips:["State your opinion first.","Give reasons with 'because' and examples.","Finish with a short conclusion."],
       starters:["In my opinion, imagination…","On the good side,…","However,…","In conclusion,…"]}
    ]},
  { n:7, title:"Afternoon tea",
    sum:"Gwendolen arrives at the Manor House and meets Cecily. At first they are charming to each other — until each discovers she is engaged to 'Ernest'. Over a very polite but sharp afternoon tea, the rivalry grows. Then Jack and Algernon appear, the truth about their names comes out, and the two furious women unite against them.",
    vocab:[
      ["AFTERNOON","the part of the day after midday"],
      ["SUGAR","the sweet substance added to tea"],
      ["RIVAL","a person who competes against another"],
      ["POLITE","showing good manners"],
      ["QUARREL","an angry argument"],
      ["DISCOVER","to find out something new"],
      ["TENSION","a feeling of nervous strain or hostility"],
      ["DECEPTION","the act of making someone believe a lie"],
      ["UNITE","to join together"],
      ["FURIOUS","very angry"],
      ["APOLOGY","a statement saying you are sorry"],
      ["MANNERS","polite ways of behaving"]
    ],
    comp:[
      ["Who arrives at the Manor House in this chapter?",["Lady Bracknell","Gwendolen","Miss Prism","Mr. Cardew"],1,"Gwendolen follows Jack to the country and meets Cecily."],
      ["How do Gwendolen and Cecily treat each other at first?",["Rudely","Politely and warmly","With silence","With fear"],1,"They are charming to each other until the confusion begins."],
      ["What do the two women discover during tea?",["They are cousins","They are both engaged to 'Ernest'","They dislike tea","They went to the same school"],1,"Each believes she is engaged to a man called Ernest."],
      ["How does the rivalry show itself at the tea table?",["They shout","Through very polite but cutting remarks","They leave at once","They cry"],1,"They stay outwardly polite while making sharp, hidden attacks (sugar, cake, etc.)."],
      ["Who appears and causes the truth to come out?",["Lady Bracknell","Jack and Algernon","Dr. Chasuble","Lane"],1,"The two men arrive and the deception is exposed."],
      ["What is the truth about the men's names?",["Both really are Ernest","Neither is really named Ernest","Only Jack is Ernest","Only Algernon is Ernest"],1,"Neither Jack nor Algernon is actually called Ernest."],
      ["What do Gwendolen and Cecily do when they learn the truth?",["Forgive the men at once","Unite against the men","Leave forever","Laugh happily"],1,"The women join forces against the two deceivers."],
      ["Why were both women deceived in the same way?",["Both men used the false name Ernest","They are sisters","They read the same book","They are twins"],0,"Each man had pretended to be 'Ernest' to the woman he loved."]
    ],
    tf:[
      ["Gwendolen and Cecily are polite when they first meet.",true,"They are charming to each other at the start."],
      ["Both women believe they are engaged to Ernest.",true,"This is the cause of their comic quarrel."],
      ["The afternoon tea scene is openly violent.",false,"It is extremely polite on the surface, but full of hidden rivalry."],
      ["Jack's real name turns out to be Ernest.",false,"At this point neither man is really named Ernest."],
      ["The women discover the men lied about their names.",true,"The men's deception is exposed."],
      ["In the end the women take the men's side.",false,"They unite against the men."]
    ],
    writing:[
      {task:"Write part of the afternoon-tea conversation between Gwendolen and Cecily. Keep it very polite but full of hidden rivalry.",
       target:"60–90 words",
       tips:["Write it as a dialogue with names.","Use polite phrases that hide real feelings.","Show tension through short, sharp replies."],
       starters:["GWENDOLEN: What a charming garden…","CECILY: I am so glad you like it…","GWENDOLEN: May I ask…","CECILY: With pleasure…"]},
      {task:"Have you ever told a small lie that grew bigger and caused problems? Describe what happened.",
       target:"70–90 words",
       tips:["Use past tenses to narrate.","Sequence with first, then, after that, finally.","End by saying what you learned."],
       starters:["Once, I told a small lie about…","At first it seemed harmless, but then…","In the end,…"]}
    ]},
  { n:8, title:"The perfect match",
    sum:"The women forgive the men once they promise to be re-christened Ernest. Then Lady Bracknell arrives. She refuses Algernon's engagement to Cecily — until she learns that Cecily has a large fortune, and suddenly calls it a perfect match. But Jack, as Cecily's guardian, refuses his consent unless Lady Bracknell allows him to marry Gwendolen. Deadlock.",
    vocab:[
      ["FORGIVE","to stop being angry with someone"],
      ["CONSENT","official permission or agreement"],
      ["INHERIT","to receive money or property from a relative"],
      ["WEALTHY","having a lot of money; rich"],
      ["GUARDIAN","an adult legally responsible for a young person"],
      ["PERMISSION","when you allow someone to do something"],
      ["STUBBORN","refusing to change your mind"],
      ["CONDITION","something that must happen first"],
      ["RESPECTABLE","considered good and proper by society"],
      ["FORTUNE","a very large amount of money"],
      ["APPROVE","to agree that something is good"],
      ["DEADLOCK","a situation where no agreement is possible"]
    ],
    comp:[
      ["Why do the women finally forgive the men?",["The men give them gifts","The men agree to be re-christened Ernest","Lady Bracknell orders it","They forget the lie"],1,"Gwendolen and Cecily forgive them for the sake of the beloved name."],
      ["Who arrives at the Manor House following Gwendolen?",["Miss Prism","Dr. Chasuble","Lady Bracknell","Mr. Cardew"],2,"Lady Bracknell follows her daughter to the country."],
      ["How does Lady Bracknell first react to Algernon's engagement to Cecily?",["She is delighted","She disapproves","She cries","She says nothing"],1,"At first she rejects the match, knowing nothing of Cecily's family."],
      ["What changes Lady Bracknell's mind about Cecily?",["Cecily's beauty","Cecily's large fortune","Jack's request","Dr. Chasuble's words"],1,"When she hears Cecily is very rich, she suddenly approves."],
      ["What does Lady Bracknell call the match once she knows about the money?",["A mistake","A perfect / suitable match","A scandal","An impossible idea"],1,"Cecily instantly becomes, in her eyes, a most attractive young lady."],
      ["Who is Cecily's legal guardian?",["Algernon","Lady Bracknell","Jack","Dr. Chasuble"],2,"As guardian, Jack must give consent for Cecily to marry."],
      ["What condition does Jack set?",["More money","He will allow Cecily's marriage only if he may marry Gwendolen","A church wedding","A public apology"],1,"Jack uses his power as guardian to bargain."],
      ["What is the result of Jack's condition?",["Everyone agrees","A deadlock","Cecily refuses Algernon","Lady Bracknell leaves"],1,"Neither Jack nor Lady Bracknell will give way, so they are stuck."]
    ],
    tf:[
      ["The women refuse to forgive the men.",false,"They forgive them once the name problem seems solvable."],
      ["Lady Bracknell approves of Cecily after learning she is wealthy.",true,"Cecily's fortune changes everything for her."],
      ["Jack is Cecily's guardian.",true,"This gives him the power to block her marriage."],
      ["Jack agrees to Cecily's marriage with no conditions.",false,"He sets a clear condition about Gwendolen."],
      ["Lady Bracknell immediately allows Jack to marry Gwendolen.",false,"She refuses, and a deadlock follows."],
      ["Cecily has a large fortune.",true,"Her wealth is why Lady Bracknell changes her mind."]
    ],
    writing:[
      {task:"Write a formal letter from Jack to Lady Bracknell asking for permission to marry Gwendolen.",
       target:"60–90 words",
       tips:["Use a formal opening and closing (Dear Lady Bracknell / Yours sincerely).","Be polite and give reasons.","Use 'would' and 'I hope' for politeness."],
       starters:["Dear Lady Bracknell,","I am writing to ask…","I would be most grateful if…","Yours sincerely, Jack Worthing"]},
      {task:"Do you think parents should approve of who their children marry? Give your opinion with reasons.",
       target:"80–100 words",
       tips:["State your opinion, then give two reasons.","Use linkers: firstly, secondly, however, in conclusion.","Consider both sides before your conclusion."],
       starters:["In my opinion,…","Firstly,…","On the other hand,…","To sum up,…"]}
    ]},
  { n:9, title:"The handbag returns to its owner",
    sum:"Lady Bracknell suddenly recognises Miss Prism as a nursemaid who, years ago, lost a baby: she absent-mindedly left the child in a handbag at Victoria Station and put her novel in the pram. That baby was Jack! He is really the son of Lady Bracknell's sister — Algernon's elder brother — and was named after his father, General Ernest John Moncrieff. So Jack's real name is Ernest, and everyone can marry at last.",
    vocab:[
      ["HANDBAG","a bag carried by hand for personal things"],
      ["MANUSCRIPT","the written pages of a book before printing"],
      ["NURSEMAID","a woman employed to look after children"],
      ["PRAM","a small carriage for pushing a baby in"],
      ["IDENTITY","who a person really is"],
      ["NEPHEW","the son of your brother or sister"],
      ["GENERAL","a very high-ranking army officer"],
      ["REVEAL","to make known something hidden"],
      ["RELATION","a member of your family"],
      ["CHRISTENING","the ceremony of naming and baptising"],
      ["EARNEST","serious and sincere"],
      ["REUNION","a happy meeting again after a long time"]
    ],
    comp:[
      ["Who does Lady Bracknell suddenly recognise?",["Dr. Chasuble","Miss Prism","Cecily","Gwendolen"],1,"She recognises Miss Prism from twenty-eight years before."],
      ["What was Miss Prism's job long ago?",["A cook","A nursemaid","A shop owner","A teacher of music"],1,"She had been a nursemaid in Lady Bracknell's family."],
      ["What did Miss Prism accidentally do with the baby?",["Left it on a train","Put it in a handbag and left it at the station","Gave it to a stranger","Took it abroad"],1,"Distracted, she put the baby in a handbag and left it at Victoria Station."],
      ["What did she put in the pram instead of the baby?",["Some clothes","The manuscript of her novel","A dog","Nothing"],1,"She had absent-mindedly placed her three-volume novel in the pram."],
      ["Whose lost baby was it, in fact?",["Dr. Chasuble's","Lady Bracknell's sister's son","Miss Prism's own","A stranger's"],1,"The lost baby was the son of Lady Bracknell's late sister — so it was Jack."],
      ["Who turns out to be Jack's younger brother?",["Dr. Chasuble","Algernon","Mr. Cardew","No one"],1,"Jack is really Algernon's elder brother."],
      ["What is Jack's real first name?",["Jack","John","Ernest","Thomas"],2,"He was named after his father, General Ernest John Moncrieff, so his name really is Ernest."],
      ["What does Jack say he has learned at the very end?",["That money matters most","The vital importance of being earnest","Never to tell the truth","That names do not matter"],1,"Jack realises 'the vital Importance of Being Earnest' — the play's final pun."]
    ],
    tf:[
      ["Miss Prism once worked as a nursemaid.",true,"She was a nursemaid in Lady Bracknell's household."],
      ["She put the baby in the pram and the manuscript in the handbag.",false,"She did the opposite: the baby went in the handbag, the manuscript in the pram."],
      ["Jack turns out to be Algernon's brother.",true,"Jack is Algernon's elder brother."],
      ["Jack's real name is Ernest.",true,"He was christened Ernest John after his father."],
      ["Jack is Lady Bracknell's nephew.",true,"He is the son of her late sister."],
      ["In the end nobody is able to get married.",false,"All the couples are finally free to marry."]
    ],
    writing:[
      {task:"Write the final scene in your own words: how does each main character feel when the truth is revealed?",
       target:"80–100 words",
       tips:["Name each character and their feeling.","Use feelings vocabulary: relieved, shocked, delighted, embarrassed.","Keep your tenses consistent."],
       starters:["When the truth comes out, Jack feels…","Gwendolen is…","Lady Bracknell…","In the end, everyone…"]},
      {task:"The play is a comedy about lies, names and identity. What message do you think Wilde is giving? Give your opinion.",
       target:"80–100 words",
       tips:["State the message clearly in your first sentence.","Support it with an example from the play.","Use linkers and finish with a conclusion."],
       starters:["I think Wilde is showing that…","For example, in the play…","In my opinion, the message is…","In conclusion,…"]}
    ]}
];

const READINGS = {
1:["Algernon Moncrieff lived in a fashionable flat in the centre of London, where his servant Lane looked after everything. One afternoon, while Algernon was playing the piano, his friend Jack Worthing arrived from the country. In town everybody knew Jack by the name of ‘Ernest’, and he had come to London for one special reason: he wanted to ask Gwendolen, Algernon’s beautiful cousin, to marry him.",
"Before Jack could say anything, Algernon began to tease him. He had found a silver cigarette case that Jack had left behind on an earlier visit. Jack asked for it back at once, but Algernon refused to give it to him. ‘First you must explain something,’ he said. ‘Inside there is a message: “From little Cecily, with her fondest love to her dear Uncle Jack.” You told me your name was Ernest, not Jack. So who is Cecily, and why does she call you her uncle?’",
"Jack saw that he had to tell the truth. In the country, he explained, he was known as Jack Worthing, and he was the guardian of a young girl called Cecily Cardew. Because he had to be a serious and responsible example for her, life in the country was rather quiet and dull.",
"So Jack had invented a wicked younger brother called Ernest, a brother who was always in trouble in the city. Whenever Jack wanted to escape to London and enjoy himself, he simply said that poor Ernest was in difficulty again and needed his help. In town he then used the name Ernest himself.",
"Algernon laughed, because he had exactly the same kind of secret. He had invented a sick friend called Bunbury, who lived in the country and was always ill. Whenever Algernon wanted to avoid a boring dinner with his aunt, Lady Bracknell, he said that dear Bunbury had taken a turn for the worse and needed him.",
"‘You are a Bunburyist,’ Algernon said happily, ‘just like me!’ The two friends understood each other perfectly. But Jack said that if Gwendolen accepted him, he would ‘kill’ his brother Ernest for ever and live an honest life. He did not yet know how difficult that promise would be to keep."],
2:["That afternoon Lady Bracknell and her daughter Gwendolen were coming to tea. Algernon had asked Lane to prepare cucumber sandwiches especially for his aunt, who was very particular about such things. But while he waited, Algernon grew hungry. He ate one sandwich, then another, and before he knew it the whole plate was empty.",
"When Lady Bracknell arrived, she sat down and asked for the cucumber sandwiches. Algernon looked at the empty plate in great surprise and quickly called Lane. The butler said, with a perfectly serious face, that there had been no cucumbers in the market that morning, ‘not even for ready money’. Lady Bracknell accepted this strange excuse without question.",
"After a while, Lady Bracknell went with Algernon into the music room to choose the songs for her next party. This was exactly the chance that Jack had been waiting for: at last he was alone with Gwendolen.",
"Nervously, Jack told Gwendolen how much he admired her. Gwendolen was delighted to hear it. ‘I have always wanted to love a man called Ernest,’ she said. ‘There is something in that name that inspires absolute confidence. From the moment I heard that Algernon had a friend named Ernest, I knew that I would love you.’",
"Jack asked her, feeling worried, ‘But surely you could still love me if my name were not Ernest?’ Gwendolen answered that Ernest was the only truly safe and beautiful name for a husband. Poor Jack decided, secretly, that he must be christened Ernest as soon as he possibly could.",
"Then he went down on one knee and asked Gwendolen to marry him, and she happily accepted. But at that very moment Lady Bracknell came back into the room — and she was not at all pleased to find her daughter sitting on the floor beside a kneeling young man."],
3:["Lady Bracknell told Gwendolen to wait outside in the carriage. Then she sat down, took out a small notebook, and said that she would interview Jack herself. In her opinion, an engagement was far too serious a matter to be left to the young people themselves.",
"She began her questions. Did Jack smoke? Yes, he did. ‘I am glad to hear it,’ she said. ‘A man should always have an occupation of some kind.’ How old was he? How much money did he have each year? Where were his houses? Jack answered everything well: he had a comfortable income and a good house in town as well as a place in the country.",
"Then came the most important question of all — his family. Here Jack became a little embarrassed. He explained that, unfortunately, he had lost both his parents when he was very young. In fact, the truth was stranger than that: he did not actually know who his parents were.",
"He told her the whole story. When he was a baby, a kind and wealthy old gentleman named Thomas Cardew had found him in the most unusual place — inside a large black leather handbag, left in the cloakroom at Victoria Station. Mr Cardew had adopted the baby and given him the name Worthing.",
"Lady Bracknell was astonished and deeply shocked. ‘To be born, or at least brought up, in a handbag,’ she said coldly, ‘shows a contempt for the ordinary decencies of family life.’ She could not possibly allow her only daughter to marry a man who had begun his life in a cloakroom.",
"Before she left, she gave Jack some firm advice: he must ‘acquire some relations as soon as possible’, and produce at least one parent before the end of the social season. Then she rose to her feet and swept out of the room, leaving Jack alone and very worried indeed."],
4:["Meanwhile, far away in the country, life was calm and peaceful at Jack’s Manor House. In the pretty garden, in the warm afternoon sun, his young ward Cecily was supposed to be studying her German lesson with her governess, Miss Prism.",
"But Cecily did not enjoy her lessons at all. She much preferred to water the flowers or to write in her diary, where she kept all her secret thoughts and dreams. Miss Prism, a serious and proper lady, kept telling her that German was very important — although Miss Prism herself was really far more interested in Dr Chasuble, the kind local rector, who often came to visit.",
"When Miss Prism and Dr Chasuble went off for a quiet walk together, Cecily was left alone in the garden. A moment later the servant announced a visitor: Mr Ernest Worthing. It was Algernon — but he had come to the country pretending to be Jack’s wicked younger brother, the famous Ernest!",
"Cecily was absolutely delighted. For many months she had imagined this romantic, wicked brother, and now here he was, standing in front of her: young, elegant, charming and handsome. She looked at him and thought, with some disappointment, that he did not really look very wicked at all.",
"They walked and talked and laughed together in the garden, and Cecily liked him more and more with every minute. Algernon, for his part, fell in love with her almost at once, and completely forgot that he was only playing a part.",
"But there was danger in the air. At that very time, in London, the real Jack had finally decided that it was time to ‘kill’ his imaginary brother Ernest for ever. So while Jack was quietly preparing his sad news, Algernon was cheerfully playing the role of that very brother — and nobody in the country suspected the truth."],
5:["Soon Jack himself arrived home, but he looked completely different from usual. He was dressed all in black, from head to foot, and his face was sad and serious. He had come to carry out the final part of his plan.",
"He announced some terrible news to Miss Prism and Dr Chasuble: his poor brother Ernest, he said, had died very suddenly in Paris, of a severe chill. Of course, it was all invented — this was simply Jack’s way of getting rid of the troublesome Ernest once and for all.",
"But then something dreadful happened. Cecily came running joyfully into the garden and cried, ‘Uncle Jack, wonderful news — your brother is here! Your brother Ernest has come all the way from town to visit us.’ And there, smiling calmly, stood Algernon, very much alive.",
"Jack was shocked and furious. He could hardly bring himself to shake hands with this false ‘brother’, and yet he could not possibly explain the truth in front of Cecily and the others. With great difficulty, he had to pretend to be pleased to see him.",
"Now both young men found themselves in exactly the same difficult situation. Jack was in love with Gwendolen, and Algernon was in love with Cecily — and both of the young ladies, as they well knew, loved the name Ernest above every other name in the world.",
"So, separately and in secret, each man went quietly to Dr Chasuble with the very same strange request. Each one asked to be christened again, that very afternoon, with the name Ernest. The good rector was rather surprised by all this, but he kindly agreed to prepare the ceremony for later that day."],
6:["When at last Algernon found himself alone with Cecily in the garden, he decided that the time had come to tell her the truth about his feelings. He said that he loved her more than anyone else in the whole world, and he asked her to be his wife.",
"To his very great surprise, Cecily answered quite calmly that they were already engaged — and had been for the last three months. Algernon stared at her, completely confused, and asked her what she could possibly mean.",
"Then she showed him her diary. In its pages she had written the entire story of their romance: the exact day on which ‘Ernest’ had first declared his love for her, the beautiful love letters he had sent her (which, in fact, she had written herself), a dramatic quarrel between them, and, naturally, a happy reconciliation soon afterwards.",
"Algernon was charmed and amazed by her wonderful imagination. He had never in his life met such a romantic and inventive young lady, and he felt extremely lucky that she had chosen to fall in love with him.",
"But then Cecily explained something that suddenly worried him. ‘There is just one thing I must tell you,’ she said seriously. ‘I could never marry a man who was not called Ernest. That name has always meant absolutely everything to me.’",
"Algernon turned pale, because his real name was not Ernest at all. Making a quick excuse, he hurried out of the garden and rushed off to find Dr Chasuble. Just like Jack, he now urgently needed to be christened Ernest — and there was clearly no time to lose."],
7:["That same afternoon another visitor arrived at the Manor House. It was Gwendolen, who had travelled all the way from London to look for Jack. Cecily welcomed her politely, and the two young ladies sat down together in the garden to talk.",
"At first they were charming to each other, and in only a few minutes they seemed to become good friends. But then they made a surprising discovery. Gwendolen said proudly that she was engaged to Mr Ernest Worthing. ‘How very strange,’ replied Cecily, ‘because I am engaged to Mr Ernest Worthing too!’",
"In a moment the two new friends had become rivals. Each was completely certain that the other must be mistaken, and each was determined not to give up her Ernest. They tried hard to stay calm and polite, but their words grew sharper and colder by the minute.",
"Then tea was served, and the quiet battle continued. With a sweet smile, Cecily asked Gwendolen whether she took sugar. ‘No sugar, thank you,’ said Gwendolen coldly — and Cecily calmly dropped four large lumps into her cup. When Gwendolen asked for bread and butter, she was given a big slice of rich cake instead. Behind every polite sentence there was a small, clever attack.",
"At last Jack and Algernon appeared together in the garden, and the whole truth finally came out. Neither of them was really called Ernest. Both had lied to the very girl he loved, and now there was no way to hide it.",
"Gwendolen and Cecily were shocked and deeply hurt. But now they understood that they had both been deceived in exactly the same way, by exactly the same trick. Feeling united, they took each other by the hand, turned their backs on the two young men, and walked proudly into the house together."],
8:["The two young men followed the ladies into the house and did their best to explain themselves. They said that they had only lied because they were so much in love, and — most importantly — that they were both perfectly ready to be christened ‘Ernest’ that very afternoon.",
"This promise, at last, softened the ladies’ hearts. Gwendolen and Cecily decided to forgive them, and for a happy moment it seemed that everything would end well after all.",
"But then Lady Bracknell herself arrived. She had followed Gwendolen all the way from London, and she was quite determined to stop the marriage. She still refused, absolutely and completely, to allow her daughter to marry Jack.",
"When she learned that her nephew Algernon wished to marry Cecily, she did not approve of that either — at least, not until she heard about Cecily’s money. It turned out that Cecily had a very large fortune indeed. At once Lady Bracknell smiled warmly, decided that Cecily was a most charming and sensible girl, and declared her ‘a perfect match’ for Algernon.",
"But now a new problem appeared. Jack was Cecily’s legal guardian, and his permission was needed before she could marry anyone. And Jack firmly refused to give it. He would only allow Cecily to marry Algernon, he said, on one condition: that Lady Bracknell allowed him to marry Gwendolen.",
"Lady Bracknell would not agree to this, and Jack would not change his mind. Neither side would give way even a little, and so they reached a complete deadlock. For a while it really seemed that nobody in the house would be able to marry at all."],
9:["Just at that difficult moment, Dr Chasuble happened to mention the name of Miss Prism. The moment she heard it, Lady Bracknell turned pale and demanded to see the governess at once. When Miss Prism came into the room, Lady Bracknell fixed her with a hard, cold stare.",
"Twenty-eight years before, she said, Miss Prism had worked as a nursemaid in her family. One day she had left the house for a walk, taking a baby with her in its pram — and she had never come back. Both the nursemaid and the baby had simply disappeared.",
"Miss Prism, frightened and ashamed, confessed the truth at last. On that terrible morning, by a dreadful mistake, she had placed the manuscript of a novel she was writing into the baby’s pram, and had put the baby itself into a large black handbag. In her confusion, she had left the handbag in the cloakroom at Victoria Station.",
"Jack listened to all this with growing excitement. He rushed upstairs and returned a moment later carrying an old black handbag. He showed it to Miss Prism, who examined it carefully and said that yes, without any doubt, it was hers — she recognised it perfectly.",
"So the great mystery was solved at last. Jack himself was that lost baby. He was the son of Lady Bracknell’s own sister, which meant, wonderfully, that he was really Algernon’s elder brother.",
"And his real name? Following the family tradition, he had been named after his father. His father had been General Ernest John Moncrieff. So Jack’s true name had been Ernest all along, without his ever knowing it! Now nothing stood in the way of happiness. Jack could marry Gwendolen, Algernon could marry Cecily, and even Miss Prism and Dr Chasuble found happiness together. ‘I’ve now realised for the first time in my life,’ said Jack, ‘the vital Importance of Being Earnest.’"]
};

const EVENTS={
1:{ev:["Jack arrives at Algernon’s London flat while his friend is playing the piano.",
"Algernon shows Jack the silver cigarette case he left behind on an earlier visit.",
"The inscription from ‘little Cecily’ forces Jack to explain his double life.",
"Jack confesses that he invented a wicked brother called Ernest to escape to town.",
"Algernon reveals his own trick: a sick imaginary friend called Bunbury.",
"Jack promises to ‘kill’ Ernest for ever if Gwendolen agrees to marry him."],
keys:["piano","cigarette","Cecily","wicked","Bunbury","Gwendolen"]},
2:{ev:["Algernon eats every one of the cucumber sandwiches he ordered for his aunt.",
"Lane covers for him, saying there were no cucumbers in the market that morning.",
"Lady Bracknell goes with Algernon into the music room, leaving Jack with Gwendolen.",
"Jack nervously tells Gwendolen how much he admires her.",
"Gwendolen declares that she has always wanted to love a man called Ernest.",
"Jack goes down on one knee and proposes, and Gwendolen happily accepts."],
keys:["cucumber","Lane","music","admired","Ernest","knee"]},
3:{ev:["Lady Bracknell sends Gwendolen to the carriage and interviews Jack herself.",
"Jack answers the questions about his age, his income and his houses well.",
"When she asks about his family, Jack admits he does not know his parents.",
"He explains that Thomas Cardew found him as a baby in a handbag at Victoria Station.",
"Lady Bracknell is deeply shocked and refuses to allow the marriage.",
"She advises Jack to acquire some relations before the end of the season."],
keys:["carriage","income","parents","Cardew","handbag","relations"]},
4:{ev:["At the Manor House, Cecily tries to avoid her German lesson with Miss Prism.",
"Cecily prefers watering the flowers and writing her secret thoughts in her diary.",
"Miss Prism goes off for a quiet walk with Dr Chasuble, the local rector.",
"A visitor is announced: Algernon, pretending to be Jack’s wicked brother Ernest.",
"Cecily is delighted to meet the romantic brother she has imagined for months.",
"Algernon falls in love with Cecily, just as Jack plans to ‘kill’ Ernest for ever."],
keys:["German","diary","Chasuble","visitor","delighted","imaginary"]},
5:{ev:["Jack comes home dressed all in black, ready to bury his invented brother.",
"He announces that Ernest has died suddenly in Paris of a severe chill.",
"Cecily runs in joyfully to say that ‘brother Ernest’ is at the house.",
"Furious but trapped, Jack must pretend to be pleased to see Algernon.",
"Both men remember that the women they love adore the name Ernest.",
"Each man secretly asks Dr Chasuble to christen him Ernest that afternoon."],
keys:["black","Paris","chill","furious","rector","christened"]},
6:{ev:["Alone in the garden, Algernon tells Cecily he loves her and proposes.",
"Cecily calmly answers that they have already been engaged for three months.",
"She shows him her diary, which records their whole invented romance.",
"Cecily admits she wrote the love letters herself and even invented a quarrel.",
"She warns him that she could never marry a man who was not called Ernest.",
"Algernon turns pale and rushes off to find Dr Chasuble at once."],
keys:["garden","engaged","romance","letters","quarrel","pale"]},
7:{ev:["Gwendolen travels from London to the Manor House and meets Cecily.",
"The two young ladies are charming to each other and seem to become friends.",
"Each discovers that the other says she is engaged to Ernest Worthing.",
"During tea, Cecily attacks politely with sugar lumps and a slice of cake.",
"Jack and Algernon appear, and the truth about their false names comes out.",
"The two women feel united against the men and walk into the house together."],
keys:["charming","rivals","sugar","cake","lied","united"]},
8:{ev:["The men explain that they lied for love and will be christened Ernest.",
"Gwendolen and Cecily decide to forgive them.",
"Lady Bracknell arrives from London, still refusing to accept Jack.",
"She approves of Cecily the moment she learns about her large fortune.",
"Jack, as Cecily’s guardian, refuses his consent unless he may marry Gwendolen.",
"Neither side will give way, and everything ends in a complete deadlock."],
keys:["forgive","fortune","nephew","guardian","permission","deadlock"]},
9:{ev:["Hearing Miss Prism’s name, Lady Bracknell demands to see the governess.",
"She reveals that Miss Prism lost a baby twenty-eight years before.",
"Miss Prism confesses she put her manuscript in the pram and the baby in a handbag.",
"Jack fetches an old black handbag, and Miss Prism recognises it as hers.",
"Jack learns he is the son of Lady Bracknell’s sister and Algernon’s elder brother.",
"Named after General Ernest John Moncrieff, Jack really is Ernest, so all can marry."],
keys:["nursemaid","manuscript","pram","cloakroom","General","Moncrieff"]}
};

return {level:'B1', lead:'Oscar Wilde · retelling · <b>B1 intermediate</b> (≈1,000 headwords)',
  CHAPTERS:CHAPTERS, READINGS:READINGS, EVENTS:EVENTS};
})();
