/* BEING EARNEST - datos nivel A2 (easy retelling).
   Mismo formato que earnest-data-b1.js. */
window.ATTWN_DATA = (function(){
const CHAPTERS = [
  { n:1, title:"The silver case",
    sum:"Jack visits his friend Algernon in London because he wants to marry Gwendolen. Algernon finds Jack’s silver cigarette case with a message from Cecily. Jack must tell the truth about his two names, and Algernon talks about his invented friend Bunbury.",
    vocab:[
      ["CASE","a small box for cigarettes or glasses"],
      ["SILVER","a grey-white metal with a nice shine"],
      ["SERVANT","a person who works in another person’s house"],
      ["FLAT","rooms to live in, on one floor of a building"],
      ["COUSIN","the child of your aunt or uncle"],
      ["GUARDIAN","a person who takes care of a child"],
      ["COUNTRY","land far from the city, with farms and fields"],
      ["SECRET","something you do not tell other people"],
      ["BORING","not interesting"],
      ["EXCUSE","a reason you give to avoid something"],
      ["TRUTH","the real facts, not a lie"],
      ["PROMISE","words that say you will really do something"]
    ],
    comp:[
      ["Where did Algernon live?",["In the country","In a flat in London","At the Manor House","At Victoria Station"],1,"Algernon lived in a nice flat in London."],
      ["What was the name of Algernon’s servant?",["Lane","Ernest","Cardew","Chasuble"],0,"His servant was called Lane."],
      ["Who did Jack want to marry?",["Cecily","Miss Prism","Gwendolen","Lady Bracknell"],2,"Jack loved Gwendolen and wanted to marry her."],
      ["What did Algernon have from Jack?",["A letter","A silver cigarette case","A ring","A diary"],1,"Algernon had Jack’s silver cigarette case."],
      ["Who wrote the words inside the case?",["Gwendolen","Lane","Algernon","Cecily"],3,"The words were from little Cecily to her Uncle Jack."],
      ["Who was Cecily?",["A young girl in Jack’s care","Jack’s sister","Algernon’s cousin","A servant"],0,"Jack was the guardian of a young girl, Cecily."],
      ["What was the name of Algernon’s sick friend?",["Ernest","Worthing","Bunbury","Thomas"],2,"Algernon invented a sick friend called Bunbury."],
      ["What did Jack want to do with his brother Ernest?",["Visit him","Give him money","Write to him","End him for ever"],3,"Jack said that after the wedding, Ernest must die."]
    ],
    tf:[
      ["The story starts in Algernon’s flat in London.",true,"Jack visited Algernon at his London flat."],
      ["The cigarette case was made of gold.",false,"It was a silver cigarette case."],
      ["In London, people called Jack ‘Ernest’.",true,"Jack used the name Ernest in town."],
      ["Cecily was Jack’s daughter.",false,"Cecily was a young girl and Jack was her guardian."],
      ["Bunbury was a real person.",false,"Algernon invented Bunbury as an excuse."],
      ["Jack wanted to marry Gwendolen.",true,"He came to London to ask her."]
    ],
    writing:[
      {task:"Write a short note from Cecily to her Uncle Jack. Ask him when he comes home and tell him news from the garden.",
       target:"30–50 words",
       tips:["Start and end like a friendly note.","Use the present simple for the garden news.","Ask one or two simple questions."],
       starters:["Dear Uncle Jack,","When do you come home?","The garden is…","Love, Cecily"]},
      {task:"You have a secret friend like Bunbury. Write about him or her. What is the friend’s name? Why is this friend useful?",
       target:"30–50 words",
       tips:["Use the present simple: My friend is…, He lives…","Give the friend a name.","Say when you use your excuse."],
       starters:["My secret friend is called…","He lives in…","When I am bored, I say…","This excuse is useful because…"]}
    ]},
  { n:2, title:"No cucumber sandwiches",
    sum:"Lady Bracknell and Gwendolen come to tea, but Algernon eats all the cucumber sandwiches. Jack asks Gwendolen to marry him and she says yes. She loves him because his name is ‘Ernest’.",
    vocab:[
      ["CUCUMBER","a long green vegetable for salads"],
      ["SANDWICH","two pieces of bread with food inside"],
      ["TEA","a hot drink; also a small afternoon meal"],
      ["AUNT","the sister of your mother or father"],
      ["HUNGRY","wanting to eat"],
      ["PLATE","a flat dish for food"],
      ["EMPTY","with nothing inside or on it"],
      ["MARKET","a place where people buy and sell food"],
      ["NERVOUS","a little afraid and worried"],
      ["KNEE","the middle part of your leg, where it bends"],
      ["SMILE","a happy look on your face"],
      ["MARRY","to become husband and wife"]
    ],
    comp:[
      ["Who came to tea with Lady Bracknell?",["Gwendolen","Cecily","Miss Prism","Nobody"],0,"Lady Bracknell came to tea with Gwendolen."],
      ["What special food did Algernon order?",["Cake","Bread and butter","Cucumber sandwiches","Fruit"],2,"Lane made cucumber sandwiches for the aunt."],
      ["Who ate all the sandwiches?",["Lane","Algernon","Jack","Lady Bracknell"],1,"Algernon was hungry and ate them all."],
      ["What was Lane’s excuse?",["The dog ate them","The cook was ill","The plate fell","There were no cucumbers at the market"],3,"Lane said there were no cucumbers at the market."],
      ["Where did Algernon take his aunt?",["To the music room","To the garden","To the station","To the kitchen"],0,"They went to the music room to look at songs."],
      ["What name did Gwendolen love?",["Jack","Ernest","Algernon","John"],1,"She always wanted to love a man called Ernest."],
      ["What did Gwendolen think about the name Jack?",["It was beautiful","It was safe","It was not interesting","It was funny"],2,"She said Jack was not an interesting name."],
      ["Who came back and saw Jack on one knee?",["Lane","Cecily","Miss Prism","Lady Bracknell"],3,"Lady Bracknell returned at that moment."]
    ],
    tf:[
      ["Algernon ordered cucumber sandwiches for his aunt.",true,"He asked Lane to make them."],
      ["Lady Bracknell ate all the sandwiches.",false,"Algernon ate them before she arrived."],
      ["Lane told the truth about the sandwiches.",false,"His excuse about the market was not true."],
      ["Gwendolen said yes to Jack.",true,"She accepted him with a big smile."],
      ["Gwendolen loved the name Ernest.",true,"She said it was a beautiful, safe name."],
      ["Lady Bracknell was happy about the proposal.",false,"She was not happy at all when she saw them."]
    ],
    writing:[
      {task:"Write a short sorry note from Algernon to his aunt about the sandwiches.",
       target:"30–50 words",
       tips:["Say sorry clearly.","Give a funny excuse.","Finish in a polite way."],
       starters:["Dear Aunt Augusta,","I am very sorry about…","I was so hungry that…","Yours, Algernon"]},
      {task:"What is a beautiful name for you? Write about a name you like and say why.",
       target:"30–50 words",
       tips:["Use the present simple.","Give two reasons with ‘because’.","Write about a real or invented name."],
       starters:["My favourite name is…","I like it because…","It sounds…","One day I want to…"]}
    ]},
  { n:3, title:"Lady Bracknell interviews Jack",
    sum:"Lady Bracknell asks Jack many questions about his money and his family. Jack says a rich man found him in a handbag at Victoria Station. Lady Bracknell is shocked and says no to the marriage.",
    vocab:[
      ["INTERVIEW","a meeting with many questions"],
      ["NOTEBOOK","a small book for writing notes"],
      ["MONEY","what you use to buy things"],
      ["FAMILY","parents, children and other relatives"],
      ["PARENTS","your mother and father"],
      ["BABY","a very young child"],
      ["HANDBAG","a bag for personal things"],
      ["STATION","a place where trains stop"],
      ["HUSBAND","the man a woman is married to"],
      ["MARRIAGE","the life of a husband and wife together"],
      ["ADVICE","words that help someone decide"],
      ["WORRIED","afraid that something bad can happen"]
    ],
    comp:[
      ["Where did Gwendolen wait?",["In the garden","In the music room","In the carriage","At the station"],2,"Lady Bracknell sent her outside to the carriage."],
      ["What did Lady Bracknell have in her hand?",["A small notebook","A handbag","A cup of tea","A letter"],0,"She sat down with a small notebook for the interview."],
      ["What did Jack have?",["No money","A house in town and one in the country","Only one small room","A farm"],1,"He had a lot of money and two houses."],
      ["Who found the baby Jack?",["Lady Bracknell","Miss Prism","A policeman","Mr Thomas Cardew"],3,"An old rich man, Mr Thomas Cardew, found him."],
      ["Where was the handbag with the baby?",["On a train","At Victoria Station","In a church","In a garden"],1,"It was in the cloakroom at Victoria Station."],
      ["How did Lady Bracknell feel about the handbag story?",["Shocked","Happy","Bored","Excited"],0,"She was shocked and cried, ‘A handbag?’"],
      ["What was Lady Bracknell’s answer to the marriage?",["Yes","Maybe next year","Ask Gwendolen","No"],3,"She said no to the marriage."],
      ["What advice did she give Jack?",["Get more money","Change his name","Find some parents soon","Move to Paris"],2,"She told him to find a father or a mother."]
    ],
    tf:[
      ["Lady Bracknell interviewed Jack with a notebook.",true,"She asked her questions with a small notebook."],
      ["Jack was poor.",false,"He had a lot of money and two houses."],
      ["Jack knew his real parents.",false,"He did not know his family at all."],
      ["Mr Cardew found the baby in a handbag.",true,"The handbag was at Victoria Station."],
      ["Lady Bracknell said yes to the marriage.",false,"She refused because Jack had no family."],
      ["Jack was very worried at the end.",true,"He stayed alone in the room, very worried."]
    ],
    writing:[
      {task:"You are Lady Bracknell. Write four questions for a person who wants to marry your daughter.",
       target:"30–50 words",
       tips:["Use question words: How much…? Where…? Do you…?","Number your questions.","Ask about money, house and family."],
       starters:["1. How much money…?","2. Where do you…?","3. Do you have…?","4. What is…?"]},
      {task:"Jack was found in a handbag. Write a short story about a strange thing you (or someone) found one day.",
       target:"30–50 words",
       tips:["Use the past simple: found, opened, saw.","Say where and when it happened.","Say how you felt at the end."],
       starters:["One day I found…","It was in…","I opened it and…","I felt…"]}
    ]},
  { n:4, title:"The Manor House",
    sum:"At Jack’s Manor House, Cecily does not want her German lesson with Miss Prism. Then Algernon arrives and pretends to be Jack’s bad brother Ernest. Cecily is very happy to meet him.",
    vocab:[
      ["GARDEN","the place with plants next to a house"],
      ["LESSON","a time when you learn something"],
      ["DIARY","a book where you write about your days"],
      ["FLOWER","the pretty coloured part of a plant"],
      ["TEACHER","a person whose job is to teach"],
      ["PRIEST","a man who works in a church"],
      ["WALK","a trip on foot"],
      ["VISITOR","a person who comes to see you"],
      ["SECRET","something you do not tell other people"],
      ["CHARMING","very nice and pleasant"],
      ["EXCITED","very happy about something new"],
      ["FALSE","not real or not true"]
    ],
    comp:[
      ["Where was Jack’s Manor House?",["In London","In the country","In Paris","Near Victoria Station"],1,"It was a big house in the country."],
      ["Who was Cecily’s teacher?",["Gwendolen","Lady Bracknell","Dr Chasuble","Miss Prism"],3,"Miss Prism was her serious teacher."],
      ["What lesson did Cecily not like?",["German","Music","English","History"],0,"She did not like her German lessons."],
      ["Who did Miss Prism like?",["Jack","Algernon","Dr Chasuble","Lane"],2,"Miss Prism liked the local priest, Dr Chasuble."],
      ["What name did the visitor use?",["Algernon","Ernest Worthing","Bunbury","John"],1,"The servant said, ‘Mr Ernest Worthing is here.’"],
      ["Who was the visitor really?",["Algernon","Jack","Dr Chasuble","Mr Cardew"],0,"It was Algernon, pretending to be the bad brother."],
      ["How did Cecily feel about the visitor?",["Angry","Afraid","Bored","Very excited"],3,"She dreamed about this brother for months."],
      ["Where was the real Jack at this time?",["In the garden","At the church","In London","In Paris"],2,"Jack was in London, preparing his sad story."]
    ],
    tf:[
      ["Cecily loved German lessons.",false,"She wanted to water the flowers instead."],
      ["Cecily wrote her dreams in a diary.",true,"All her secret dreams were in the diary."],
      ["Miss Prism liked Dr Chasuble.",true,"She had a secret: she liked the priest."],
      ["The visitor was Jack’s real brother.",false,"It was Algernon, and the brother was not real."],
      ["Algernon fell in love with Cecily.",true,"He fell in love very fast."],
      ["Everybody knew the truth about the visitor.",false,"Nobody knew the truth."]
    ],
    writing:[
      {task:"Write a diary page for Cecily about the day she met ‘Ernest’.",
       target:"30–50 words",
       tips:["Start with the day: Monday, 14th July.","Use the past simple: met, talked, laughed.","Write about your feelings."],
       starters:["Dear Diary,","Today I met…","He was…","I felt…"]},
      {task:"Describe your perfect garden. What is in it? What do you do there?",
       target:"30–50 words",
       tips:["Use there is / there are.","Name flowers, trees or animals.","Say what you like to do there."],
       starters:["My perfect garden has…","There are…","In the garden I…","I love it because…"]}
    ]},
  { n:5, title:"In mourning",
    sum:"Jack comes home in black clothes and says his brother Ernest is dead. But Algernon is in the house, alive, playing Ernest! In secret, both men ask Dr Chasuble to christen them ‘Ernest’.",
    vocab:[
      ["BLACK","the darkest colour, the colour of night"],
      ["DEAD","not alive"],
      ["NEWS","new information about something"],
      ["COLD","an illness with a bad nose and cough"],
      ["LIE","words that are not true"],
      ["ALIVE","living, not dead"],
      ["SHOCKED","very surprised in a bad way"],
      ["HAND","the part of the body at the end of your arm"],
      ["CHRISTEN","to give someone a name in church"],
      ["PRIEST","a man who works in a church"],
      ["AFTERNOON","the part of the day after twelve o’clock"],
      ["SURPRISED","feeling that something is strange and new"]
    ],
    comp:[
      ["What colour were Jack’s clothes?",["White","Grey","Brown","Black"],3,"He was in black from head to foot."],
      ["What was Jack’s news?",["His aunt was ill","His brother Ernest was dead","He was married","He lost his money"],1,"He said his poor brother Ernest was dead."],
      ["Where did ‘Ernest’ die, in Jack’s story?",["In Paris","In London","At the Manor House","In Rome"],0,"Jack said he died in Paris."],
      ["What killed ‘Ernest’, in Jack’s story?",["An accident","Old age","A bad cold","A fall"],2,"Jack said he was very ill with a bad cold."],
      ["Who ran into the garden with happy news?",["Miss Prism","Cecily","Gwendolen","Lane"],1,"Cecily cried, ‘Your brother Ernest is here!’"],
      ["Who stood there, alive, as ‘Ernest’?",["Dr Chasuble","Mr Cardew","Lane","Algernon"],3,"Algernon smiled calmly, very much alive."],
      ["What did both men ask Dr Chasuble for?",["A christening with the name Ernest","A funeral","A wedding","A dinner"],0,"Each man asked to be christened Ernest."],
      ["When did the men want the christening?",["Next week","On Sunday","That afternoon","Next year"],2,"They asked for it that same afternoon."]
    ],
    tf:[
      ["Jack came home in black clothes.",true,"He wore black from head to foot."],
      ["Jack’s news about Ernest was true.",false,"Ernest was not real, so the news was a lie."],
      ["Cecily was sad when ‘Ernest’ arrived.",false,"She ran in with a happy face."],
      ["Jack told everyone the truth at once.",false,"He could not explain in front of Cecily."],
      ["Both ladies loved the name Ernest.",true,"Jack and Algernon both knew this."],
      ["Dr Chasuble agreed to the christenings.",true,"He was surprised but kind, and he agreed."]
    ],
    writing:[
      {task:"Write Jack’s sad speech to the house: tell them the news about brother Ernest.",
       target:"30–50 words",
       tips:["Use sad, serious words.","Use the past simple: died, was.","Keep the sentences short."],
       starters:["I have very sad news.","My poor brother…","He died in…","We must all be strong."]},
      {task:"Write about a big surprise in your life. What happened? How did you feel?",
       target:"30–50 words",
       tips:["Use the past simple.","Use time words: one day, then, suddenly.","End with your feeling."],
       starters:["One day…","Suddenly…","I could not believe it because…","In the end I felt…"]}
    ]},
  { n:6, title:"The engagement",
    sum:"Algernon asks Cecily to marry him. She says they got engaged three months ago — in her diary! Cecily can only love a man called Ernest, so Algernon runs to get a christening.",
    vocab:[
      ["ENGAGED","with a promise to marry someone"],
      ["WIFE","the woman a man is married to"],
      ["DIARY","a book where you write about your days"],
      ["ROMANCE","a love story between two people"],
      ["LETTER","a written message you send to someone"],
      ["QUARREL","an angry talk between people"],
      ["IMAGINATION","the power to make pictures in your mind"],
      ["LUCKY","with good things happening to you"],
      ["AMAZED","very, very surprised"],
      ["EXCUSE","a reason you give to avoid something"],
      ["CHRISTENING","the church ceremony that gives a name"],
      ["FEELING","something you feel, like love or fear"]
    ],
    comp:[
      ["What did Algernon ask Cecily?",["To be his wife","To play the piano","To write a letter","To make tea"],0,"He said, ‘Please be my wife.’"],
      ["How long were they ‘engaged’, in Cecily’s story?",["One week","One year","Three months","Three days"],2,"She said they got engaged three months ago."],
      ["Where was the whole romance written?",["In a newspaper","In Cecily’s diary","In Jack’s letters","In a school book"],1,"The whole romance was in the pages of her diary."],
      ["Who really wrote ‘Ernest’s’ love letters?",["Ernest","Algernon","Jack","Cecily"],3,"Cecily wrote the beautiful letters herself."],
      ["What was also in the diary story?",["A wedding","A journey","A big quarrel","A dance"],2,"She wrote about a big quarrel and a happy ending."],
      ["How did Algernon feel about the diary?",["Amazed","Angry","Bored","Afraid"],0,"He was amazed by her imagination."],
      ["What name did Cecily want for her husband?",["Algernon","Ernest","Jack","John"],1,"She said, ‘I can only marry a man called Ernest.’"],
      ["What did Algernon run to find?",["A ring","A letter","A train to London","Dr Chasuble"],3,"He ran to Dr Chasuble for a fast christening."]
    ],
    tf:[
      ["Algernon asked Cecily to marry him.",true,"He asked her to be his wife."],
      ["Cecily and Algernon met three months before.",false,"They met that day; the engagement was in her diary."],
      ["Cecily wrote love letters to herself.",true,"She wrote ‘Ernest’s’ letters herself."],
      ["Algernon was angry about the diary.",false,"He was amazed and felt lucky."],
      ["Cecily could marry a man with any name.",false,"Only the name Ernest was good for her."],
      ["Algernon’s real name was Ernest.",false,"His real name was Algernon, so he had a problem."]
    ],
    writing:[
      {task:"Write one page of Cecily’s diary about ‘Ernest’. Invent a romantic moment.",
       target:"30–50 words",
       tips:["Use the past simple.","Add feelings: happy, nervous, excited.","Make it romantic, like Cecily."],
       starters:["Dear Diary,","Today Ernest said…","My heart…","I will never forget…"]},
      {task:"Is it good to imagine stories about your life? Write your opinion.",
       target:"30–50 words",
       tips:["Say your opinion in the first sentence.","Give one reason with ‘because’.","Give one example."],
       starters:["I think imagination is…","It is good because…","But sometimes…","For example,…"]}
    ]},
  { n:7, title:"Afternoon tea",
    sum:"Gwendolen comes to the Manor House and meets Cecily. At tea, both ladies say they are engaged to ‘Ernest Worthing’. Then the truth comes out, and the two ladies unite against Jack and Algernon.",
    vocab:[
      ["TEA","a hot drink; also a small afternoon meal"],
      ["SUGAR","the white sweet thing you put in drinks"],
      ["RIVAL","a person who wants the same thing as you"],
      ["POLITE","with good manners"],
      ["BATTLE","a fight between two sides"],
      ["CUP","a small container for tea or coffee"],
      ["BREAD","a basic food made from flour"],
      ["BUTTER","a soft yellow food made from milk"],
      ["CAKE","a sweet food for parties and teas"],
      ["TRICK","a clever plan to deceive someone"],
      ["SHARP","cutting; a sharp word can hurt"],
      ["HURT","feeling pain in the body or the heart"]
    ],
    comp:[
      ["Who arrived at the Manor House?",["Lady Bracknell","Gwendolen","Miss Prism","Mr Cardew"],1,"Gwendolen came from London to look for Jack."],
      ["How were the ladies at first?",["Friendly","Angry","Silent","Afraid"],0,"They talked in a friendly way, like new friends."],
      ["What name did both ladies say?",["Jack Worthing","Algernon Moncrieff","Bunbury","Ernest Worthing"],3,"Each said she was engaged to Mr Ernest Worthing."],
      ["What did Cecily put in Gwendolen’s cup?",["Milk","Nothing","Four big lumps of sugar","Salt"],2,"Gwendolen said no sugar, but Cecily put in four lumps."],
      ["What did Cecily give instead of bread and butter?",["A big piece of cake","Fruit","Biscuits","Nothing"],0,"She gave her a big piece of cake instead."],
      ["Who came into the garden at last?",["Lady Bracknell and Lane","Jack and Algernon","Dr Chasuble and Miss Prism","Nobody"],1,"The two men arrived and the truth came out."],
      ["What was the truth about the name Ernest?",["Only Jack was Ernest","Only Algernon was Ernest","No man was really Ernest","Both were Ernest"],2,"There was no Ernest at all."],
      ["What did the ladies do at the end?",["They went to London","They cried alone","They forgave the men at once","They walked into the house together"],3,"They took each other by the hand and left together."]
    ],
    tf:[
      ["Gwendolen came to look for Jack.",true,"She travelled from London for him."],
      ["The ladies were rivals from the first minute.",false,"At first they were friendly."],
      ["Both ladies said they were engaged to Ernest Worthing.",true,"That was the big surprise at tea."],
      ["Gwendolen wanted sugar in her tea.",false,"She said, ‘No sugar, thank you.’"],
      ["The truth came out when the men arrived.",true,"No man was really called Ernest."],
      ["At the end, the ladies were angry with each other.",false,"They walked into the house together, like sisters."]
    ],
    writing:[
      {task:"Write a short polite tea dialogue between Gwendolen and Cecily. They are angry inside.",
       target:"30–50 words",
       tips:["Write it as a dialogue with names.","Use polite words: please, thank you.","Show cold feelings with short answers."],
       starters:["CECILY: Do you take sugar?","GWENDOLEN: No, thank you.","CECILY: Some cake?","GWENDOLEN: How kind."]},
      {task:"Write about a small lie that made a big problem. What happened?",
       target:"30–50 words",
       tips:["Use the past simple.","Use first, then, in the end.","Say what you learned."],
       starters:["Once I said…","At first it was easy.","Then…","In the end…"]}
    ]},
  { n:8, title:"The perfect match",
    sum:"The ladies forgive the men because they promise to take the name Ernest. Lady Bracknell arrives and likes Cecily when she hears about her fortune. But Jack says no to that marriage, so there is a deadlock.",
    vocab:[
      ["FORGIVE","to stop being angry with someone"],
      ["PROMISE","words that say you will really do something"],
      ["CARRIAGE","an old vehicle pulled by horses"],
      ["NEPHEW","the son of your brother or sister"],
      ["FORTUNE","a very large amount of money"],
      ["MATCH","two people who are good together"],
      ["GUARDIAN","a person who takes care of a child"],
      ["PERMISSION","the yes you need before you do something"],
      ["CONDITION","something that must happen first"],
      ["DEADLOCK","a situation where nobody can move or win"],
      ["MIND","the part of you that thinks"],
      ["MONEY","what you use to buy things"]
    ],
    comp:[
      ["Why did the ladies forgive the men?",["The men gave them flowers","Lady Bracknell asked them","The men promised to take the name Ernest","They forgot the lie"],2,"The men were ready to change their names."],
      ["Who arrived in a carriage?",["Miss Prism","Lady Bracknell","Dr Chasuble","Mr Cardew"],1,"Lady Bracknell followed Gwendolen from London."],
      ["What was Lady Bracknell’s first answer about Jack and Gwendolen?",["Yes","Maybe","Ask your father","No"],3,"She told Jack, ‘Gwendolen cannot marry you.’"],
      ["What changed her mind about Cecily?",["Cecily’s fortune","Cecily’s sweet face","Jack’s words","Algernon’s tears"],0,"When she heard about the money, everything changed."],
      ["What did Lady Bracknell call Cecily then?",["A poor girl","A charming girl","A bad student","A stranger"],1,"She said, ‘What a charming girl.’"],
      ["Who was Cecily’s guardian?",["Algernon","Lady Bracknell","Jack","Dr Chasuble"],2,"Cecily needed Jack’s permission to marry."],
      ["What was Jack’s condition?",["Lady Bracknell must let him marry Gwendolen","More money for Cecily","A house in London","A church wedding"],0,"He said, ‘Let me marry Gwendolen.’"],
      ["How did the chapter end?",["Everybody agreed","Everybody married","Lady Bracknell left","With a deadlock"],3,"Nobody changed their mind, so there was a deadlock."]
    ],
    tf:[
      ["The men promised to change their names to Ernest.",true,"Dr Chasuble could christen them that afternoon."],
      ["Lady Bracknell stayed in London.",false,"She followed Gwendolen to the Manor House."],
      ["Lady Bracknell liked Cecily from the first moment.",false,"She changed only after she heard about the fortune."],
      ["Cecily had a lot of money.",true,"She had a very large fortune."],
      ["Jack gave his permission with no conditions.",false,"He had one condition about Gwendolen."],
      ["At the end of the chapter, nobody could marry.",true,"It was a complete deadlock."]
    ],
    writing:[
      {task:"Write a polite letter from Jack to Lady Bracknell. Ask for permission to marry Gwendolen.",
       target:"30–50 words",
       tips:["Use Dear… and Yours sincerely.","Be very polite.","Give one good reason."],
       starters:["Dear Lady Bracknell,","I love Gwendolen very much.","Please give me…","Yours sincerely, Jack"]},
      {task:"Money changed Lady Bracknell’s mind. Is money important for a marriage? Write your opinion.",
       target:"30–50 words",
       tips:["Say your opinion first.","Use ‘because’ for your reason.","Finish with a short conclusion."],
       starters:["In my opinion, money is…","This is because…","But love is…","In conclusion,…"]}
    ]},
  { n:9, title:"The handbag returns to its owner",
    sum:"Lady Bracknell recognises Miss Prism, a nursemaid who lost a baby long ago. The baby was Jack! He is Algernon’s big brother, and his real name is Ernest, so everybody can marry.",
    vocab:[
      ["NURSEMAID","a woman whose job is to care for babies"],
      ["PRAM","a small bed on wheels for a baby"],
      ["HANDBAG","a bag for personal things"],
      ["MISTAKE","something you do wrong without wanting to"],
      ["CLOAKROOM","a room in a station where you leave bags"],
      ["MYSTERY","something strange that nobody can explain"],
      ["SISTER","a girl with the same parents as you"],
      ["AUNT","the sister of your mother or father"],
      ["GENERAL","a top army officer"],
      ["EARNEST","serious and honest"],
      ["PALE","with little colour in the face"],
      ["UPSTAIRS","on a higher floor of a house"]
    ],
    comp:[
      ["Whose name changed Lady Bracknell’s face?",["Bunbury’s","Miss Prism’s","Lane’s","Mr Cardew’s"],1,"Dr Chasuble said the name Miss Prism."],
      ["What was Miss Prism’s job long ago?",["A cook","A teacher of music","A shop girl","A nursemaid"],3,"She worked as a nursemaid for the family."],
      ["What did Miss Prism put in the pram?",["Her book","The baby","A handbag","Flowers"],0,"By mistake, she put her book into the pram."],
      ["Where did she leave the handbag?",["On a train","In a church","At Victoria Station","In a garden"],2,"She left it in the cloakroom at Victoria Station."],
      ["What did Jack bring from upstairs?",["A letter","An old black handbag","A diary","A photo"],1,"He came back with the old handbag."],
      ["Who was the lost baby?",["Algernon","Dr Chasuble","Lane","Jack"],3,"Jack was that lost baby."],
      ["Who was Jack’s brother?",["Dr Chasuble","Mr Cardew","Algernon","Lane"],2,"Jack was Algernon’s big brother."],
      ["What was Jack’s real name?",["Ernest","John only","Thomas","Augustus"],0,"He got his father’s name: Ernest John Moncrieff."]
    ],
    tf:[
      ["Miss Prism was a nursemaid twenty-eight years ago.",true,"She worked for Lady Bracknell’s family."],
      ["Miss Prism put the baby in the pram.",false,"She put the baby in a handbag and her book in the pram."],
      ["Jack found the old handbag upstairs.",true,"He ran upstairs and brought it back."],
      ["Jack’s mother was Lady Bracknell’s sister.",true,"So Lady Bracknell was his aunt."],
      ["Algernon was Jack’s father.",false,"Algernon was Jack’s little brother."],
      ["At the end, nobody could marry.",false,"Everybody could marry at last."]
    ],
    writing:[
      {task:"Write the end of the story in your own words. Who marries who? How do they feel?",
       target:"30–50 words",
       tips:["Name the three couples.","Use feeling words: happy, amazed.","Use the present simple or past simple."],
       starters:["At the end,…","Jack marries…","Everybody feels…","It is a happy ending because…"]},
      {task:"Jack’s name was important in this story. Write: is a name important for a person? Why?",
       target:"30–50 words",
       tips:["Give your opinion first.","Use one example from the play.","Finish with a conclusion."],
       starters:["I think a name is…","In the play, Gwendolen…","For me,…","In conclusion,…"]}
    ]}
];

const READINGS = {
1:["Algernon Moncrieff lived in a nice flat in London. His servant was called Lane. One afternoon his friend Jack came to visit. In London people called Jack ‘Ernest’. Jack loved Gwendolen, Algernon’s pretty cousin. He wanted to ask her to marry him.",
"Algernon had Jack’s silver cigarette case. Jack left it at his flat before. Inside the case there were some words. They said: ‘From little Cecily to her dear Uncle Jack.’ Algernon was surprised. ‘Your name is Ernest,’ he said. ‘So who is Jack? And who is Cecily?’",
"Jack told Algernon the truth. In the country his name was Jack. He was the guardian of a young girl, Cecily. Cecily lived in his big house. Jack had to be serious and good there. So life in the country was often boring for him.",
"Jack invented a brother called Ernest. This brother was not real. Jack said Ernest lived in London and was often bad. When Jack wanted fun, he said, ‘I must help my brother.’ Then he went to London. In London, Jack used the name Ernest himself.",
"Algernon laughed. He had a secret too. He invented a sick friend called Bunbury. Bunbury lived in the country. When Algernon did not want a boring dinner, he said, ‘Poor Bunbury is ill. I must go to him.’ It was a very useful excuse.",
"The two friends understood each other well. But Jack made a promise. ‘If Gwendolen says yes, my brother Ernest must die,’ he said. ‘Ernest is not real, so it is easy.’ Algernon smiled. He did not believe it was so easy."],
2:["That afternoon Lady Bracknell came to tea with Gwendolen. Algernon asked Lane to make cucumber sandwiches. His aunt loved them. But Algernon was hungry. He ate one sandwich, then another one. Soon the plate was empty. There were no sandwiches left.",
"Lady Bracknell sat down and asked for the sandwiches. Algernon looked at the empty plate. He called Lane quickly. Lane had a good excuse. ‘There were no cucumbers at the market today,’ he said. Lady Bracknell believed him. She did not ask more questions.",
"Then Algernon took his aunt to the music room. They looked at songs for her party. Now Jack was alone with Gwendolen. This was his big moment. He was very nervous. He told Gwendolen that he admired her very much.",
"Gwendolen was very happy. ‘I always wanted to love a man called Ernest,’ she said. ‘Ernest is a beautiful name. It is a safe name. When I heard your name, I knew I loved you.’ Jack listened with a worried face.",
"Jack asked her a careful question. ‘Do you love me only for my name? What about the name Jack?’ Gwendolen said no. ‘Jack is not an interesting name,’ she answered. So Jack made a secret plan. He wanted a new name: Ernest.",
"Then Jack went down on one knee. He asked Gwendolen to marry him. She said yes with a big smile. But at that moment Lady Bracknell came back. She saw Jack on the floor. She was not happy at all."],
3:["Lady Bracknell sent Gwendolen outside to the carriage. Then she sat down with a small notebook. She wanted to interview Jack herself. Marriage was a serious thing, she thought. Young people could not decide it alone. She started her questions.",
"She asked Jack many things. Did he smoke? How old was he? How much money did he have? Where were his houses? Jack answered well. He had a lot of money. He had a house in town and a house in the country. Lady Bracknell was pleased.",
"Then came the question about his family. Jack was embarrassed. ‘I lost my parents when I was a baby,’ he said. But the truth was stranger. Jack did not know his parents at all. He did not know his real family.",
"Jack told her his story. Many years ago, an old rich man found a baby. His name was Mr Thomas Cardew. He found the baby in a big black handbag. The handbag was at Victoria Station, in the cloakroom. Mr Cardew took the baby home. That baby was Jack.",
"Lady Bracknell was shocked. ‘A handbag?’ she cried. In her eyes, this was terrible. A man from a handbag was not a good husband. Her daughter could not marry a man with no family. She said no to the marriage.",
"Before she left, she gave Jack some advice. ‘Find some parents soon,’ she said coldly. ‘Find a father or a mother. Then we can talk again.’ Then she walked out of the room. Jack stayed there alone. He was very worried."],
4:["Far from London, life was quiet at Jack’s Manor House. It was a big house in the country with a pretty garden. Young Cecily lived there. Her teacher was Miss Prism, a serious lady. That afternoon Cecily had a German lesson in the garden.",
"Cecily did not like German lessons. She wanted to water the flowers. She also loved writing in her diary. All her secret dreams were in that diary. Miss Prism said German was important. But Miss Prism had a secret too. She liked Dr Chasuble, the local priest.",
"Dr Chasuble came to visit. He and Miss Prism went for a walk together. Now Cecily was alone in the garden. Then the servant came with news. ‘Mr Ernest Worthing is here,’ he said. A young visitor walked into the garden.",
"But it was not Ernest. Ernest was not real. The visitor was Algernon! He pretended to be Jack’s bad brother. Cecily was very excited. For months she dreamed about this brother. Now he stood in front of her. He was young and charming.",
"They walked in the garden and talked. They laughed a lot together. Cecily liked him more every minute. Algernon fell in love with her very fast. He forgot that he was only playing a game. He forgot his false name.",
"But there was a problem. At that same time, Jack was in London. He had a plan for his brother Ernest. He wanted to say that Ernest was dead. So Jack prepared his sad story. And Algernon played Ernest in the garden. Nobody knew the truth."],
5:["Then Jack came home to the Manor House. He looked very different. His clothes were black from head to foot. His face was sad and serious. He walked slowly into the garden. Everybody looked at him in surprise. Miss Prism and Dr Chasuble waited for his news.",
"Jack told them some terrible news. ‘My poor brother Ernest is dead,’ he said. ‘He died in Paris. He was very ill with a bad cold.’ Of course, this was not true. Ernest was not real. Jack only wanted to end his old lie.",
"Then something terrible happened. Cecily ran into the garden with a happy face. ‘Uncle Jack, wonderful news!’ she cried. ‘Your brother Ernest is here! He came from London to visit us.’ And there stood Algernon. He smiled calmly. He was very much alive.",
"Jack was angry and shocked. His ‘dead’ brother stood in his garden! But he could not tell the truth. Cecily was there, and the others too. So Jack shook hands with Algernon. He pretended to be happy. It was very hard for him.",
"Now the two men had the same problem. Jack loved Gwendolen. Algernon loved Cecily. And both ladies loved one special name: Ernest. But Jack’s real name was Jack. And Algernon’s real name was Algernon. What could they do? They needed new names fast.",
"Each man went to Dr Chasuble in secret. Each man asked the same thing. ‘Please christen me again with the name Ernest. Please do it this afternoon.’ The priest was surprised by these strange requests. But he was kind, and he agreed."],
6:["Later, Algernon was alone with Cecily in the garden. It was time to speak about his feelings. ‘I love you more than anyone in the world,’ he said. ‘Please be my wife.’ He waited for her answer with a nervous heart.",
"Cecily’s answer was a big surprise. ‘But we are already engaged,’ she said calmly. ‘We got engaged three months ago.’ Algernon looked at her. He did not understand anything. How was that possible? It was their first day together! They met only that day.",
"Then Cecily showed him her diary. The whole romance was in its pages. She wrote the day when ‘Ernest’ first said ‘I love you’. She wrote his beautiful love letters herself. She wrote about a big quarrel too. And after the quarrel, a happy ending.",
"Algernon was amazed. Cecily invented the whole story! He never met a girl with such imagination. He felt very lucky. This wonderful girl chose to love him. He wanted to marry her more than ever. He smiled at her and held her hand.",
"But then Cecily said something important. ‘There is one thing you must know,’ she said. ‘I can only marry a man called Ernest. That name means everything to me. It is a name with music in it.’ Algernon’s face turned white.",
"Algernon had a big problem. His real name was not Ernest. He made a quick excuse and left the garden. He ran to find Dr Chasuble. Like Jack, he needed a christening fast. He needed the name Ernest today, not tomorrow."],
7:["That afternoon a new visitor arrived at the Manor House. It was Gwendolen. She came from London to look for Jack. Cecily welcomed her politely. The two young ladies sat in the garden together. They started to talk in a friendly way.",
"At first they liked each other. They seemed like new good friends. But then came a surprise. ‘I am engaged to Mr Ernest Worthing,’ Gwendolen said proudly. Cecily smiled coldly. ‘How strange. I am engaged to Mr Ernest Worthing too.’",
"In one minute the friends became rivals. Each lady was sure about her Ernest. Each lady thought the other was wrong. They tried to stay calm and polite. But their words became sharp and cold. The air in the garden felt icy.",
"Then came the tea. The polite battle continued. ‘Do you take sugar?’ asked Cecily sweetly. ‘No sugar, thank you,’ said Gwendolen. Cecily put four big lumps in her cup. Gwendolen asked for bread and butter. Cecily gave her a big piece of cake instead.",
"At last Jack and Algernon came into the garden. Now the truth came out. Jack’s name was not Ernest. Algernon’s name was not Ernest. There was no Ernest at all! Both men lied to the girl they loved. It was a bad moment for everybody.",
"Gwendolen and Cecily were shocked and hurt. But they understood something important. Both men played the same trick. So the two ladies were not rivals now. They took each other by the hand. Then they walked into the house together, like sisters."],
8:["The two men followed the ladies into the house. They tried to explain everything. ‘We lied because we were in love,’ they said. ‘And we are ready to change our names. This afternoon Dr Chasuble can christen us Ernest.’ The ladies listened carefully.",
"This promise made the ladies happy again. Gwendolen and Cecily decided to forgive the men. For a moment everything seemed fine. But then a carriage stopped outside the house. Lady Bracknell walked in. She followed Gwendolen all the way from London.",
"Lady Bracknell was still angry. ‘Gwendolen cannot marry you,’ she told Jack coldly. Then she heard new information. Her nephew Algernon wanted to marry Cecily. At first she did not like this idea. Who was this country girl? What was her family?",
"Then she heard about Cecily’s money. Cecily had a very large fortune. Suddenly everything changed. Lady Bracknell smiled warmly at Cecily. ‘What a charming girl,’ she said. ‘What a sweet face. She is a perfect match for Algernon.’ Money opened her heart very fast.",
"But there was a new problem. Jack was Cecily’s guardian. Cecily needed his permission to marry. And Jack said no. He had one condition. ‘Let me marry Gwendolen,’ he said. ‘Then Cecily can marry Algernon.’ It was a clever plan, he thought.",
"Lady Bracknell refused. Jack did not change his mind. She did not change her mind. Nobody moved one centimetre. It was a complete deadlock. It seemed that nobody in the house could marry at all. The afternoon looked dark for everyone."],
9:["At that moment Dr Chasuble said the name ‘Miss Prism’. Lady Bracknell’s face changed at once. ‘Miss Prism?’ she cried. ‘Bring her here immediately!’ Miss Prism came into the room. She saw Lady Bracknell and turned pale with fear. Everyone in the room went quiet.",
"Lady Bracknell told an old story. Twenty-eight years ago, Miss Prism worked for her family. She was a nursemaid. One day she went out with a baby in a pram. She never came back. The nursemaid and the baby disappeared completely.",
"Miss Prism confessed the truth at last. On that day she made a terrible mistake. She put her book into the pram. And she put the baby into a big black handbag! Then she left the handbag at Victoria Station, in the cloakroom.",
"Jack listened with great excitement. He ran upstairs fast. He came back with an old black handbag. ‘Is this your handbag?’ he asked. Miss Prism looked at it carefully. ‘Yes,’ she said. ‘This is my handbag. I am sure of it.’",
"So the mystery was solved. Jack was that lost baby! His mother was Lady Bracknell’s sister. So Jack was Algernon’s big brother. He had a real family at last. Lady Bracknell was his aunt. Everybody in the room was amazed.",
"And Jack’s real name? He got his father’s name as a baby. His father was General Ernest John Moncrieff. So Jack’s true name was Ernest! Now everybody could marry at last. Jack married Gwendolen. Algernon married Cecily. Even Dr Chasuble married Miss Prism. ‘Now I see the importance of being earnest,’ said Jack happily."]
};

const EVENTS={
1:{ev:["Jack visits Algernon’s flat in London.","Algernon shows Jack the silver cigarette case.","Jack tells the truth about Cecily and his two names.","Jack explains his invented brother Ernest.","Algernon talks about his sick friend Bunbury.","Jack promises to end his brother Ernest."],keys:["flat","case","Cecily","brother","Bunbury","Gwendolen"]},
2:{ev:["Algernon eats all the cucumber sandwiches.","Lane says there were no cucumbers at the market.","Algernon takes Lady Bracknell to the music room.","Jack is alone with Gwendolen and speaks of love.","Gwendolen says she loves the name Ernest.","Jack proposes on one knee and Lady Bracknell returns."],keys:["sandwiches","cucumbers","Lane","Ernest","knee","Bracknell"]},
3:{ev:["Lady Bracknell sends Gwendolen to the carriage.","Lady Bracknell asks Jack about his money and houses.","Jack says he does not know his parents.","Jack tells the story of the handbag at Victoria Station.","Lady Bracknell says no to the marriage.","She tells Jack to find some parents soon."],keys:["notebook","money","handbag","Cardew","marriage","advice"]},
4:{ev:["Cecily has a German lesson in the garden.","Cecily writes her dreams in her diary.","Miss Prism walks with Dr Chasuble.","A visitor comes and says he is Ernest.","Algernon pretends to be Jack’s bad brother.","Algernon and Cecily fall in love."],keys:["garden","Prism","diary","Chasuble","Algernon","brother"]},
5:{ev:["Jack comes home in black clothes.","Jack says his brother Ernest died in Paris.","Cecily brings the news that Ernest is here.","Jack shakes hands with the false brother.","Both men have the same name problem.","Each man asks Dr Chasuble to christen him Ernest."],keys:["black","Paris","alive","hands","christen","Chasuble"]},
6:{ev:["Algernon asks Cecily to be his wife.","Cecily says they got engaged three months ago.","Cecily shows him the romance in her diary.","Algernon is amazed by her imagination.","Cecily says she can only marry an Ernest.","Algernon runs to Dr Chasuble for a christening."],keys:["wife","engaged","diary","letters","quarrel","Ernest"]},
7:{ev:["Gwendolen arrives at the Manor House.","Both ladies say they are engaged to Ernest Worthing.","The two ladies become rivals.","Cecily serves sugar and cake at the tea.","The men arrive and the truth comes out.","Gwendolen and Cecily unite against the men."],keys:["Gwendolen","engaged","sugar","cake","trick","hand"]},
8:{ev:["The men promise to be christened Ernest.","Gwendolen and Cecily forgive the men.","Lady Bracknell arrives at the Manor House.","Cecily’s fortune changes Lady Bracknell’s mind.","Jack refuses his permission with one condition.","Nobody agrees and there is a deadlock."],keys:["forgive","carriage","fortune","match","guardian","deadlock"]},
9:{ev:["Lady Bracknell asks to see Miss Prism.","Lady Bracknell tells the story of the lost baby.","Miss Prism confesses her mistake with the pram.","Jack brings the old black handbag.","Jack learns he is Algernon’s big brother.","Jack’s real name is Ernest, and all can marry."],keys:["Prism","nursemaid","pram","handbag","mystery","Ernest"]}
};

return {level:'A2', lead:'Oscar Wilde · easy retelling · <b>A2 elementary</b> (≈600 headwords)',
  CHAPTERS:CHAPTERS, READINGS:READINGS, EVENTS:EVENTS};
})();
