/* BEING EARNEST - datos nivel B2 (retold at upper-intermediate level).
   Mismo formato que earnest-data-b1.js. */
window.ATTWN_DATA = (function(){
const CHAPTERS = [
  { n:1, title:"The silver case",
    sum:"Jack Worthing calls at Algernon Moncrieff’s London flat intending to propose to Gwendolen, but a silver cigarette case gives him away: its inscription proves that ‘Ernest’ is really Jack, guardian of young Cecily in the country. Jack admits he invented a wicked brother, Ernest, as an excuse to escape to town — and Algernon confesses to an equally useful invention, an invalid friend called Bunbury.",
    vocab:[
      ["WHIM","a sudden wish or idea, often not a very serious one"],
      ["INSCRIPTION","words written or engraved on an object"],
      ["GUARDIAN","an adult legally responsible for a young person"],
      ["RESPECTABLE","considered proper and socially acceptable"],
      ["REPUTATION","the opinion people generally have of someone"],
      ["EXTRAVAGANT","spending or costing far too much money"],
      ["TEDIOUS","boring and lasting too long"],
      ["DECEPTION","the act of making someone believe something untrue"],
      ["INVALID","a person weakened by long illness"],
      ["PROPOSAL","an offer of marriage"],
      ["ADMIRATION","a feeling of respect and approval"],
      ["CONFESS","to admit something wrong or embarrassing"]
    ],
    comp:[
      ["Why has Jack come up to London on this occasion?",["To recover his cigarette case","To propose marriage to Gwendolen","To visit his invalid friend Bunbury","To escape from Lady Bracknell"],1,"His main purpose is the proposal to Gwendolen; the cigarette case only becomes an issue once he arrives."],
      ["How did Algernon come to have Jack’s cigarette case?",["Jack lent it to him","He took it from Lane","Jack left it behind on an earlier visit","Cecily posted it to him"],2,"Jack had carelessly left the case behind on a previous visit to the flat."],
      ["What first makes Algernon suspect that his friend is not who he claims to be?",["The inscription inside the case","A letter from Cecily","Lane’s gossip","Gwendolen’s remarks"],0,"The inscription is addressed to ‘Uncle Jack’, yet Algernon has always known his friend as Ernest."],
      ["Who is Cecily Cardew?",["Jack’s niece","Jack’s ward, granddaughter of the man who adopted him","Algernon’s cousin","Lane’s daughter"],1,"Cecily is the granddaughter of Mr Cardew, and Jack is her legal guardian."],
      ["Why did Jack invent a brother instead of simply travelling to town openly?",["He enjoys lying for its own sake","A guardian must protect a respectable reputation, so he needs an excuse to escape","Cecily forbids him to travel","He is ashamed of his friends in London"],1,"As Cecily’s guardian he has to set a high moral tone, so the fictional brother lets him escape without damaging his reputation."],
      ["What service does the invented Bunbury perform for Algernon?",["He lends him money","He lets him avoid tiresome social engagements","He writes his letters","He looks after the flat"],1,"Bunbury’s convenient illnesses give Algernon an excuse to escape boring dinners, especially Lady Bracknell’s."],
      ["What does Jack promise to do if Gwendolen accepts him?",["Confess everything to Lady Bracknell","Kill off his imaginary brother and live honestly","Move permanently to the country","Adopt the name Ernest legally"],1,"Jack declares that Ernest will be disposed of for ever and that he will lead a thoroughly honest life."],
      ["What does Algernon’s final smile suggest?",["He believes Jack will find honesty harder than he expects","He is jealous of Gwendolen","He plans to keep the cigarette case","He thinks Jack is joking about marriage"],0,"Algernon suspects that a man who has lived a double life for years will not give it up so easily — and events prove him right."]
    ],
    tf:[
      ["Jack is known as Ernest in London but as Jack in the country.",true,"The double identity is the engine of the whole plot: Ernest in town, Jack at home."],
      ["Algernon returns the cigarette case as soon as Jack asks for it.",false,"He refuses to hand it over until the mysterious inscription has been explained."],
      ["Cecily is the granddaughter of the man who adopted Jack.",true,"She is old Mr Cardew’s granddaughter, and Jack is her guardian."],
      ["Bunbury is a real friend of Algernon’s who suffers from poor health.",false,"Bunbury is entirely imaginary — a fiction whose ‘illnesses’ excuse Algernon from dull engagements."],
      ["Algernon is shocked and disapproving when he hears about Jack’s double life.",false,"Far from disapproving, he is delighted to recognise a fellow Bunburyist."],
      ["Jack intends to end his double life if his proposal is accepted.",true,"He promises to kill off Ernest for ever once Gwendolen says yes."]
    ],
    writing:[
      {task:"You have just discovered that a good friend has been using a false name for years. Write an informal email to another friend, describing how you found out and how you feel about the deception.",
       target:"100–140 words",
       tips:["Open and close like a real informal email (Hi…, Anyway, write soon!).","Narrate the discovery with past tenses and sequencers: at first, then, it turned out that…","Balance the story with your reaction: shocked, amused, disappointed?"],
       starters:["Hi Sam,","You’ll never believe what I found out yesterday…","It turns out that all this time he…","To be honest, I still don’t know whether to laugh or…"]},
      {task:"Write an essay giving your opinion on the following statement: ‘It is sometimes acceptable to keep part of your life secret from the people close to you.’",
       target:"100–140 words",
       tips:["State your position in the introduction and return to it in the conclusion.","Support each argument with an example — Jack’s double life is an obvious one.","Use linkers of contrast and concession: however, even so, on the other hand."],
       starters:["Many people believe that total honesty is essential in any relationship…","On the one hand, a certain amount of privacy…","However, secrets have a habit of…","On balance, I would argue that…"]}
    ]},
  { n:2, title:"No cucumber sandwiches",
    sum:"Over a disastrous afternoon tea — Algernon has already devoured the cucumber sandwiches ordered for his aunt — Jack seizes his chance with Gwendolen. She accepts his proposal enthusiastically, though for a worrying reason: her lifelong ideal is to love a man called Ernest. Lady Bracknell returns just in time to interrupt the happy scene and dismiss the engagement.",
    vocab:[
      ["PRIVILEGE","a special right or advantage"],
      ["DIGNITY","calm, serious and controlled behaviour"],
      ["PRETEXT","a false reason used to hide the real one"],
      ["MANOEUVRE","a clever, planned movement or trick"],
      ["CONFIDENCE","trust or firm belief in someone or something"],
      ["HESITATION","a pause caused by doubt"],
      ["CHRISTEN","to give someone a name in a baptism ceremony"],
      ["ENGAGEMENT","a formal agreement to marry"],
      ["OBSTACLE","something that blocks progress"],
      ["FORMIDABLE","impressively powerful and rather frightening"],
      ["RECEPTION","a formal party for receiving guests"],
      ["DESTINED","certain to become or to do something in the future"]
    ],
    comp:[
      ["Why is there nothing left on the plate when Lady Bracknell arrives?",["Lane forgot to prepare the sandwiches","Algernon has eaten them all while waiting","Jack ate them out of nervousness","The cook sent them to the wrong flat"],1,"Algernon, made hungry by waiting, finishes every sandwich himself before his aunt appears."],
      ["How does Lane explain the missing sandwiches?",["He blames the cook","He claims there were no cucumbers at the market, even for ready money","He says Jack ate them","He admits the truth at once"],1,"The butler lies smoothly to protect his employer, and Lady Bracknell accepts the excuse."],
      ["Why does Algernon lead Lady Bracknell into the music room?",["He wants her opinion of his playing","To give Jack a private moment with Gwendolen","To hide the empty plate from her","To discuss Bunbury’s health"],1,"Choosing songs is only a pretext; the manoeuvre deliberately leaves Jack alone with Gwendolen."],
      ["What reason does Gwendolen give for loving Jack?",["His fortune and property","His name, which she believes is Ernest","His country estate","His complete honesty"],1,"Her ideal has always been to love a man called Ernest — a name that inspires absolute confidence."],
      ["How does Gwendolen feel about the name Jack?",["It produces no vibrations and could hardly be loved","She finds it charming","She prefers it to Ernest","She has never thought about it"],0,"She dismisses Jack as a respectable name that no sensible woman could give her heart to."],
      ["What does Jack secretly resolve during the conversation?",["To confess his real name at once","To be christened Ernest as soon as possible","To break off the relationship","To consult Algernon first"],1,"Alarmed by Gwendolen’s obsession, he decides on the spot that he must acquire the name Ernest."],
      ["What does Lady Bracknell do when she discovers the couple?",["She congratulates them warmly","She announces that Gwendolen is engaged to no one","She sends for Lane","She leaves the flat in silence"],1,"She corrects her daughter at once: any engagement will be decided and announced by her parents."],
      ["What does Gwendolen’s calm confidence during the proposal suggest about her?",["She had foreseen, and quite possibly planned, the whole scene","She does not really love Jack","She is too shy to speak plainly","She is frightened of her mother"],0,"Far from being surprised, she watches Jack struggle with the air of someone whose plan is working perfectly."]
    ],
    tf:[
      ["Algernon ordered the cucumber sandwiches especially for Lady Bracknell.",true,"They were prepared for his aunt, who was famously particular — which makes eating them all the worse."],
      ["Lane refuses to tell a lie on his employer’s behalf.",false,"Without blinking, Lane invents the story that there were no cucumbers at the market."],
      ["Lady Bracknell angrily accuses Algernon of eating the sandwiches himself.",false,"She never suspects him; she accepts the improbable excuse with dignity, though annoyed."],
      ["Gwendolen accepts Jack partly because of the name she believes he has.",true,"Her devotion to the name Ernest is the deciding factor — which is Jack’s bad luck."],
      ["Jack feels sure that Gwendolen would love him whatever his name was.",false,"He tests the idea cautiously and is alarmed to find that the name matters enormously."],
      ["Lady Bracknell claims that an engagement is a matter for the parents to arrange.",true,"Gwendolen, she says, will be informed when and if an engagement is decided for her."]
    ],
    writing:[
      {task:"Write a story for your school’s English magazine that begins with this sentence: ‘When the guests arrived, the plate was already empty.’",
       target:"100–140 words",
       tips:["Plan a clear beginning, complication and ending before you write.","Use a range of past tenses: past simple, past continuous and past perfect.","Build humour or tension through what the characters say and do."],
       starters:["When the guests arrived, the plate was already empty.","Nobody wanted to admit that…","Just as everyone sat down,…","In the end, the only possible explanation was…"]},
      {task:"Write an article for the school magazine with the title ‘What’s in a name?’, discussing whether a person’s name really influences the way we judge them.",
       target:"100–140 words",
       tips:["Hook the reader with a question or striking example in the first line.","Give one or two real-life examples, then your own view.","Finish with a memorable closing sentence that answers the title."],
       starters:["Would you trust someone simply because of their name?","In Wilde’s famous play, two women insist on marrying a man called…","Research suggests that names can affect…","So, next time you meet a stranger,…"]}
    ]},
  { n:3, title:"Lady Bracknell interviews Jack",
    sum:"Lady Bracknell subjects Jack to a formal interview about his habits, income and, above all, his family. His answers satisfy her until he confesses that he was found, as a baby, in a handbag in the cloakroom at Victoria Station. Horrified at the idea of a son-in-law with no relations, she refuses her consent and advises him to acquire a parent or two without delay.",
    vocab:[
      ["INTERVIEW","a formal meeting at which questions are asked"],
      ["ELIGIBLE","suitable to be chosen, especially for marriage"],
      ["INTERROGATION","long and aggressive questioning"],
      ["INCOME","the money a person receives regularly"],
      ["ESTATE","a large area of land in the country with a big house"],
      ["EMBARRASSMENT","a feeling of awkward shame"],
      ["CIRCUMSTANCES","the facts and conditions surrounding an event"],
      ["CHARITABLE","generous towards people in need"],
      ["FORTUNE","a very large amount of money"],
      ["ALLIANCE","a close union between people or families, e.g. by marriage"],
      ["HUMILIATED","made to feel ashamed and small"],
      ["ORIGIN","where a person or thing comes from"]
    ],
    comp:[
      ["Why does Lady Bracknell interview Jack?",["To decide whether his name deserves a place on her list of eligible young men","To offer him employment","To buy his country estate","To find a husband for Cecily"],0,"She keeps a list of acceptable suitors and will only consider Jack if his answers satisfy her."],
      ["Which of Jack’s answers actually pleases Lady Bracknell?",["That he smokes, since a man ought to have an occupation","That he plays the piano","That he dislikes the country","That he lives alone"],0,"With typical upside-down logic, she approves of smoking as a form of occupation."],
      ["How does Jack perform in the early part of the interview?",["Badly from the very first question","Well — his age, income and property are all satisfactory","He refuses to answer anything","He lies about his money"],1,"Everything goes smoothly until the fatal question of his family is raised."],
      ["What did Mr Thomas Cardew do for the baby he found?",["Handed him to the police","Adopted him, gave him the surname Worthing and left him a fortune","Sent him abroad","Returned him to the cloakroom"],1,"The charitable Mr Cardew adopted the foundling and made him a wealthy man."],
      ["What exactly horrifies Lady Bracknell about Jack’s story?",["The handbag was of poor quality","He has no known family, and society demands respectable relations","He was brought up in the country","Mr Cardew had no title"],1,"For her, a man without relations has no recognised position, whatever his income."],
      ["What is Lady Bracknell’s parting advice to Jack?",["To buy a larger house","To make every effort to find some relations, producing at least one parent","To change his profession","To leave London for good"],1,"With absurd practicality, she instructs him to acquire relations before the season ends."],
      ["Where was the handbag containing the baby discovered?",["On a train to Brighton","In the cloakroom at Victoria Station","In a London park","At Mr Cardew’s house"],1,"The bag had been left in the cloakroom at Victoria Station — a detail that later solves everything."],
      ["Why is the failed interview such a serious blow to Jack?",["He loses his fortune","Without Lady Bracknell’s consent he cannot hope to marry Gwendolen","He must sell his estate","Gwendolen has stopped loving him"],1,"Gwendolen’s mother controls the engagement, so her refusal blocks the marriage completely."]
    ],
    tf:[
      ["Gwendolen is present while her mother interviews Jack.",false,"Lady Bracknell dispatches her to wait in the carriage before the questioning begins."],
      ["Jack’s income and property initially make a favourable impression.",true,"He passes the financial part of the examination comfortably."],
      ["Jack knows that his parents died when he was a baby.",false,"The truth is stranger: he has no idea who his parents were at all."],
      ["Jack describes the handbag as an ordinary one, with handles.",true,"He adds the detail helpfully, as if it made the story more respectable."],
      ["Lady Bracknell suggests the problem could be solved if Jack found some relations.",true,"Her advice to ‘acquire’ relations implies the door is not entirely closed."],
      ["Jack ends the interview feeling calm and hopeful.",false,"He is left furious, humiliated and painfully aware of the obstacle before him."]
    ],
    writing:[
      {task:"Write a formal letter from Jack to Lady Bracknell, politely arguing that he would make a suitable husband for Gwendolen in spite of his unknown origins.",
       target:"100–140 words",
       tips:["Use formal conventions: Dear Lady Bracknell, … Yours sincerely.","Organise your arguments in paragraphs: income, character, devotion.","Be persuasive but respectful — no complaints, no sarcasm."],
       starters:["Dear Lady Bracknell,","I am writing with regard to our recent conversation…","While I regret that I cannot name my parents, I would point out that…","I would be deeply grateful if you would reconsider…"]},
      {task:"Write an essay giving your opinion on the following question: ‘Should a person’s family background matter when choosing a husband or wife?’",
       target:"100–140 words",
       tips:["Take a clear position and defend it consistently.","Contrast past attitudes, like Lady Bracknell’s, with modern ones.","Use concession: although, admittedly, it is true that… but…"],
       starters:["In Wilde’s day, marriage was often treated as a business arrangement…","Admittedly, families can influence a couple’s happiness…","Nevertheless, I believe that…","To conclude, what really matters is…"]}
    ]},
  { n:4, title:"The Manor House",
    sum:"At Jack’s country estate, Cecily dodges her German lesson while her governess, Miss Prism, exchanges shy attentions with Dr Chasuble, the rector. Then Algernon arrives, introducing himself as Jack’s scandalous brother Ernest. Cecily, who has spent months romanticising this wicked relative, is delighted — and Algernon, who only came out of curiosity, promptly falls in love.",
    vocab:[
      ["GOVERNESS","a woman employed to teach children in their home"],
      ["DETERMINATION","firm refusal to give up"],
      ["ABSORBING","so interesting that it takes all your attention"],
      ["RECTOR","a priest in charge of a parish"],
      ["SCANDALOUS","shocking to accepted moral standards"],
      ["EXPEDITION","a journey made for a particular purpose"],
      ["LEGEND","a famous story that may not be true"],
      ["ENCHANTED","completely charmed and delighted"],
      ["CURIOSITY","a strong desire to find out about something"],
      ["COMPLIMENT","a remark that expresses praise"],
      ["IDYLLIC","peaceful, beautiful and seemingly perfect"],
      ["FATEFUL","having important, often unpleasant, consequences"]
    ],
    comp:[
      ["What is Cecily supposed to be doing at the start of the chapter?",["Watering the flowers","Studying her German lesson","Writing to Ernest","Serving tea to visitors"],1,"Miss Prism has set her a German lesson, which Cecily resists with quiet determination."],
      ["What does Cecily record in her diary?",["Only things that really happened","Both what happened and what ought to have happened","Her German homework","Miss Prism’s lectures"],1,"Her diary improves on reality — a habit that will matter greatly in Chapter 6."],
      ["What weakness does the stern Miss Prism reveal?",["A love of gossip","A soft spot for Dr Chasuble","A dislike of gardens","A secret fortune"],1,"Whenever the rector appears, the governess visibly softens and duty is forgotten."],
      ["Under what identity does Algernon present himself at the Manor House?",["Bunbury","Ernest Worthing, Jack’s younger brother","Mr Moncrieff of London","Dr Chasuble’s nephew"],1,"He borrows the identity of the famous wicked brother — who does not actually exist."],
      ["Why is Cecily slightly disappointed at first sight of ‘Ernest’?",["He is older than she expected","He does not look nearly as wicked as she had hoped","He is badly dressed","He barely speaks to her"],1,"Months of romantic imagining had prepared her for a villain; the reality looks disappointingly respectable."],
      ["Why did Algernon originally travel down to the country?",["Jack invited him","Curiosity about the girl whose name he had seen on the cigarette case","To escape from Bunbury","To meet Miss Prism"],1,"His Bunburying expedition begins as curiosity about Cecily — and turns into something far more serious."],
      ["What is Jack doing in London at the same time?",["Proposing to Gwendolen","Preparing to announce the death of his invented brother","Organising a party","Buying Cecily a present"],1,"Ironically, Jack is arranging Ernest’s funeral just as Algernon brings Ernest to life."],
      ["Why does the chapter end with a sense of approaching disaster?",["Two versions of Ernest — one dead, one alive — are about to meet","Miss Prism threatens to resign","Cecily plans to run away","Dr Chasuble forbids visitors"],0,"Jack is about to kill off the very brother Algernon is impersonating, so a collision is inevitable."]
    ],
    tf:[
      ["Cecily believes that German lessons improve her appearance.",false,"Quite the opposite — she is convinced German grammar makes attractive people plainer."],
      ["Miss Prism abandons her lecture when Dr Chasuble appears.",true,"The rector’s arrival melts the governess’s strictness at once."],
      ["Algernon tells Cecily his true identity as soon as they meet.",false,"He keeps up the role of the wicked brother Ernest throughout the visit."],
      ["Cecily had built a romantic legend around the wicked brother long before meeting him.",true,"She had been imagining him for months, sighing over his supposed wickedness."],
      ["Algernon treats the whole visit as a game and stays emotionally detached.",false,"Although it began as a game, he finds himself genuinely falling in love with Cecily."],
      ["Jack has decided that his imaginary brother must disappear for good.",true,"In London he is already preparing to announce Ernest’s death."]
    ],
    writing:[
      {task:"Imagine you are Cecily. Write an informal email to a pen-friend describing the unexpected arrival of your guardian’s ‘wicked’ brother and your impressions of him.",
       target:"100–140 words",
       tips:["Write in the first person with plenty of feeling and exaggeration, as Cecily would.","Contrast expectation and reality: I had always imagined… but in fact…","Close with a hint about what might happen next."],
       starters:["Dear Emily,","The most thrilling thing has happened at the Manor House…","I had always pictured him as…","I shall write again the moment anything else happens…"]},
      {task:"Write an article for a teenage magazine with the title ‘Imagination: a gift or a trap?’, using examples of people who prefer dreams to reality.",
       target:"100–140 words",
       tips:["Open with a question that draws the reader in.","Present both sides — imagination as creativity, imagination as escape.","End with clear advice or a conclusion of your own."],
       starters:["Do you ever find your daydreams more interesting than your life?","Take Cecily, the heroine of a famous comedy, who invented…","Psychologists point out that imagination…","Dream by all means — but…"]}
    ]},
  { n:5, title:"In mourning",
    sum:"Jack comes home in deep mourning to announce that his brother Ernest has died of a chill in Paris — only to find ‘Ernest’ alive, smiling and charming everyone, in the shape of Algernon. Unable to expose the impostor without exposing himself, Jack is forced to play along. Privately, both men then ask Dr Chasuble to christen them Ernest that very afternoon.",
    vocab:[
      ["MOURNING","dark clothes and solemn behaviour showing grief after a death"],
      ["SORROW","deep sadness"],
      ["CONDOLENCES","formal expressions of sympathy after a death"],
      ["TRAGEDY","a terrible and very sad event"],
      ["GRIEF","intense sadness, especially after a loss"],
      ["IMPOSTOR","a person who pretends to be someone else"],
      ["PREDICAMENT","a difficult situation with no easy way out"],
      ["DEVOTION","strong love and loyalty"],
      ["BAPTISM","the church ceremony of naming someone with water"],
      ["CEREMONY","a formal set of actions performed on an occasion"],
      ["RADIANT","shining with happiness"],
      ["DENOUNCE","to accuse someone publicly of something bad"]
    ],
    comp:[
      ["What impression does Jack try to create on his return?",["That he has been promoted","That he is grieving for a dead brother","That he is newly engaged","That he has been seriously ill"],1,"His mourning clothes and rehearsed sorrow are designed to convince everyone Ernest is dead."],
      ["According to Jack, how and where did Ernest die?",["In London, in an accident","Of a severe chill, in Paris","At sea, in a storm","Of old age, in Rome"],1,"A sudden chill in Paris is the cause of death Jack invents for his fictional brother."],
      ["How does Dr Chasuble respond to the sad news?",["He doubts the story","He offers condolences and promises to mention the tragedy in his sermon","He cancels all christenings","He questions Cecily about it"],1,"The kindly rector accepts the death without suspicion and offers spiritual comfort."],
      ["What ruins Jack’s carefully staged performance?",["Gwendolen’s sudden arrival","Cecily announcing that brother Ernest is waiting in the house","A telegram from Paris","Lane’s confession"],1,"At the worst possible moment, the ‘dead’ brother turns out to be standing in the dining room."],
      ["Why can’t Jack simply denounce Algernon on the spot?",["Algernon would tell Gwendolen","Exposing the impostor would mean confessing his own years of lying","He is afraid of Dr Chasuble","Cecily would never believe him"],1,"Ernest never existed — so unmasking Algernon would unmask Jack’s own deception too."],
      ["What situation do the two men share by the end of the chapter?",["Each loves a woman devoted to the name Ernest, which neither of them possesses","Both are engaged to Cecily","Both are in mourning","Both have confessed everything"],0,"Gwendolen and Cecily both worship the name Ernest, and neither man is really called that."],
      ["What do the men separately ask Dr Chasuble to do?",["Perform a funeral service","Christen each of them Ernest that same afternoon","Marry them immediately","Keep Cecily indoors"],1,"Each privately books a christening, unaware that the other has done exactly the same."],
      ["What makes the christening requests comic for the reader?",["Two grown men urgently demand baptism on the same day for the same secret reason","Dr Chasuble refuses angrily","The church has burnt down","The men make their requests together, openly"],0,"The reader sees the symmetry that the characters cannot: identical secret requests, identical motive."]
    ],
    tf:[
      ["Jack’s mourning outfit is complete down to the smallest detail.",true,"Black from head to foot, with gloves and a crape hat-band — the costume is perfect."],
      ["The household immediately suspects that the death is invented.",false,"Nobody doubts the story; Dr Chasuble even offers to mention it in his sermon."],
      ["Algernon slips quietly away as soon as Jack arrives.",false,"Far from hiding, he strolls out smiling to greet his ‘brother’ in front of everyone."],
      ["Jack is forced to welcome Algernon as his brother in public.",true,"Trapped by his own invention, he must shake hands and accept congratulations."],
      ["Dr Chasuble refuses to christen two adults on the same afternoon.",false,"Though puzzled, he kindly agrees to perform the ceremony for each of them."],
      ["Each man keeps his christening plan secret from the other.",true,"The requests are made separately and in the strictest secrecy."]
    ],
    writing:[
      {task:"Write a story for a competition that begins with this sentence: ‘The man they were mourning walked calmly into the garden.’",
       target:"100–140 words",
       tips:["Decide immediately how the ‘dead’ man comes to be alive — mistake, trick or lie?","Describe the onlookers’ reactions before giving the explanation.","Use dramatic vocabulary: froze, gasped, turned pale, stared."],
       starters:["The man they were mourning walked calmly into the garden.","For a long moment nobody moved.","It was Grandmother who finally broke the silence…","Only later did we discover that…"]},
      {task:"Write an essay giving your opinion on the following statement: ‘A small lie never hurt anyone.’ Use examples from the play or from life to support your view.",
       target:"100–140 words",
       tips:["Define what you understand by a ‘small’ lie in your introduction.","Show how Jack’s harmless invention grows until it traps him.","Weigh advantages against consequences before concluding."],
       starters:["Most people tell small lies almost every day…","At first, an invented excuse seems harmless…","The trouble begins when…","In conclusion, I would argue that…"]}
    ]},
  { n:6, title:"The engagement",
    sum:"Algernon proposes to Cecily and learns, to his astonishment, that they have officially been engaged for three months: she has written the whole romance — his letters included — in her diary. Charmed by her imagination, he is rather less charmed by her one condition: like Gwendolen, she could only ever love a man called Ernest. Algernon races off to arrange his christening.",
    vocab:[
      ["PRETENCE","behaviour intended to deceive people"],
      ["SINCERITY","honesty of feeling; meaning what you say"],
      ["REMARKABLE","unusual and deserving attention"],
      ["EVIDENCE","facts or objects that prove something"],
      ["RECONCILIATION","becoming friends again after a quarrel"],
      ["QUARREL","an angry argument"],
      ["COMPOSE","to write or create something, e.g. a letter or music"],
      ["FASCINATING","extremely interesting or attractive"],
      ["CONDITION","something that must happen before something else can"],
      ["INNOCENT","without guilt or bad intentions"],
      ["APPOINTMENT","an arranged meeting at a fixed time"],
      ["URGENCY","the need for immediate action"]
    ],
    comp:[
      ["How honest is Algernon’s declaration of love?",["Completely false from start to finish","Sincere in feeling, though made under a false name","A joke he instantly regrets","Part of a plan agreed with Jack"],1,"His feelings are genuine — the irony is that he expresses them while pretending to be Ernest."],
      ["What does Cecily reveal about their engagement?",["That it must wait a year","That, according to her diary, it has already lasted three months","That Jack has forbidden it","That she is engaged to someone else"],1,"In her imagination — and her diary — they became engaged months before they ever met."],
      ["Who actually wrote the love letters from ‘Ernest’?",["Algernon","Cecily herself","Jack","Miss Prism"],1,"She composed every one of them herself, on behalf of the brother she had never seen."],
      ["Why did Cecily break off the imaginary engagement at one point?",["She met someone else","She felt a serious romance needed to be broken off at least once","Ernest stopped writing to her","Miss Prism ordered her to end it"],1,"In her view no engagement counts as serious unless it has survived at least one dramatic quarrel."],
      ["How does Algernon react to the contents of the diary?",["With alarm and suspicion","With delight at her extraordinary inventiveness","With boredom","With anger about the invented letters"],1,"He is enchanted — he even admires the love letters he never wrote."],
      ["Which condition threatens Algernon’s new happiness?",["Cecily insists that her husband must be called Ernest","Cecily demands a large fortune","Jack must give his consent first","Cecily refuses ever to leave the country"],0,"Her lifelong dream has been to love a man called Ernest — and Algernon’s name is Algernon."],
      ["What does Cecily think of the name Algernon?",["It is musical and aristocratic","It has no music in it whatsoever","It would suit a wicked brother perfectly","It is even better than Ernest"],1,"She pities any woman married to an Algernon — while talking to one, which is the joke."],
      ["Why does Algernon leave the garden in such a hurry?",["He must reach Dr Chasuble and become Ernest before the truth emerges","He is late for dinner with Lady Bracknell","Jack has ordered him back to London","He wants to buy Cecily a ring"],0,"Like Jack before him, he sees that only an urgent christening can save his engagement."]
    ],
    tf:[
      ["Algernon and Cecily first met three months before this scene.",false,"They met barely a day earlier; the three-month engagement exists only in Cecily’s diary."],
      ["The diary records a quarrel followed by a reconciliation.",true,"Cecily invented a dramatic break-up and a touching reconciliation to make the romance serious."],
      ["Algernon is offended that Cecily invented his letters.",false,"He is charmed, privately judging the letters he never wrote to be excellent."],
      ["Cecily says she could love Algernon whatever his name happened to be.",false,"She fears she could not — for her, the name Ernest is essential."],
      ["Algernon’s real name is a serious obstacle to the engagement.",true,"Cecily’s condition makes the name Algernon a direct threat to his hopes."],
      ["Algernon invents an excuse before hurrying away to find Dr Chasuble.",true,"He covers his urgent departure with a hastily invented appointment."]
    ],
    writing:[
      {task:"Write a review of a book or film in which imagination and reality become confused. Say what happens, what you liked, and who should see or read it.",
       target:"100–140 words",
       tips:["Name the work and summarise the plot in one or two sentences without spoiling the end.","Give a balanced judgement: strengths first, then any weaknesses.","Close with a clear recommendation and who it is best suited for."],
       starters:["If you enjoy stories where dreams take over,…","The plot follows a character who…","What makes it so enjoyable is…","All in all, I would recommend it to anyone who…"]},
      {task:"Imagine you are Algernon. Write an informal letter to a friend in London explaining why you suddenly need to change your name, without revealing Cecily’s identity.",
       target:"100–140 words",
       tips:["Keep the tone light and self-mocking, as Algernon would.","Explain the situation step by step, hiding names where necessary.","End by asking your friend for advice or discretion."],
       starters:["My dear Freddy,","You will laugh, but I find I must urgently become someone else…","The lady in question has one small requirement…","Not a word of this at the club, I beg you…"]}
    ]},
  { n:7, title:"Afternoon tea",
    sum:"Gwendolen appears at the Manor House and takes tea with Cecily. Their instant friendship collapses when each claims to be engaged to Ernest Worthing, and a battle of exquisite politeness follows over the teacups. When Jack and Algernon arrive, the truth about their names finally comes out — and the two deceived women unite in outrage and sweep into the house together.",
    vocab:[
      ["RIVAL","a person competing with another for the same thing"],
      ["COURTESY","polite and respectful behaviour"],
      ["HOSTESS","a woman who receives and entertains guests"],
      ["DECEITFUL","dishonest; deliberately hiding the truth"],
      ["BETRAYAL","the breaking of someone’s trust"],
      ["EMBRACE","to hold someone in your arms"],
      ["DIGNIFIED","calm and serious in a way that earns respect"],
      ["CONSEQUENCE","a result that follows from an action"],
      ["MISUNDERSTANDING","a failure to understand something correctly"],
      ["SURRENDER","to give up or give in"],
      ["ASTONISHED","extremely surprised"],
      ["FASHIONABLE","popular in style at a particular time"]
    ],
    comp:[
      ["Why has Gwendolen come to the Manor House?",["Lady Bracknell has sent her","She has followed Jack into the country","Cecily invited her to stay","She is visiting Dr Chasuble"],1,"Determined not to lose Jack, she travels down from London on her own initiative."],
      ["How does the meeting between the two young women begin?",["With open hostility","With warmth and declarations of instant friendship","In embarrassed silence","With an argument about the garden"],1,"Within minutes they agree they are destined to be the closest of friends — which makes the collapse funnier."],
      ["What discovery destroys the new friendship?",["Each claims to be engaged to Ernest Worthing","They love the same house","Cecily has read Gwendolen’s diary","Gwendolen insults Miss Prism"],0,"Both believe themselves engaged to the same man — the non-existent Ernest."],
      ["How is the rivalry expressed at the tea table?",["Through shouting and tears","Through perfectly polite words concealing deliberate attacks","Through complete silence","Through a physical struggle"],1,"The battle is fought with courtesy: every sweet remark hides a small act of war."],
      ["What does Cecily do when Gwendolen declines sugar?",["Removes the cup entirely","Drops four lumps into her tea regardless","Calls the servant to apologise","Drinks the tea herself"],1,"Since sugar is ‘no longer fashionable’, Cecily sweetens her rival’s cup generously."],
      ["What truth emerges when the men finally appear?",["Both men are really called Ernest","Neither man is called Ernest at all","Only Algernon is Ernest","Jack and Algernon are cousins"],1,"Gwendolen’s Ernest proves to be Jack, Cecily’s proves to be Algernon — and Ernest himself does not exist."],
      ["Why do the women suddenly stop being rivals?",["They realise they were deceived by the same trick and turn against the men","They decide neither wants to marry","Lady Bracknell orders them to make peace","Each falls in love with someone new"],0,"Shared betrayal unites them instantly; the men, not each other, are now the enemy."],
      ["What does the tea-table scene suggest about polite society?",["Perfect manners can carry as much aggression as an open argument","Tea parties are always friendly","Servants control every conversation","Politeness makes conflict impossible"],0,"Wilde’s joke is that etiquette does not prevent warfare — it simply provides the weapons."]
    ],
    tf:[
      ["Cecily already knows who Gwendolen is when she arrives.",false,"She has never heard of her, and welcomes the stranger warmly."],
      ["Each woman consults her diary to support her claim to Ernest.",true,"Both treat their diaries as unanswerable documentary evidence."],
      ["Gwendolen receives bread and butter exactly as she requested.",false,"She is given a large slice of cake instead — a deliberate act of tea-table warfare."],
      ["The quarrel descends into raised voices and open insults.",false,"Outwardly the conversation stays icily polite; the aggression is all beneath the surface."],
      ["Both men had used the same false name independently of each other.",true,"Each had presented himself as Ernest to the woman he loved."],
      ["The chapter ends with the women leaving together, united against the men.",true,"Calling each other sister, they turn their backs and retire into the house."]
    ],
    writing:[
      {task:"Write an article for the school magazine with the title ‘Politeness: the most elegant weapon’, about how people can attack each other without ever raising their voices.",
       target:"100–140 words",
       tips:["Open with a short scene or example the reader will recognise.","Analyse why indirect attacks can hurt more than open ones.","Finish with your own view: is such politeness civilised or dishonest?"],
       starters:["Have you ever been insulted by someone who never stopped smiling?","In Wilde’s most famous comedy, two ladies fight a duel with sugar and cake…","The secret of the polite attack is…","Perhaps true good manners would mean…"]},
      {task:"Write a story that begins with this sentence: ‘The two women smiled at each other, but the smiles did not reach their eyes.’",
       target:"100–140 words",
       tips:["Establish quickly what the two characters both want.","Let the tension grow through small details and double-edged dialogue.","Decide on a twist or resolution before you start writing."],
       starters:["The two women smiled at each other, but the smiles did not reach their eyes.","Each was quite sure the other would give way first.","Over the teacups, the conversation turned dangerous.","It was only when the door opened that…"]}
    ]},
  { n:8, title:"The perfect match",
    sum:"The men win forgiveness by promising to be re-christened Ernest, but Lady Bracknell arrives to forbid everything. She rejects Cecily as a wife for Algernon — until she hears the size of Cecily’s fortune, at which point the match becomes ideal. Jack, however, refuses his consent as guardian unless he himself may marry Gwendolen, and the whole affair grinds into deadlock.",
    vocab:[
      ["DISGRACE","loss of other people’s respect and approval"],
      ["HONOURABLE","morally correct and deserving respect"],
      ["SACRIFICE","giving up something valuable for a greater purpose"],
      ["CONSENT","official permission or agreement"],
      ["OBJECTION","a reason given for disagreeing with something"],
      ["BLACKMAIL","forcing someone to act by using threats"],
      ["NEGOTIATION","discussion intended to reach an agreement"],
      ["DEADLOCK","a situation in which no agreement is possible"],
      ["STUBBORN","refusing to change your mind"],
      ["MIRACULOUS","wonderful and surprising, like a miracle"],
      ["INSPECT","to look at something closely and critically"],
      ["EPISODE","a single event within a longer series of events"]
    ],
    comp:[
      ["What finally persuades the women to forgive the men?",["Expensive presents","Their willingness to face christening for love","Lady Bracknell’s orders","A long written apology"],1,"The promise of baptism strikes both ladies as heroic self-sacrifice — irresistible evidence of devotion."],
      ["How did Lady Bracknell discover where Gwendolen had gone?",["She guessed from experience","She paid Gwendolen’s maid for the information","Jack telegraphed her","Algernon confessed everything"],1,"She bribed the maid, discovered the destination and caught the first available train."],
      ["What is her first reaction to Algernon’s engagement to Cecily?",["Immediate delight","Cool disapproval of a girl she knows nothing about","She faints from shock","She consults Dr Chasuble"],1,"An unknown country ward is, in her eyes, nobody in particular — until the money is mentioned."],
      ["What single fact transforms her opinion of Cecily?",["Her beauty","Her large fortune","Her excellent German","Her famous diary"],1,"The moment the fortune is mentioned, Cecily acquires charm, profile and distinct social possibilities."],
      ["What does Lady Bracknell’s sudden change of heart reveal about her values?",["Money outweighs breeding the moment it appears in sufficient quantity","She secretly admires Jack","She distrusts all young women","She believes love conquers everything"],0,"Her principles about family bend instantly before a fortune — Wilde’s satire on society’s real priorities."],
      ["What legal power does Jack hold over the situation?",["He can disinherit Algernon","As Cecily’s guardian, his consent is required before she can marry","He controls Gwendolen’s money","He can dismiss Dr Chasuble"],1,"Cecily cannot marry without her guardian’s consent until she comes of age."],
      ["What bargain does Jack propose?",["Money in exchange for silence","His consent for Cecily’s marriage in exchange for consent to his own","A delay of exactly one year","No bargain at all"],1,"He offers a simple exchange of consents — which Lady Bracknell regards as blackmail."],
      ["Why does the chapter end in deadlock?",["Neither Jack nor Lady Bracknell will be the first to give way","Cecily rejects both men","Dr Chasuble cancels the christenings","Gwendolen returns to London"],0,"Two equally stubborn negotiators refuse to move, leaving four people’s happiness suspended."]
    ],
    tf:[
      ["The ladies forgive the men before Lady Bracknell arrives.",true,"The reconciliation is complete just as her carriage is heard at the door."],
      ["Lady Bracknell finally accepts Jack as a suitable husband for Gwendolen.",false,"Her position has not moved an inch: the cloakroom origin still disqualifies him."],
      ["Cecily’s fortune makes Lady Bracknell suddenly discover her charm.",true,"Qualities invisible five minutes earlier appear as soon as the money is mentioned."],
      ["Jack gives his consent to Cecily’s marriage without conditions.",false,"He attaches one precise condition: permission to marry Gwendolen."],
      ["Under her grandfather’s will, Cecily may marry whenever she wishes without consent.",false,"She needs her guardian’s consent until she comes of age — which gives Jack his bargaining power."],
      ["The happiness of four people depends on resolving a single disagreement.",true,"Both marriages hang on the same exchange of consents."]
    ],
    writing:[
      {task:"Write a formal letter from Jack to Lady Bracknell, setting out his condition: he will consent to Cecily’s marriage the moment she consents to his own with Gwendolen.",
       target:"100–140 words",
       tips:["Keep the register formal and coldly polite throughout.","Present the proposal as a reasonable exchange, not a threat.","Structure it: situation, offer, condition, courteous closing."],
       starters:["Dear Lady Bracknell,","As Miss Cardew’s legal guardian, I find myself obliged to…","I am, however, prepared to reconsider, provided that…","I await your reply with the greatest interest…"]},
      {task:"Write an essay giving your opinion on the following statement: ‘When families judge a marriage, money still matters more than love.’",
       target:"100–140 words",
       tips:["Refer to Lady Bracknell’s instant conversion as your literary example.","Bring in a modern example or observation for contrast.","Signal your structure clearly: firstly, furthermore, nevertheless, in conclusion."],
       starters:["In Wilde’s comedy, a penniless nobody becomes a perfect match within minutes…","Firstly, it must be admitted that financial security…","Nevertheless, treating marriage as a transaction…","In conclusion, I believe that…"]}
    ]},
  { n:9, title:"The handbag returns to its owner",
    sum:"A chance mention of Miss Prism unlocks everything: twenty-eight years earlier, as a nursemaid, she absent-mindedly left a baby in a handbag at Victoria Station and put her novel in the pram. That baby was Jack — the son of Lady Bracknell’s sister, Algernon’s elder brother, and christened Ernest after his father, General Ernest John Moncrieff. With his name and family restored, every couple is free to marry.",
    vocab:[
      ["NURSEMAID","a woman employed to look after a baby"],
      ["MANUSCRIPT","the written pages of a book before it is printed"],
      ["CATASTROPHIC","causing sudden and complete disaster"],
      ["CLOAKROOM","a room where bags and coats are left temporarily"],
      ["DEPOSIT","to put something somewhere to be kept safe"],
      ["VANISH","to disappear suddenly and completely"],
      ["AGITATION","anxious excitement that is hard to control"],
      ["BATTERED","old and damaged by long use"],
      ["TRIUMPHANT","showing great joy at a victory or success"],
      ["IRRITATION","the feeling of being annoyed"],
      ["DISSOLVE","to disappear or break apart gradually"],
      ["EARNEST","serious and sincere"]
    ],
    comp:[
      ["What makes Lady Bracknell react so violently near the start of the chapter?",["The sight of an old handbag","Hearing the name Miss Prism","Dr Chasuble’s sermon","An accusation from Jack"],1,"The governess’s name means something to her that nobody else in the room suspects."],
      ["What position did Miss Prism once hold?",["Governess to Gwendolen","Nursemaid in the household of Lady Bracknell’s sister","Housekeeper to Mr Cardew","Teacher at a village school"],1,"Twenty-eight years earlier she had been trusted with a baby boy in that family."],
      ["What was eventually found in the abandoned pram?",["The baby, fast asleep","The manuscript of a three-volume novel","A black leather handbag","Nothing at all"],1,"The pram contained only the pages of her unpublished novel — the baby was gone."],
      ["What catastrophic mistake did Miss Prism make that morning?",["She took the wrong pram","She put the manuscript in the pram and the baby in her handbag","She lost her railway ticket","She boarded the wrong train"],1,"In a moment of distraction she exchanged baby and book, then left the handbag at the station."],
      ["How does Jack prove that he was the lost baby?",["He produces a birth certificate","He fetches the very handbag, which Miss Prism identifies as hers","He shows a letter from Mr Cardew","Lady Bracknell recognises his face"],1,"The battered handbag, identified by its marks and initials, is the decisive piece of evidence."],
      ["What new relationships does the discovery give Jack?",["He becomes Algernon’s elder brother and Lady Bracknell’s nephew","He becomes Cecily’s cousin","He becomes Dr Chasuble’s heir","He becomes Miss Prism’s son"],0,"As the son of Lady Bracknell’s late sister, he gains at a stroke the family he always lacked."],
      ["Why does Jack’s real name turn out to be Ernest?",["He chose it himself as a child","As eldest son he was named after his father, General Ernest John Moncrieff","Miss Prism christened him secretly","The name was sewn into the handbag"],1,"Family tradition named the first son after the father — so Jack was Ernest from the very beginning."],
      ["Why is Jack’s final remark about being earnest both a joke and a truth?",["His lie turned out to be accidentally true, so he becomes honest without ever having told the truth","He has learned nothing at all","He is still lying at the end","He secretly hates his new name"],0,"The pun closes the play: the man who lied about being Ernest discovers he was Ernest — and earnest — all along."]
    ],
    tf:[
      ["Miss Prism deliberately abandoned the baby at the station.",false,"It was a catastrophic accident caused by absent-mindedness, not an intentional act."],
      ["Jack’s handbag is identified by its marks and initials.",true,"Miss Prism examines the stain, the damage and the initials, and recognises it beyond doubt."],
      ["Jack turns out to be Lady Bracknell’s own son.",false,"He is the son of her late sister — her nephew, not her child."],
      ["The discovery makes Jack Algernon’s younger brother.",false,"It is the other way round: Jack is the elder of the two brothers."],
      ["Miss Prism and Dr Chasuble also reach an understanding at the end.",true,"The play closes with three happy couples, the rector and the governess among them."],
      ["Jack had been telling the truth about his name without ever knowing it.",true,"His invented identity was, by pure accident, his real one — the final irony of the play."]
    ],
    writing:[
      {task:"Write a review of ‘The Importance of Being Earnest’ for the school magazine, aimed at students deciding whether to read it. Include what you enjoyed and any criticism.",
       target:"100–140 words",
       tips:["Summarise the plot in two sentences at most, without revealing the final twist.","Comment on the humour, the characters and the famous dialogue.","End with a star rating or a clear recommendation."],
       starters:["Imagine lying about your name — and discovering the lie was true all along…","Wilde fills every scene with…","If the play has a weakness, it is perhaps…","Overall, I would give it…"]},
      {task:"Write an essay giving your opinion on the following statement: ‘The play proves that the truth always comes out in the end.’",
       target:"100–140 words",
       tips:["Take a position: does the play prove it, or does it mock the very idea?","Use two examples: the cigarette case and the handbag both expose secrets.","Note the irony that Jack is rewarded, not punished, for his lies."],
       starters:["At first sight, Wilde’s comedy seems to show that lies never last…","The cigarette case betrays Jack, and years later a handbag…","On the other hand, it is hard to ignore that…","My own conclusion is that…"]}
    ]}
];

const READINGS = {
1:["Algernon Moncrieff occupied an elegantly furnished flat in a fashionable part of London, where his devoted butler, Lane, attended to his every whim. One idle afternoon, while Algernon was entertaining himself rather badly at the piano, his old friend Jack Worthing was announced. In town Jack went by the name of ‘Ernest’, and on this occasion he had arrived with a serious purpose: he intended to propose to Algernon’s cousin, the fascinating Gwendolen Fairfax.",
"Before Jack could raise the subject, Algernon produced a silver cigarette case that his friend had carelessly left behind on a previous visit. Jack demanded it back, but Algernon, scenting a mystery, refused to hand it over until the inscription inside had been explained. It read: from little Cecily, with her fondest love to her dear Uncle Jack. Why, Algernon wondered aloud, should a man who called himself Ernest be addressed as Jack by a girl he had never mentioned?",
"Cornered, Jack reluctantly confessed the truth. In the country he was plain Jack Worthing, a respectable landowner and the legal guardian of Cecily Cardew, the granddaughter of the man who had adopted him. Since a guardian is expected to set a high moral tone, country life had become suffocatingly dull, and Jack had grown desperate for some harmless escape from his own good reputation. His solution, he admitted, was not an entirely honest one.",
"That solution was an invented younger brother named Ernest, a wicked and extravagant young man who was forever getting into scrapes in London. Whenever Jack felt trapped by his duties, he would announce gravely that poor Ernest was in trouble again and required his immediate attention. Once safely in town, however, Jack simply became Ernest himself, enjoying all the pleasures that his country reputation denied him. The deception had worked beautifully for years.",
"Far from being shocked, Algernon burst out laughing, for he practised precisely the same art. He had invented a permanent invalid called Bunbury, a friend whose health collapsed with remarkable convenience whenever Algernon wished to avoid a tedious dinner with his aunt, Lady Bracknell. Thanks to Bunbury, he explained cheerfully, he could escape to the country whenever town society threatened to become unbearable. He even had a private name for the habit: Bunburying.",
"‘You are one of the most advanced Bunburyists I know,’ Algernon declared with genuine admiration. Jack protested that he was nothing of the kind: if Gwendolen accepted his proposal, he intended to kill off his imaginary brother once and for all and settle down to a thoroughly honest life. Algernon merely smiled. A man who had lived a double life for years, he suspected, would not find the truth quite so easy to keep."],
2:["Lady Bracknell and Gwendolen were expected for tea, and Algernon had ordered cucumber sandwiches specially, since his aunt was famously particular about what she was served. Unfortunately, the long wait made him hungry. He absent-mindedly took one sandwich, then another, assuring Jack all the while that eating them was a host’s privilege. By the time the doorbell finally rang, nothing remained on the plate but crumbs, and Algernon was looking distinctly guilty.",
"When Lady Bracknell swept in and requested her favourite sandwiches, Algernon stared at the empty plate with an expression of theatrical horror and rang for Lane. Without so much as blinking, the loyal butler announced that there had been no cucumbers at the market that morning, not even for ready money. Lady Bracknell accepted this improbable excuse with dignity, though she was clearly annoyed, and consoled herself by discussing the arrangements for her next reception.",
"Before long, Algernon skilfully persuaded his aunt to join him in the music room, on the pretext of choosing songs for her party. The manoeuvre left Jack and Gwendolen alone at last, and Jack, though trembling with nerves, recognised that such an opportunity might never come again. Gathering his courage, he began, somewhat awkwardly, to tell Gwendolen how deeply he admired her, while she watched him with the calm confidence of a woman who had foreseen the whole scene.",
"To his delight, Gwendolen confessed that she returned his feelings entirely, though her explanation was unsettling. Her ideal, she declared, had always been to love a man called Ernest; the name inspired absolute confidence, and from the moment Algernon had first mentioned his friend Ernest, she had been destined to adore him. Jack cautiously asked whether she could love him if his name were, for the sake of argument, Jack. Gwendolen dismissed the idea without hesitation.",
"Jack, it seemed, was a perfectly respectable name, but it produced no vibrations whatsoever; a woman could hardly be expected to give her heart to it. Privately alarmed, Jack resolved on the spot to be christened Ernest at the earliest opportunity. Then, kneeling down in the proper romantic fashion, he formally proposed, and Gwendolen accepted him with enormous satisfaction, remarking that he had taken quite long enough to get to the point.",
"Their happiness lasted precisely as long as it took Lady Bracknell to return. Finding her daughter being proposed to on the carpet, she rose to her full and considerable height and demanded an explanation. Gwendolen announced her engagement proudly, but her mother corrected her at once: she was engaged to no one. When, and if, Gwendolen became engaged, she would be informed of the fact by her parents. The romance had run straight into a formidable obstacle."],
3:["Having dispatched Gwendolen to wait in the carriage, Lady Bracknell settled herself with great ceremony, produced a small notebook and pencil, and informed Jack that she now proposed to interview him. She kept a list, she explained, of eligible young men, and if his answers proved satisfactory, his name might one day appear on it. Jack, feeling rather like a prisoner facing trial, straightened his tie and prepared himself for the interrogation.",
"The interview began promisingly. Did he smoke? He did — and Lady Bracknell approved, observing that a man ought to have some occupation. His age, twenty-nine, was acceptable; his income was more than comfortable; and he owned a house in a fashionable square as well as an estate in the country. Jack answered each question smoothly, and for a while it genuinely seemed that he might satisfy the most demanding mother in London.",
"Then came the question of his family, and Jack’s confidence collapsed. He admitted, with visible embarrassment, that he had lost both his parents — though not, as Lady Bracknell assumed, through their death. The awkward truth was that he had no idea who his parents had been. He was an orphan of completely unknown origin, and he now had to explain the extraordinary circumstances in which he had been discovered as a baby.",
"He had been found, he explained, by the late Mr Thomas Cardew, a wealthy and charitable old gentleman, in the cloakroom at Victoria Station. He had been lying inside a large black leather handbag — an ordinary handbag, Jack added helpfully, with handles. Mr Cardew had adopted the child, given him the surname Worthing, and eventually left him a considerable fortune. It was, Jack admitted, an unusual beginning for a respectable gentleman.",
"Lady Bracknell listened with mounting horror. To be born, or at any rate brought up, in a handbag struck her as showing complete disrespect for ordinary family life, and she announced icily that her only daughter could hardly be expected to form an alliance with a piece of lost luggage. Whatever his income, a man with no relations of any kind could occupy no recognised position in good society. The interview, clearly, was over.",
"Her advice, delivered as she rose to leave, was brutally practical: Jack should make every effort to acquire some relations as quickly as possible, and to produce at least one parent before the fashionable season came to an end. Until then, an engagement was out of the question. She swept from the room magnificently, leaving Jack furious, humiliated and painfully aware that his mysterious origin now stood between him and everything he wanted."],
4:["Meanwhile, in the garden of Jack’s Manor House in the country, the atmosphere could hardly have been more peaceful. Roses were in bloom, tea was expected shortly, and Cecily Cardew, Jack’s pretty young ward, was supposed to be improving her mind. Her governess, Miss Prism, had set her a German lesson, and Cecily was resisting it with quiet determination, privately convinced that German grammar was designed to make attractive people plainer.",
"Cecily found watering the flowers infinitely more rewarding than irregular verbs, and her diary more absorbing still, for in it she recorded not merely what happened but what ought to have happened. Miss Prism disapproved of such fancies; she had, however, romantic weaknesses of her own. Whenever Dr Chasuble, the local rector, appeared at the garden gate, the stern governess softened visibly, and her lectures on duty were quickly abandoned.",
"When Miss Prism and Dr Chasuble strolled off together down the lane, Cecily was left to her own devices — but not for long. The servant announced a most unexpected visitor: Mr Ernest Worthing, her guardian’s scandalous younger brother. In reality, of course, the caller was Algernon, who had travelled down from London on a Bunburying expedition of his own, determined to meet the girl whose name he had seen on the cigarette case.",
"Cecily was thrilled beyond measure. For months she had heard her uncle sigh over his wicked brother, and she had secretly constructed a whole romantic legend around him. Now here he stood: elegant, confident and undeniably charming. Her single disappointment, which she confessed at once, was that he did not look nearly as wicked as she had hoped. Algernon, enchanted, promised faithfully to behave as badly as circumstances would allow.",
"They wandered about the garden talking, and every minute drew them closer together. Algernon had come merely to satisfy his curiosity, yet he found himself falling genuinely in love, forgetting almost entirely that his name, his history and his wickedness were all borrowed. Cecily, for her part, felt that reality was at last beginning to live up to her imagination, which was the highest compliment she could possibly pay it.",
"There was, however, a shadow hanging over this idyllic scene. At that very moment, up in London, the real Jack had reached a fateful decision: the imaginary Ernest had served his purpose and must now be disposed of for ever. While Algernon was charming Cecily in the role of the wicked brother, Jack was buying mourning clothes for that same brother’s funeral. The two schemes were heading straight for a collision."],
5:["The following afternoon Jack returned to the Manor House, and his appearance took everyone by surprise. He was dressed in the deepest mourning from head to foot, complete with black gloves and a black band upon his hat, and he wore an expression of carefully rehearsed sorrow. To Miss Prism and Dr Chasuble, who hurried across the garden to comfort him, it seemed obvious that some terrible tragedy had struck the family.",
"Jack broke the sad news with a heavy sigh: his unfortunate brother Ernest had passed away in Paris, carried off quite suddenly by a severe chill. Dr Chasuble offered his deepest condolences and promised to refer to the tragedy in next Sunday’s sermon. Nobody suspected the truth — that the grief was pure theatre, and that Jack was simply burying, once and for all, a brother who had never existed.",
"Then the plan fell spectacularly to pieces. Cecily came running from the house, radiant with excitement, and announced the most wonderful surprise: Uncle Jack’s brother Ernest had arrived and was waiting in the dining room. Before Jack could utter a word, Algernon strolled out into the garden, very much alive, wearing his most innocent smile. For a man officially dead in Paris, everyone might have agreed, he was looking remarkably well.",
"Jack turned pale with fury, and small wonder. He could hardly denounce the impostor without confessing that Ernest had never existed, and that he himself had been lying to his household for years. Trapped by his own invention, he was forced to shake hands with his ‘brother’ and accept the congratulations of the delighted onlookers, while privately promising himself that Algernon would be on the very first train back to London.",
"Yet beneath their quarrel, the two men shared exactly the same predicament. Jack was engaged to Gwendolen, who worshipped the name Ernest; Algernon was rapidly conquering Cecily, whose devotion to that name was, if anything, even stronger. Neither man was actually called Ernest, and both understood that the truth, once revealed, might very well cost him the affection of the woman he loved. Something clearly had to be done, and done quickly.",
"The solution each man privately hit upon was identical. One after the other, and in the strictest secrecy, they sought out Dr Chasuble and asked to be christened Ernest that very afternoon. The rector found it slightly odd that two grown men should suddenly require baptism on the same day, but he was far too kind to ask awkward questions, and he agreed to perform the ceremony for each of them between five and six o’clock."],
6:["Left alone with Cecily at last, Algernon abandoned all pretence of casual conversation. He told her, with unusual sincerity, that she was the most beautiful and remarkable girl he had ever met, and he begged her to marry him. It was, he felt, the first completely honest thing he had said since arriving at the Manor House — even if, unfortunately, he happened to be saying it under somebody else’s name.",
"Cecily received the proposal with puzzling calm. There was really no need for such excitement, she explained sweetly: they had already been engaged for the last three months. Algernon, who had met her barely twenty-four hours earlier, wondered for one dizzy moment whether he had misheard. Cecily assured him, with perfect seriousness, that he had heard her correctly, and kindly offered to show him the written evidence on which the whole engagement rested.",
"The evidence was her diary. Its pages recorded the entire history of their romance: the day the fascinating wicked brother had proposed, the box of letters he had written to her — every one of which she had composed herself — the day she had broken off the engagement after a dreadful quarrel, and the touching reconciliation that followed. A romance, Cecily observed, could hardly be considered serious unless it had been broken off at least once.",
"Far from being alarmed, Algernon was utterly enchanted. He had never encountered such creative devotion in his life, and he privately considered the love letters he had never written the finest he had never read. The engagement, both agreed, could now continue on a more official basis, with real meetings and conversations replacing imaginary ones. Algernon felt himself the luckiest man in England — until Cecily, quite innocently, added one final condition.",
"Her love, she confessed, had always depended upon his name. It had been her girlish dream to love someone called Ernest; there was something in that name that inspired complete trust. She pitied any poor woman whose husband was called, for instance, Algernon — a name, she remarked, without any music in it whatsoever. Could she love him under some other name? She feared, quite honestly, that she could not.",
"Algernon received this information with a frozen smile, for his real name was, of course, precisely Algernon. Inventing an urgent appointment, he kissed her hand and hurried off across the garden in search of Dr Chasuble. A christening had suddenly become a matter of the utmost urgency, and as he ran he reflected, not for the first time, that Bunburying was proving a far more complicated art than he had ever imagined."],
7:["Later that afternoon a stylish young lady descended from a cab at the Manor House: Gwendolen Fairfax had followed Jack into the country. Cecily, knowing nothing of her existence, welcomed the unexpected visitor warmly and ordered tea to be served in the garden. The two young women took an instant liking to each other, exchanged compliments and confidences, and agreed within minutes that they were clearly destined to become the closest of friends.",
"The friendship lasted exactly as long as it took the truth to surface. Gwendolen mentioned, with quiet pride, her engagement to Mr Ernest Worthing. Cecily, astonished, replied that there must be some mistake, since she herself was engaged to Mr Ernest Worthing. Each consulted her diary, each found her own claim confirmed in writing, and each remained perfectly certain that the other was the victim of a delusion. The temperature at the tea table dropped noticeably.",
"Both remained icily polite, for a lady never abandons her manners merely because her heart is breaking; but beneath the courtesy a duel had begun. Each hinted, delicately, that the other was suffering from an unfortunate misunderstanding, or possibly from something worse. Each made it elegantly clear that she had not the slightest intention of surrendering Ernest. The insults grew sharper as the smiles grew sweeter — a combination perfected at English tea parties.",
"The refreshments themselves became weapons. Asked whether she took sugar, Gwendolen replied loftily that sugar was no longer fashionable — whereupon Cecily dropped four lumps into her cup. Offered bread and butter, Gwendolen accepted graciously — and received an enormous slice of cake instead. Rising with tremendous dignity, Gwendolen observed that she had never been so treated in her life, and that her young hostess seemed to her a false and deceitful girl.",
"At the height of the battle Jack and Algernon appeared in the garden, one after the other, each fresh from arranging his christening. In the space of barely two minutes the whole structure of lies collapsed. Gwendolen learned that her Ernest was really called Jack; Cecily discovered that hers was actually Algernon; and both ladies grasped the essential, unforgivable fact — neither of them was engaged to anybody called Ernest at all.",
"The rivals were rivals no longer, for they now had something far more satisfying in common: betrayal. Calling each other ‘sister’, they embraced with great feeling and demanded to know where Jack’s brother Ernest actually was — only to be told that he had never existed. Deeply wounded, the two young women turned their backs on their deceivers with a single dignified movement and retired into the house, leaving the men to face the consequences."],
8:["The gentlemen did not remain in disgrace for long, chiefly because the ladies found silence even harder to bear than betrayal. Called upon to explain themselves, Jack and Algernon insisted that they had lied for the most honourable of reasons — the hope of meeting, and of marrying, the women they adored. Better still, each announced that he had already arranged to be christened Ernest that very afternoon, whatever the inconvenience involved.",
"The announcement changed everything. A willingness to face baptism for love struck both ladies as evidence of real self-sacrifice, and self-sacrifice, as Gwendolen observed, is precisely what a woman most admires in a man. The couples flew into each other’s arms, all deceptions forgiven if not entirely forgotten, and for one radiant moment the future looked cloudless. That, naturally, was when Lady Bracknell’s carriage was heard arriving at the front door.",
"Lady Bracknell had bribed Gwendolen’s maid, discovered her daughter’s destination, and followed her down by the first available train. Her position had not moved an inch: Jack, a man whose origins were located in a railway cloakroom, remained an impossible son-in-law, and Gwendolen was instructed to forget the entire regrettable episode immediately. Jack listened to it all with icy politeness, but he was already quietly preparing a devastating counter-attack of his own.",
"Algernon then presented Cecily as his future wife, and his aunt inspected the girl without enthusiasm — until Jack, with deliberate carelessness, mentioned the size of Cecily’s fortune. The effect was miraculous. Lady Bracknell decided on the spot that Miss Cardew was a most attractive and distinctly promising young lady, discovered unsuspected charm in her profile, and pronounced the match a thoroughly suitable one. Money, it appeared, was the one argument she never resisted.",
"It was now Jack’s turn to hold the winning card. As Cecily’s legal guardian, his consent was required before she could marry, and he refused, flatly and cheerfully, to give it. His ward, he declared, would be free to marry Algernon over his objection only when she came of age — and under the terms of her grandfather’s will, that meant a wait of quite considerable length. There was, however, one simple arrangement he was prepared to accept.",
"His terms were simplicity itself: the moment Lady Bracknell consented to his marriage with Gwendolen, he would joyfully consent to Cecily’s marriage with Algernon. Lady Bracknell refused to be blackmailed, as she saw it, and Jack refused to weaken. Neither would move an inch, and the negotiations arrived at a perfect deadlock. Four people stood within reach of happiness, and one stubborn question of family blocked the way for all of them."],
9:["The deadlock was broken from the most unexpected direction. Dr Chasuble, arriving to announce that everything was ready for the christenings, happened to mention Miss Prism — and at the sound of that name Lady Bracknell started as though she had been struck. In a voice that silenced the entire room, she demanded that the governess be fetched immediately. Nobody present had the faintest idea what the two women could possibly have in common.",
"The explanation reached back twenty-eight years. Miss Prism, it emerged, had once been employed as a nursemaid in the household of Lady Bracknell’s sister, in sole charge of a baby boy. One morning she had left the house pushing the child in its pram — and neither nursemaid, pram nor baby had ever returned. The pram was discovered weeks later, containing nothing but the pages of an unpublished three-volume novel. The baby had simply vanished.",
"Under Lady Bracknell’s terrible gaze, Miss Prism broke down and confessed everything. On that fatal morning, distracted beyond forgiveness, she had made one catastrophic mistake: she had placed her manuscript in the pram and had put the baby itself into her large black handbag. Then, in her confusion, she had gone on to deposit the handbag in the cloakroom at Victoria Station, and had fled, too ashamed ever to admit what she had done.",
"Jack had listened to this confession with growing agitation, and now he dashed from the room, reappearing moments later with a battered black handbag. Was this, he asked breathlessly, the very bag? Miss Prism examined it with the greatest care — the damage from a long-ago accident, the stain, the initials on the lock — and confirmed that it was unquestionably hers. Jack announced, overcome with emotion, that he himself was the baby she had lost.",
"The final pieces fell into place with dizzying speed. If Jack was that baby, then he was the son of Lady Bracknell’s late sister — which made him Algernon’s elder brother, and gave him, at a single stroke, precisely the thing he had always lacked: a family. Poor Miss Prism was forgiven, Gwendolen was triumphant, and Lady Bracknell found herself, to her considerable irritation, the aunt of the very man she had rejected for having no relations.",
"One question remained: his real name. As the eldest son, Jack had naturally been named after his father, General Ernest John Moncrieff — so his name had genuinely been Ernest all along. Every obstacle had dissolved: Jack claimed Gwendolen, Algernon claimed Cecily, and even Dr Chasuble and Miss Prism reached a quiet understanding of their own. Jack admitted that he had finally grasped the vital importance of being earnest — and for once he was speaking nothing but the truth."]
};

const EVENTS={
1:{ev:["Jack arrives at Algernon’s flat, planning to propose to Gwendolen.","Algernon refuses to return the cigarette case until its inscription is explained.","Jack confesses that he is Cecily’s guardian and leads a double life.","Jack describes his invented wicked brother, Ernest.","Algernon admits to his own invention, the invalid Bunbury.","Jack vows to kill off Ernest if Gwendolen accepts him."],keys:["piano","inscription","guardian","Ernest","Bunbury","Gwendolen"]},
2:{ev:["Algernon eats every cucumber sandwich before his aunt arrives.","Lane covers for him with the story about the market.","Algernon draws Lady Bracknell away into the music room.","Gwendolen confesses her devotion to the name Ernest.","Jack proposes and Gwendolen accepts.","Lady Bracknell returns and declares the engagement invalid."],keys:["cucumbers","Lane","Ernest","christened","carpet","engagement"]},
3:{ev:["Lady Bracknell sends Gwendolen to the carriage and opens her notebook.","Jack answers the questions about smoking, age, income and property well.","The question of family exposes Jack’s unknown origin.","Jack recounts being found in a handbag by Mr Cardew.","Lady Bracknell is horrified and ends the interview.","She advises Jack to acquire some relations and sweeps out."],keys:["notebook","income","handbag","Cardew","cloakroom","relations"]},
4:{ev:["Cecily resists her German lesson in the garden.","Miss Prism walks off with Dr Chasuble.","A visitor is announced: Mr Ernest Worthing.","Cecily meets the ‘wicked brother’ she has long imagined.","Algernon genuinely falls in love with Cecily.","In London, Jack prepares to announce Ernest’s death."],keys:["garden","German","diary","Chasuble","Cecily","mourning"]},
5:{ev:["Jack returns home in deep mourning.","He announces that Ernest has died of a chill in Paris.","Cecily presents the living ‘Ernest’ — Algernon.","Jack is forced to greet the impostor as his brother.","Both men realise the women they love worship the name Ernest.","Each secretly asks Dr Chasuble for a christening that afternoon."],keys:["Paris","chill","sermon","impostor","baptism","rector"]},
6:{ev:["Algernon sincerely proposes to Cecily.","Cecily announces that they have been engaged for three months.","She shows him the diary, the letters and the invented quarrel.","Algernon is enchanted by her imagination.","Cecily explains that she could only love a man called Ernest.","Algernon rushes off to arrange his christening."],keys:["proposal","months","letters","reconciliation","Algernon","christening"]},
7:{ev:["Gwendolen arrives and instantly befriends Cecily.","Both women claim to be engaged to Ernest Worthing.","The friendship turns into a duel of exquisite politeness.","Sugar and cake become weapons at the tea table.","The men appear and the truth about their names emerges.","The deceived women unite and withdraw into the house."],keys:["tea","diary","sugar","cake","sister","betrayal"]},
8:{ev:["The men are forgiven after promising to be christened Ernest.","Lady Bracknell arrives, having bribed Gwendolen’s maid.","She again rejects Jack as a husband for Gwendolen.","Cecily’s fortune turns her into a perfect match for Algernon.","Jack refuses his consent unless he may marry Gwendolen.","The negotiations end in complete deadlock."],keys:["forgiven","carriage","maid","fortune","guardian","deadlock"]},
9:{ev:["Dr Chasuble’s mention of Miss Prism electrifies Lady Bracknell.","The story of the lost baby and the abandoned pram emerges.","Miss Prism confesses the mix-up of manuscript and baby.","Jack produces the battered handbag and Miss Prism identifies it.","Jack proves to be Algernon’s elder brother and gains a family.","His real name is revealed as Ernest, and every couple is united."],keys:["Prism","pram","manuscript","handbag","Moncrieff","earnest"]}
};

return {level:'B2', lead:'Oscar Wilde · retelling · <b>B2 upper-intermediate</b> (≈2,000 headwords)',
  CHAPTERS:CHAPTERS, READINGS:READINGS, EVENTS:EVENTS};
})();
