/* BEING EARNEST - datos nivel C1 (advanced retelling).
   Mismo formato que attwn-data-*.js; EVENTS completos. */
window.ATTWN_DATA = (function(){
const CHAPTERS = [
  { n:1, title:"The silver case",
    sum:"Algernon Moncrieff’s London flat: Jack Worthing, known in town as ‘Ernest’, arrives to propose to Gwendolen, but a silver cigarette case inscribed by ‘little Cecily’ forces him to confess a double life. Algernon, delighted, matches the confession with an invention of his own — a chronically ill and wholly imaginary friend named Bunbury.",
    vocab:[
      ["INDOLENCE","elegant laziness; a settled avoidance of effort"],
      ["SCRUTINY","close, critical examination"],
      ["DUPLICITY","deceitfulness; the keeping of a double face"],
      ["RESPECTABILITY","the state of being regarded as socially proper"],
      ["PROPRIETY","conformity to accepted standards of behaviour"],
      ["FABRICATION","an invented story; a lie constructed with care"],
      ["PRETEXT","a false reason given to conceal the real one"],
      ["FLIPPANT","treating serious matters with unbecoming lightness"],
      ["WARD","a young person under the legal care of a guardian"],
      ["IMPECCABLE","faultless; impossible to criticise"],
      ["FORMIDABLE","inspiring fear or respect through force of character"],
      ["INVALID","a person weakened by long illness"]
    ],
    comp:[
      ["What does the narrator suggest about Algernon’s attitude to his own idleness?",["He is ashamed of it","He regards it as a kind of accomplishment","He conceals it from Lane","He blames it on his aunt"],1,"His indolence is ‘cultivated’ and playing the piano badly is counted ‘to his credit’ — laziness worn as a distinction."],
      ["Why is the cigarette case such effective evidence against Jack?",["It is stolen property","Its inscription belongs to a life that ‘Ernest’ cannot explain","It proves Jack is poor","Cecily engraved a false name on it"],1,"A gift addressed to ‘dear Uncle Jack’ cannot be reconciled with the identity of Ernest."],
      ["What is ironic about Jack’s reason for inventing Ernest?",["He hates London","His duty to appear moral is precisely what drives him to systematic lying","He wants Cecily to marry Ernest","He needs the money"],1,"The obligation to model respectability for Cecily produces the deception it forbids."],
      ["How does Algernon receive Jack’s confession?",["With moral outrage","With delighted professional recognition","With jealousy of Cecily","With complete indifference"],1,"Far from being shocked, he identifies a fellow practitioner and names the art: Bunburying."],
      ["What function does Bunbury serve in Algernon’s life?",["He manages Algernon’s money","He provides an unanswerable excuse for escaping social duty","He writes Algernon’s letters","He supplies medical advice"],1,"Bunbury’s convenient relapses release Algernon from engagements he wishes to avoid."],
      ["What does the narrator imply by calling Bunbury ‘a valuable investment’?",["Algernon lends him money","Algernon’s tenderness for Bunbury is really self-interest","Bunbury pays Algernon rent","The friendship improves Algernon’s health"],1,"The affection is for the usefulness of the fiction, not for any person."],
      ["What is Jack’s stated plan if Gwendolen accepts him?",["To move to Paris","To kill off his invented brother and live honestly","To adopt Cecily formally","To confess everything to Lady Bracknell"],1,"He intends to abolish Ernest — a promise the plot will make peculiarly difficult to keep."],
      ["What target of Wilde’s satire does this chapter chiefly establish?",["The dishonesty of servants","A society whose rigid propriety makes deception a practical necessity","The cruelty of guardians","The vanity of musicians"],1,"Both men lie not to do evil but to escape the suffocating demands of respectability."]
    ],
    tf:[
      ["Algernon regards Bunburying as a shameful necessity to be abandoned.",false,"He defends it as an art and very nearly a social duty."],
      ["Jack became Cecily’s guardian through the old gentleman who adopted him.",true,"Thomas Cardew adopted Jack; Cecily is Cardew’s granddaughter."],
      ["It is the words engraved inside the case that first betray Jack.",true,"‘Uncle Jack’ from ‘little Cecily’ cannot be squared with the name Ernest."],
      ["Jack intends to go on Bunburying after his marriage.",false,"He plans to kill off Ernest and retire into honesty."],
      ["Bunbury is a distant cousin whom Algernon dislikes.",false,"Bunbury is wholly imaginary — an invented invalid friend."],
      ["In town Jack permits himself pleasures his country reputation forbids.",true,"As ‘Ernest’ he enjoys exactly what Cecily’s guardian could never be seen enjoying."]
    ],
    writing:[
      {task:"Write an essay discussing the following statement: ‘In the world of the play, a spotless reputation is only possible for those who lie well.’ Refer to both Jack and Algernon.",
       target:"150–190 words",
       tips:["Take a clear position in your opening paragraph and sustain it throughout.","Support each point with a specific example: the invented brother, the invented invalid.","Use concessive structures (although, admittedly, granted that) to weigh the opposing view."],
       starters:["At first sight, respectability and deception appear to be opposites…","Jack’s case suggests that…","Algernon, by contrast, treats dishonesty as…","On balance, the chapter implies that…"]},
      {task:"Write a character analysis of Algernon Moncrieff as he appears in this chapter, considering how far his charm depends on his refusal to take anything seriously.",
       target:"150–190 words",
       tips:["Organise your analysis by trait, not by plot event.","Anchor each claim in something Algernon says or does — the sandwiches, the case, Bunbury.","Close with an evaluative judgement rather than a summary."],
       starters:["Algernon presents himself as…","His treatment of Bunbury reveals…","What redeems — or fails to redeem — this frivolity is…","Ultimately, Algernon functions as…"]}
    ]},
  { n:2, title:"No cucumber sandwiches",
    sum:"Lady Bracknell and Gwendolen come to tea; Algernon devours the cucumber sandwiches ordered for his aunt, and Lane lies about it flawlessly. While Algernon distracts Lady Bracknell in the music room, Jack proposes to Gwendolen, who accepts him — chiefly because her lifelong ideal has been to love a man called Ernest.",
    vocab:[
      ["IMPERIOUS","commanding; expecting instant obedience"],
      ["COMPOSURE","calm self-possession under pressure"],
      ["EVASION","an indirect answer designed to avoid the truth"],
      ["DEVOUR","to eat greedily and completely"],
      ["INFATUATION","an intense, unreasoning passion"],
      ["CANDOUR","disarming frankness"],
      ["MANOEUVRE","a skilful move planned to gain an advantage"],
      ["RESOLVE","to decide firmly on a course of action"],
      ["SUPERFICIAL","concerned only with the surface of things"],
      ["HYPOTHESIS","a supposition put forward for testing"],
      ["NOTORIOUS","widely known for something bad"],
      ["CREDENTIALS","the qualifications that entitle a person to trust"]
    ],
    comp:[
      ["What is comic about Algernon’s handling of the cucumber sandwiches?",["He forgets to order them","He solemnly provides them for his aunt and then eats every one himself","He serves them to Jack first","He hides them from Lane"],1,"The elaborate courtesy collapses into pure appetite, leaving Lane to repair the damage."],
      ["What does Lane’s explanation about the cucumbers reveal?",["He is careless with money","A good servant lies more smoothly than his master","He dislikes Lady Bracknell","There really were no cucumbers"],1,"His imperturbable ‘not even for ready money’ is polished, instantaneous collusion."],
      ["Why does Algernon take Lady Bracknell into the music room?",["He wants her opinion of his playing","To engineer Jack’s moment alone with Gwendolen","To hide the empty plate","To discuss Bunbury privately"],1,"The exit is a deliberate manoeuvre that clears the stage for the proposal."],
      ["How does Gwendolen upset the conventions of a proposal?",["She refuses to answer","She announces that she had decided to accept him before he manages to ask","She calls her mother in","She proposes to Algernon instead"],1,"Her candour leaves Jack ‘remarkably little to propose’ — she directs the scene."],
      ["What, precisely, is Gwendolen in love with?",["Jack’s estate","The name Ernest and the confidence it inspires","Jack’s modesty","London society"],1,"Her ideal attaches to two syllables rather than to the man who happens to bear them."],
      ["Why does Jack float the name ‘Jack’ as a hypothesis?",["He is testing whether her love could survive his real name","He prefers plain names","He wants to tease her","He has forgotten his own name"],0,"The experiment fails: Jack is a ‘domestic’ name, without music or vibrations."],
      ["What does Jack resolve after Gwendolen’s verdict on names?",["To abandon the engagement","To be christened Ernest at the earliest opportunity","To change her mind gradually","To consult Algernon"],1,"He concludes that the superficial must be taken seriously — and corrected by arrangement."],
      ["What is Lady Bracknell’s position on the engagement at the chapter’s end?",["She approves warmly","She denies that any engagement exists until she has examined Jack herself","She defers to Gwendolen","She merely postpones the wedding"],1,"An engagement, in her view, is announced by parents; Jack must first survive her interview."]
    ],
    tf:[
      ["Algernon eats the sandwiches as a deliberate insult to his aunt.",false,"He eats them absently, out of appetite and habit, not malice."],
      ["Lane’s excuse is accepted by Lady Bracknell without question.",true,"The evasion passes into the record unchallenged."],
      ["Gwendolen is taken completely by surprise by Jack’s declaration.",false,"She replies that his admiration has long been perfectly obvious to her."],
      ["Gwendolen suggests she could love Jack whatever he was called.",false,"She dismisses ‘Jack’ outright and insists that only Ernest is safe."],
      ["Jack privately decides to acquire the name Ernest by christening.",true,"He resolves to correct the accident of his name by arrangement."],
      ["Lady Bracknell treats the engagement as settled once she returns.",false,"She dissolves it on the spot, pending her own examination of Jack."]
    ],
    writing:[
      {task:"Write a review of a stage production of the play for a culture website, focusing on how the tea-and-proposal scene was performed and whether its irony survived the staging.",
       target:"150–190 words",
       tips:["Invent concrete production details — timing, delivery, set — and judge them.","Balance praise and criticism so the review feels fair rather than promotional.","End with a clear recommendation for your readers."],
       starters:["Few scenes depend so entirely on timing as…","The director’s boldest choice was…","Where the production faltered was…","For anyone who doubts that comedy can be…"]},
      {task:"Write an article for an international student magazine entitled ‘Judged by our names?’, exploring whether names shape how people are perceived, using Gwendolen’s ideal as your springboard.",
       target:"150–190 words",
       tips:["Open with a hook — a question or striking claim — before introducing the play.","Move from Wilde’s satire to modern evidence or examples of name-based judgement.","Keep the register lively but precise; an article may address the reader directly."],
       starters:["Would you trust an Ernest more than a Jack?","Gwendolen Fairfax loves a man she has barely met because…","Research on first impressions suggests…","Perhaps Wilde’s joke is on us:…"]}
    ]},
  { n:3, title:"Lady Bracknell interviews Jack",
    sum:"Lady Bracknell subjects Jack to a formal interview covering income, property and — decisively — family. His confession that he was found, as a baby, in a handbag in the cloakroom at Victoria Station proves fatal: she refuses her consent until he can produce at least one parent.",
    vocab:[
      ["INTERROGATION","prolonged, formal questioning"],
      ["ELIGIBLE","suitable, socially or financially, to be chosen"],
      ["MERCENARY","motivated by money rather than feeling"],
      ["NEGLIGENCE","culpable failure to take proper care"],
      ["INCREDULITY","the refusal or inability to believe"],
      ["FOUNDLING","an abandoned child of unknown parents"],
      ["PEDIGREE","a line of distinguished ancestors"],
      ["CONTEMPT","the feeling that something is beneath consideration"],
      ["ANCESTRY","the family line from which one descends"],
      ["ULTIMATUM","a final demand backed by a threat"],
      ["VERDICT","a formal judgement or decision"],
      ["CONNOISSEUR","an expert judge in matters of taste"]
    ],
    comp:[
      ["What does the notebook-and-pencil detail suggest about Lady Bracknell?",["She is forgetful","Courtship in her world is processed like an official application","She is secretly writing a novel","She distrusts her own memory"],1,"The interview is bureaucratic: candidates are entered on lists if their answers satisfy."],
      ["Why does Lady Bracknell approve of Jack’s smoking?",["She smokes herself","She counts it as an occupation, and idle men alarm her","Doctors recommend it","It proves he is wealthy"],1,"The reasoning is deliberately absurd: any occupation, even smoking, is better than none."],
      ["What is satirised by the order of her questions?",["Her poor education","That character and affection come nowhere, far behind income and family","Her fear of trains","Her devotion to Gwendolen"],1,"Money and pedigree are the substance of the examination; love is never on the list."],
      ["How does Lady Bracknell interpret Jack’s loss of both parents?",["As a tragedy deserving sympathy","As something close to carelessness on his part","As proof of weak health in the family","As a purely legal difficulty"],1,"Her celebrated logic treats misfortune as a fault of etiquette: losing both ‘looks like carelessness’."],
      ["Why does Jack’s offer to produce the handbag fall flat?",["The handbag is lost","Physical evidence cannot supply what she actually wants — ancestry","She suspects forgery","She has already seen it"],1,"Her objection is not to proof but to origin: a handbag is not a pedigree."],
      ["What does her horror of marrying ‘into a cloakroom’ convey?",["A literal fear of stations","That for her, family origin is a qualification, not a detail","Concern about lost luggage","A joke to relieve the tension"],1,"Jack’s fortune and manners weigh nothing against the unanswered question of who he is."],
      ["What is ironic about Lady Bracknell’s parting advice?",["She tells him to acquire relations, as though relatives could be produced on demand","She advises him to travel abroad","She suggests he write to the newspapers","She asks him to adopt a child"],0,"‘Acquire some relations’ treats family as a commodity — the satire’s sharpest point."],
      ["How does Jack respond to his defeat?",["He weeps openly","He abuses his opponent once the door is safely closed","He follows her into the street","He proposes to someone else"],1,"The narrator calls it the traditional English manner — courage after the fact."]
    ],
    tf:[
      ["Jack fails the financial part of the interview.",false,"His income and property are found more than satisfactory."],
      ["Lady Bracknell saves the question of family for the end.",true,"She reserves her decisive category for last, like a connoisseur."],
      ["Jack conceals the story of the handbag from her.",false,"He confesses it fully and even offers to produce the handbag itself."],
      ["Mr Cardew named the baby after a railway destination.",true,"He held a first-class ticket to Worthing and named the foundling accordingly."],
      ["Lady Bracknell rejects Jack chiefly because his fortune is too small.",false,"His fortune is real; it is his lack of ancestry that ruins him."],
      ["Algernon reacts to the disaster with tactful silence.",false,"He plays a wedding march next door with malicious cheerfulness."]
    ],
    writing:[
      {task:"Write a formal letter from Lady Bracknell to a friend of equal rank, reporting her interview with Mr Worthing and justifying her refusal according to her own inimitable logic.",
       target:"150–190 words",
       tips:["Sustain a formal register throughout — no contractions, elaborate courtesy.","Let the comedy come from her values, not from open jokes: report absurd priorities solemnly.","Follow letter conventions: salutation, structured paragraphs, formal close."],
       starters:["My dear Lady Harbury,","I write to acquaint you with a most unsatisfactory interview…","His income, I confess, was unexceptionable; his origins, however,…","Until he produces a parent of either sex,…"]},
      {task:"Write an essay discussing the statement: ‘Lady Bracknell’s interview is comic precisely because it is honest about what society values.’",
       target:"150–190 words",
       tips:["Define the paradox early: her rudeness is society’s politeness with the mask off.","Use two or three concrete moments from the interview as evidence.","Address a counter-argument — is she an exception rather than the rule?"],
       starters:["Lady Bracknell says aloud what her class prefers to imply…","Her approval of smoking as ‘an occupation’ shows…","The handbag scandalises her not because…","In the end, the laughter is directed at…"]}
    ]},
  { n:4, title:"The Manor House",
    sum:"At Jack’s country estate, Cecily dodges her German lesson while Miss Prism exchanges decorous signals with Dr Chasuble. Then Algernon arrives masquerading as Jack’s wicked brother Ernest — and discovers that Cecily has been devotedly in love with that scandalous invention for months.",
    vocab:[
      ["IDYLLIC","peacefully perfect, like a scene from pastoral poetry"],
      ["DECOROUS","correct and restrained in manner"],
      ["CLERGYMAN","an ordained minister of the church"],
      ["MASQUERADE","a pretence; appearing as someone one is not"],
      ["IMPOSTOR","a person who assumes a false identity"],
      ["HYPOCRISY","professing virtues one does not practise"],
      ["NOTORIETY","fame of a disreputable kind"],
      ["COURTSHIP","the wooing of an intended partner"],
      ["SENTIMENTAL","indulging emotion for its own sake"],
      ["SEVERITY","strictness; harshness of manner"],
      ["FARCE","comedy built on absurd situations and precise timing"],
      ["FLIRTATION","playful, half-serious romantic attention"]
    ],
    comp:[
      ["What does Cecily’s preference for watering flowers over German imply?",["She is incurably lazy","She values what responds to attention over what is merely improving","She dislikes Miss Prism personally","She intends to become a gardener"],1,"Flowers, ‘unlike grammar’, respond to care — her logic is practical, not idle."],
      ["How does Cecily’s diary treat the truth?",["As a strict record of facts","As raw material to be improved into what ought to have happened","As a secret code","As preparation for publication"],1,"She records the ideal rather than the actual — imagination as a superior form of truth."],
      ["What is comic about Miss Prism’s disapproval of imagination?",["She has no imagination at all","Her severity has the intensity of someone correcting faults she recognises","She secretly encourages it in Cecily","She confuses it with arithmetic"],1,"The narrator hints that she is condemning her own buried past."],
      ["How is the Prism–Chasuble romance conducted?",["Through open declarations","Through decorous hints, quotations and conveniently prescribed walks","Through letters","Through Cecily as a messenger"],1,"A headache curable only by a walk in his company is courtship in respectable disguise."],
      ["Why is Cecily ‘slightly disappointed’ by the visitor?",["He is older than she expected","He fails to look as wicked as his reputation promised","He does not know her name","He arrives without gifts"],1,"His respectable appearance even raises her suspicion of a double life in reverse."],
      ["What is the ‘reverse hypocrisy’ Cecily hopes Ernest has avoided?",["Pretending to be wicked while secretly being good","Pretending to be good while secretly being wicked","Pretending to be rich while poor","Pretending to be ill while healthy"],0,"She inverts the usual charge: seeming bad while being good would also be a deception."],
      ["What, according to the narrator, punishes Algernon’s curiosity?",["Exposure by Miss Prism","Falling genuinely in love","Losing his fortune","Jack’s sudden arrival"],1,"He comes as ‘a tourist in someone else’s fiction’ and is captured by real feeling."],
      ["What makes the chapter’s ending an exercise in dramatic irony?",["The reader knows the ‘dead’ brother is courting in the garden while Jack rehearses the news of his death","Cecily knows Algernon’s true name","Miss Prism recognises Algernon","Dr Chasuble suspects everything"],0,"The audience holds both halves of the coincidence; the household holds neither."]
    ],
    tf:[
      ["Miss Prism believes disagreeable studies improve the character.",true,"German is valuable to her precisely because Cecily finds it disagreeable."],
      ["Cecily’s diary is a faithful record of daily events.",false,"It records what ought to have happened — memory improved upon."],
      ["Dr Chasuble is fully aware that he is being courted.",false,"His learning is ‘exceeded only by his failure to notice’."],
      ["Curiosity about the Cecily of the cigarette case brings Algernon to the house.",true,"He comes to inspect the girl whose inscription unmasked Jack — and is caught himself."],
      ["Cecily finds Algernon’s appearance convincingly wicked.",false,"She is disappointed: he looks entirely respectable."],
      ["Jack is travelling home to announce his brother’s marriage.",false,"He is coming to announce Ernest’s death and bury the fiction for good."]
    ],
    writing:[
      {task:"Write an article for a literary magazine entitled ‘The diary as fiction’, discussing why people curate idealised versions of their lives, from Cecily’s diary to modern social media.",
       target:"150–190 words",
       tips:["Bridge explicitly from Cecily’s method to a modern parallel within your first paragraph.","Offer at least one reason people edit their lives, and one cost of doing so.","Finish with a memorable closing line rather than a flat summary."],
       starters:["Cecily Cardew records not what happened, but what ought to have happened…","A century later, her diary has millions of imitators…","We edit our lives, perhaps, because…","The danger begins when the author starts believing…"]},
      {task:"Write a character analysis of Miss Prism, considering how Wilde uses her severity, her lost novel and her guarded courtship to satirise respectability itself.",
       target:"150–190 words",
       tips:["Treat her contradictions as the key: strict governess, secret novelist, shy romantic.","Link each observation to the play’s wider satire of propriety.","Reserve judgement until the final sentences, then commit to one."],
       starters:["Miss Prism guards respectability like a woman who…","Her hostility to sentiment sits oddly beside…","In her decorous pursuit of Dr Chasuble, Wilde shows…","She is less a hypocrite than…"]}
    ]},
  { n:5, title:"In mourning",
    sum:"Jack comes home in deep mourning, announcing that his brother Ernest has died in Paris — only to find ‘Ernest’ alive in his own garden in the person of Algernon. Trapped by their interlocking fictions, both men secretly ask Dr Chasuble to christen them Ernest that very afternoon.",
    vocab:[
      ["BEREAVEMENT","the state of having lost someone to death"],
      ["CONDOLENCES","formal expressions of sympathy after a death"],
      ["SOLEMNITY","deep, ceremonial seriousness"],
      ["AUDACITY","shameless daring"],
      ["CHARADE","an absurd pretence kept up for appearances"],
      ["PREDICAMENT","a difficult situation with no easy exit"],
      ["ECCLESIASTICAL","relating to the church"],
      ["BAPTISM","the church ceremony of naming and admission"],
      ["DENOUNCE","to condemn publicly; to expose"],
      ["IMMACULATE","spotless; perfectly turned out"],
      ["PARISHIONER","a member of a priest’s local congregation"],
      ["COMBUSTIBLE","liable to catch fire; explosive"]
    ],
    comp:[
      ["What detail undercuts the sincerity of Jack’s mourning?",["His clothes are the wrong colour","His grief appears rehearsed, worn like a costume","He laughs as he arrives","He forgets his brother’s name"],1,"An expression ‘practised on the train’ signals performance rather than sorrow."],
      ["What is ironic about the sympathy Jack receives?",["It is offered coldly","Genuine condolences are lavished on a wholly invented death","It comes from strangers","It arrives too late"],1,"Real feeling is spent on a fiction — the chapter’s central joke."],
      ["Why is Jack’s truthful protest — that he has no brother — disbelieved?",["He whispers it","Everyone can see the ‘brother’ standing there alive","Cecily contradicts him with documents","Dr Chasuble forbids the subject"],1,"His one honest sentence of the day is defeated by Algernon’s living presence."],
      ["Why can Jack not simply denounce Algernon?",["He is physically afraid of him","Exposing the impostor would expose his own invention of Ernest","Algernon holds evidence against him","The law forbids it"],1,"The two lies are interlocked: to destroy one is to confess the other."],
      ["What does ‘a reconciliation with a corpse of his own manufacture’ mean?",["Jack forgives a dead relative","Jack must publicly embrace the fictional brother he has just declared dead","Jack attends a funeral","Jack repairs a broken statue"],1,"The handshake reconciles him with his own walking fabrication."],
      ["Why does Algernon refuse to leave by the first train?",["The trains are cancelled","Cecily now outweighs every other consideration","Jack begs him to stay","He is waiting for Lady Bracknell"],1,"No timetable on earth, the narrator notes, could compete with her."],
      ["What do the two secret visits to Dr Chasuble have in common?",["Both men confess their lies","Both request the same christening, urgently, under the same name","Both ask about funerals","Both seek marriage licences"],1,"Identical requests, identical motive: the women’s fixation on the name Ernest."],
      ["How is Dr Chasuble characterised through his reaction?",["Suspicious and probing","Serenely incurious — faith without observation","Hostile to baptism","Eager for gossip"],1,"He finds nothing odd in a sudden epidemic of christenings among healthy adults."]
    ],
    tf:[
      ["Jack’s mourning clothes are described as carelessly assembled.",false,"His mourning is deep and conscientious down to the hatband — that is the joke."],
      ["Cecily believes she is performing an act of family kindness.",true,"She begs Jack to be reconciled with his unfortunate ‘brother’."],
      ["Of the two liars in the garden, Jack is the one enjoying himself.",false,"Algernon relishes the scene; Jack, trapped in black, nearly chokes on it."],
      ["Both men hold a legal claim to the name Ernest.",false,"Neither has the smallest legal claim to it — hence the christenings."],
      ["Dr Chasuble appoints both christenings for the same afternoon.",true,"He consults his diary and books the ceremonies for half-past five."],
      ["Gwendolen is already travelling toward the Manor House.",true,"Fate, ‘always punctual’ in comedies, has her on the train."]
    ],
    writing:[
      {task:"Write a review of the mourning scene as staged in an imagined production, assessing how a director should balance farce with the outward appearance of grief.",
       target:"150–190 words",
       tips:["Discuss specific staging choices: costume, pace, the moment Algernon appears.","Evaluate rather than describe — say what worked, what failed, and why.","Address your reader as a potential audience member."],
       starters:["Playing grief for laughs is a dangerous business…","The black gloves and hatband did half the comedy’s work…","The production’s masterstroke came when…","Whether the balance holds will depend on…"]},
      {task:"Write an essay discussing the statement: ‘In comedy, the liar’s real punishment is having to maintain the lie.’ Refer closely to Jack’s predicament in this chapter.",
       target:"150–190 words",
       tips:["Establish the principle first, then test it against Jack’s afternoon.","Show the mechanism: each lie forbids the confession that would end the other.","Consider briefly whether Algernon escapes this punishment or shares it."],
       starters:["Comedy rarely bothers to punish its liars with exposure…","Jack, dressed in mourning for a living man,…","The trap closes because…","Wilde’s suggestion, perhaps, is that deception…"]}
    ]},
  { n:6, title:"The engagement",
    sum:"Algernon proposes to Cecily and learns that, according to her diary, they have already been engaged for three months — complete with love letters she wrote herself and a quarrel she invented for effect. Since she too could only love a man named Ernest, he hurries off to arrange his christening.",
    vocab:[
      ["TRANQUILLITY","unruffled calm"],
      ["IMPROVISE","to invent on the spur of the moment"],
      ["CORRESPONDENCE","an exchange of letters"],
      ["RUPTURE","a sudden breaking-off of relations"],
      ["FANCIFUL","born of imagination rather than fact"],
      ["CHRONICLE","a detailed record of events in order"],
      ["INGENUITY","inventive cleverness"],
      ["DEVOTION","committed, self-giving love"],
      ["IMMOVABLE","impossible to shift from a position"],
      ["COUNTERFEIT","an imitation passed off as genuine"],
      ["IMPERATIVE","an unavoidable demand or necessity"],
      ["ELOQUENT","fluent and persuasive in expression"]
    ],
    comp:[
      ["Why is Algernon left ‘without a line’ by Cecily’s reply?",["She rejects him outright","She accepts a proposal he has only just made as though it were three months old","She laughs at his clothes","She calls for Miss Prism"],1,"His gift for improvisation fails before an engagement that predates his arrival."],
      ["According to Cecily, how did she come to love Ernest?",["They met secretly in town","Constant discussion and disapproval of him made falling in love inevitable","Jack encouraged the match","She was persuaded by his letters"],1,"A man talked about so constantly and condemned so thoroughly, she reasons, must be loved."],
      ["What is revealing about the letters Cecily shows him?",["They were forged by Miss Prism","She wrote them herself on his behalf — and is genuinely moved by them","They were never delivered","They are written in German"],1,"She authored both sides of the correspondence and can hardly read ‘his’ best lines without crying."],
      ["Why did Cecily break off the imaginary engagement in March?",["‘Ernest’ had offended her","A serious engagement, she felt, required at least one rupture","Miss Prism ordered it","She had simply forgotten it"],1,"The quarrel was aesthetic: an engagement without one would hardly have been serious."],
      ["What does Algernon’s reaction to the diary romance show about him?",["Alarm at her instability","Admiration — he prizes ingenuity above conventional truth","Boredom","Fear of Jack’s anger"],1,"He is enchanted to have been courted, quarrelled with and forgiven in his absence."],
      ["What is the ‘clause’ that turns Algernon’s triumph cold?",["Cecily’s demand for wealth","Her devotion is conditional on the name Ernest","Jack’s guardianship","A ten-year delay"],1,"Her fondness rests on a name to which he has no claim whatsoever."],
      ["What is ironic about Algernon’s departure from the garden?",["He leaves without his hat","He hurries off to become genuinely the counterfeit he has been performing","He goes to confess everything to Jack","He abandons Cecily entirely"],1,"He entered as a false Ernest and exits determined to be baptised a true one."],
      ["What does Cecily do the moment he leaves?",["She bursts into tears","She rewrites the proposal in her diary more eloquently than it happened","She follows him to the church","She burns the letters"],1,"Life, once again, is edited upward into literature."]
    ],
    tf:[
      ["Cecily receives the proposal with astonishment.",false,"She receives it with tranquillity: they are, of course, already engaged."],
      ["The engagement was recorded in the diary before Algernon ever met Cecily.",true,"It began on a specific February date, entirely without his participation."],
      ["Cecily wept over letters she knew she had written herself.",true,"Some were so beautiful, she admits, that she could hardly read them without crying."],
      ["Algernon persuades Cecily that his own name could inspire confidence.",false,"She is sympathetic but immovable: the name lacks the essential quality."],
      ["Algernon leaves the garden to consult Jack about his position.",false,"He hurries to Dr Chasuble to secure his christening."],
      ["The narrator suggests that love in this household requires paperwork.",true,"Becoming Ernest is ‘chiefly a matter of paperwork’ — a christening by appointment."]
    ],
    writing:[
      {task:"Write a character analysis of Cecily Cardew, considering whether her diary makes her the play’s most innocent dreamer or its most efficient romantic strategist.",
       target:"150–190 words",
       tips:["Frame the analysis around the either/or of the question, then complicate it.","Use the letters, the dated engagement and the invented quarrel as your evidence.","Compare her briefly with Gwendolen to sharpen the portrait."],
       starters:["Cecily appears, at first glance, to be the play’s one natural creature…","Yet her diary conducts a courtship with the efficiency of…","Where Gwendolen inherited her ideal, Cecily manufactured hers…","The truth may be that innocence and strategy…"]},
      {task:"Write a formal letter from Algernon to Dr Chasuble, composed that evening, confirming the arrangements for his christening and offering suitably dignified — though carefully vague — reasons for the request.",
       target:"150–190 words",
       tips:["Keep the register elaborately formal; the comedy lies in the evasiveness.","Invent polite circumlocutions for what cannot be admitted.","Close with conventional expressions of respect and a practical detail (time, place)."],
       starters:["Dear Dr Chasuble,","I write to confirm the small ecclesiastical matter we discussed…","Certain family circumstances, upon which I need not enlarge,…","I remain, with sincere respect,…"]}
    ]},
  { n:7, title:"Afternoon tea",
    sum:"Gwendolen arrives at the Manor House and befriends Cecily instantly — until each discovers the other claims to be engaged to Ernest Worthing. Their exquisitely polite tea-table duel ends when the men appear, the false names collapse, and the two women unite against their deceivers.",
    vocab:[
      ["CORDIALITY","warm, sincere friendliness"],
      ["PREMONITION","a feeling that something is about to happen"],
      ["ETIQUETTE","the formal code of polite behaviour"],
      ["CIVILITY","formal politeness, possibly without warmth"],
      ["RESTRAINT","self-control; force held in reserve"],
      ["INSINUATION","an indirect, unpleasant suggestion"],
      ["EXQUISITE","refined to the point of perfection"],
      ["CATASTROPHE","a sudden, complete disaster"],
      ["SOLIDARITY","unity based on shared interests or injuries"],
      ["OSTENTATIOUS","showy; designed to be noticed"],
      ["RIVALRY","competition for the same prize"],
      ["DUEL","a formal combat between two opponents"]
    ],
    comp:[
      ["What is the narrator’s joke about the women’s instant friendship?",["It is genuine and lifelong","It is signed like a treaty neither has read — and lasts a quarter of an hour","It is based on shared schooling","It is imposed by the servants"],1,"The speed and totality of the intimacy guarantee its collapse."],
      ["Why is the collapse of the friendship called ‘administrative’?",["A servant causes it","It begins over the paperwork of rival claims — announcements and diary entries","Lady Bracknell orders it","It happens in an office"],1,"Each produces documentary evidence of engagement to the same name."],
      ["What does Gwendolen’s remark about her diary suggest?",["She distrusts her memory","Her self-dramatisation: life exists to be sensational reading","She is writing a novel","She fears losing it"],1,"One should always have ‘something sensational to read in the train’."],
      ["How do sugar and cake function in the tea scene?",["As simple refreshment","As weapons — each polite offering is a calculated act of aggression","As symbols of wealth","As tests of good health"],1,"Four lumps and a large slice of cake are artillery delivered with a smile."],
      ["Why does the servants’ presence sharpen the conflict?",["The servants take sides","Open war being impossible, hostility must be refined into perfect politeness","They spread gossip","They clear the tea too soon"],1,"Restraint, in this duel, becomes the deadliest weapon available."],
      ["What ‘dreadful arithmetic’ do the women perform when the men arrive?",["Counting the cost of the tea","Two engagements, two claimed Ernests — and no Ernest at all in the county","Adding their fortunes together","Counting the trains they have missed"],1,"The exchanged corrections reveal that neither suitor bears the essential name."],
      ["What transforms the rivals into allies?",["Lady Bracknell’s arrival","The discovery that both were deceived by the identical trick","A shared taste in hats","Miss Prism’s intervention"],1,"Deprived of its object, rivalry dissolves instantly into solidarity."],
      ["How do the women stage their exit?",["In tears, separately","Arm in arm, with ostentatious tenderness, forbidding pursuit — at least immediate pursuit","Silently, by different doors","With formal curtsies to the men"],1,"The withdrawal is choreographed both to punish and to invite negotiation."]
    ],
    tf:[
      ["The women quarrel from the moment they meet.",false,"They begin with radiant cordiality; the quarrel arrives with the rival claims."],
      ["Gwendolen never travels without her diary.",true,"It supplies her with something sensational to read in the train."],
      ["Cecily serves the tea exactly as her guest requests.",false,"She delivers four lumps of sugar and cake precisely against Gwendolen’s stated wishes."],
      ["The battle at the tea table is conducted within the rules of etiquette.",true,"Every blow is delivered as an act of politeness."],
      ["Each woman initially believes the other is engaged to a different man.",false,"Each believes herself engaged to the same Mr Ernest Worthing."],
      ["The men’s arrival clears up the confusion to everyone’s satisfaction.",false,"It collapses the deception and unites the women against them."]
    ],
    writing:[
      {task:"Write an article entitled ‘Politeness as a weapon’, using the tea scene as your central example and extending the idea to modern situations where courtesy conceals aggression.",
       target:"150–190 words",
       tips:["Open with the paradox — perfect manners, open warfare — before analysing it.","Choose one modern arena (office email, diplomacy, social media) and draw the parallel precisely.","Vary sentence length for rhythm; an article should be a pleasure to read."],
       starters:["No shots are fired at Cecily Cardew’s tea table, and no prisoners are taken…","The sugar tongs, in the right hands, are a deadlier instrument than…","We still fight this way:…","True rudeness, Wilde suggests, wears its best gloves…"]},
      {task:"Write a review comparing this scene of the play with any comic scene of rivalry you know from film or television, evaluating which handles hostility-beneath-manners more effectively.",
       target:"150–190 words",
       tips:["Name your comparison early and give the reader its essential situation in one sentence.","Compare techniques — dialogue, timing, what remains unsaid — rather than plots.","Deliver a clear verdict and justify it in your closing lines."],
       starters:["A century before television perfected the passive-aggressive dinner party,…","My chosen rival scene comes from…","Where Wilde relies on epigram, the modern scene relies on…","On points, the victory goes to…"]}
    ]},
  { n:8, title:"The perfect match",
    sum:"Forgiveness is bought with promises of re-christening, but Lady Bracknell arrives and vetoes everything — until Cecily’s fortune converts her instantly and the match becomes ‘perfect’. Jack, as guardian, then withholds his consent to Cecily’s marriage unless he may marry Gwendolen, and the negotiation freezes into deadlock.",
    vocab:[
      ["STIPULATION","a condition insisted upon in an agreement"],
      ["IMPASSE","a deadlock from which no progress is possible"],
      ["INTRANSIGENT","refusing to modify one’s position"],
      ["PRAGMATIC","guided by practical results rather than principle"],
      ["INDICTMENT","a formal accusation of serious wrongdoing"],
      ["DETACHMENT","cool, uninvolved objectivity"],
      ["INSTANTANEOUS","occurring in the same instant"],
      ["MALICE","the desire to harm or embarrass"],
      ["EXPEDITE","to speed a process up"],
      ["OBSTINATE","stubborn beyond persuasion"],
      ["BLACKMAIL","extracting concessions by threat"],
      ["DEPLORABLE","deserving strong condemnation"]
    ],
    comp:[
      ["Why do the women accept the men’s defence?",["The men produce documents","Lying ‘for love’, sealed by a promise of baptism, is judged a sufficient sacrifice","Lady Bracknell orders forgiveness","Dr Chasuble intercedes"],1,"Two men prepared to be re-christened for their sakes prove irresistible."],
      ["What does Bunbury’s sudden ‘death’ demonstrate?",["Algernon’s genuine grief","That fictions are disposed of the moment they stop being useful","Lady Bracknell’s medical knowledge","The skill of his physicians"],1,"With Cecily won, the invalid can be loyally dispatched in a single sentence."],
      ["What causes Lady Bracknell’s ‘conversion’ regarding Cecily?",["Cecily’s manners at tea","The mention of her fortune","Algernon’s pleading","Jack’s recommendation"],1,"Distinction, promise and solidity appear the instant the money is named."],
      ["What is the force of the auctioneer comparison?",["Lady Bracknell sells paintings","She inspects the girl as an object whose value must be appraised","She speaks unusually loudly","She carries a hammer"],1,"Courtship is commerce: the examination is a valuation, not an introduction."],
      ["What is ironic about Jack’s indictment of Algernon?",["It is delivered in verse","He condemns, with a straight face, exactly the crimes he has himself committed","It is legally binding","Algernon confesses at once"],1,"The impersonator of Ernest solemnly denounces the impersonation of Ernest."],
      ["What are Jack’s terms for giving his consent?",["A public apology","Consent for Cecily the moment Lady Bracknell consents to Gwendolen","Half of Cecily’s fortune","Algernon’s permanent exile"],1,"His stipulation is pure bargaining: marriage for marriage."],
      ["Why does the narrator call the lovers ‘spectators at their own auction’?",["They are bored by the scene","Their futures are being traded between two negotiators over their heads","They are bidding for furniture","They enjoy the entertainment"],1,"The people most concerned have the least say — the satire of matrimony as market."],
      ["What actually interrupts the impasse?",["Lady Bracknell relents","Gwendolen faints","Dr Chasuble’s incidental mention of Miss Prism","A telegram from London"],2,"Not argument but accident: a name spoken in passing turns the whole plot."]
    ],
    tf:[
      ["The men’s apology rests mainly on a claim of sincerity in love.",true,"Each had lied, but ‘for love’ — an offence recast as a compliment."],
      ["Algernon kills off Bunbury as smoothly as Jack tried to kill off Ernest.",true,"The invalid dies in a sentence once his usefulness has ended."],
      ["Lady Bracknell’s first inspection of Cecily finds her remarkable.",false,"She finds nothing remarkable — until the fortune is mentioned."],
      ["Jack’s objection to Algernon’s character is entirely disinterested.",false,"It is strategic, wielded with relish and a certain malice."],
      ["Jack has the legal power to block Cecily’s marriage until she comes of age.",true,"As her guardian, his consent is required."],
      ["The chapter ends with the deadlock broken by persuasion.",false,"It is broken by accident — the mention of Miss Prism’s name."]
    ],
    writing:[
      {task:"Write a formal letter from Jack to Lady Bracknell, composed that evening, setting out his terms with lawyer-like courtesy: his consent to Cecily’s marriage in exchange for hers to his own.",
       target:"150–190 words",
       tips:["Adopt the structure of a business proposal: position, terms, invitation to reply.","Keep the tone immaculately polite while the content remains pure blackmail.","Use formal connectors: accordingly, in consequence, should you see fit."],
       starters:["Dear Lady Bracknell,","You will recall that, as Miss Cardew’s guardian, my consent…","I am prepared to give that consent upon a single condition…","I await your reply with the greatest respect, Jack Worthing"]},
      {task:"Write an essay discussing the statement: ‘In the play, marriage is a market and love a currency of uncertain value.’ Refer closely to Lady Bracknell’s change of mind about Cecily.",
       target:"150–190 words",
       tips:["Define the metaphor precisely before applying it to the scene.","Contrast the instant revaluation of Cecily with the fixed devaluation of Jack.","Concede what the ending suggests about love’s eventual victory — or its price."],
       starters:["Lady Bracknell inspects brides the way a dealer inspects paintings…","Cecily’s worth changes in a single sentence because…","Jack, by contrast, remains unsaleable, since…","If marriage is a market here, the ending asks whether…"]}
    ]},
  { n:9, title:"The handbag returns to its owner",
    sum:"Lady Bracknell recognises Miss Prism as the nursemaid who, twenty-eight years earlier, mislaid a baby in a handbag at Victoria Station. That baby was Jack: son of Lady Bracknell’s late sister, elder brother to Algernon, and christened after his father — General Ernest John Moncrieff. His name was Ernest all along, and every marriage can proceed.",
    vocab:[
      ["REMORSE","deep, lasting regret for a past wrong"],
      ["ABSTRACTION","absent-mindedness; attention elsewhere"],
      ["PERAMBULATOR","a baby carriage; a pram"],
      ["AGITATION","visible nervous excitement"],
      ["BARRISTER","a courtroom lawyer"],
      ["PROSAIC","plain and unromantic; matter-of-fact"],
      ["REVELATION","a dramatic disclosure of something hidden"],
      ["IMPLICATION","a meaning suggested rather than stated"],
      ["IRONY","an outcome that mocks what was expected"],
      ["EXHIBIT","an object produced as evidence"],
      ["DENOUEMENT","the final unravelling of a plot"],
      ["PHILOSOPHICAL","calmly accepting of misfortune or surprise"]
    ],
    comp:[
      ["Why does Miss Prism edge toward the door?",["She dislikes Jack","A guilt twenty-eight years old recognises its moment of reckoning","She is late for church","She is afraid of Algernon"],1,"Her instinct to escape confirms the accusation before it has been spoken."],
      ["What exactly was Miss Prism’s error?",["She stole the baby","In a fit of abstraction she exchanged baby and manuscript between handbag and perambulator","She lost the perambulator","She missed her train"],1,"The novel travelled tenderly around London; the infant was deposited at Victoria Station."],
      ["Why does Jack produce the handbag ‘like a barrister’?",["He wants to sell it","It is his decisive exhibit — the physical proof connecting him to the lost child","He is qualified in law","He wishes to return stolen property"],1,"The identification of the bag is the identification of the man."],
      ["What is comic about Miss Prism’s reaction to the returned handbag?",["She denies that it is hers","She is chiefly delighted to have her property restored, overlooking the human revelation","She faints on the spot","She demands the manuscript as well"],1,"The bag appears to matter to her at least as much as the baby it once contained."],
      ["Why is Jack’s cry of ‘Mother!’ doubly mistaken?",["He addresses the wrong room","Miss Prism neither bore him nor lost him as a mother — she is unmarried and merely careless","Lady Bracknell is his mother","He has no mother at all"],1,"He offers forgiveness for a sin she never committed; she recoils from the implication."],
      ["What does the discovery of his parentage finally give Jack?",["A larger fortune","The one qualification Lady Bracknell demanded: relations","A new estate","A military career"],1,"The foundling acquires ancestry — precisely the thing money could not buy."],
      ["What is the crowning irony of Jack’s lifelong deceptions?",["They are punished severely","His central lie — a brother, and the name Ernest — turns out to have been the truth","They are never discovered","Algernon invented them first"],1,"He has been telling the truth all his life without knowing it."],
      ["How does the final pun summarise the play?",["It condemns dishonesty solemnly","‘Being Earnest’ fuses the name with the virtue, mocking a society that cannot tell them apart","It celebrates wealth","It rejects marriage altogether"],1,"The vital importance rests on a homophone — sincerity and a Christian name made interchangeable."]
    ],
    tf:[
      ["The mere mention of Miss Prism’s name is enough to transfix Lady Bracknell.",true,"She stiffens at the name and demands to see the governess at once."],
      ["The perambulator was eventually recovered containing the baby.",false,"It was found containing the manuscript of a novel; the baby was in the handbag."],
      ["Miss Prism has kept the handbag with her ever since that morning.",false,"She left it in the cloakroom and never dared reclaim it; Jack has it."],
      ["Miss Prism accepts Jack’s embrace as her long-lost son.",false,"She recoils, scandalised: she is unmarried, and nobody’s mother."],
      ["Jack turns out to be Algernon’s elder brother.",true,"As the elder son he was named after their father, the General."],
      ["Lady Bracknell remembers the General’s first name instantly.",false,"Memory fails; the Army Lists must supply ‘Ernest John’."]
    ],
    writing:[
      {task:"Write an essay discussing the statement: ‘The play ends by rewarding every deception it contains.’ To what extent does the resolution undermine — or complete — Wilde’s satire?",
       target:"150–190 words",
       tips:["List the rewarded deceptions briefly, then argue what the pattern means.","Distinguish between what the characters learn and what the audience learns.","Commit to a position on the final pun: surrender, joke, or verdict."],
       starters:["No liar in this play is ever really punished…","Jack’s greatest falsehood is converted, by a handbag, into fact…","One reading is that Wilde surrenders his satire to romance…","The truer conclusion may be that earnestness itself…"]},
      {task:"Write a character analysis of Lady Bracknell across the whole play, arguing whether she is its villain, its truest realist, or its finest comic creation.",
       target:"150–190 words",
       tips:["Choose one of the three labels as your thesis and test it against the other two.","Draw evidence from at least two scenes: the interview and the conversion over Cecily’s fortune.","Let your conclusion acknowledge what the play would lose without her."],
       starters:["Lady Bracknell blocks every marriage in the play, and yet…","Her logic is monstrous only because it is consistent…","Calling her a villain flatters the world she represents…","She survives every revolution of the plot because…"]}
    ]}
];

const READINGS = {
1:["Algernon Moncrieff occupied a fashionable London flat with the serene conviction that elegance excused almost everything, including idleness. While his imperturbable butler Lane arranged the afternoon tea, Algernon played the piano with more feeling than accuracy — an arrangement he considered greatly to his credit. Into this scene of cultivated indolence came his friend Jack Worthing, known throughout town as ‘Ernest’, freshly arrived from the country and visibly rehearsing something important. He had come, he announced, for pleasure; in truth he had come to propose to Gwendolen Fairfax, Algernon’s beautiful cousin, whom he adored with a seriousness his friend found faintly vulgar.",
"Algernon, however, was in no mood to smooth anybody’s path to matrimony. With theatrical ceremony he produced a silver cigarette case that Jack had left behind on a previous visit, and declined to return it until its inscription had been explained. The engraving read: ‘From little Cecily, with her fondest love to her dear Uncle Jack.’ Under this genial scrutiny Jack squirmed, protested, and finally surrendered. A man who calls himself Ernest in town cannot easily account for being somebody’s Uncle Jack in the country, and Algernon, scenting duplicity, pursued the point with the relentless courtesy of a born interrogator.",
"The truth, once extracted, proved delightfully symmetrical. In the country Jack was Mr Worthing, a landowner of impeccable respectability and the legal guardian of a young ward, Cecily Cardew, granddaughter of the old gentleman who had adopted him. Since a guardian must radiate moral seriousness at all hours, country life obliged Jack to be exemplary to the point of tedium. Respectability, he had discovered, is a full-time occupation, and like all occupations it demanded an occasional holiday. His solution was not to abandon propriety but to delegate it — to leave virtue at home and to travel under another name entirely.",
"Accordingly Jack had equipped himself with a wholly fictitious younger brother named Ernest: a scoundrel who lived in town, ran up debts, and lurched from scandal to scandal with gratifying regularity. Whenever the country grew intolerable, Jack would announce, with a sorrowful face, that poor Ernest was in trouble again and required rescue. He would then hasten to London and become Ernest himself, enjoying in that character all the amusements his own reputation forbade. The fabrication was economical, elastic and, until the arrival of the cigarette case, entirely watertight. A pretext, Jack felt, was only immoral when it was clumsy.",
"Far from being shocked, Algernon was enchanted, for he practised the identical art under a different flag. He had invented an invalid friend called Bunbury, a gentleman of magnificently poor health who resided in the country and collapsed whenever Algernon received an invitation he wished to avoid. Bunbury’s convenient relapses had rescued him from countless dinners with his formidable aunt, Lady Bracknell, and Algernon spoke of him with genuine tenderness, as one speaks of a valuable investment. To deceive one’s family, he explained, was not merely permissible; performed with sufficient style, it came very close to being a social duty.",
"‘You are a Bunburyist,’ Algernon declared, bestowing the title like a knighthood, ‘and one of the most advanced I know.’ Jack accepted the diagnosis but firmly rejected the vocation: if Gwendolen accepted him, he intended to kill off his imaginary brother without ceremony and settle into blameless honesty. Algernon, who regarded blameless honesty as a form of premature death, listened with the tolerant smile of a man who has heard reformed sinners announce their retirement before. Neither of them suspected how expensive the name Ernest was about to become, nor how flippant fate could prove toward men who invent relations."],
2:["That afternoon Lady Bracknell and her daughter Gwendolen were expected for tea, and Algernon had ordered cucumber sandwiches with the solemnity of a general provisioning a campaign. Unfortunately, the general then devoured his own supplies. Waiting makes a man reflective, and reflection made Algernon hungry: he ate one sandwich absently, a second on principle, and the remainder out of simple consistency. By the time the doorbell rang, the plate offered nothing but crumbs and the memory of good intentions. Jack, who had been forbidden to touch them on the grounds that they were reserved for an aunt, observed the whole performance with justifiable bitterness.",
"Lady Bracknell entered like a state occasion — imperious, magnificently dressed and entirely certain of her opinions. She surveyed the room, accepted a chair as though conferring an honour, and asked for the cucumber sandwiches she had been promised. Algernon inspected the empty plate with beautifully acted astonishment and rang for Lane. The butler, whose composure nothing on earth could disturb, announced gravely that there had been no cucumbers in the market that morning, ‘not even for ready money’. Lady Bracknell received the evasion as fact, and the fiction passed into the record unchallenged — proof that in polite society a well-delivered lie outranks an inconvenient truth.",
"Algernon then performed his true service of the afternoon: he escorted his aunt into the music room to discuss the programme for her reception, leaving Jack alone with Gwendolen. It was a manoeuvre of pure Bunburyism, executed indoors. Jack seized his chance with more anxiety than grace. He admired Miss Fairfax, he confessed, more than any girl he had ever met. Gwendolen replied that she was perfectly aware of it, that his admiration had long been public knowledge, and that she had always intended to accept him — a candour which left Jack with remarkably little to propose.",
"Her reason, however, was rather less flattering than her acceptance. Gwendolen explained that her ideal, cherished since girlhood, had always been to love a man called Ernest. The name, she declared, produced vibrations; it inspired ‘absolute confidence’. She had resolved to love him before they had ever met, on the strength of the syllables alone. Jack listened with mounting alarm to this infatuation with a word. His beloved was not in love with his character, his income or his person so much as with two syllables that did not, strictly speaking, belong to him at all.",
"Cautiously, he conducted an experiment. Suppose, he said, that his name were not Ernest — suppose it were something else, something respectable but plain. Jack, for instance? Gwendolen dismissed the hypothesis with serene brutality: Jack was a notoriously domestic name, a name without music, a name that produced absolutely no vibrations whatever. Ernest alone was safe. Jack privately resolved, then and there, to be christened Ernest at the earliest opportunity, reasoning that if a name could be acquired by accident it could surely be corrected by arrangement. The superficial, he was beginning to learn, must be taken very seriously indeed.",
"He proposed formally, on one knee, and was formally accepted; Gwendolen even complimented the performance. At that precise moment Lady Bracknell re-entered the room and discovered her daughter being knelt to by a young man of entirely unexamined credentials. She commanded Gwendolen to rise, informed the couple that an engagement was a matter for parents to announce, and made it icily clear that Mr Worthing was, as yet, engaged to nobody. Gwendolen was dispatched to the carriage. Jack remained behind, straightening his waistcoat and his nerves, about to undergo the most celebrated interview in the history of English comedy."],
3:["Gwendolen having been banished to the carriage, Lady Bracknell settled herself in the best chair, produced a small notebook and pencil, and began an interrogation she had evidently conducted many times before. Jack, she remarked, was not on her list of eligible young men, though she was prepared to enter him if his answers proved satisfactory. What followed resembled less a conversation than an examination for entry into a very exclusive profession — that of son-in-law. She asked her questions in an order all her own, and weighed the replies with the impartial severity of a customs officer searching luggage for undeclared defects.",
"The early questions went swimmingly. Did he smoke? He did — and Lady Bracknell approved, for a man should always have an occupation of some kind, and London was full of men with nothing whatever to do. His age was suitable, his income comfortable, his property reassuringly solid: a house in town and a place in the country. Jack began to entertain hopes. He had answered like a model candidate, and a less mercenary examiner might already have blessed the match. But Lady Bracknell was saving her decisive category for last, as connoisseurs save the best wine: the question of family.",
"Were his parents living? Jack was obliged to admit that he had lost both of them — a formulation Lady Bracknell found careless rather than tragic. To lose one parent might be counted a misfortune, she observed; to lose both ‘looks like carelessness’. Pressed further, Jack confessed the truth in all its splendour: he did not actually know who his parents were. He had been found. The word dropped into the conversation like a stone into a quiet pond, and Lady Bracknell repeated it with the incredulity of a woman handling a forged banknote. Found? Found where, precisely — and by whom?",
"The facts, patiently extracted, were these. As an infant Jack had been discovered by the late Mr Thomas Cardew, a charitable old gentleman, in the cloakroom at Victoria Station — inside a large black leather handbag, ordinary in every respect except for its contents. Mr Cardew, who happened to hold a first-class ticket to Worthing, had adopted the foundling and named him after his destination. Jack related all this with the uneasy dignity of a man who knows his origins sound better as farce than as pedigree, and offered, helpfully, to produce the handbag itself. The offer was not well received.",
"Lady Bracknell’s verdict was immediate and monumental. To be born, or at any rate bred, in a handbag displayed, she announced, ‘a contempt for the ordinary decencies of family life’; and she could scarcely be expected to permit her only daughter to marry into a cloakroom. Ancestry, in her philosophy, was not an ornament but a qualification, and Jack possessed none. His fortune was real, his manners were passable, his affection was perfectly sincere — and all of it together weighed nothing against the single unanswerable question of who, precisely, he was. On that point the handbag maintained a discreet silence.",
"Her advice, delivered as she rose to leave, was severely practical: Mr Worthing would do well to acquire some relations as soon as possible, and to produce at least one parent, of either sex, before the season was entirely over. With that ultimatum she swept from the room. Jack responded to defeat in the traditional English manner — by abusing his opponent eloquently once the door had closed — while from the next room Algernon, who had heard everything, struck up a wedding march on the piano with malicious cheerfulness. Jack’s occupation, for the foreseeable future, was to invent a family."],
4:["While Jack’s prospects were being demolished in London, life at his Manor House continued in a state of studied innocence. In the rose garden, on a golden afternoon, his ward Cecily Cardew was engaged in a struggle as old as education itself: avoiding her German lesson. Her governess, Miss Prism, held that German improved the character precisely because it was disagreeable; Cecily held that watering the flowers was the more useful occupation, since flowers, unlike grammar, responded to attention. The idyllic setting concealed a household quite as rich in secret romance as any drawing room in fashionable London, and rather more industrious about it.",
"Cecily’s true education was conducted in her diary, where she recorded not what had happened but what ought to have happened — a method she considered a great improvement on memory. Miss Prism disapproved of diaries, of sentimental fiction, and of imagination in general, with the special severity of a woman correcting faults she recognised. Her own attention, moreover, was imperfectly fixed on German irregular verbs; it strayed, with clockwork regularity, toward Dr Chasuble, the local rector, a gentle clergyman whose considerable learning was exceeded only by his failure to notice that he was being courted. Their decorous flirtation proceeded entirely in quotations and blushes.",
"Dr Chasuble duly appeared, and Miss Prism developed a sudden headache that could be cured only by a long walk in his company — a medical arrangement that surprised nobody, least of all Cecily. Left gloriously unsupervised, she abandoned German without a pang. At that moment the servant announced a visitor whose card bore the most thrilling name in her private mythology: Mr Ernest Worthing. Her uncle’s scandalous younger brother — the wicked Ernest, hero of a hundred forbidden daydreams — had apparently arrived in person, at the precise hour when the entire apparatus of her moral protection was out walking.",
"The visitor was, of course, Algernon, conducting the most ambitious Bunbury of his career: a masquerade in his friend’s own house, under the identity of a man who did not exist. He had come out of curiosity about the Cecily of the cigarette case, and curiosity was punished in the usual way — he fell in love almost immediately. Cecily, for her part, examined the famous impostor with frank interest and pronounced herself slightly disappointed: he did not look wicked at all. He looked, in fact, respectable. She hoped he had not been pretending to be bad while really being good; that, she observed, would be hypocrisy.",
"They walked among the roses, and the courtship advanced at the pace of all Cecily’s enterprises — considerably faster than the parties concerned quite realised. Algernon, who had arrived as a tourist in someone else’s fiction, found himself speaking with an earnestness that startled him; Cecily received his compliments graciously, as tributes long overdue. The notoriety of ‘Ernest’ was, to her, his principal ornament: a wicked reputation gave a man something to be reformed of, and reforming him promised to be delightful. Neither of them mentioned that the gentleman under discussion was a complete fabrication; only one of them knew it.",
"Danger, meanwhile, was approaching by the same railway line. In London the real Jack had at last resolved to dispose of his imaginary brother for ever, and was travelling home with the sorrowful news of Ernest’s sudden death abroad already rehearsed. The timing was arranged with the precision of farce: the same afternoon would deliver both the report of the brother’s death and the brother himself — alive, charming, and paying court in the garden. Nobody at the Manor House suspected anything, which is, after all, the natural condition of characters in a comedy, and of a good many people outside one."],
5:["Jack made his entrance that afternoon in the deepest, most conscientious mourning: black coat, black gloves, black hatband, and an expression of chastened grief that had evidently been practised on the train. The effect was magnificent. Miss Prism and Dr Chasuble hurried forward with their condolences, and Jack received them with beautifully judged solemnity, announcing that his poor brother Ernest had died quite suddenly in Paris, carried off by a severe chill. Everyone agreed that he bore his bereavement nobly. It is, after all, not especially difficult to be brave about a loss when the deceased has never at any point existed.",
"The performance deserved a better audience. Jack had scarcely finished burying his fiction when Cecily came running from the house, radiant with news that demolished it: his brother Ernest had arrived an hour ago and was at that moment in the house, longing to see him. Jack objected, with perfect truth, that he had no brother. Nobody believed the only honest sentence he had spoken all day. Before he could protest further, Algernon strolled out into the garden — alive, immaculate, and wearing the audacity of his position like a flower in his buttonhole. The dead man, it appeared, kept an excellent tailor.",
"What followed was a masterpiece of strangled fury. Jack, in mourning for the very man now advancing to greet him, could neither denounce the impostor without confessing his own invention, nor welcome him without choking. Cecily, deeply moved, begged him to be reconciled with his unfortunate brother; Dr Chasuble murmured warmly about forgiveness; and Jack, trapped inside his own charade, was obliged to perform a public reconciliation with a corpse of his own manufacture. Algernon accepted the reluctant handshake with warmth. Of the two liars in the garden, only one was enjoying himself, and it was not the one dressed in black.",
"Privately, Jack ordered his ‘brother’ out of the house by the first train, in language that deep mourning scarcely permitted. Algernon declined to be evicted. He had discovered Cecily, and no timetable on earth could compete with her. Indeed, both men now confronted the same delicate predicament: each loved a woman who had fastened her affections, with mystifying firmness, upon the name Ernest — a name to which neither of them possessed the smallest legal claim. It was an obstacle that no honest method could remove; fortunately, neither gentleman was inconveniently attached to honest methods, and both had already glimpsed the same solution.",
"The solution each devised was identical, secret, and ecclesiastical. Jack sought out Dr Chasuble and enquired, with elaborate casualness, whether the rector might christen him — a grown man — that very afternoon; certain doubts, he hinted, had arisen concerning his infant baptism. Barely an hour later Algernon arrived on the same errand, with the same urgency, requesting the same name. Dr Chasuble, who found nothing remarkable in a sudden epidemic of christenings among healthy adults, consulted his diary and appointed the ceremonies for half-past five. He was a man whose faith in his parishioners was matched only by his inattention to them.",
"So the afternoon quietly assembled its combustible materials. In one part of the house stood a man in full bereavement for a brother who was downstairs displaying an excellent appetite; in the garden, that same brother was courting a ward he had known for scarcely an hour; and at the church, two separate christenings had been booked under a single borrowed name. All the situation now required was an audience capable of appreciating it. Fate, which in comedies is always punctual, had already provided one: at that very moment Gwendolen Fairfax was sitting in a train, travelling toward the Manor House with questions of her own."],
6:["Algernon, so far from catching any train, caught Cecily alone in the garden and came to the point with commendable speed: he declared a love so complete that it surprised even its owner, and asked her to marry him. Cecily received the proposal with the tranquillity of a woman confirming an appointment. Of course, she said; they had been engaged for the last three months. Algernon, who could improvise his way through most conversations, found himself for once without a line. Engaged? For three months? He begged, with genuine respect, to be told how this had been managed without his participation.",
"Cecily was delighted to explain, and fetched the documentation. Ever since Uncle Jack had first confessed to possessing a wicked younger brother, Ernest had been the principal topic of conversation between herself and Miss Prism — and naturally, she said, a girl ends by falling in love with a man who is discussed so constantly and disapproved of so thoroughly. She had entered the engagement in her diary on a particular day in February, under a particular tree, with full details available upon request. The romance had been conducted entirely without his knowledge, which had not noticeably slowed its progress in the slightest.",
"There was more. Cecily produced a bundle of love letters — the letters ‘Ernest’ had written her throughout the engagement, every one of which she had been obliged to compose herself, since he never wrote. Some were so beautiful, she admitted, that she could hardly read them without crying. The correspondence had naturally included a quarrel: she had broken off the engagement in March, noting in her diary that it would hardly have been a serious engagement without at least one rupture, and had forgiven him within the week. Algernon listened to this fanciful chronicle with an admiration that was entirely unqualified.",
"He was, in truth, enchanted. Other men were obliged to court their beloveds laboriously, in person and in real time; he had been courted, accepted, quarrelled with and forgiven entirely in his absence, by a girl whose ingenuity had supplied both halves of the romance. He told her, with a sincerity that felt curiously novel to him, that she was the most wonderful girl he had ever met, and kissed her; Cecily recorded the event with the diligence of a historian entering a treaty in the archives. An engagement so imaginatively begun, Algernon resolved, deserved at last to be conducted in person.",
"Then came the clause that turned his triumph cold. Cecily mentioned, in the fond tone reserved for absolute conditions, that a great part of her devotion rested upon his name. It had always been her girlish dream to love someone called Ernest; there was something in the name, she explained, that a woman could trust completely. Algernon, experimentally, wondered aloud whether she might not love him under some other name — supposing, purely for the sake of argument, that he were called something like Algernon. Cecily was sympathetic but immovable. Algernon was a pleasant enough name; its single defect was that it was not Ernest.",
"The symmetry of his position with Jack’s did not escape him, though its full comedy still did. Making an excuse of the most transparent kind, he seized his hat and hurried off in search of Dr Chasuble, to secure his christening before the rector’s afternoon filled up with identical appointments. He had entered the garden as a counterfeit Ernest and left it determined to become a genuine one — the imperative of love being, in this household, chiefly a matter of paperwork. Behind him, among the roses, Cecily opened her diary and began composing an account of the proposal considerably more eloquent than the original."],
7:["Gwendolen Fairfax arrived at the Manor House that same afternoon, unannounced and unaccompanied, having decided that developments in her engagement required personal supervision. Cecily, who knew nothing of Gwendolen and delighted in visitors, received her with open cordiality, and for ten radiant minutes the two young women discovered in each other every imaginable perfection. They exchanged compliments, first names and premonitions of eternal friendship with the speed of diplomats signing a treaty neither has read. Gwendolen announced that her first impressions of people were never wrong, and that she liked Cecily immensely. The friendship thus established lasted very nearly a quarter of an hour.",
"Its collapse was administrative. Gwendolen mentioned, in passing, her engagement to Mr Ernest Worthing; Cecily corrected her gently, as one correcting a misprint — it was she who was engaged to Mr Ernest Worthing, though the announcement had not yet appeared. Each lady then produced her evidence. Each consulted her diary — Gwendolen never travelled without hers, since one should always have ‘something sensational to read in the train’ — and each found her own claim documented beyond appeal. The compliments ceased. The two new friends regarded one another across the tea table with the polite fixity of rival empires reviewing a disputed frontier.",
"Battle was joined over the teacups, conducted according to the strictest rules of etiquette and with unmistakable intent to wound. Asked whether she took sugar, Gwendolen replied that sugar was no longer fashionable; Cecily placed four lumps in her cup. Offered her choice of bread and butter or cake, Gwendolen selected bread and butter, cake being rarely seen in the best houses; Cecily sent her a large slice of cake. Every civility arrived like a projectile. The presence of the servants made open warfare impossible, which merely improved its quality: restraint, in this particular duel, was the deadliest weapon available to either side.",
"The insinuations grew steadily grander. Gwendolen let it be known that town possessed refinements the country could scarcely imagine; Cecily agreed warmly, adding that this no doubt explained why so many refined people seemed to flee to the country to recover. Compliments were exchanged on hats, gardens and upbringing, each one engineered to detonate on arrival. By the time footsteps sounded on the gravel, the two ladies had achieved that pitch of exquisite politeness which, between women of spirit, announces a state of war; and each was entirely confident that the arriving gentlemen would establish her own claim and demolish the other’s.",
"The men appeared — separately, and each to his own catastrophe. Cecily flew to Algernon and addressed him as Ernest; Gwendolen claimed Jack under the same name; and in the ensuing exchange of corrections the entire architecture of deception came down at once. The gentleman embracing Cecily was identified by Gwendolen as her own cousin, Algernon Moncrieff; the gentleman claimed by Gwendolen was identified by Cecily as her guardian, Uncle Jack. A dreadful arithmetic completed itself simultaneously in both female minds: two engagements, two Ernests claimed — and, upon honest inspection of the premises, no Ernest of any description in the entire county.",
"The ladies’ response had a dignity the gentlemen could not begin to match. Their rivalry, deprived of its object, dissolved instantly into solidarity: each embraced the other as a fellow victim, and the questions they put to their suitors were brief and unanswerable. Was either of them actually called Ernest? Neither was. Was either of them engaged to anybody called Ernest? Silence. The two women rose, linked arms with ostentatious tenderness, and withdrew into the house, united against the sex that had deceived them — pausing at the door only long enough to make it clear that the men were not to follow. At least, not immediately."],
8:["The gentlemen, left among the ruins of the tea table, consoled themselves in the manner of their kind — Jack with reproaches, Algernon with muffins — before following the ladies indoors to attempt a defence. Their explanation was at least symmetrical: each had lied, but each had lied for love, which in their view converted the offence into a species of compliment. Rather more persuasive than the apology was the announcement that both of them had already arranged to be re-christened Ernest that very afternoon. Faced with two men prepared to be baptised for their sakes, Gwendolen and Cecily pronounced the sacrifice sufficient and forgave them.",
"Domestic peace had lasted only minutes when Lady Bracknell was announced, having pursued her daughter from London and entered the room like an unfavourable verdict. Her position was unchanged: the engagement between Gwendolen and Mr Worthing was cancelled, had never existed, and was not a subject for discussion. She then noticed Algernon and inquired whether this was the house of his invalid friend Bunbury. Algernon explained, after a moment’s thought, that Bunbury had died that afternoon quite suddenly, his physicians having at last discovered that he could not possibly live — a medical opinion with which Bunbury had loyally and promptly complied.",
"The next item of business was Cecily, whose engagement to Algernon was submitted for inspection. Lady Bracknell examined the girl with the detachment of an auctioneer and found nothing remarkable — until Jack, with a certain deliberate malice, mentioned the size of Cecily’s fortune. The effect was instantaneous and transformative. Qualities invisible a moment earlier came crowding into view: Miss Cardew’s profile acquired distinction, her manners promise, her prospects solidity. Lady Bracknell, who had never once confused sentiment with business, declared her a thoroughly attractive young lady and the match a most eligible one. Few conversions in history have been so rapid, or so sincere.",
"It was now Jack’s turn to obstruct, and he did it with relish. As Cecily’s guardian he was entitled to withhold his consent to her marriage until she came of age, and he withheld it flatly, citing — with a magnificently straight face — Algernon’s deplorable dishonesty: the impersonation, the false name, the fraudulent courtship conducted under his own roof. That a man guilty of precisely the same crimes should deliver this indictment troubled Jack not at all; consistency, he would have said, is the virtue of those without a strategy. His terms were simple and pragmatic: he would consent to Cecily’s marriage the moment Lady Bracknell consented to his own.",
"The stipulation was received as blackmail, which is what it was, and refused as such. To surrender Gwendolen to a cloakroom foundling merely to expedite her nephew’s wedding was, Lady Bracknell indicated, entirely out of the question; her nephew could wait, and so, if necessary, could everybody. Jack proved equally intransigent. Neither appeal nor argument would move him: no Gwendolen, no Cecily. The negotiation had thus arrived at a perfect impasse — two immovable wills politely deadlocked across a drawing room, while the four lovers whose futures were being traded stood by, reduced to the condition of spectators at their own auction.",
"Lady Bracknell gathered her gloves and prepared to remove Gwendolen from the premises, observing that they had already missed several trains and that any further delay might expose them to comment on the platform. The comedy stood, for one long moment, at a genuine dead end: every marriage blocked, every party obstinate, every exit closed. What broke the deadlock was neither persuasion nor surrender but an accident of conversation. Dr Chasuble, arriving to announce that everything was ready for the christenings, happened to mention the name of Miss Prism — and Lady Bracknell repeated that name in a voice that made the whole room turn."],
9:["At the name of Miss Prism, Lady Bracknell had stiffened like a pointer. The governess was summoned; she entered unsuspecting, caught sight of Lady Bracknell, and began edging toward the door with a guilt that had evidently been waiting twenty-eight years for this appointment. In a voice of judicial thunder, Lady Bracknell demanded to know where the baby was. The company stared. Twenty-eight years earlier, she explained, this woman had left a house in London wheeling a perambulator that contained an infant of the male sex, and had never returned. The perambulator had eventually been recovered; the infant, however, had not.",
"Miss Prism’s defences collapsed. In a voice trembling with ancient remorse she confessed the negligence that had shadowed an otherwise respectable career. On the morning in question she had had charge of two objects: the baby, and the manuscript of a novel she had written in her few hours of leisure. In a moment of abstraction never satisfactorily explained, she had placed the manuscript in the perambulator — and the baby in her large leather handbag. The handbag she had then deposited in the cloakroom at Victoria Station; the novel she had wheeled tenderly around London. She had never dared to reclaim either.",
"Jack had listened to this confession with an agitation that nobody present could account for. Begging a moment’s patience, he rushed from the room; the company heard luggage being flung about overhead like thunder; and he returned bearing a battered black leather handbag, which he presented to Miss Prism with the air of a barrister producing his decisive exhibit. Was this, he asked, the handbag? Miss Prism examined its scars and fastenings with rising emotion and declared that it was; she recognised every mark upon it, and was delighted to have it so unexpectedly restored. Rather more than a handbag, Jack replied with feeling, had just been restored: he himself was the baby.",
"There followed the afternoon’s finest misunderstanding. Jack, concluding that the woman who had mislaid him must be the mother who had borne him, advanced upon Miss Prism crying ‘Mother!’ and offering complete forgiveness for whatever her past might contain. Miss Prism, scandalised to the roots of her respectability, recoiled from both the embrace and the implication: she was unmarried, and intended to remain uninsulted. It fell to Lady Bracknell to supply the prosaic truth. The mislaid infant had been the son of her own late sister, Mrs Moncrieff — which made Jack, by an irony nobody had ordered, Algernon’s elder brother.",
"The revelation rearranged the room. Jack, the foundling of Victoria Station, stood identified as a Moncrieff: nephew to Lady Bracknell, son of a distinguished family, and possessor at last of the one qualification that money had been unable to buy — relations. Algernon accepted his sudden promotion to younger brother philosophically; he had, after all, been Jack’s brother all afternoon. There remained a single question, and upon its answer two engagements now depended. The baby had certainly been christened; every family tradition insisted on it. What, then, was Jack’s real name? Lady Bracknell searched her memory and found it inconveniently empty.",
"She could recall only that, being the eldest son, the child had naturally been named after his father, General Moncrieff — whose first name, after so many years, defeated everybody present. But the Army Lists of the period stood conveniently on Jack’s own shelves, and he tore through them with trembling hands. There it stood: Moncrieff — Ernest John. Jack had been telling the truth all his life without knowing it: his name really was Ernest, and he really did have a troublesome younger brother. Amid the denouement’s general embracing, he pronounced the moral he had so expensively learned — that he had now realised, for the first time, ‘the vital Importance of Being Earnest’."]
};

const EVENTS={
1:{ev:["Jack arrives at Algernon’s flat under the name Ernest","Algernon produces the forgotten cigarette case","The inscription from Cecily exposes Jack’s double identity","Jack confesses to inventing a wicked brother","Algernon reveals his imaginary invalid, Bunbury","Jack vows to abolish Ernest if Gwendolen accepts him"],keys:["piano","inscription","guardian","Ernest","Bunbury","Gwendolen"]},
2:{ev:["Algernon devours the sandwiches intended for his aunt","Lane covers the loss with an elegant lie","Algernon lures Lady Bracknell into the music room","Jack declares himself and Gwendolen forestalls him","Gwendolen confesses her devotion to the name Ernest","Lady Bracknell interrupts the proposal and dismisses it"],keys:["cucumber","Lane","music","candour","vibrations","carriage"]},
3:{ev:["Lady Bracknell opens her formal interrogation","Jack passes the questions of money and property","He admits that he does not know his parents","The story of the handbag at Victoria Station emerges","Lady Bracknell refuses a son-in-law without ancestry","She departs demanding that Jack acquire relations"],keys:["notebook","occupation","parents","handbag","cloakroom","relations"]},
4:{ev:["Cecily evades her German lesson in the garden","Miss Prism betrays her fondness for Dr Chasuble","A visitor is announced as Ernest Worthing","Algernon begins his masquerade as the wicked brother","Cecily and Algernon fall for each other among the roses","Jack travels home to announce Ernest’s death"],keys:["German","diary","Chasuble","card","roses","railway"]},
5:{ev:["Jack arrives in deep mourning for an invented brother","He announces Ernest’s death in Paris of a chill","Cecily reveals that ‘Ernest’ is alive in the house","Jack is forced into a reconciliation with his own fiction","Both men secretly arrange christenings with Dr Chasuble","Gwendolen travels toward the Manor House"],keys:["mourning","Paris","chill","handshake","christen","Gwendolen"]},
6:{ev:["Algernon proposes and learns he is already engaged","Cecily explains the three-month engagement in her diary","She reveals the love letters she wrote herself","The invented quarrel and reconciliation are disclosed","Algernon is captivated and the kiss is recorded","He hurries away to be christened Ernest"],keys:["engaged","diary","letters","quarrel","kissed","christening"]},
7:{ev:["Gwendolen arrives and the women swear instant friendship","Both claim engagement to Ernest Worthing","The tea table becomes a polite battlefield","Insults are exchanged through sugar and cake","The men appear and the deception collapses","The women unite and withdraw together"],keys:["friendship","diary","sugar","cake","Algernon","arms"]},
8:{ev:["The men apologise and promise to be re-christened","Lady Bracknell arrives and learns of Bunbury’s death","Cecily’s fortune transforms Lady Bracknell’s opinion","Jack withholds his consent to Cecily’s marriage","Jack’s bargain is refused and deadlock follows","Dr Chasuble’s mention of Miss Prism changes everything"],keys:["muffins","Bunbury","fortune","consent","impasse","Prism"]},
9:{ev:["Lady Bracknell recognises Miss Prism and demands the baby","Miss Prism confesses the handbag and manuscript mix-up","Jack produces the very handbag and is identified","Jack mistakes Miss Prism for his mother","Jack proves to be the son of Lady Bracknell’s sister","The Army Lists reveal his true name: Ernest"],keys:["perambulator","manuscript","handbag","Mother","Moncrieff","Ernest"]}
};

return {level:'C1', lead:'Oscar Wilde · advanced retelling · <b>C1 advanced</b> (≈3,000 headwords)',
  CHAPTERS:CHAPTERS, READINGS:READINGS, EVENTS:EVENTS};
})();
