# -*- coding: utf-8 -*-
"""Unité 4 de FRANCÉS — vocabulario y gramática de las 36 semanas
(6 grados x 6 semanas), según la lista de temas de la profesora.

Los temas por grado son suyos; el reparto en semanas, el vocabulario
francés y las definiciones son propuesta (ver el documento "Cahier
Unité 4"). Las definiciones van EN FRANCÉS y nunca contienen la
palabra definida, igual que fr_definitions.py — que se reutiliza como
primera fuente (473 entradas) y sólo se completa aquí lo que falta.
"""

# ---------------------------------------------------------------- #
#  Definiciones nuevas (las que no están ya en fr_definitions.DEF)  #
# ---------------------------------------------------------------- #
DEF_U4 = {
# --- 5e : animaux, nombres, projet ---
'singe': "Animal qui grimpe aux arbres et imite l'homme.",
'treize': "Le nombre après douze.",
'quatorze': "Le nombre après treize.",
'quinze': "La moitié de trente.",
'seize': "Le nombre après quinze.",
'dix-sept': "Le nombre après seize.",
'dix-huit': "Le nombre après dix-sept.",
'dix-neuf': "Le dernier nombre avant vingt.",
'vingt': "Deux fois dix.",
'animal': "Être vivant qui n'est pas une plante ni un humain.",
'préféré': "Celui qu'on aime le plus.",
'petit': "Qui n'est pas grand.",
'grand': "Qui n'est pas petit.",
'gentil': "Qui est aimable avec les autres.",
'mignon': "Petit et joli, qui donne envie de sourire.",
'aimer': "Trouver quelqu'un ou quelque chose agréable.",
'avoir': "Posséder quelque chose.",
'couleur': "Ce que l'oeil voit : rouge, bleu, vert…",
'nom': "Le mot qui sert à appeler une personne ou une chose.",

# --- 6e : loisirs, sports, fréquence, négation, goûts ---
'dessin': "Activité où l'on trace des images sur du papier.",
'chant': "Activité où l'on fait de la musique avec la voix.",
'jeux': "Activités que l'on fait pour s'amuser.",
'basket': "Sport où l'on lance un ballon dans un panier.",
'volley': "Sport où l'on frappe un ballon par-dessus un filet.",
'tennis': "Sport de raquette qui se joue sur un court.",
'judo': "Art martial japonais où l'on fait tomber l'adversaire.",
'équitation': "Sport que l'on pratique sur un cheval.",
'ski': "Sport de glisse sur la neige.",
'gymnastique': "Sport d'agilité avec des figures et des sauts.",
'patinage': "Sport de glisse sur la glace.",
'faire': "Le verbe que l'on utilise pour dire quel sport on pratique.",
'toujours': "Tout le temps, sans exception.",
'souvent': "Beaucoup de fois, presque toujours.",
'quelquefois': "De temps en temps, pas régulièrement.",
'parfois': "À certains moments seulement.",
'rarement': "Presque jamais, très peu de fois.",
'jamais': "Aucune fois, à aucun moment.",
'semaine': "Période de sept jours.",
'mois': "Période d'environ trente jours.",
'rien': "Aucune chose.",
'personne': "Aucun être humain.",
'détester': "Ne pas aimer du tout.",
'jouer': "S'amuser ou pratiquer un sport.",
'pratiquer': "Faire régulièrement une activité.",
'adorer': "Aimer énormément.",
'préférer': "Aimer mieux que les autres.",
'goût': "Ce que l'on aime ou ce que l'on n'aime pas.",
'préférence': "Le choix de ce que l'on aime le mieux.",
'relaxant': "Qui détend et fait du bien.",
'amusant': "Qui fait rire ou passer un bon moment.",
'fatigant': "Qui demande beaucoup d'énergie.",
'difficile': "Qui demande beaucoup d'efforts.",
'facile': "Qui ne demande presque aucun effort.",
'sondage': "Enquête où l'on pose la même question à beaucoup de gens.",
'question': "Phrase que l'on dit pour obtenir une information.",
'réponse': "Ce que l'on dit après une question.",
'camarade': "Un autre élève de ta classe.",
'résultat': "Ce que l'on obtient à la fin d'une enquête.",
'majorité': "Le plus grand nombre de personnes.",
'populaire': "Que beaucoup de gens aiment.",
'pourquoi': "Le mot qui sert à demander la raison.",

# --- 7e : vêtements, accessoires, couleurs, porter/mettre, styles ---
'jean': "Pantalon en toile bleue très courant.",
'short': "Pantalon court pour l'été ou le sport.",
'baskets': "Chaussures de sport confortables.",
'casquette': "Couvre-chef souple avec une visière devant.",
'écharpe': "Bande de laine que l'on met autour du cou.",
'lunettes': "Objet à deux verres que l'on porte sur le nez.",
'ceinture': "Bande de cuir qui tient le pantalon à la taille.",
'montre': "Petit objet du poignet qui donne l'heure.",
'bracelet': "Bijou que l'on porte autour du poignet.",
'collier': "Bijou que l'on porte autour du cou.",
'clair': "Se dit d'une couleur pâle, proche du blanc.",
'foncé': "Se dit d'une couleur sombre, proche du noir.",
'porter': "Avoir un vêtement sur soi.",
'mettre': "Enfiler un vêtement sur soi.",
'enlever': "Retirer un vêtement que l'on a sur soi.",
'essayer': "Mettre un vêtement pour voir s'il convient.",
'choisir': "Prendre une chose plutôt qu'une autre.",
'acheter': "Obtenir une chose en payant.",
'taille': "La mesure d'un vêtement : S, M, L…",
'miroir': "Surface où l'on voit son reflet.",
'cabine': "Petite pièce du magasin où l'on essaie les vêtements.",
'tenue': "L'ensemble des vêtements que l'on porte.",
'classique': "D'un style simple et intemporel, jamais démodé.",
'sportif': "D'un style confortable, inspiré du sport.",
'décontracté': "D'un style détendu, pas du tout formel.",
'élégant': "D'un style raffiné et soigné.",
'chic': "Qui a beaucoup d'allure et de distinction.",
'vintage': "D'un style ancien redevenu à la mode.",
'coloré': "Qui a beaucoup de couleurs vives.",
'simple': "Sans décoration ni complication.",
'moderne': "De notre époque, actuel.",
'original': "Différent de tout le reste, unique.",
'avis': "Ce que l'on pense d'une chose.",
'trouver': "Le verbe qui sert à donner son opinion : je … que…",
'défilé': "Présentation où des mannequins marchent devant le public.",
'mode': "La façon de s'habiller à une époque donnée.",
'modèle': "Personne qui présente des vêtements.",
'podium': "Estrade sur laquelle on défile ou monte en gagnant.",
'présenter': "Montrer quelque chose au public.",
'décrire': "Dire comment est une personne ou une chose.",
'style': "La manière personnelle de s'habiller.",
'look': "L'allure générale que donne une tenue.",
'accessoire': "Petit objet qui complète une tenue.",
'joli': "Agréable à regarder.",

# --- 8e : caractère, identité, COI, interview ---
'sympathique': "Agréable, avec qui on aime être.",
'timide': "Qui n'ose pas parler devant les autres.",
'bavard': "Qui parle beaucoup.",
'généreux': "Qui donne volontiers aux autres.",
'drôle': "Qui fait rire.",
'sérieux': "Qui ne plaisante pas et fait bien son travail.",
'curieux': "Qui veut tout savoir et pose des questions.",
'patient': "Qui sait attendre sans s'énerver.",
'travailleur': "Qui fait beaucoup d'efforts dans son travail.",
'égoïste': "Qui ne pense qu'à soi.",
'sociable': "Qui aime être avec les autres.",
'personnalité': "L'ensemble de ce qui fait qu'on est soi-même.",
'caractère': "La manière d'être et de réagir d'une personne.",
'qualité': "Un bon côté de quelqu'un.",
'défaut': "Un mauvais côté de quelqu'un.",
'opinion': "Ce que l'on pense d'un sujet.",
'admirer': "Trouver quelqu'un remarquable.",
'respecter': "Traiter quelqu'un avec considération.",
'penser': "Avoir une idée dans la tête.",
'parler': "Dire des mots à quelqu'un.",
'dire': "Exprimer quelque chose avec des mots.",
'donner': "Offrir une chose à quelqu'un.",
'prêter': "Donner une chose que l'on veut récupérer.",
'offrir': "Donner en cadeau.",
'téléphoner': "Appeler quelqu'un avec un portable.",
'demander': "Poser une question ou réclamer une chose.",
'répondre': "Donner une réponse.",
'écrire': "Tracer des mots pour communiquer.",
'pronom': "Petit mot qui remplace un nom.",
'message': "Ce que l'on envoie pour communiquer.",
'lettre': "Message écrit que l'on envoie par la poste.",
'interview': "Entretien où un journaliste pose des questions.",
'prénom': "Le mot qui vient avant le nom de famille.",
'âge': "Le nombre d'années que l'on a.",
'nationalité': "Le pays dont on est citoyen.",
'origine': "L'endroit d'où l'on vient.",
'intérêt': "Ce qui attire l'attention et plaît.",
'portrait': "Description d'une personne, en mots ou en image.",
'passion': "Ce que l'on aime avec beaucoup de force.",
'rêve': "Ce que l'on imagine et espère pour plus tard.",

# --- 9e : médias, réseaux, rubriques, source, COD ---
'magazine': "Publication illustrée qui paraît chaque semaine ou mois.",
'titre': "Les mots en gros qui annoncent un article.",
'podcast': "Émission audio que l'on écoute quand on veut.",
'média': "Moyen qui sert à diffuser l'information.",
'compte': "Espace personnel que l'on ouvre sur un site.",
'abonné': "Personne qui suit un compte ou reçoit un journal.",
'publication': "Ce que l'on met en ligne pour le montrer.",
'commentaire': "Ce que l'on écrit sous une publication.",
'partager': "Faire voir un contenu à d'autres personnes.",
'abonner': "Le verbe qui dit que l'on commence à suivre un compte.",
'story': "Publication éphémère qui disparaît après un jour.",
'influenceur': "Personne suivie par beaucoup de gens en ligne.",
'profil': "La page qui présente qui tu es sur un réseau.",
'rubrique': "Partie d'un journal consacrée à un sujet.",
'manchette': "Le très gros titre en haut de la première page.",
'économie': "Domaine de l'argent, du travail et du commerce.",
'société': "Domaine de la vie des gens et de leurs problèmes.",
'météo': "Rubrique qui annonce le temps qu'il va faire.",
'international': "Qui concerne les autres pays.",
'sciences': "Domaine de la recherche et des découvertes.",
'divers': "Se dit des faits variés : accidents, vols, incendies.",
'source': "L'origine d'une information.",
'fiable': "En quoi on peut avoir confiance.",
'vérifier': "Contrôler si une information est vraie.",
'infox': "Fausse nouvelle fabriquée pour tromper.",
'rumeur': "Information qui circule sans être confirmée.",
'mensonge': "Ce que l'on dit en sachant que c'est faux.",
'journaliste': "Personne qui cherche et écrit l'information.",
'légende': "Petit texte qui explique une photo.",
'vrai': "Conforme à la réalité.",
'faux': "Contraire à la réalité.",
'lire': "Comprendre un texte avec les yeux.",
'regarder': "Diriger les yeux vers quelque chose.",
'écouter': "Faire attention à ce que l'on entend.",
'publier': "Mettre un texte à la disposition du public.",
'suivre': "Recevoir tout ce que publie un compte.",
'commenter': "Écrire son avis sous une publication.",
'voir': "Percevoir avec les yeux.",
'vidéo': "Images animées que l'on regarde sur un écran.",
'rédaction': "L'équipe qui écrit le journal, et son bureau.",
'colonne': "Bande verticale de texte dans un journal.",

# --- 10e : faits, opinions, émotions, argumentation ---
'public': "L'ensemble des gens qui lisent ou regardent.",
'audience': "Le nombre de personnes qui suivent une émission.",
'diffuser': "Transmettre largement une information.",
'fait': "Ce qui s'est réellement passé et se vérifie.",
'subjectif': "Qui dépend du point de vue de la personne.",
'vérifiable': "Que l'on peut contrôler avec des preuves.",
'donnée': "Chiffre ou information précise que l'on utilise.",
'témoignage': "Récit de quelqu'un qui a vu la scène.",
'parti': "Se dit d'un point de vue non neutre : un … pris.",
'certitude': "Ce dont on est absolument sûr.",
'indignation': "Colère devant une injustice.",
'inquiétude': "Sentiment de celui qui craint un problème.",
'enthousiasme': "Grande énergie joyeuse pour une chose.",
'méfiance': "Attitude de celui qui ne fait pas confiance.",
'choquant': "Qui provoque une réaction brutale de surprise.",
'inquiétant': "Qui fait craindre quelque chose de grave.",
'rassurant': "Qui enlève la peur et calme.",
'révoltant': "Tellement injuste que cela met en colère.",
'émouvant': "Qui touche le coeur.",
'complément': "Mot ou groupe qui complète le verbe.",
'direct': "Se dit du complément qui suit le verbe sans préposition.",
'indirect': "Se dit du complément introduit par la préposition à.",
'ordre': "La place que les mots occupent dans la phrase.",
'phrase': "Ensemble de mots qui exprime une idée complète.",
'remplacer': "Mettre une chose à la place d'une autre.",
'répéter': "Dire encore une fois la même chose.",
'envoyer': "Faire partir une chose vers quelqu'un.",
'expliquer': "Faire comprendre quelque chose.",
'montrer': "Faire voir quelque chose.",
'éviter': "Faire en sorte qu'une chose n'arrive pas.",
'relief': "Ce que l'on fait quand on met un mot en valeur.",
'souligner': "Attirer l'attention sur un point important.",
'insister': "Répéter avec force pour convaincre.",
'important': "Qui compte beaucoup.",
'essentiel': "Absolument nécessaire.",
'surtout': "Le mot qui marque ce qui compte le plus.",
'précisément': "De façon exacte, sans approximation.",
'affirmer': "Dire avec assurance que c'est vrai.",
'sujet': "Le mot qui fait l'action du verbe.",
'accent': "L'insistance que l'on met sur un mot.",
'tribune': "Texte d'opinion publié dans un journal.",
'argument': "Raison que l'on donne pour convaincre.",
'exemple': "Cas précis qui illustre une idée.",
'nuance': "Petite différence qui rend un avis moins tranché.",
'objection': "Raison que l'on oppose à un argument.",
'convaincre': "Amener quelqu'un à penser comme soi.",
'réfuter': "Démontrer qu'un argument est faux.",
'dénoncer': "Faire connaître publiquement une injustice.",
'illustrer': "Rendre une idée claire par un exemple.",
'conclusion': "La dernière partie, qui ferme le raisonnement.",
'connecteur': "Mot qui relie les idées : d'abord, cependant, donc…",
'thèse': "L'idée principale que l'on veut défendre.",
}

# ------------------------------------------------------------------ #
#  Word Sudoku: palabras de letras TODAS DISTINTAS (4 y 6 letras).   #
#  El motor usa las letras como símbolos, así que una letra repetida  #
#  hace el puzzle imposible. gen_fr_u4.py lo valida.                  #
# ------------------------------------------------------------------ #
SUDOKU_POOL_4 = [
 'ROSE','BLEU','NOIR','VERT','GRIS','CHAT','OURS','LION','LOUP','PORC',
 'DEUX','CINQ','SEPT','HUIT','NEUF','ONZE','JUPE','ROBE','GANT','JEAN',
 'JUDO','VELO','JEUX','INFO','LIRE','VOIR','DIRE','AMIS','VRAI','FAUX',
 'MODE','AVIS','GOUT','PEUR','JOIE','MOTS','PAIN','LAIT','CIEL','MURS',
 'PIED','MAIN','DENT','SOIR','NUIT','BOIS','EAUX','FILM','LUNE','MERS',
 'NOMS','PARC','PONT','RUES','TAXI','VENT','VIES','YEUX','ZERO','DOUX',
]
SUDOKU_POOL_6 = [
 'MEDIAS','SOURCE','COMPTE','GENTIL','SIMPLE','MONTRE','JUPONS','BASKET',
 'DANSER','CHANTE','CINEMA','JUDOKA','COURSE','DOUTES','FIABLE','PUBLIC',
 'ECRANS','PROFIL','DIRECT','PHRASE','MONTER','VALEUR','GRANDE','CHEVAL',
 'POULES','LAPINS','OISEAU','QUINZE','VINGTS','VIOLET','JAUNES','BLANCS',
 'ROUGES','NOIRES','PARDON','PORTES','SAVOIR','MARQUE','BOUCLE','PRENOM',
 'LANGUE','PARTIE','MINUTE','FACILE','GARCON','MAISON','TIMBRE','SALUER',
]

# ---------------------------------------------------- #
#  Las 36 semanas: 6 grados x 6 semanas de la Unité 4  #
# ---------------------------------------------------- #
# Cada semana: theme (título francés), gram (foco gramatical, en español
# para el profesor), words (vocabulario de la semana). Las palabras se
# reparten en tres días: D1 = primera mitad, D2 = segunda mitad,
# D3 = todas (repaso), que es como se dan las tres sesiones.
WEEKS = {
'g5': [
 {'theme':'Les couleurs', 'gram':"c'est un / c'est une · il est + couleur",
  'words':['rouge','bleu','vert','jaune','noir','blanc','rose','gris','orange','violet','marron']},
 {'theme':'Les animaux', 'gram':"le genre du nom · un / une",
  'words':['chien','chat','cheval','vache','cochon','poule','lapin','oiseau','poisson','souris','canard','singe']},
 {'theme':'Les nombres 1–10', 'gram':"j'ai … ans · combien de… ?",
  'words':['deux','trois','quatre','cinq','six','sept','huit','neuf','dix']},
 {'theme':'Les nombres 11–20', 'gram':"les nombres avec trait d'union · le pluriel en -s",
  'words':['onze','douze','treize','quatorze','quinze','seize','dix-sept','dix-huit','dix-neuf','vingt']},
 {'theme':'Animaux et couleurs', 'gram':"l'accord de l'adjectif de couleur",
  'words':['chat','chien','souris','oiseau','poisson','lapin','noir','blanc','gris','rouge','jaune','vert']},
 {'theme':'Projet — Mon animal préféré', 'gram':"révision : présenter un animal, sa couleur et combien",
  'words':['animal','préféré','couleur','nom','petit','grand','gentil','mignon','aimer','avoir','maison','famille']},
],
'g6': [
 {'theme':'Les loisirs', 'gram':"j'aime / j'adore / je déteste + nom",
  'words':['lecture','musique','danse','cinéma','photo','peinture','théâtre','vélo','cuisine','dessin','chant','jeux']},
 {'theme':'Les sports et le verbe faire', 'gram':"faire au singulier · faire du / de la / de l'",
  'words':['football','basket','volley','natation','tennis','course','judo','équitation','ski','gymnastique','patinage','faire']},
 {'theme':'Les adverbes de fréquence', 'gram':"la place de l'adverbe après le verbe",
  'words':['toujours','souvent','quelquefois','parfois','rarement','jamais','matin','soir','semaine','mois','dimanche','samedi']},
 {'theme':'La négation simple', 'gram':"ne … pas · ne … jamais · du → de",
  'words':['jamais','rien','personne','aimer','détester','jouer','pratiquer','sport','souvent','toujours','rarement','faire']},
 {'theme':'Goûts et préférences', 'gram':"je préfère · justifier avec parce que",
  'words':['adorer','aimer','détester','préférer','goût','préférence','relaxant','amusant','fatigant','difficile','facile','musique']},
 {'theme':'Projet — Sondage de la classe', 'gram':"révision : interroger et rapporter les résultats",
  'words':['sondage','question','réponse','classe','camarade','résultat','majorité','populaire','pourquoi','préféré','souvent','jamais']},
],
'g7': [
 {'theme':'Les vêtements', 'gram':"un / une / des · l'adjectif après le nom",
  'words':['pantalon','chemise','robe','jupe','manteau','pull','veste','botte','chaussure','jean','short','baskets']},
 {'theme':'Les accessoires', 'gram':"porter au présent (les six personnes)",
  'words':['sac','casquette','chapeau','écharpe','lunettes','ceinture','montre','bracelet','collier','gant']},
 {'theme':'Les adjectifs de couleur', 'gram':"l'accord · blanc/blanche · marron et orange invariables",
  'words':['rouge','bleu','vert','jaune','blanc','noir','violet','marron','orange','gris','rose','clair','foncé']},
 {'theme':'Porter et mettre', 'gram':"mettre au présent · porter ≠ mettre",
  'words':['porter','mettre','enlever','essayer','choisir','acheter','taille','miroir','cabine','tenue','magasin','prix']},
 {'theme':'Les styles vestimentaires', 'gram':"à mon avis · je trouve que",
  'words':['classique','sportif','décontracté','élégant','chic','vintage','coloré','simple','moderne','original','avis','trouver']},
 {'theme':'Projet — Défilé de mode', 'gram':"révision : décrire un look et le commenter",
  'words':['défilé','mode','modèle','podium','présenter','décrire','tenue','style','look','accessoire','joli','photo']},
],
'g8': [
 {'theme':'Vêtements et accessoires', 'gram':"révision du 7e · décrire une tenue",
  'words':['tenue','look','style','porter','mettre','accessoire','chemise','veste','baskets','casquette','écharpe','montre']},
 {'theme':'Les traits de caractère', 'gram':"l'accord : -eux/-euse · gentil/gentille",
  'words':['sympathique','timide','bavard','généreux','drôle','sérieux','curieux','patient','gentil','travailleur','égoïste','sociable']},
 {'theme':'Personnalité, goûts et opinions', 'gram':"justifier une opinion avec parce que",
  'words':['personnalité','caractère','qualité','défaut','avis','opinion','admirer','respecter','aimer','détester','trouver','penser']},
 {'theme':'Les pronoms COI', 'gram':"me · te · lui · nous · vous · leur",
  'words':['parler','dire','donner','prêter','offrir','téléphoner','demander','répondre','écrire','pronom','message','lettre']},
 {'theme':"L'interview", 'gram':"Est-ce que… ? · Qu'est-ce que… ? · le COI à la forme négative",
  'words':['interview','question','réponse','journaliste','prénom','nom','âge','nationalité','origine','langue','intérêt','curieux']},
 {'theme':'Projet — Portrait et interview', 'gram':"révision : interroger et rédiger un portrait",
  'words':['portrait','décrire','présenter','ami','camarade','famille','passion','rêve','projet','avenir','qualité','caractère']},
],
'g9': [
 {'theme':'Les médias', 'gram':"les pronoms sujets · le sujet obligatoire · on",
  'words':['presse','journal','magazine','télévision','radio','chaîne','reportage','article','information','titre','podcast','média']},
 {'theme':'Les réseaux sociaux', 'gram':"partager, s'abonner, commenter",
  'words':['réseau','compte','abonné','publication','commentaire','partager','abonner','story','influenceur','profil','écran','message']},
 {'theme':'Les rubriques du journal', 'gram':"le genre des rubriques · la une · les faits divers",
  'words':['rubrique','manchette','actualité','politique','économie','société','culture','sport','météo','international','sciences','divers']},
 {'theme':"La source et l'infox", 'gram':"la négation complète : pas · jamais · plus · rien · personne",
  'words':['source','fiable','vérifier','infox','rumeur','mensonge','journaliste','légende','preuve','doute','vrai','faux']},
 {'theme':'Les pronoms COD', 'gram':"le · la · l' · les · la place devant le verbe",
  'words':['pronom','lire','regarder','écouter','publier','suivre','commenter','voir','partager','article','photo','vidéo']},
 {'theme':'Projet — La une de la classe', 'gram':"révision : rédiger des titres et citer la source",
  'words':['manchette','titre','article','photo','légende','rédaction','publier','journal','classe','source','information','colonne']},
],
'g10': [
 {'theme':'Médias et réseaux sociaux', 'gram':"révision du 9e · COD et COI séparés",
  'words':['média','réseau','presse','information','publication','abonné','chaîne','article','écran','public','audience','diffuser']},
 {'theme':'Faits et opinions', 'gram':"les marqueurs d'opinion · le fait vérifiable",
  'words':['fait','opinion','objectif','subjectif','vérifiable','preuve','donnée','témoignage','rumeur','parti','avis','certitude']},
 {'theme':'Émotions et réactions', 'gram':"l'accord des adjectifs en -ant",
  'words':['indignation','surprise','inquiétude','enthousiasme','méfiance','choquant','inquiétant','rassurant','révoltant','émouvant','colère','espoir']},
 {'theme':'COD et COI ensemble', 'gram':"l'ordre fixe des deux pronoms",
  'words':['pronom','complément','direct','indirect','ordre','phrase','remplacer','répéter','envoyer','expliquer','montrer','éviter']},
 {'theme':'La mise en relief', 'gram':"c'est … qui / que · ce qui / ce que … c'est",
  'words':['relief','souligner','insister','valeur','important','essentiel','surtout','précisément','affirmer','montrer','sujet','accent']},
 {'theme':'Projet — Tribune argumentée', 'gram':"révision : les connecteurs logiques",
  'words':['tribune','argument','exemple','nuance','objection','convaincre','réfuter','dénoncer','illustrer','conclusion','connecteur','thèse']},
],
}

GRADE_TITLE = {
 'g5':  'Les couleurs, les animaux, les nombres',
 'g6':  'Les loisirs et les sports',
 'g7':  'Les vêtements et le style',
 'g8':  "Le caractère et l'identité",
 'g9':  "Les médias et l'information",
 'g10': 'Faits, opinions et argumentation',
}

GRADES = ['g5','g6','g7','g8','g9','g10']
GRADE_LABEL = {'g5':'5e','g6':'6e','g7':'7e','g8':'8e','g9':'9e','g10':'10e'}
GRADE_ES    = {'g5':'5.º','g6':'6.º','g7':'7.º','g8':'8.º','g9':'9.º','g10':'10.º'}
GRADE_LEVEL = {'g5':'A1.1','g6':'A1.2','g7':'A2.1','g8':'A2.2','g9':'A2.2','g10':'B1.1'}
