# -*- coding: utf-8 -*-
"""Localiza a INGLÉS los juegos de Grammar (instrucciones, UI, feedback, notas)."""
import os
REPO=os.path.dirname(os.path.abspath(__file__))

REPL = {
'reported-speech.html': [
 ('Contar lo que otra persona dijo. Lee el resumen y practica con el juego: elige la transformación correcta, recibe feedback al instante.',
  'Report what another person said. Read the summary, then play: choose the correct transformation and get instant feedback.'),
 ('🔤 Otro juego: Ordena la oración →','🔤 Another game: Put the sentence in order →'),
 ('<b>Lo esencial</b>','<b>The essentials</b>'),
 ('El verbo suele <b>retroceder un tiempo</b>: present → past, past → past perfect, <i>will → would</i>, <i>can → could</i>.',
  'The verb usually <b>shifts back one tense</b>: present → past, past → past perfect, <i>will → would</i>, <i>can → could</i>.'),
 ('Cambian los <b>pronombres</b> (I → he/she, my → his/her, you → me…).',
  '<b>Pronouns</b> change (I → he/she, my → his/her, you → me…).'),
 ('Cambian el <b>tiempo y el lugar</b>: now → then, today → that day, tomorrow → the next day, here → there, this → that, last week → the week before.',
  '<b>Time and place words</b> change: now → then, today → that day, tomorrow → the next day, here → there, this → that, last week → the week before.'),
 ('<b>Preguntas:</b> orden de afirmación (sin <i>do/does/did</i>); sí/no → <i>if/whether</i>.',
  '<b>Questions:</b> statement word order (no <i>do/does/did</i>); yes/no → <i>if/whether</i>.'),
 ('<b>Órdenes/peticiones:</b> <i>tell + objeto + (not) to + infinitivo</i> → <i>He told me to wait / not to be late.</i>',
  '<b>Orders/requests:</b> <i>tell + object + (not) to + infinitive</i> → <i>He told me to wait / not to be late.</i>'),
 ('Present simple → past (am → was) y el pronombre I → he.','Present simple → past (am → was); pronoun I → he.'),
 ('Past simple → past perfect (finished → had finished); my → her.','Past simple → past perfect (finished → had finished); my → her.'),
 ('Pregunta de sí/no → if + orden de afirmación, sin "do"; speak → spoke.','Yes/no question → if + statement word order, no "do"; speak → spoke.'),
 ('Pregunta wh- → orden de afirmación; are → was; you → I.','Wh- question → statement word order; are → was; you → I.'),
 ('Orden → tell + objeto + to + infinitivo.','Order → tell + object + to + infinitive.'),
 ('Orden negativa → not + to + infinitivo; say to → tell.','Negative order → not + to + infinitive; say to → tell.'),
 ('can → could; el infinitivo no cambia (drive).','can → could; the infinitive does not change (drive).'),
 ('Volvemos al presente y a la 1ª persona: was → am; she → I.','Back to present and first person: was → am; she → I.'),
 ('Pregunta directa: recupera "do" y el orden de pregunta; lived → live; I → you.','Direct question: bring back "do" and question word order; lived → live; I → you.'),
 ("'Elige el <b>reported speech</b> correcto:'","'Choose the correct <b>reported speech</b>:'"),
 ("'Elige el <b>direct speech</b> correcto (las palabras exactas):'","'Choose the correct <b>direct speech</b> (the exact words):'"),
 ("'Ver resultado'","'See result'"), ("'Siguiente →'","'Next →'"),
 ('¡Correcto!</b> ','Correct!</b> '), ('❌ <b>Casi.</b>','❌ <b>Almost.</b>'),
 ("+'Respuesta: <b>'","+'Answer: <b>'"),
 ('¡Excelente! Dominas el reported speech. 🌟','Excellent! You have mastered reported speech. 🌟'),
 ('Buen trabajo. Repasa los cambios de tiempo y pronombres. 👍','Good job. Review the tense and pronoun changes. 👍'),
 ('Vas bien. Revisa el resumen de arriba y vuelve a intentar. 💪','You are getting there. Check the summary above and try again. 💪'),
 ('Sigue practicando: lee el resumen y juega otra vez. ✍️','Keep practising: read the summary and play again. ✍️'),
 ('↻ Jugar otra vez','↻ Play again'),
],
'reported-speech-order.html': [
 ('Reported Speech · Ordena la oración — Portal NIS','Reported Speech · Word Order — Portal NIS'),
 ('Toca las palabras para construir la oración…','Tap the words to build the sentence…'),
 ('🔤 Reported Speech — Ordena la oración','🔤 Reported Speech — Word Order'),
 ('Lee la oración en <b>Direct speech</b>. Luego ordena las palabras para formar el <b>Reported speech</b> correcto.',
  'Read the sentence in <b>Direct speech</b>. Then put the words in order to form the correct <b>Reported speech</b>.'),
 ('🧩 Otro juego: Elige la opción correcta →','🧩 Another game: Choose the correct option →'),
 ('<span class="pill">Oración ','<span class="pill">Sentence '),
 ('Ordena el <b>reported speech</b>:','Put the <b>reported speech</b> in order:'),
 ('>↺ Reiniciar<','>↺ Reset<'),
 ('>Mostrar respuesta<','>Show answer<'),
 ('>Comprobar<','>Check<'),
 ('✅ <b>¡Correcto!</b> ','✅ <b>Correct!</b> '),
 ('🤔 Aún no. Revisa el orden (tiempo verbal, pronombres) e inténtalo otra vez.','🤔 Not yet. Check the order (verb tense, pronouns) and try again.'),
 ("'👀 Respuesta: <b>'","'👀 Answer: <b>'"),
 ("'Ver resultado'","'See result'"), ("'Siguiente →'","'Next →'"),
 ("'¡Excelente orden! 🌟'","'Excellent ordering! 🌟'"),
 (" : pct>=60?'Buen trabajo. 👍' : pct>=40?'Vas mejorando. 💪' : 'Repasa el resumen y vuelve a intentar. ✍️'",
  " : pct>=60?'Good job. 👍' : pct>=40?'Getting better. 💪' : 'Review and try again. ✍️'"),
 ('↻ Jugar otra vez','↻ Play again'),
],
'grammar-quiz.html': [
 ('Simple para rutinas y hechos; continuous para lo que pasa ahora (now, at the moment, Look!, Listen!).',
  'Simple for routines and facts; continuous for what is happening now (now, at the moment, Look!, Listen!).'),
 ('Present perfect para experiencias y resultados (ever, never, already, since, for); past simple para tiempo terminado (yesterday, last…, ago).',
  'Present perfect for experiences and results (ever, never, already, since, for); past simple for finished time (yesterday, last…, ago).'),
 ('La pasiva: be + participio. El foco está en la acción o el objeto, no en quién la hace (by + agente, opcional).',
  'The passive: be + past participle. The focus is on the action or the object, not on who does it (by + agent, optional).'),
 ('Condicionales mixtos, wish e inversión formal (Had I…, Were I…, Should it…).',
  'Mixed conditionals, wish and formal inversion (Had I…, Were I…, Should it…).'),
 ('"every day" = rutina → present simple (goes).','"every day" = routine → present simple (goes).'),
 ('Rutina + "I" → drink.','Routine + "I" → drink.'),
 ('Hecho permanente → works.','Permanent fact → works.'),
 ('"last year" (terminado) → past simple.','"last year" (finished) → past simple.'),
 ('Resultado en el presente → present perfect.','Result in the present → present perfect.'),
 ('"When" + momento definido → past simple.','"When" + a definite time → past simple.'),
 ('Pasado pasivo: was + painted.','Past passive: was + painted.'),
 ('Presente pasivo: is + spoken.','Present passive: is + spoken.'),
 ('Futuro pasivo: will be + finished.','Future passive: will be + finished.'),
 ('Pasado pasivo: was built.','Past passive: was built.'),
 ('Presente pasivo plural: are cleaned.','Present passive (plural): are cleaned.'),
 ('Presente continuo pasivo: is being built.','Present continuous passive: is being built.'),
 ('Pasado pasivo: was stolen.','Past passive: was stolen.'),
 ('Present perfect pasivo: have been sent.','Present perfect passive: have been sent.'),
 ('Second conditional (were para todas las personas).','Second conditional (were for all persons).'),
 ('Mixto: condición pasada → resultado presente (would live).','Mixed: past condition → present result (would live).'),
 ('Inversión: "Had I known" = "If I had known".','Inversion: "Had I known" = "If I had known".'),
 ('Second conditional: would + infinitivo.','Second conditional: would + infinitive.'),
 ('Mixto: condición presente → resultado pasado (would have given).','Mixed: present condition → past result (would have given).'),
 ('Inversión formal: "Should it rain" = "If it rains".','Formal inversion: "Should it rain" = "If it rains".'),
 ('wish + past simple para un deseo presente.','wish + past simple for a present wish.'),
 ("'Nivel '+SET.level","'Level '+SET.level"),
 ("'Ver resultado'","'See result'"), ("'Siguiente →'","'Next →'"),
 ('¡Correcto!</b> ','Correct!</b> '), ('❌ <b>Casi.</b>','❌ <b>Almost.</b>'),
 ("pct>=80?'¡Excelente! 🌟':pct>=60?'Buen trabajo. 👍':pct>=40?'Vas mejorando. 💪':'Repasa la regla de arriba y vuelve a intentar. ✍️'",
  "pct>=80?'Excellent! 🌟':pct>=60?'Good job. 👍':pct>=40?'Getting better. 💪':'Review the rule above and try again. ✍️'"),
 ('↻ Jugar otra vez','↻ Play again'),
],
}

for f, reps in REPL.items():
    p=os.path.join(REPO,f); s=open(p,encoding='utf-8').read(); miss=[]
    for old,new in reps:
        if old in s: s=s.replace(old,new)
        else: miss.append(old)
    open(p,'w',encoding='utf-8').write(s)
    print(f, '-> reemplazos OK' if not miss else '-> FALTARON:')
    for m in miss: print('   NO-MATCH:', m[:80])
