/* Lo que hace CADA CURSO en cada semana del arco — NIS 2026.
 *
 * POR QUE ESTA APARTE
 * En project-arcs.js, cada semana dice lo que hace el PROYECTO (`hace`) y la
 * pagina anade debajo lo que cada area da esa semana segun el Annual Plan del
 * colegio. Faltaba lo del medio y es lo que pidio el usuario: la tarea
 * concreta de cada curso dentro del proyecto, semana a semana, como ya se
 * veia de Ingles porque el Scope si reparte por semana.
 *
 * Va en un archivo propio y no dentro de cada arco por dos razones:
 *   - project-arcs.js lo editan varias sesiones a la vez; anadir 160 celdas
 *     ahi multiplica los choques.
 *   - asi se puede completar grado por grado sin tocar nada mas: la pagina
 *     pinta el bloque si existe y lo omite si no.
 *
 * QUE ES DEL COLEGIO Y QUE NO
 * El contenido de cada curso sale del Annual Plan y, en 1.o, de los
 * Project.docx del grado, que ya vienen leccion a leccion. **El reparto por
 * semana y la forma de decirlo son propuesta del portal**, y la pagina lo
 * marca con la etiqueta «para acordar con cada profesor». Donde un arco ya
 * trae `cursos` dentro de su fase (g1.t3), manda ese y esto no se usa.
 *
 * FORMA:  'clave.del.arco': { numeroDeSemana: {curso: 'lo que hace'} }
 * Las claves de curso son las de AREA_ORDEN en project.html: science, social,
 * math, english, comunicacion, pe, tutoria, art, music, spiritual.
 */
(function(){
window.PROJECT_ARCS_CURSOS = {

/* ================================================== 1.o · T1 · P1+P2 ==== */
'g1.t1': {
  1:{social:'Quién soy: el DNI, para qué sirve y qué dice de mí. Con el DNI de clase se vota el nombre del aula.',
     science:'Las huellas dactilares con tampón y lupa: nadie tiene las mismas. Primera observación con instrumento.',
     comunicacion:'Mi nombre y mi apellido, escritos y leídos. Nombres propios con mayúscula.',
     math:'Contar cuántos somos y cuántas piezas tiene el mural: conteo y correspondencia.',
     english:'Key routines and functional phrases: saludar, decir mi nombre y mi edad.',
     art:'Autorretrato delante del espejo, mirando la forma de los ojos y el tono de piel.',
     music:'Pulso y ritmo: patrones simples con percusión corporal para la canción del aula.',
     pe:'Control corporal en desplazamientos variados; juegos cooperativos con reglas simples.',
     tutoria:'Qué emociones traigo a 1.º; el mural de piezas de puzle donde cabe cada uno.'},
  2:{science:'Por dónde viaja la comida y para qué sirven los pulmones: dos experimentos con el propio cuerpo.',
     math:'Medir cuánto he crecido y comparar con antes: medida y comparación de longitudes.',
     comunicacion:'Contar en orden lo que sé hacer ahora y no sabía antes: primero, después, ahora.',
     social:'Mi línea de tiempo con fotos de antes y de ahora, ordenadas.',
     english:'Describir lo que puedo hacer: I can…',
     art:'Ilustración de la línea de tiempo con las fotos.',
     music:'Canción del crecimiento con gestos.',
     pe:'Actividades motrices para el cuidado del cuerpo: qué puedo hacer ahora que antes no.',
     tutoria:'Lo que me costaba y ya no me cuesta.'},
  3:{social:'De dónde viene mi apellido, dónde vivo y cómo ha cambiado mi distrito y mi colegio.',
     comunicacion:'La ficha de mi familia y mi distrito, dictada y copiada.',
     math:'Los sitios del barrio en un plano sencillo: posición y recorrido.',
     science:'Qué hay vivo en mi barrio: primera lista de seres vivos del entorno.',
     english:'I live in… My school is…',
     art:'Dibujo del sitio del barrio que más me gusta.',
     music:'Juegos y canciones tradicionales de la familia, de antes y de ahora.',
     pe:'Juegos tradicionales que jugaban los abuelos.',
     tutoria:'Las tradiciones de mi casa: qué hacemos que no hace nadie más.'},
  4:{social:'La diferencia entre un derecho y una responsabilidad; el árbol del círculo de confianza y qué hace cada persona.',
     comunicacion:'La entrevista: preparar dos preguntas y anotar la respuesta con las palabras del otro.',
     science:'Quiénes viven en el colegio además de nosotros: primera pregunta sobre los insectos.',
     math:'Cuántas personas hay en mi círculo de confianza: conteo y comparación entre círculos.',
     english:'This is my… He/She helps me. Thank you.',
     art:'El árbol del círculo de confianza, dibujado.',
     music:'Canción del trabajo en equipo.',
     pe:'Juegos por parejas: confiar y sostener al otro.',
     tutoria:'A quién pido ayuda y cómo se la pido.'},
  5:{social:'Paseo de exploración por el colegio: qué hay aquí que haya que proteger y qué problema vemos.',
     comunicacion:'La carta de agradecimiento a alguien de la comunidad: a quién va y qué le pide.',
     science:'Registro de lo observado en el paseo: qué vi, dónde y cuántos.',
     math:'Contar los problemas encontrados y ordenarlos de más a menos frecuente.',
     english:'Look at this. Please help us. Thank you for your work.',
     art:'Cartel del problema elegido para el vídeo.',
     music:'Cortina musical del vídeo de concienciación.',
     pe:'Recorrido del paseo: orientación y cuidado del grupo.',
     tutoria:'Qué necesita el aula para estar en orden: acuerdos.'},
  6:{tutoria:'La cesta de las palabras mágicas y el reto de cooperación en equipo.',
     art:'Autorretrato en 3D como cierre del periodo, con material de volumen.',
     comunicacion:'Cuento colectivo escrito entre todos.',
     math:'La torre de papel: altura, base y estabilidad; medir y comparar.',
     science:'Por qué unas torres se caen y otras no: primera idea de equilibrio.',
     social:'Convivir: qué acuerdo nos hace falta para trabajar juntos.',
     english:'Team words: my turn, your turn, well done!',
     music:'Yoga y atención plena con música en la salida a la playa.',
     pe:'Salida a la playa: juego cooperativo y cuidado del entorno.'},
  7:{science:'Arranca P2. Se observan los insectos del aula y del colegio: cuándo aparecen, dónde y cada cuánto. Mitos y hechos.',
     math:'Registro de cuántos insectos y de qué tipo: tabla de conteo.',
     comunicacion:'Qué creemos y qué nos preguntamos: dos columnas, dictadas y copiadas.',
     social:'Quién más vive en este sitio: los otros habitantes del colegio.',
     english:'I can see an ant. There are three. It is under the leaf.',
     art:'Dibujo de observación del insecto, del natural y con lupa.',
     music:'Sonidos del patio: escucha y discriminación.',
     pe:'Paseo de observación por el colegio, en silencio y por turnos.',
     tutoria:'Mirar sin tocar: cómo se observa a un ser vivo.'},
  8:{science:'Partes del cuerpo del insecto, cómo se mueven, de qué tamaño son y para qué sirve cada parte; qué comen y dónde viven.',
     math:'Contar patas, alas y partes; comparar tamaños con una regla.',
     comunicacion:'El diagrama etiquetado: escribir el nombre de cada parte donde toca.',
     english:'It has got six legs. These are the wings. It eats leaves.',
     art:'Diagrama a gran tamaño para la pared del aula.',
     social:'Dónde viven en el colegio: mapa de los sitios donde aparecen.',
     music:'Ritmos con seis pulsos, como seis patas.',
     pe:'Juego de imitación de movimientos de insectos.',
     tutoria:'Qué me da miedo y por qué; hablarlo en grupo.'},
  9:{science:'Para qué sirven: polinización, descomposición y cadenas alimentarias; qué pasaría si desaparecieran.',
     social:'Cómo les afecta lo que hacemos con la comida, la limpieza y los materiales.',
     comunicacion:'El cartel de cuidado: frase corta, clara y en imperativo.',
     math:'Cuántos insectos hacen falta para polinizar: estimación sencilla con material.',
     english:'Bees help the flowers. Do not step on them.',
     art:'Cartel de cuidado con letra grande y un solo dibujo.',
     music:'Canción de los insectos para el vídeo.',
     pe:'Circuito de la polinización: llevar sin derramar.',
     tutoria:'Cuidar lo pequeño: por qué importa.'},
  10:{science:'Situaciones reales de aula con un insecto y qué respuestas caben; se elige el problema del prototipo.',
      social:'Se acuerda el protocolo de clase: qué hacemos cuando aparece uno.',
      math:'El plano del prototipo: tamaño, cuántas piezas y cuántas de cada una.',
      comunicacion:'Escribir el protocolo en pasos numerados.',
      english:'Do not touch it. Call the teacher. We need a box.',
      art:'Plano del prototipo dibujado por el equipo.',
      music:'Sintonía del protocolo para recordarlo.',
      pe:'Simulacro del protocolo: moverse sin correr.',
      tutoria:'Ponerse de acuerdo en equipo sin pelear.'},
  11:{science:'Se construye el prototipo con material reciclado siguiendo el plano y se comprueba si funciona.',
      art:'Construcción del prototipo y póster de cómo funciona.',
      comunicacion:'Presentación oral del prototipo y grabación del vídeo.',
      math:'Comprobar que las medidas del prototipo coinciden con el plano.',
      social:'El vídeo para la comunidad: a quién va dirigido y qué le pide.',
      english:'We made it with bottles. It works like this. It helps the ants.',
      music:'Música del vídeo final.',
      pe:'Presentación del prototipo en el patio.',
      tutoria:'Escuchar la mejora que propone otro equipo y aplicarla.'}
},

/* ================================================== 1.o · T2 · P3+P4 ==== */
'g1.t2': {
  1:{science:'Qué es un fenómeno natural y qué lo convierte en desastre: primeros casos.',
     social:'Los sucesos que han pasado aquí, puestos en orden en la línea de tiempo de la clase.',
     comunicacion:'Contar un suceso en orden: qué pasó primero y qué después.',
     math:'Los años en la recta numérica: antes y después, más cerca y más lejos.',
     english:'There was an earthquake. It happened in Lima.',
     art:'Ilustración de un suceso de la línea de tiempo.',
     music:'Sonidos de la naturaleza: escucha y clasificación.',
     pe:'Reacción rápida: juegos de parar y moverse a la señal.',
     tutoria:'Qué siento cuando tiembla y con quién lo hablo.'},
  2:{social:'Costa, sierra y selva: cómo es el suelo, el clima y qué crece o tiembla en cada una.',
     science:'Por qué en cada región pasa algo distinto: relieve, agua y clima.',
     comunicacion:'La ficha de región con las mismas cuatro casillas para las tres.',
     math:'Comparar temperaturas y alturas de las tres regiones: mayor y menor.',
     english:'It is hot in the jungle. It rains a lot.',
     art:'Las tres regiones en un mural colectivo.',
     music:'Una canción de cada región.',
     pe:'Juegos tradicionales de cada región.',
     tutoria:'De qué región viene mi familia.'},
  3:{science:'Antes, durante y después: qué se prepara, qué se hace y qué se revisa.',
     social:'La zona segura del colegio y quién avisa: el plan de todos.',
     comunicacion:'Escribir instrucciones en imperativo y en orden.',
     math:'Contar los pasos hasta la zona segura y cronometrarlos.',
     english:'Get under the table. Do not run. Go to the safe zone.',
     art:'Cartel de las recomendaciones, con pictogramas.',
     music:'Señal sonora del simulacro.',
     pe:'Ensayo del desplazamiento a la zona segura.',
     tutoria:'Mantener la calma: qué hago con mi miedo.'},
  4:{science:'Por qué unas construcciones aguantan y otras no: base, columnas y peso. El experimento de la columna.',
     math:'Formas y medidas del edificio: base ancha, altura y cuántas piezas.',
     art:'Construcción del edificio del equipo para la ciudad colaborativa.',
     social:'Qué necesita una ciudad para funcionar: qué edificio hace falta.',
     comunicacion:'El nombre del edificio y su cartel.',
     english:'Our building is strong. The base is wide.',
     music:'Ritmo de trabajo para construir en equipo.',
     pe:'Transportar material entre todos sin que se caiga.',
     tutoria:'Si mi edificio se cae, se cae la calle: responsabilidad compartida.'},
  5:{science:'Causa y prevención: qué provoca cada problema y qué lo evita.',
     social:'Qué podemos prevenir nosotros y qué no depende de nosotros.',
     comunicacion:'Fichas de causa y prevención, emparejadas.',
     math:'Clasificar las fichas en dos columnas y contar cuántas hay en cada una.',
     english:'The rubbish blocks the water. We can clean the drain.',
     art:'Diseño de las fichas para que se entiendan sin leer.',
     music:'Canción de prevención para el simulacro.',
     pe:'Circuito de prevención: obstáculos y decisiones.',
     tutoria:'Qué puedo hacer yo esta semana.'},
  6:{comunicacion:'El portafolio del periodo: elegir el mejor trabajo y decir por qué.',
     social:'Presentación del portafolio y del simulacro a la clase.',
     science:'Revisión de lo aprendido sobre la Tierra y las regiones.',
     math:'Contar y ordenar los trabajos del portafolio.',
     english:'This is my best work. I learned about the jungle.',
     art:'Portada del portafolio.',
     music:'Cierre musical del periodo.',
     pe:'Simulacro completo, cronometrado.',
     tutoria:'Autoevaluación con caritas.'},
  7:{science:'Arranca P4. De dónde sale la comida: la semilla, lo que necesita y el registro de germinación.',
     math:'Medir la planta cada día y anotar: registro y comparación.',
     comunicacion:'El registro diario escrito: día, qué veo, cuánto mide.',
     social:'Quién cultiva lo que comemos.',
     english:'Day 1: nothing. It is two centimetres. I gave it water.',
     art:'Dibujo de observación de la planta cada semana.',
     music:'Canción de la semilla.',
     pe:'Juego del crecimiento: de semilla a árbol.',
     tutoria:'Cuidar algo todos los días aunque no pase nada.'},
  8:{social:'Qué se cultiva en cada región y por qué: el mapa de región y cultivo.',
     science:'Qué necesita cada cultivo: clima, agua y suelo.',
     comunicacion:'Escribir en el mapa el nombre de cada alimento y su región.',
     math:'Contar cuántos alimentos hay por región y comparar.',
     english:'Rice grows on the coast. This banana is from the jungle.',
     art:'El mapa de Perú con los alimentos dibujados.',
     music:'Canción de los alimentos del Perú.',
     pe:'Juego de la cosecha por regiones.',
     tutoria:'Qué comida de otra región me gustaría probar.'},
  9:{social:'El viaje de la comida hasta el colegio: agricultor, camión, mercado, tienda y yo.',
     comunicacion:'La dramatización del mercado: quién soy y qué digo.',
     math:'Pagar y dar el vuelto con monedas de juguete.',
     science:'La cadena de frío: por qué unas cosas van en frío.',
     english:'I am the farmer. How much is it? Here you are.',
     art:'Decorado y carteles del mercado.',
     music:'Pregones del mercado, con ritmo.',
     pe:'Cargar y transportar en equipo.',
     tutoria:'Dar las gracias a quien nos trae la comida.'},
  10:{science:'Higiene de los alimentos: lavar, guardar en frío y mirar la fecha.',
      comunicacion:'El folleto de higiene en tres caras, con pasos numerados.',
      social:'Qué hace mi familia en casa con la comida.',
      math:'Las fechas del calendario: antes y después de la fecha de vencimiento.',
      english:'Wash the fruit. Put the milk in the fridge. Look at the date.',
      art:'Diseño del folleto para que se entienda sin leer.',
      music:'Canción del lavado de manos, cronometrada.',
      pe:'Rutina de higiene antes y después de la actividad física.',
      tutoria:'El folleto es para mi familia: a quién se lo doy.'},
  11:{science:'Qué me hace por dentro cada alimento: energía, crecimiento y protección.',
      math:'Repartir el plato en partes: la mitad y las porciones.',
      social:'La lonchera de mi casa y la de la clase.',
      comunicacion:'Explicar por qué elegí cada alimento de mi plato.',
      english:'Bread gives me energy. Fruit protects me. Milk makes me grow.',
      art:'El plato dibujado y etiquetado.',
      music:'Ensayo de la actuación de la feria.',
      pe:'Juego de la lonchera equilibrada.',
      tutoria:'Probar algo nuevo sin obligar a nadie.'},
  12:{social:'La Feria de Científicos de la Comida: montar el puesto y recibir a los visitantes.',
      comunicacion:'Las tres frases del puesto, aprendidas y dichas mirando al visitante.',
      science:'Explicar el viaje del alimento y su aporte a quien pregunte.',
      math:'La lonchera equilibrada: contar y repartir delante del visitante.',
      english:'Welcome to our stand. This potato comes from Puno. Would you like to try?',
      art:'Montaje del puesto y de la lonchera.',
      music:'Actuación de apertura de la feria.',
      pe:'Recorrido de la feria sin chocarse.',
      tutoria:'Recibir a un invitado: mirar, saludar y explicar.'}
},

/* ================================================== 2.o · T1 · P1+P2 ==== */
'g2.t1': {
  1:{social:'"About me" y las diferencias entre compañeros: quién soy y dónde estoy.',
     science:'Se plantea la pregunta de investigación del trimestre a partir del recorrido.',
     comunicacion:'La tarjeta de observación: escribir lo que se ve, no lo que se opina.',
     math:'Contar lo observado en el recorrido y comparar entre zonas del colegio.',
     english:'I can see… I can hear… It is clean / dirty.',
     art:'Dibujo del sitio del colegio que más gusta y del que menos.',
     pe:'Recorrido por el colegio: orientación y desplazamiento en grupo.',
     tutoria:'Lo que me gusta y lo que no de mi colegio, dicho sin ofender a nadie.'},
  2:{science:'Los cuatro tipos de contaminación, dos por semana, y su búsqueda en el propio colegio antes de mirar la lámina.',
     social:'Qué actividades humanas producen cada tipo de contaminación.',
     comunicacion:'Nombrar y describir lo encontrado con adjetivos precisos.',
     math:'Contar cuántos focos de cada tipo hay y en qué zona.',
     english:'There is rubbish here. The bus makes smoke.',
     art:'Mapa ilustrado del colegio con los focos marcados.',
     pe:'Salida de búsqueda por zonas, por equipos.',
     tutoria:'Qué parte de eso lo hacemos nosotros.'},
  3:{science:'Reducir, reutilizar y reciclar: qué significa cada verbo y en qué se diferencian.',
     social:'Las reglas de convivencia del aula aplicadas a la basura.',
     math:'Clasificar residuos reales en tres grupos y contar cuántos hay en cada uno.',
     comunicacion:'Escribir el cartel de cada cubo con una frase clara.',
     english:'We can use this again. Paper goes here.',
     art:'Los tres cubos, decorados y etiquetados.',
     music:'Ritmos con objetos reutilizados.',
     tutoria:'Qué puedo dejar de usar yo esta semana.'},
  4:{science:'Elegir algo que se pueda ver y contar: vasos, luces, papeles, grifos.',
     math:'Qué se puede contar y qué no: la pregunta tiene que responderse con un número.',
     comunicacion:'Escribir la pregunta de investigación en una frase.',
     social:'A quién afecta lo que voy a contar.',
     english:'How many…? I am going to count for five days.',
     art:'La ficha de mi pregunta, ilustrada.',
     pe:'Recorrido de conteo: pasar por los puntos sin saltarse ninguno.',
     tutoria:'Elegir una cosa y sostenerla toda la semana.'},
  5:{math:'Tabla de conteo con palotes, que es lo que Math da estas dos semanas. Contar siempre a la misma hora.',
     science:'Registrar el dato en el momento y no de memoria.',
     comunicacion:'Anotar la fecha, la hora y el lugar de cada conteo.',
     social:'Comparar mi zona con la de otro compañero.',
     english:'I saw six bottles. There are more on Monday.',
     art:'Diseño de la hoja de registro.',
     pe:'Constancia diaria: el conteo se hace todos los días.',
     tutoria:'Cumplir un compromiso de cinco días.'},
  6:{math:'El mismo dato en gráfico de barras y en pictograma con escala hasta 10; cuál se entiende mejor y por qué.',
     comunicacion:'Poner título al gráfico y escribir una frase con el hallazgo.',
     science:'Qué dice el gráfico que no decía la tabla.',
     social:'Qué haríamos con ese dato si fuéramos el colegio.',
     english:'On Monday there were six. Friday was the worst day.',
     art:'El gráfico en grande para la pared.',
     music:'Canción del conteo con la escala del pictograma.',
     tutoria:'Enseñar mi gráfico a otro y escuchar qué entiende.'},
  7:{social:'Arranca P2 con "My Personal Story": qué ha cambiado en mi vida. Se trae de casa una foto y un objeto antiguos.',
     comunicacion:'Describir el objeto antiguo y lo que se usa ahora en su lugar.',
     math:'Ordenar hechos en el tiempo: antes, después, hace cuánto.',
     science:'Los materiales de antes y los de ahora: en qué se diferencian.',
     english:'Before there was… Now there is…',
     art:'Dibujo de la pareja antes / ahora.',
     music:'Una canción de antes y una de ahora.',
     tutoria:'Qué de antes me gustaría que volviera.'},
  8:{math:'El calendario, la hora y las relaciones entre día, semana, mes y año.',
     social:'Línea de tiempo personal y del colegio, con hechos ordenados.',
     comunicacion:'Escribir cada hito con su fecha en una frase.',
     science:'Qué cambia con el tiempo en un ser vivo y en un objeto.',
     english:'In 1990 there was a market. Then they built the road.',
     art:'La línea de tiempo ilustrada, en formato largo.',
     pe:'Juegos de antes y de ahora, comparados.',
     tutoria:'Mi historia también es historia del colegio.'},
  9:{social:'Entrevista a un abuelo, un vecino o alguien del colegio que lleve muchos años aquí.',
     comunicacion:'Tres preguntas preparadas antes y las respuestas escritas con las palabras del otro.',
     math:'Cuántos años lleva aquí esa persona: resta sencilla con años.',
     science:'Qué elementos naturales del entorno han desaparecido según la entrevista.',
     english:'What was it like before? Thank you for talking to me.',
     art:'Retrato de la persona entrevistada.',
     music:'Una canción que esa persona recuerde de su infancia.',
     tutoria:'Escuchar sin interrumpir y agradecer.'},
  10:{comunicacion:'Las partes de la carta y el borrador: la carta del proyecto ES el borrador de Comunicación.',
      social:'A quién va dirigida la carta y qué autoridad tiene esa persona.',
      math:'Elegir el número del gráfico que entra en la carta.',
      science:'Qué evidencia sostiene la petición.',
      english:'Dear Mr Mayor, I am writing because…',
      art:'El sobre y la presentación de la carta.',
      pe:'Trabajo por parejas de revisión: leer la carta del otro.',
      tutoria:'Pedir algo con respeto y con razones.'},
  11:{comunicacion:'Carta final con el gráfico pegado; lectura en voz alta a la clase.',
      social:'Entrega de la carta a la persona real.',
      math:'Explicar el gráfico al leer la carta.',
      science:'Contar cómo se recogió el dato.',
      english:'In my school there are … every day.',
      art:'Exposición de las cartas y los gráficos.',
      music:'Cierre musical del trimestre.',
      tutoria:'Qué siento al haber pedido algo de verdad.'}
},

/* ================================================== 2.o · T2 · P3+P4 ==== */
'g2.t2': {
  1:{social:'Expresiones culturales: artesanía, textiles, danza, fiestas, gastronomía y música.',
     comunicacion:'Contar en tres frases una cosa que hace mi familia y no hace nadie más.',
     art:'Dibujo o muestra de esa expresión cultural.',
     math:'Cuántas familias del aula comparten la misma tradición: conteo y comparación.',
     science:'De qué está hecho el objeto o el plato elegido: materiales.',
     english:'My family makes… My grandma taught me.',
     music:'La música de mi familia: se escucha y se identifica el instrumento.',
     tutoria:'Nadie se ríe de la tradición de otro: acuerdo del aula.'},
  2:{social:'Tradiciones, símbolos nacionales, cambio y continuidad; oficios de mi comunidad y para qué sirven.',
     comunicacion:'Ficha de antes y ahora con la misma estructura para todos.',
     math:'Ordenar en el tiempo y contar cuántos años separan las dos escenas.',
     science:'Qué materiales se usaban antes y cuáles ahora.',
     english:'They played with a spinning top. Now we play on a tablet.',
     art:'Las dos escenas, dibujadas una al lado de la otra.',
     music:'Un juego cantado tradicional, aprendido.',
     tutoria:'Qué me gustaría conservar de lo de antes.'},
  3:{math:'Preposiciones de lugar y representación de espacios cercanos en un mapa.',
     social:'Elementos naturales y sociales del entorno, situados en el mapa.',
     comunicacion:'Dar instrucciones para llegar a un sitio usando los puntos de referencia.',
     science:'Qué elementos del mapa están vivos y cuáles no.',
     english:'It is next to the door. Turn left at the tree.',
     art:'El mapa dibujado a mano con leyenda.',
     pe:'Juego de orientación siguiendo el mapa de un compañero.',
     tutoria:'Explicar bien para que el otro llegue.'},
  4:{science:'Los animales del Perú: vertebrados e invertebrados, partes externas y para qué sirve cada cubierta.',
     social:'De qué región del Perú es cada animal.',
     comunicacion:'La ficha del animal con su clasificación y la razón.',
     math:'Contar y agrupar los animales del aula por grupo.',
     english:'It has got a backbone. Fish are vertebrates.',
     art:'Dibujo del animal con sus partes señaladas.',
     music:'Sonidos de animales: escucha y reconocimiento.',
     pe:'Juego de desplazamientos imitando animales.'},
  5:{science:'El reino vegetal del Perú: con flor y sin flor, las partes de la planta y qué hace cada una.',
     comunicacion:'La ficha de la planta, etiquetada.',
     math:'Medir la planta y contar sus partes.',
     social:'Qué plantas se usan en mi comunidad y para qué.',
     english:'The roots drink water. This plant has got flowers.',
     art:'Dibujo del natural de la planta.',
     music:'Canción de las plantas con gestos.',
     tutoria:'Cuidar la planta del aula durante todo el periodo.'},
  6:{social:'La Fiesta de la cultura: cada niño atiende una parada de la exhibición.',
     comunicacion:'Las tres frases de mi parada, dichas mirando al visitante.',
     art:'Montaje de la parada con lo traído de casa.',
     music:'Danza o pieza que abre la exhibición.',
     math:'Cuántos visitantes pasaron por mi parada: conteo en el momento.',
     science:'Explicar el animal o la planta que llevé a la parada.',
     english:'Welcome! This is my family’s dance. It comes from Cusco.',
     pe:'Recorrido de la exhibición sin aglomerarse.'},
  7:{science:'Arranca P4: preguntas de investigación y predicciones para el viaje.',
     social:'Qué es Pachacámac y por qué vamos.',
     comunicacion:'Escribir la pregunta y la predicción antes de ir.',
     math:'Cuánto se tarda en llegar y a qué hora salimos.',
     english:'What did they build it with? I think I will see…',
     art:'Portada del Field Journal.',
     pe:'Preparación física de la salida: caminar y llevar la mochila.',
     tutoria:'Normas de la salida, acordadas entre todos.'},
  8:{science:'Seguir instrucciones para una investigación sencilla, registrar en el Field Journal y tomar medidas.',
     math:'Cómo se mide en el campo: pasos, palmos y cinta.',
     comunicacion:'Las casillas del Field Journal, dibujadas con regla antes de la salida.',
     social:'Reglas de convivencia para compartir y qué hacer en una situación de riesgo.',
     english:'I can see a wall. It is made of mud.',
     art:'Diseño del cuaderno de campo.',
     pe:'Ensayo del desplazamiento en grupo.',
     tutoria:'Qué hago si me pierdo del grupo.'},
  9:{social:'Viaje de estudios: qué construyeron, en qué trabajaban, cómo conseguían la comida.',
     science:'Qué animales y plantas había alrededor y cómo hacían tejidos con lo que tenían.',
     comunicacion:'Escribir en el momento lo que se ve y lo que se oye.',
     math:'Medir lo que se pueda: alto, ancho, número de escalones.',
     art:'Dibujo del natural en el sitio, aunque salga feo.',
     english:'It is bigger than my school. Who carried them?',
     pe:'Caminata del recorrido, con paradas.',
     tutoria:'Respetar un sitio que no es nuestro.'},
  10:{social:'Pasado y presente: qué ha cambiado y qué se ha quedado; instituciones que dan servicios hoy.',
      comunicacion:'Ordenar los hechos en secuencia y contarlos.',
      math:'Situar los hechos en la línea de tiempo con la escala correcta.',
      science:'Qué materiales de entonces siguen usándose.',
      english:'They lived here before us. We use the same land.',
      art:'La línea de tiempo ilustrada, de ellos a nosotros.',
      music:'Instrumentos de entonces y de ahora.',
      tutoria:'Qué heredamos sin haberlo pedido.'},
  11:{social:'Cuidar el patrimonio, proteger la naturaleza y valorar el trabajo de las personas.',
      comunicacion:'Redactar el compromiso de la clase con fecha y responsable.',
      math:'Cuántas veces al mes haremos la acción comprometida.',
      science:'Qué efecto real tendrá esa acción.',
      english:'We promise to… We will do it every Friday.',
      art:'El cartel del compromiso, firmado por todos.',
      tutoria:'Firmar solo lo que se puede cumplir.',
      pe:'La acción comprometida, si implica movimiento, se ensaya.'},
  12:{comunicacion:'Cada niño responde a la pregunta que hizo en la semana 7 con lo que dice su Field Journal.',
      science:'Distinguir lo que se observó de lo que se creía antes de ir.',
      social:'Puesta en común de los hallazgos del grupo.',
      math:'Comparar las medidas tomadas por los distintos equipos.',
      english:'Our question was… We saw that… Now we think…',
      art:'Exposición de los cuadernos de campo abiertos.',
      music:'Cierre del periodo.',
      tutoria:'Decir también lo que no se pudo averiguar.'}
},

/* ================================================== 2.o · T3 · P5+P6 ==== */
'g2.t3': {
  1:{science:'Fuentes de energía: el sol, el calor y el viento. Pregunta de investigación y predicción.',
     comunicacion:'Escribir la pregunta y la suposición antes de probar nada.',
     math:'Qué se va a medir y con qué unidad.',
     social:'De qué va el show y para quién es.',
     english:'What happens if…? I think the shadow will be bigger.',
     art:'Bocetos de los personajes del teatro de sombras.',
     music:'Elección de la música del show.',
     tutoria:'Trabajar para alguien más pequeño: qué cambia.'},
  2:{science:'Se cambia UNA cosa y se deja el resto igual: la prueba justa con la linterna.',
     math:'Medir la sombra en centímetros y anotar cada intento.',
     comunicacion:'Anotar qué se cambió y qué se dejó igual.',
     english:'I move the torch. The shadow is 20 cm.',
     art:'Construcción de los títeres planos.',
     social:'Repartir quién mueve la linterna y quién mide.',
     pe:'Control fino del movimiento: mover despacio y parar.',
     tutoria:'Respetar el turno de cada uno en la prueba.'},
  3:{science:'El efecto de la luz sobre el cuerpo y el ambiente: color, sombras e iluminación, con papeles de colores.',
     math:'Ordenar los materiales de más a menos transparentes.',
     comunicacion:'Nombrar lo observado con precisión: pasa, pasa un poco, no pasa.',
     art:'Filtros de color para el teatro.',
     english:'The light goes through the plastic. The book stops the light.',
     music:'Cómo cambia la escena con música distinta.',
     social:'Qué colores usa cada cultura para qué.',
     tutoria:'Probar sin adelantar la conclusión.'},
  4:{art:'Construcción del teatro de sombras y ensayo.',
     social:'Reparto de roles con la regla de equidad: quién narra y quién sostiene la linterna.',
     comunicacion:'El guion del show, en frases cortas.',
     science:'Ajustar la distancia de la linterna según lo aprendido.',
     math:'Medir el escenario y las distancias del montaje.',
     english:'Look at the wall! Now the shadow is very big.',
     music:'Ensayo de la música con la escena.',
     pe:'Colocación y movimiento en el escenario.'},
  5:{comunicacion:'Función para Nursery: narrar despacio y alto.',
     science:'Explicar por qué la sombra cambiaba de tamaño, con palabras que entienda un niño de cuatro años.',
     art:'La función completa.',
     music:'Música en directo del show.',
     english:'What can you see?',
     social:'Recibir y acompañar a los visitantes pequeños.',
     math:'Cuántos niños vinieron: conteo.',
     tutoria:'Cuidar a alguien más pequeño durante una hora.'},
  6:{science:'Arranca P6. Producción de movimiento: empujar y tirar, probado con lo que hay en la clase.',
     math:'Clasificar acciones en dos columnas y contar cuántas hay en cada una.',
     comunicacion:'Nombrar la acción con el verbo correcto.',
     english:'I push the door. I pull the rope.',
     pe:'Juegos de empujar y tirar por parejas, con seguridad.',
     art:'Fichas ilustradas de cada acción.',
     social:'Qué acciones de la casa son empujar y cuáles tirar.',
     tutoria:'Medir la fuerza con el compañero: ni poco ni demasiado.'},
  7:{science:'La misma cosa empujada fuerte y flojo; se mide cuánto llega.',
     math:'Suma hasta tres cifras para acumular las tiradas; comparar totales.',
     comunicacion:'Registrar en la tabla el tipo de empujón y la distancia.',
     english:'A soft push: 30 cm. A hard push: one metre.',
     pe:'Lanzamientos controlados: suave, medio y fuerte.',
     art:'Diseño de la hoja de registro.',
     social:'Turnos y honestidad al medir.',
     tutoria:'Anotar el resultado aunque no sea el que esperaba.'},
  8:{science:'Efecto de la superficie sobre el movimiento: la misma canica sobre cuatro superficies.',
     math:'Ordenar de más a menos y hacer el ranking.',
     comunicacion:'Explicar por qué una superficie frena más que otra.',
     english:'It goes further on the tiles. The carpet stops it.',
     art:'El ranking, en formato de podio.',
     pe:'Correr sobre superficies distintas y notar la diferencia.',
     social:'Qué superficies hay en el colegio y por qué son así.',
     tutoria:'Usar el mismo empujón para todos: la prueba justa.'},
  9:{science:'Gravedad y caída de los objetos: dos cosas distintas soltadas a la vez.',
     math:'Comparar predicción y resultado en una tabla de dos columnas.',
     comunicacion:'Escribir la predicción antes y el resultado después, sin borrar.',
     english:'I thought the big one would fall first. They fell together.',
     art:'Ilustración de la caída, cuadro a cuadro.',
     pe:'Juegos de recepción y caída controlada.',
     social:'Ponerse de acuerdo en qué se suelta y desde dónde.',
     tutoria:'Equivocarse en la predicción está bien.'},
  10:{art:'Construcción del juguete o la máquina, que tiene que moverse sin que nadie la toque.',
      science:'Qué fuerza la mueve y cómo se aprovecha.',
      math:'Medir cuánto se mueve y en cuánto tiempo.',
      comunicacion:'Instrucciones de uso en tres pasos.',
      english:'Pull this and it moves. It is made with a bottle.',
      pe:'Probar la máquina en el patio.',
      social:'Repartir el trabajo del montaje.',
      tutoria:'Dejar que otro pruebe mi máquina sin ayudarle.'},
  11:{comunicacion:'Segunda función para Nursery: explicar con palabras que entienda un niño de cuatro años.',
      science:'Qué empuja mi máquina y por qué se mueve.',
      art:'Puesto de la máquina y su cartel.',
      math:'Cuántas veces funcionó y cuántas no.',
      english:'Do you want to try? Push it here.',
      music:'Música del show final.',
      pe:'Organización del espacio de la función.',
      tutoria:'Dejar tocar y esperar sin impacientarse.'}
},
/* ================================================== 3.o · T1 · P1+P2 ==== */
'g3.t1': {
  1:{social:'Perú y su organización: regiones y distritos de Lima. Dónde está mi distrito.',
     science:'Se abre el proceso de indagación con una investigación de campo: qué sabe la gente de Nordic sobre el tema.',
     comunicacion:'Registrar lo averiguado con sus fuentes.',
     math:'Contar y comparar las respuestas de la investigación de campo.',
     english:'My district has… There are two parks.',
     art:'Mapa ilustrado del distrito.',
     pe:'Recorrido de reconocimiento del entorno del colegio.',
     tutoria:'Qué me gusta y qué cambiaría de donde vivo.'},
  2:{social:'Planos y croquis, autoridades municipales del distrito y el proceso electoral.',
     comunicacion:'Arranca "mi biografía": los primeros datos de mi vida.',
     math:'Leer un plano a escala sencilla y situar puntos.',
     science:'Qué problemas del distrito tienen causa observable.',
     english:'The mayor decides. Who decides here?',
     art:'Croquis del distrito con sus autoridades señaladas.',
     tutoria:'Quién decide en mi casa, en mi aula y en mi distrito.',
     pe:'Juegos de reglas acordadas y respetadas.'},
  3:{social:'Problemas locales de la comunidad y del colegio.',
     science:'Identificar problemas dentro del proceso de indagación; se elige el de la campaña.',
     comunicacion:'El árbol del problema, escrito: causas debajo y consecuencias arriba.',
     math:'Cuántos compañeros ven ese problema: primer sondeo.',
     english:'The problem is… It happens because…',
     art:'El árbol del problema, dibujado en grande.',
     tutoria:'Elegir un problema del que podamos ocuparnos de verdad.',
     pe:'Trabajo en equipo para el reparto de tareas.'},
  4:{math:'Encuesta con preguntas propias, tabla de frecuencias y conclusiones.',
     social:'Presupuesto de campaña: qué cuesta lo que proponemos.',
     english:'Entrevista a los profesores sobre hábitos saludables.',
     comunicacion:'Escribir las preguntas de la encuesta con opciones cerradas.',
     science:'Qué dato hace falta para sostener la propuesta.',
     art:'Diseño de la hoja de encuesta.',
     tutoria:'Preguntar a todos, no solo a mis amigos.',
     pe:'Organización del reparto de encuestas por zonas.'},
  5:{math:'Gráficos de barras a partir de la encuesta.',
     science:'El plan de solución se pone en práctica.',
     comunicacion:'Presentación de la autobiografía.',
     social:'La campaña en clase: mensaje y destinatario.',
     english:'Most people chose… 14 out of 30 students said…',
     art:'Cartel de campaña con el dato más alto.',
     music:'Lema cantado de la campaña.',
     tutoria:'Convencer con razones, no con ruido.'},
  6:{social:'Elecciones en clase y escucha de las opiniones de los compañeros.',
     comunicacion:'Redactar la propuesta elegida y publicarla.',
     math:'Contar los votos y representarlos.',
     science:'Qué se comprobará de la propuesta ganadora.',
     english:'Our class chose… It won with 18 votes.',
     art:'Publicación de la propuesta en el panel del aula.',
     tutoria:'Aceptar el resultado aunque no sea el mío.',
     pe:'Juego cooperativo de cierre de periodo.'},
  7:{social:'Arranca P2: necesidades y deseos, nociones de presupuesto.',
     science:'Dieta equilibrada, grupos de alimentos y la pirámide.',
     math:'Clasificar en dos columnas y poner precio a cada línea.',
     comunicacion:'Explicar por qué algo es necesidad y no deseo.',
     english:'We need a table. We want a nice sign.',
     art:'Fichas ilustradas de necesidades y deseos.',
     tutoria:'Distinguir lo que quiero de lo que necesito.',
     pe:'Alimentación y actividad física: qué necesita el cuerpo.'},
  8:{science:'Natural frente a procesado, perecedero y no perecedero, energético / constructor / protector.',
     english:'Idea principal de un texto informativo sobre el origen de los alimentos.',
     math:'Leer las cantidades de la etiqueta y compararlas entre productos.',
     comunicacion:'Resumir en una frase qué lleva de verdad el producto.',
     social:'Quién produce y quién vende lo que comemos.',
     art:'La etiqueta ampliada y señalada.',
     tutoria:'Mirar detrás del envase antes de elegir.',
     pe:'Qué come un cuerpo que se mueve.'},
  9:{social:'Plan de negocio del quiosco saludable: costos y recursos necesarios.',
     science:'Efectos de una mala alimentación y diseño del plan del snack.',
     math:'Costo, precio y cuántos hay que vender: el punto en que cuadra.',
     english:'Párrafo de opinión sobre el snack elegido.',
     comunicacion:'El plan de negocio escrito con sus apartados.',
     art:'Imagen y nombre del quiosco.',
     tutoria:'Repartir los roles del quiosco.',
     pe:'Higiene en la manipulación de alimentos.'},
  10:{social:'La venta en el recreo, con los roles repartidos.',
      science:'Se aplica la solución: la propuesta de lonchera.',
      math:'Registro de ventas: cuánto se vendió, qué sobró, cuánto se recaudó.',
      comunicacion:'Anotar lo que dice la gente que compra.',
      english:'How much is it? Here you are. Thank you!',
      art:'Montaje del quiosco.',
      tutoria:'Atender con amabilidad aunque haya cola.',
      pe:'Organización del espacio del recreo.'},
  11:{math:'Análisis de datos y gráficos de resultados.',
      social:'Presentación del plan de negocio con lo que de verdad pasó.',
      english:'Versión final del párrafo de opinión.',
      comunicacion:'Conclusión: qué cambiaríamos la próxima vez.',
      science:'Se comprueba si el snack cumplió lo que prometía.',
      art:'Panel final con los gráficos y las fotos del quiosco.',
      tutoria:'Contar también lo que salió mal.',
      music:'Cierre del trimestre.'}
},

/* ================================================== 3.o · T2 · P3+P4 ==== */
'g3.t2': {
  1:{social:'Las 24 regiones, los paisajes del Perú y los lugares turísticos. Se reparten las regiones por equipos.',
     science:'Las regiones naturales y sus recursos.',
     comunicacion:'La ficha de la región con sus apartados.',
     math:'Situar la región en el mapa con coordenadas sencillas.',
     english:'My region is in the north. The capital is…',
     art:'El mapa de la región, dibujado a mano.',
     tutoria:'Mi región me toca a mí: hacerla propia.',
     pe:'Juegos tradicionales de la región asignada.'},
  2:{social:'Años y décadas, antes y después de Cristo, descripción de hechos históricos.',
     english:'Secuencia de sucesos con pasado simple y conectores de tiempo.',
     math:'Situar los años en la recta y calcular cuánto tiempo pasó.',
     comunicacion:'Escribir cada hecho con su fecha en una frase.',
     science:'Desde cuándo ocurre el problema ambiental de la región.',
     art:'La línea de tiempo ilustrada.',
     tutoria:'Lo que pasa hoy empezó hace tiempo.',
     music:'Música de la región en distintas épocas.'},
  3:{science:'Recursos renovables y no renovables.',
     social:'Símbolos nacionales e historia de las banderas.',
     english:'Vocabulario de las actividades económicas del Perú.',
     math:'Clasificar los recursos y contar cuántos hay de cada tipo.',
     comunicacion:'Explicar por qué un recurso es renovable solo si se hace algo.',
     art:'Fichas de recursos con su símbolo.',
     tutoria:'Lo que se acaba y lo que vuelve.',
     pe:'Juego de reparto de recursos limitados.'},
  4:{social:'Principales actividades económicas y presupuesto a escala nacional.',
     science:'Proceso de producción y transformación de los recursos: minería, pesca, agricultura, textil.',
     math:'La cadena de producción con sus cantidades y costos.',
     comunicacion:'Describir la cadena paso a paso.',
     english:'First they cut the wood. Then it travels to Lima.',
     art:'Infografía de la cadena de producción.',
     tutoria:'Quién trabaja en cada paso.',
     pe:'Circuito de la cadena de producción.'},
  5:{social:'Problemas ambientales por región y estrategias para reducir la contaminación.',
     english:'Párrafos de problema y solución con can y should.',
     science:'Qué evidencia hay del problema en la región.',
     math:'Comparar cifras del problema entre dos regiones.',
     comunicacion:'El párrafo de problema y solución en castellano.',
     art:'Cartel de la estrategia propuesta.',
     tutoria:'Proponer algo que se pueda hacer de verdad.',
     music:'Canción de concienciación de la región.'},
  6:{social:'Cierre de P3: proyecto de investigación por grupos con gráficos, línea de tiempo y actividad económica.',
     comunicacion:'Presentación oral con apoyo visual.',
     math:'Los gráficos del expediente, terminados.',
     science:'Explicación del recurso y su problema.',
     english:'My region produces… The problem is…',
     art:'Montaje del expediente de la región.',
     tutoria:'Hablar del trabajo del equipo, no solo del mío.',
     music:'Apertura musical de las presentaciones.'},
  7:{science:'Arranca P4: ecosistemas con foco en el bosque, componentes vivos y no vivos, clasificación animal y hábitats.',
     social:'Reglas del viaje y preguntas de investigación.',
     comunicacion:'Escribir las preguntas de la entrevista antes de salir.',
     math:'Qué se va a medir en el viaje y con qué.',
     english:'How long have you worked here? What has changed?',
     art:'Portada del cuaderno de campo.',
     tutoria:'Normas de la salida, acordadas.',
     pe:'Preparación de la caminata.'},
  8:{social:'Viaje de estudios: turismo responsable y límites personales en espacios públicos.',
     science:'Cuaderno de campo: qué se ve, qué se oye, qué se recoge.',
     comunicacion:'Escribir en el sitio, no de memoria.',
     math:'Medidas tomadas en el campo.',
     art:'Dibujo del natural en el ecosistema.',
     english:'I saw… She told me that…',
     pe:'Caminata y cuidado del grupo.',
     tutoria:'Dejar el sitio como lo encontramos.'},
  9:{science:'Cadenas alimentarias, impacto humano en los ecosistemas y estrategias de conservación.',
     english:'Sentimientos y motivos del personaje y formación de preguntas.',
     comunicacion:'Explicar la cadena con conectores de causa.',
     math:'Contar individuos por especie y comparar.',
     social:'Qué hace la gente del lugar y cómo afecta al ecosistema.',
     art:'La red alimentaria dibujada con flechas.',
     tutoria:'Nuestro impacto también cuenta.',
     pe:'Juego de la cadena alimentaria.'},
  10:{science:'Desastres naturales que afectan a los ecosistemas.',
      social:'Comparación bosque / selva / otros paisajes peruanos.',
      math:'Pictogramas y gráficos de comparación.',
      comunicacion:'El cuadro comparativo escrito.',
      english:'There were more trees before. It went down by half.',
      art:'Los pictogramas, dibujados.',
      tutoria:'Qué se pierde cuando se rompe un ecosistema.',
      pe:'Simulacro relacionado con el desastre estudiado.'},
  11:{science:'Diseño de la propuesta de conservación.',
      math:'Plano cartesiano, perímetro y patrones para levantar la maqueta.',
      art:'Construcción de la maqueta del hábitat.',
      comunicacion:'Las etiquetas de la maqueta.',
      social:'A quién va dirigida la propuesta.',
      english:'This part is polluted. These animals live here.',
      tutoria:'Repartir la construcción entre todos.',
      pe:'Transporte y montaje de la maqueta.'},
  12:{comunicacion:'Ensayo oral y defensa de la propuesta en asamblea.',
      social:'Responsabilidad cívica: la clase discute cada propuesta y decide cuál sostiene.',
      science:'Responder a las objeciones con datos del cuaderno de campo.',
      math:'Explicar los gráficos ante la asamblea.',
      english:'I propose that… The evidence is…',
      art:'Exposición de las maquetas.',
      tutoria:'Escuchar la propuesta del otro antes de defender la mía.',
      music:'Cierre de la asamblea.'}
},

/* ================================================== 3.o · T3 · P5+P6 ==== */
'g3.t3': {
  1:{science:'Elementos del sistema solar, el sol en el centro, planetas y planetas enanos.',
     english:'Texto informativo sobre los planetas; vocabulario de órbita, gravedad y rotación.',
     math:'Ordenar los planetas por distancia y por tamaño.',
     comunicacion:'La ficha de mi planeta con tres datos verificados.',
     social:'Quién descubrió qué y cuándo.',
     art:'El mapa del sistema solar a escala aproximada.',
     tutoria:'Lo que no se ve también se puede estudiar.',
     pe:'Juego de órbitas en el patio.'},
  2:{science:'Rotación y traslación de la Tierra.',
     social:'El reloj de sol y el repaso de la hora.',
     english:'Presente simple frente a continuo para describir el experimento.',
     math:'Las horas del día y las estaciones en el calendario.',
     comunicacion:'Explicar el experimento por escrito, paso a paso.',
     art:'Construcción del reloj de sol.',
     tutoria:'Lo que parece obvio y no lo es.',
     pe:'Juego de sombras a distintas horas.'},
  3:{science:'Fases de la luna y mareas.',
     english:'Futuro con will para hacer predicciones: qué fase habrá dentro de dos semanas.',
     math:'El ciclo lunar en el calendario: contar días entre fases.',
     comunicacion:'Escribir la predicción con su razón.',
     social:'Qué culturas se guiaban por la luna.',
     art:'El calendario lunar ilustrado.',
     tutoria:'Escribir la predicción antes de mirar.',
     music:'Canciones sobre la luna.'},
  4:{science:'Misiones espaciales y concepto básico de gravedad.',
     social:'Profesiones ligadas a la exploración espacial y presupuesto de una misión.',
     math:'El presupuesto de la misión: sumar, comparar y decidir qué se deja fuera.',
     comunicacion:'Justificar por escrito qué se deja fuera y por qué.',
     english:'The rocket costs the most. We cannot take everything.',
     art:'Diseño de la misión y su emblema.',
     tutoria:'Elegir cuando no alcanza para todo.',
     pe:'Pruebas de resistencia como las de un astronauta.'},
  5:{science:'Diseño del experimento o modelo, recogida de datos y exhibición.',
     math:'La escala del modelo: cuánto representa un centímetro.',
     comunicacion:'Explicar el modelo a los visitantes.',
     art:'Construcción y montaje del modelo.',
     english:'This planet is bigger than Earth. This is our scale.',
     social:'Organización de la exhibición y reparto de turnos.',
     tutoria:'Decir la escala en voz alta: sin ella el modelo engaña.',
     music:'Ambientación sonora de la exhibición.'},
  6:{comunicacion:'Arranca P6: lectura de no ficción narrativa sobre un niño que alcanza una meta.',
     tutoria:'Crecimiento y metas personales; fortalezas y aspectos a mejorar. Se elige EL hábito.',
     science:'Qué hábito se puede medir y cómo.',
     math:'Qué unidad usar para medirlo: minutos, veces, vasos.',
     english:'I want to read more. I will count the minutes.',
     social:'Qué hábitos valora mi comunidad.',
     art:'La ficha del hábito elegido.',
     pe:'Hábitos de movimiento: cuáles se pueden medir.'},
  7:{math:'Registro diario del hábito: la misma tabla del modelo, con otro dato dentro.',
     comunicacion:'Párrafo de reflexión de la semana.',
     science:'Anotar también los días en que no se hizo nada.',
     tutoria:'Sostener un registro siete días.',
     english:'Monday: 10 minutes. I forgot on Wednesday.',
     social:'Comparar mi registro con el de un compañero, sin competir.',
     art:'Diseño de la hoja de registro.',
     pe:'Registro del movimiento diario.'},
  8:{math:'Qué dicen los siete números juntos: media informal, día mejor y día peor.',
     tutoria:'Diseño del plan de rutina saludable a partir del registro.',
     social:'Derechos y responsabilidades, autonomía y la importancia de saber decir que no.',
     english:'Futuro con will y going to para el plan.',
     comunicacion:'Escribir el plan con horario y obstáculos.',
     science:'Qué condiciones hacen que el hábito funcione.',
     art:'El plan en formato visual.',
     pe:'La parte física del plan.'},
  9:{social:'Presupuesto básico del proyecto personal y toma de decisiones.',
     comunicacion:'Escritura de opinión: por qué mi meta importa.',
     math:'Qué recursos necesito y cuánto cuestan.',
     english:'In my opinion… The first reason is…',
     science:'Qué evidencia tengo de que el plan sirve.',
     tutoria:'Pedir ayuda para lo que no puedo solo.',
     art:'Boceto del póster de la rutina.',
     pe:'Ajuste del plan a lo que el cuerpo aguanta.'},
  10:{comunicacion:'Línea de tiempo de crecimiento personal, texto de reflexión final y presentación oral de dos o tres minutos.',
      art:'Mini póster de la rutina saludable.',
      math:'Los datos de la semana, presentados.',
      english:'I measured my reading for a week. My advice is…',
      tutoria:'Ensayo de la charla ante un compañero.',
      social:'Qué aporta mi meta a los demás.',
      science:'Explicar el método del registro.',
      music:'Ensayo del cierre de año.'},
  11:{tutoria:'Última semana: todos los pósters y todas las metas se cuelgan juntos y cada niño lee la meta de otro y le escribe una línea.',
      comunicacion:'Escribir el mensaje para el compañero.',
      art:'Montaje del muro de las metas.',
      social:'Cierre del año: qué nos llevamos.',
      math:'Fecha de revisión de cada meta, en el calendario.',
      english:'My goal: read 15 minutes a day. We check on the 30th.',
      music:'Cierre musical del año.',
      pe:'Juego final de curso.'}
},
/* ================================================== 4.o · T1 · P1+P2 ==== */
'g4.t1': {
  1:{science:'Seres vivos y no vivos: qué tiene que hacer algo para considerarse vivo.',
     social:'Democracia y participación ciudadana: cómo se decide en un grupo.',
     comunicacion:'El punto y la coma en la clasificación escrita.',
     math:'Clasificar y contar los casos de cada columna.',
     english:'It is alive because it grows and feeds.',
     art:'Fichas de los casos difíciles: fuego, semilla, virus.',
     tutoria:'Ponerse de acuerdo en un criterio antes de discutir.',
     pe:'El cuerpo en movimiento: señales de que está vivo.'},
  2:{science:'Nutrición, metabolismo y excreción: las tres funciones que mantienen el cuerpo en marcha.',
     social:'Reglas, acuerdos y convivencia democrática; se compara con las funciones del cuerpo.',
     comunicacion:'El diagrama del sistema, etiquetado y explicado.',
     math:'Cuánto entra y cuánto sale: proporciones sencillas.',
     english:'The food enters through the mouth. The stomach breaks it down.',
     art:'El diagrama del sistema, dibujado en grande.',
     tutoria:'Qué pasa cuando una parte del grupo no cumple su función.',
     pe:'Frecuencia cardíaca antes y después del ejercicio.'},
  3:{science:'Sensibilidad y homeostasis: cómo el cuerpo detecta y se autorregula.',
     math:'Se abre la encuesta: preguntas abiertas y cerradas.',
     social:'Escuchar la opinión de los compañeros.',
     comunicacion:'Redactar preguntas que se puedan contar.',
     english:'How many hours do you sleep? Do you eat breakfast?',
     art:'Diseño de la hoja de encuesta.',
     tutoria:'Preguntar sobre hábitos sin juzgar a nadie.',
     pe:'Reacción y equilibrio: el cuerpo que se autorregula.'},
  4:{science:'Crecimiento y reproducción como funciones de los seres vivos.',
     math:'Se pasa la encuesta y se recogen las respuestas.',
     social:'Participación en asambleas.',
     comunicacion:'Conectores narrativos para contar la anécdota.',
     english:'I asked 30 students. Twelve chose option b.',
     art:'Registro visual de las respuestas.',
     tutoria:'Guardar la respuesta de otro con discreción.',
     pe:'Crecimiento y actividad física.'},
  5:{science:'Herencia: qué se transmite y qué no.',
     math:'Tabular con el modelo de barras parte-todo.',
     comunicacion:'Técnicas de expresión oral para la presentación.',
     social:'Qué se hereda además de los rasgos: costumbres y hábitos.',
     english:'Most students sleep less than 7 hours.',
     art:'El gráfico de la encuesta, terminado.',
     tutoria:'Lo que traigo de casa y lo que elijo yo.',
     pe:'Hábitos de descanso y rendimiento.'},
  6:{science:'Reflexión de cierre de P1: qué dice la encuesta.',
     social:'Participación, compromiso y reflexión democrática; se elige el hábito del acuerdo.',
     comunicacion:'Escritura de la anécdota personal sobre ese hábito.',
     math:'La conclusión de la encuesta en una frase con cifra.',
     english:'Last month I… I felt tired all day.',
     art:'Ilustración de la anécdota.',
     tutoria:'Contar algo propio sin exponer a nadie más.',
     pe:'El hábito elegido, si es de movimiento, se prueba.'},
  7:{science:'Arranca P2. Sistema nervioso: el sistema que coordina a los demás.',
     english:'Texto narrativo.',
     comunicacion:'Explicar el recorrido de una señal, paso a paso.',
     math:'Tiempos de reacción medidos en la clase.',
     social:'Quién coordina en un grupo y cómo.',
     art:'El mapa de la coordinación, con flechas.',
     tutoria:'Actuar antes de pensar: cuándo pasa y qué hacer.',
     pe:'Pruebas de reacción y coordinación.'},
  8:{science:'Sistema inmunológico: cómo se defiende el cuerpo y qué pasa cuando falla.',
     comunicacion:'Adjetivo y grados del adjetivo para describir con precisión.',
     social:'Salud pública: qué protege a todos y no solo a uno.',
     math:'Comparar datos de vacunación o de faltas por enfermedad.',
     english:'The skin is the first barrier. White blood cells fight germs.',
     art:'Ficha de defensas del cuerpo.',
     tutoria:'Lavarse las manos y dormir: lo que depende de mí.',
     pe:'Descanso, higiene y defensa del cuerpo.'},
  9:{science:'Sistema urinario y su papel en la excreción; se cierra el mapa de los tres sistemas.',
     comunicacion:'Explicar por escrito cómo depende un sistema de otro.',
     math:'Cuánta agua bebemos y cuánta necesitamos: cálculo.',
     social:'Qué servicios del colegio sostienen la salud.',
     english:'The blood carries the nutrients. The kidneys filter the blood.',
     art:'Los tres sistemas conectados en un solo dibujo.',
     tutoria:'Beber agua: el hábito más fácil de cumplir.',
     pe:'Hidratación antes, durante y después.'},
  10:{social:'Hábitos saludables. Cada equipo redacta su propuesta de acuerdo: qué se compromete a hacer la clase, quién lo comprueba y cada cuánto.',
      comunicacion:'Redacción del acuerdo con sus apartados.',
      math:'El dato de la encuesta que entra en la propuesta.',
      science:'Qué efecto tendría el hábito propuesto.',
      english:'I propose that we… Our survey shows that…',
      art:'Cartel del acuerdo para el aula.',
      tutoria:'Comprometerse solo a lo que se puede cumplir.',
      pe:'La parte física del acuerdo.'},
  11:{social:'Asamblea: se presentan las propuestas con el gráfico delante, se debate y se vota una.',
      comunicacion:'Defensa oral de la propuesta y firma del acuerdo.',
      math:'Recuento de votos y presentación del gráfico.',
      science:'Cómo se comprobará que el acuerdo funciona.',
      english:'We, class 4A, agree to… We will review it on…',
      art:'El acuerdo firmado, colgado con su fecha de revisión.',
      tutoria:'Cumplir lo que se firma.',
      music:'Cierre del periodo.'}
},

/* ================================================== 4.o · T2 · P3+P4 ==== */
'g4.t2': {
  1:{social:'La situación del Mundial: identidad, identidad cultural y símbolos peruanos.',
     comunicacion:'Argumentar por escrito qué me llevaría del Perú y por qué no otra cosa.',
     art:'El cartel de lo que me llevaría.',
     math:'Cuántos compañeros eligieron lo mismo: conteo y comparación.',
     english:'I would take… It shows that Peruvians…',
     science:'De qué está hecho lo que elegí: materiales y origen.',
     music:'La música que representaría al Perú fuera.',
     tutoria:'Representar a todos, no solo a los míos.'},
  2:{social:'Diversidad cultural de las tres regiones: tradiciones, vestimenta, danzas y expresiones.',
     comunicacion:'La ficha de región con las mismas casillas para las tres.',
     art:'Vestimenta y símbolos de cada región, ilustrados.',
     math:'Distancias y tamaños de las tres regiones.',
     english:'The coast is dry and narrow. It produces grapes.',
     science:'Qué condiciona el clima de cada región.',
     music:'Una danza o pieza de cada región.',
     pe:'Danzas de las tres regiones.'},
  3:{science:'Los ecosistemas del Perú: debajo de cada conjunto de tradiciones hay un sitio que las hizo posibles.',
     social:'Qué actividad económica permite cada ecosistema.',
     math:'Situar los ecosistemas en el mapa y medir distancias.',
     comunicacion:'Explicar la relación entre ecosistema y tradición.',
     english:'The desert depends on the rivers.',
     art:'El mapa de ecosistemas, coloreado y con leyenda.',
     tutoria:'Lo que somos también depende de dónde vivimos.',
     pe:'Actividades físicas propias de cada ecosistema.'},
  4:{social:'Cómo se representan los países internacionalmente; cómo podrían hacerlo los hinchas peruanos fuera.',
     comunicacion:'Analizar qué muestra y qué esconde cada campaña.',
     english:'This campaign shows only beaches. The slogan says…',
     art:'Mural con los ejemplos recogidos.',
     math:'Cuántas campañas muestran cada cosa: recuento.',
     science:'Qué imagen del país es cierta y cuál no.',
     tutoria:'Qué imagen daríamos nosotros.',
     music:'La música de cada campaña.'},
  5:{art:'Creación de la propuesta: pósters, atuendos, cánticos o presentaciones culturales.',
     social:'Acuerdos para que se respete cada expresión cultural que se comparte.',
     comunicacion:'El texto que acompaña la propuesta.',
     math:'Medidas y proporciones del material de la propuesta.',
     english:'Our campaign is for… Our slogan is…',
     music:'Composición del cántico.',
     science:'Materiales sostenibles para el atuendo o el póster.',
     pe:'Ensayo de la parte física de la presentación.'},
  6:{comunicacion:'Presentaciones orales de las propuestas.',
     social:'Reflexión final sobre identidad, pertenencia y respeto a la diversidad.',
     art:'Exposición de las propuestas.',
     english:'Our proposal is… We chose it because…',
     music:'Actuación de las propuestas.',
     math:'Votación y recuento de la propuesta preferida.',
     tutoria:'Escuchar la propuesta de otro equipo con respeto.',
     pe:'Presentación con movimiento.'},
  7:{social:'Arranca P4. Ica: ubicación, recursos y actividades económicas.',
     english:'Textos instructivos: qué llevar, cómo viajar con responsabilidad.',
     comunicacion:'El texto instructivo en castellano, en imperativo y numerado.',
     math:'Cuánto se tarda, cuánto cuesta y a qué hora se sale.',
     science:'Qué clima vamos a encontrar y qué implica.',
     art:'Portada del cuaderno de viaje.',
     tutoria:'Para muchos es su primer viaje sin la familia.',
     pe:'Preparación física del viaje.'},
  8:{social:'Actividades productivas y extractivas en Ica: cómo vive de lo que tiene una región desértica.',
     science:'Se prepara la observación de campo: qué mirar y cómo registrarlo.',
     math:'La tabla de observación con sus columnas y unidades.',
     comunicacion:'Las preguntas para la gente del lugar.',
     english:'I will observe… I will note the time.',
     art:'Diseño de la ficha de observación.',
     tutoria:'Preguntar con respeto a quien trabaja.',
     pe:'Caminata de preparación.'},
  9:{social:'Viaje de estudios: sitios históricos, zonas productivas y ambientes naturales.',
     science:'Investigación y observación de campo: notas, preguntas y evidencias recogidas en el sitio.',
     comunicacion:'Escribir en el sitio, con las palabras de quien habla.',
     math:'Medidas y conteos tomados en Ica.',
     english:'There were grapes everywhere. He told me the well is deeper now.',
     art:'Dibujo del natural en Ica.',
     pe:'Recorrido y cuidado del grupo.',
     tutoria:'Dejar el sitio como lo encontramos.'},
  10:{social:'Actividades económicas y uso de los recursos; sostenibilidad y retos ambientales.',
      science:'Por qué el uso responsable del agua es la condición de todo lo demás.',
      math:'Cuánta agua usa cada actividad: comparación de cantidades.',
      comunicacion:'El texto informativo sobre el agua, sin opinión.',
      english:'The water comes from underground. Agriculture uses most of it.',
      art:'Infografía del ciclo del agua en Ica.',
      tutoria:'Lo que se agota no vuelve solo.',
      pe:'Hidratación en clima seco.'},
  11:{social:'Diseño de una comunidad sostenible inspirada en Ica.',
      science:'De dónde sale el agua, la energía y adónde van los residuos.',
      math:'Plano de la comunidad con medidas y escala.',
      comunicacion:'La memoria del diseño, escrita.',
      english:'The water is recycled here. The energy comes from the sun.',
      art:'La maqueta o el plano de la comunidad.',
      tutoria:'Diseñar para todos, no solo para nosotros.',
      pe:'Cómo se mueve la gente en esa comunidad.'},
  12:{comunicacion:'Se arma la guía: textos instructivos, informativos y de opinión.',
      social:'A quién se entrega la guía y para qué sirve.',
      english:'It takes four hours by coach. Take a hat and water.',
      art:'Maquetación e ilustración de la guía.',
      math:'Los datos de la guía, comprobados.',
      science:'La sección de qué mirar que nadie mira.',
      tutoria:'Escribir para quien viene después.',
      music:'Cierre del periodo.'}
},

/* ================================================== 4.o · T3 · P5+P6 ==== */
'g4.t3': {
  1:{science:'Fuerzas: qué hace que algo se mueva, se pare o cambie de forma.',
     social:'El problema: el colegio no sabe qué tiempo hace, solo lo que siente.',
     comunicacion:'Plantear el problema por escrito en una frase.',
     math:'Qué se puede medir y con qué unidad.',
     english:'We want to measure the rain. Nobody knows how much it rains here.',
     art:'Bocetos de posibles instrumentos.',
     tutoria:'Elegir un problema que podamos resolver.',
     pe:'Fuerzas en el propio cuerpo al empujar y frenar.'},
  2:{science:'Tipos de fuerza: cuál mueve el aire, cuál mueve el agua.',
     math:'Decimales: leer, escribir y expresar hasta tres cifras decimales.',
     comunicacion:'Nombrar cada fuerza con precisión.',
     english:'Gravity pulls things down. The wind pushes the flag.',
     art:'El mapa de fuerzas, ilustrado.',
     social:'Qué fuerzas de la naturaleza afectan a nuestra zona.',
     tutoria:'Lo que no se ve también actúa.',
     pe:'Empuje, tracción y rozamiento en juegos.'},
  3:{science:'Cada equipo elige qué va a medir: lluvia, viento, temperatura o humedad.',
     math:'Comparar y ordenar decimales para fijar la escala del instrumento.',
     comunicacion:'Justificar por escrito por qué ese instrumento y no otro.',
     english:'We chose a bottle because it is straight.',
     art:'El plano del instrumento con sus medidas.',
     social:'Reparto de instrumentos entre equipos para cubrir todo.',
     tutoria:'Aceptar el instrumento que le toca al equipo.',
     pe:'Manipulación fina en la construcción.'},
  4:{science:'Energía y sus formas. Construcción del instrumento.',
     math:'Suma y resta de decimales para calibrarlo contra una medida conocida.',
     art:'Construcción y acabado del instrumento.',
     comunicacion:'Instrucciones de uso del instrumento.',
     english:'It is 20 cm tall. We will make the base wider.',
     social:'Dónde se instala y quién lo cuida.',
     tutoria:'La versión 1 sale mal: por eso se llama versión 1.',
     pe:'Montaje del instrumento en el patio.'},
  5:{science:'Prueba y ajuste: dos instrumentos midiendo lo mismo tienen que dar lo mismo.',
     math:'Multiplicación y división de decimales para convertir la lectura.',
     comunicacion:'Registrar el error encontrado y la corrección.',
     english:'We poured exactly 50 ml. Our scale said 45.',
     art:'Escala definitiva, marcada y legible.',
     social:'Acuerdo sobre quién mide cada día.',
     tutoria:'Reconocer el error del propio instrumento.',
     pe:'Rutina diaria de la medición.'},
  6:{science:'Arranca P6. Recursos naturales: de dónde sale el agua que usamos. Empieza el registro diario.',
     math:'La tabla de registro con fecha, hora y unidad.',
     comunicacion:'Anotar también el estado del cielo, en palabras.',
     social:'De dónde viene el agua del colegio.',
     english:'Monday, 8 a.m.: 3 mm. It was cloudy.',
     art:'Panel del registro para la pared.',
     tutoria:'Medir todos los días a la misma hora.',
     pe:'Turnos de medición en el patio.'},
  7:{science:'Ciclo del agua, ahora con el propio registro delante.',
     math:'Ángulos y figuras 2D para el plano de la estación.',
     comunicacion:'Explicar el ciclo con los datos propios dentro.',
     english:'We measured 3 mm of precipitation.',
     art:'El ciclo del agua con nuestros números encima.',
     social:'Qué pasa con el agua después de usarla.',
     tutoria:'Un dato propio vale más que uno copiado.',
     pe:'Actividad al aire libre según el tiempo.'},
  8:{science:'Clima y tiempo: la diferencia entre lo que se espera y lo que se mide.',
     math:'Área y perímetro de la estación.',
     comunicacion:'Clasificar frases en clima o tiempo y justificar.',
     english:'It is raining today — weather. Lima is dry all year — climate.',
     social:'Qué clima tiene nuestra zona y cómo condiciona la vida.',
     art:'Panel de clima frente a tiempo.',
     tutoria:'No confundir un día con una costumbre.',
     pe:'Cómo cambia la clase de PE según el tiempo.'},
  9:{science:'Instrumentos de medida: se comparan los del colegio con los profesionales.',
     math:'Qué error tiene el nuestro y cuánto importa.',
     comunicacion:'Redactar la estimación del error.',
     english:'We measured 22 degrees. The official was 24.',
     social:'Quién publica el tiempo oficial y de dónde saca los datos.',
     art:'Gráfico de la diferencia entre las dos medidas.',
     tutoria:'Decir el margen de error no es debilidad.',
     pe:'Medición en distintas zonas del colegio.'},
  10:{math:'Probabilidad como fracción y como porcentaje, aplicada al propio registro.',
      science:'Se publica el pronóstico antes de que pase.',
      comunicacion:'El texto del pronóstico, claro y con fecha.',
      english:'We predict rain on Thursday. The pressure is falling.',
      art:'El cartel del pronóstico en el pasillo.',
      social:'A quién le sirve nuestro pronóstico.',
      tutoria:'Arriesgarse a decir algo antes de saberlo.',
      pe:'Planificar la actividad según el pronóstico.'},
  11:{science:'Contraste del pronóstico con lo que pasó.',
      math:'Las cuatro operaciones para cerrar el balance.',
      comunicacion:'La oración, sujeto y predicado, para redactar el informe final.',
      english:'We forecast rain and it did not rain. Next time we would…',
      art:'Presentación del informe y del panel de datos.',
      social:'Entrega del informe a quien pueda usarlo.',
      tutoria:'Explicar por qué fallamos vale más que acertar.',
      music:'Cierre del año.'}
},

/* ================================================== 5.o · T1 · P1+P2 ==== */
'g5.t1': {
  1:{science:'Partículas pequeñas, átomos y partículas subatómicas.',
     social:'Los acuerdos de aula: las reglas de este territorio.',
     comunicacion:'Arranca el taller de escritura: se elige el cuaderno y el formato.',
     math:'Órdenes de magnitud: de lo grande a lo muy pequeño.',
     english:'In a solid the particles are close together.',
     art:'El modelo de partículas, dibujado en los tres estados.',
     tutoria:'Qué territorio queremos que sea esta aula.',
     pe:'Ocupación del espacio: partículas en movimiento.'},
  2:{science:'Pregunta de investigación, variables dependiente e independiente y formulación de hipótesis.',
     comunicacion:'Escribir la hipótesis en forma "si… entonces…".',
     math:'Qué se mide y en qué unidad.',
     social:'Qué preguntas del territorio se pueden investigar.',
     english:'If I heat the water, then the sugar will dissolve faster.',
     art:'Ficha de la hipótesis.',
     tutoria:'Una hipótesis puede fallar y sigue valiendo.',
     pe:'Variables en el rendimiento físico.'},
  3:{science:'Cambios físicos: tipos de mezcla, estados de la materia, fuerzas de repulsión y cohesión.',
     comunicacion:'El cuento urbano realista: primeras escenas.',
     social:'Autorregulación: qué hago cuando algo no sale.',
     math:'Proporciones de la mezcla y su registro.',
     english:'I mixed sand and water. Nothing new appeared.',
     art:'Registro visual del experimento.',
     tutoria:'Trabajar con material que se puede estropear.',
     pe:'Mezcla y separación: juegos de agrupación.'},
  4:{science:'Cómo se separa lo que hemos mezclado: métodos y la propiedad que usa cada uno.',
     social:'Reglas de nuestra comunidad, igualdad y respeto.',
     math:'Medir cuánto se recupera de cada componente.',
     comunicacion:'El procedimiento escrito paso a paso.',
     english:'I used filtering because the sand does not dissolve.',
     art:'Esquema del montaje de separación.',
     tutoria:'Repartir el trabajo del laboratorio.',
     pe:'Precisión y cuidado en el manejo de material.'},
  5:{science:'Cambios químicos: reacciones reversibles e irreversibles.',
     social:'Conflictos en el territorio: qué se puede deshacer y qué no.',
     comunicacion:'Avance del cuento: el conflicto de la historia.',
     math:'Contar y clasificar los cambios observados.',
     english:'Melting ice is reversible. Burning paper is not.',
     art:'Panel de reversible / no reversible con evidencias.',
     tutoria:'Lo que se dice no se puede deshacer.',
     pe:'Cambios en el cuerpo tras el esfuerzo: cuáles vuelven.'},
  6:{social:'"Territorial issues": los problemas del territorio.',
     comunicacion:'Análisis crítico del género preferido; cada alumno fija el género de su cuento.',
     science:'Qué problema del territorio se va a investigar.',
     math:'Qué dato haría falta para demostrarlo.',
     english:'I will write a report because my reader is…',
     art:'Portada del expediente del territorio.',
     tutoria:'Elegir género y sostener la elección.',
     music:'Ambiente sonoro del cuento.'},
  7:{science:'Arranca P2. Reinos de los seres vivos: quién más vive en este territorio.',
     english:'Empieza el libro "The lost city".',
     comunicacion:'Descripción de un ser vivo del territorio.',
     math:'Clasificar y contar por reino.',
     social:'Qué seres vivos comparten el colegio con nosotros.',
     art:'Láminas de los cinco reinos.',
     tutoria:'Mirar lo que siempre estuvo ahí.',
     pe:'Observación del entorno del colegio.'},
  8:{science:'Impacto humano: problemas ambientales, gestión de residuos, vertederos y reciclaje. Se pesa o se cuenta lo que el colegio tira en un día.',
     math:'Categorías del conteo, cerradas antes de empezar.',
     comunicacion:'Registrar el dato con su hora y su lugar.',
     social:'Quién se lleva la basura del colegio y adónde va.',
     english:'We counted plastic, paper and food.',
     art:'Panel del primer día de conteo.',
     tutoria:'Contar lo que tiramos sin señalar a nadie.',
     pe:'Recogida y transporte del material del conteo.'},
  9:{science:'Contaminación, deforestación, pérdida de hábitat y depredación. Sigue el conteo.',
     math:'Problemas de varios pasos y ecuaciones de una variable.',
     comunicacion:'Explicar el día raro del registro.',
     social:'Qué decisiones del colegio explican los picos.',
     english:'On Friday there was much more plastic.',
     art:'Registro semanal ilustrado.',
     tutoria:'Sostener el conteo cinco días.',
     pe:'Trabajo de campo diario.'},
  10:{math:'Recolección de datos con preguntas abiertas y cerradas; gráficos de barras, de líneas y de puntos. ¿Cuál dice la verdad sobre nuestro dato?',
      comunicacion:'Justificar por escrito la elección del gráfico.',
      science:'Qué muestra el gráfico que no mostraba la tabla.',
      english:'Avance del libro y vocabulario del expediente.',
      social:'A quién se le presenta el dato.',
      art:'El gráfico definitivo, en limpio.',
      tutoria:'Elegir el gráfico honesto, no el bonito.',
      music:'Cierre sonoro del expediente.'},
  11:{science:'Conclusión de la investigación contrastada con la hipótesis.',
      comunicacion:'Versión final del cuento de 200 a 250 palabras.',
      math:'Los datos y el gráfico, incorporados al expediente.',
      social:'Qué propone el expediente al colegio.',
      english:'The data shows that… We propose…',
      art:'Montaje del Expediente del Territorio.',
      tutoria:'Entregar las dos cosas juntas: son el mismo territorio.',
      music:'Cierre del trimestre.'}
},

/* ============================================== 5.o · P4+P5 · Cajamarca == */
'g5.p4p5': {
  1:{science:'Preparación científica: el estudiante aprende a observar científicamente.',
     comunicacion:'El cuaderno del investigador: qué se anota y cómo.',
     math:'Qué se puede medir en el campo y con qué instrumento.',
     social:'Adónde vamos y qué se sabe ya de ese sitio.',
     english:'I am interested in… I have noticed that…',
     art:'Portada e índice del cuaderno de campo.',
     tutoria:'Ser investigador: qué cambia en cómo miro.',
     pe:'Preparación física del viaje.'},
  2:{science:'Preparación del viaje: el estudiante define qué observará y por qué.',
     math:'La tabla de registro, dibujada antes de salir.',
     comunicacion:'Escribir el plan de observación.',
     social:'Normas del viaje y responsabilidades.',
     english:'I will observe for 20 minutes. I will use a hand lens.',
     art:'Diseño de la ficha de observación.',
     tutoria:'Lo que no decidas mirar, no lo vas a ver.',
     pe:'Marcha y resistencia para la salida.'},
  3:{science:'Viaje a Cajamarca: el estudiante recolecta evidencias durante el viaje.',
     comunicacion:'Escribir en el sitio, con fecha y condiciones.',
     math:'Medidas y conteos en el campo.',
     social:'Observación del entorno humano y productivo.',
     english:'Date: 12 June. Sunny, 22 °C. I observed 14 insects.',
     art:'Dibujo del natural, aunque salga imperfecto.',
     pe:'Recorrido y cuidado del grupo.',
     tutoria:'Respetar el lugar y a quien vive en él.'},
  4:{science:'Análisis de evidencias: el estudiante identifica relaciones y patrones.',
     math:'Organizar los datos y buscar el patrón.',
     comunicacion:'El mapa de evidencias, con lo que se repite y lo que se contradice.',
     social:'Qué explica el patrón encontrado.',
     english:'This happened three times. This does not fit the pattern.',
     art:'El mapa de evidencias, dibujado.',
     tutoria:'No quitar lo que no encaja.',
     pe:'Trabajo por equipos en el análisis.'},
  5:{science:'Explicaciones científicas: el estudiante explica fenómenos utilizando evidencia.',
     comunicacion:'La ficha de explicación: afirmación, prueba y razonamiento.',
     math:'Qué dato sostiene cada afirmación.',
     english:'I claim that… My evidence is… This shows that…',
     social:'Qué consecuencias tiene la explicación para el lugar.',
     art:'Esquema visual de la explicación.',
     tutoria:'Explicar es más difícil que describir.',
     pe:'Exposición corta ante el grupo.'},
  6:{science:'Cierre de P4: el estudiante transforma aprendizajes en una nueva investigación.',
     comunicacion:'Redacción de la propuesta de investigación.',
     math:'Qué haría falta medir para responderla.',
     social:'Por qué importa esa pregunta aquí.',
     english:'How does light affect…? I would need to measure…',
     art:'Ficha de la propuesta.',
     tutoria:'Una buena investigación termina en una pregunta mejor.',
     music:'Cierre de periodo.'},
  7:{science:'Inicio de P5 y Student Achievement Day #2: se elige la pregunta de investigación.',
     comunicacion:'Presentación oral de la propuesta ante la clase.',
     math:'Viabilidad: ¿se puede medir con lo que hay?',
     social:'A quién le sirve esta investigación.',
     english:'My research question is… It matters because…',
     art:'Panel de la propuesta para el SAD.',
     tutoria:'Anotar las objeciones que me hacen.',
     pe:'Presentación ante público.'},
  8:{science:'Diseño de la investigación: variables, control y repeticiones.',
     math:'Cuántas repeticiones y cómo se registran.',
     comunicacion:'El procedimiento escrito para que otro lo repita.',
     english:'I will change… I will measure… I will repeat it three times.',
     social:'Permisos y materiales necesarios.',
     art:'El plano del montaje experimental.',
     tutoria:'Tres repeticiones mínimo: la regla del laboratorio.',
     pe:'Organización del espacio de trabajo.'},
  9:{science:'Desarrollo experimental: toma de datos con seguridad y repeticiones.',
     math:'Tabla de datos en bruto, sin retocar.',
     comunicacion:'Anotar también los intentos fallidos y por qué.',
     english:'Trial 2: 14 cm. Trial 3 failed because…',
     social:'Trabajo en equipo durante el experimento.',
     art:'Registro fotográfico o dibujado del proceso.',
     tutoria:'Guardar el intento que salió mal.',
     pe:'Constancia diaria en la toma de datos.'},
  10:{science:'Interpretación y comunicación: el argumento científico con sus limitaciones.',
      math:'Media, dispersión y qué se puede afirmar con esos datos.',
      comunicacion:'Redacción del argumento con sus limitaciones.',
      english:'The evidence supports… However, I only tested three plants.',
      social:'Qué implicaría el hallazgo si se confirma.',
      art:'Panel de la Feria, maquetado.',
      tutoria:'Decir lo que el trabajo no demuestra.',
      music:'Preparación de la Feria.'},
  11:{science:'Science Fair: presentación del proyecto y respuesta a preguntas.',
      comunicacion:'Exposición oral y turno de preguntas.',
      math:'Explicación de los datos ante los visitantes.',
      english:'My research question was… If I did it again, I would…',
      social:'Atención a los visitantes de la Feria.',
      art:'Montaje del puesto.',
      tutoria:'"No lo sé" es una respuesta válida si dices cómo lo averiguarías.',
      music:'Apertura de la Feria de Ciencias.'}
}
};
})();
