/* Lo que hace CADA CURSO en cada semana del arco — NIS 2026.
 *
 * POR QUE ESTA APARTE
 * En project-arcs.js, cada semana dice lo que hace el PROYECTO (`hace`) y la
 * pagina anade debajo lo que cada area da esa semana segun el Annual Plan del
 * colegio. Faltaba lo del medio y es lo que pidio el usuario: la tarea
 * concreta de cada curso dentro del proyecto, semana a semana, como ya se
 * veia de Ingles porque el Scope si reparte por semana.
 *
 * Va en un archivo propio y no dentro de cada arco por dos razones:
 *   - project-arcs.js lo editan varias sesiones a la vez; anadir 160 celdas
 *     ahi multiplica los choques.
 *   - asi se puede completar grado por grado sin tocar nada mas: la pagina
 *     pinta el bloque si existe y lo omite si no.
 *
 * QUE ES DEL COLEGIO Y QUE NO
 * El contenido de cada curso sale del Annual Plan y, en 1.o, de los
 * Project.docx del grado, que ya vienen leccion a leccion. **El reparto por
 * semana y la forma de decirlo son propuesta del portal**, y la pagina lo
 * marca con la etiqueta «para acordar con cada profesor». Donde un arco ya
 * trae `cursos` dentro de su fase (g1.t3), manda ese y esto no se usa.
 *
 * FORMA:  'clave.del.arco': { numeroDeSemana: {curso: 'lo que hace'} }
 * Las claves de curso son las de AREA_ORDEN en project.html: science, social,
 * math, english, comunicacion, pe, tutoria, art, music, spiritual.
 */
(function(){
window.PROJECT_ARCS_CURSOS = {

/* ================================================== 1.o · T1 · P1+P2 ==== */
'g1.t1': {
  1:{social:'Quién soy: el DNI, para qué sirve y qué dice de mí. Con el DNI de clase se vota el nombre del aula.',
     science:'Las huellas dactilares con tampón y lupa: nadie tiene las mismas. Primera observación con instrumento.',
     comunicacion:'Mi nombre y mi apellido, escritos y leídos. Nombres propios con mayúscula.',
     math:'Contar cuántos somos y cuántas piezas tiene el mural: conteo y correspondencia.',
     english:'Key routines and functional phrases: saludar, decir mi nombre y mi edad.',
     art:'Autorretrato delante del espejo, mirando la forma de los ojos y el tono de piel.',
     music:'Pulso y ritmo: patrones simples con percusión corporal para la canción del aula.',
     pe:'Control corporal en desplazamientos variados; juegos cooperativos con reglas simples.',
     tutoria:'Qué emociones traigo a 1.º; el mural de piezas de puzle donde cabe cada uno.'},
  2:{science:'Por dónde viaja la comida y para qué sirven los pulmones: dos experimentos con el propio cuerpo.',
     math:'Medir cuánto he crecido y comparar con antes: medida y comparación de longitudes.',
     comunicacion:'Contar en orden lo que sé hacer ahora y no sabía antes: primero, después, ahora.',
     social:'Mi línea de tiempo con fotos de antes y de ahora, ordenadas.',
     english:'Describir lo que puedo hacer: I can…',
     art:'Ilustración de la línea de tiempo con las fotos.',
     music:'Canción del crecimiento con gestos.',
     pe:'Actividades motrices para el cuidado del cuerpo: qué puedo hacer ahora que antes no.',
     tutoria:'Lo que me costaba y ya no me cuesta.'},
  3:{social:'De dónde viene mi apellido, dónde vivo y cómo ha cambiado mi distrito y mi colegio.',
     comunicacion:'La ficha de mi familia y mi distrito, dictada y copiada.',
     math:'Los sitios del barrio en un plano sencillo: posición y recorrido.',
     science:'Qué hay vivo en mi barrio: primera lista de seres vivos del entorno.',
     english:'I live in… My school is…',
     art:'Dibujo del sitio del barrio que más me gusta.',
     music:'Juegos y canciones tradicionales de la familia, de antes y de ahora.',
     pe:'Juegos tradicionales que jugaban los abuelos.',
     tutoria:'Las tradiciones de mi casa: qué hacemos que no hace nadie más.'},
  4:{social:'La diferencia entre un derecho y una responsabilidad; el árbol del círculo de confianza y qué hace cada persona.',
     comunicacion:'La entrevista: preparar dos preguntas y anotar la respuesta con las palabras del otro.',
     science:'Quiénes viven en el colegio además de nosotros: primera pregunta sobre los insectos.',
     math:'Cuántas personas hay en mi círculo de confianza: conteo y comparación entre círculos.',
     english:'This is my… He/She helps me. Thank you.',
     art:'El árbol del círculo de confianza, dibujado.',
     music:'Canción del trabajo en equipo.',
     pe:'Juegos por parejas: confiar y sostener al otro.',
     tutoria:'A quién pido ayuda y cómo se la pido.'},
  5:{social:'Paseo de exploración por el colegio: qué hay aquí que haya que proteger y qué problema vemos.',
     comunicacion:'La carta de agradecimiento a alguien de la comunidad: a quién va y qué le pide.',
     science:'Registro de lo observado en el paseo: qué vi, dónde y cuántos.',
     math:'Contar los problemas encontrados y ordenarlos de más a menos frecuente.',
     english:'Look at this. Please help us. Thank you for your work.',
     art:'Cartel del problema elegido para el vídeo.',
     music:'Cortina musical del vídeo de concienciación.',
     pe:'Recorrido del paseo: orientación y cuidado del grupo.',
     tutoria:'Qué necesita el aula para estar en orden: acuerdos.'},
  6:{tutoria:'La cesta de las palabras mágicas y el reto de cooperación en equipo.',
     art:'Autorretrato en 3D como cierre del periodo, con material de volumen.',
     comunicacion:'Cuento colectivo escrito entre todos.',
     math:'La torre de papel: altura, base y estabilidad; medir y comparar.',
     science:'Por qué unas torres se caen y otras no: primera idea de equilibrio.',
     social:'Convivir: qué acuerdo nos hace falta para trabajar juntos.',
     english:'Team words: my turn, your turn, well done!',
     music:'Yoga y atención plena con música en la salida a la playa.',
     pe:'Salida a la playa: juego cooperativo y cuidado del entorno.'},
  7:{science:'Arranca P2. Se observan los insectos del aula y del colegio: cuándo aparecen, dónde y cada cuánto. Mitos y hechos.',
     math:'Registro de cuántos insectos y de qué tipo: tabla de conteo.',
     comunicacion:'Qué creemos y qué nos preguntamos: dos columnas, dictadas y copiadas.',
     social:'Quién más vive en este sitio: los otros habitantes del colegio.',
     english:'I can see an ant. There are three. It is under the leaf.',
     art:'Dibujo de observación del insecto, del natural y con lupa.',
     music:'Sonidos del patio: escucha y discriminación.',
     pe:'Paseo de observación por el colegio, en silencio y por turnos.',
     tutoria:'Mirar sin tocar: cómo se observa a un ser vivo.'},
  8:{science:'Partes del cuerpo del insecto, cómo se mueven, de qué tamaño son y para qué sirve cada parte; qué comen y dónde viven.',
     math:'Contar patas, alas y partes; comparar tamaños con una regla.',
     comunicacion:'El diagrama etiquetado: escribir el nombre de cada parte donde toca.',
     english:'It has got six legs. These are the wings. It eats leaves.',
     art:'Diagrama a gran tamaño para la pared del aula.',
     social:'Dónde viven en el colegio: mapa de los sitios donde aparecen.',
     music:'Ritmos con seis pulsos, como seis patas.',
     pe:'Juego de imitación de movimientos de insectos.',
     tutoria:'Qué me da miedo y por qué; hablarlo en grupo.'},
  9:{science:'Para qué sirven: polinización, descomposición y cadenas alimentarias; qué pasaría si desaparecieran.',
     social:'Cómo les afecta lo que hacemos con la comida, la limpieza y los materiales.',
     comunicacion:'El cartel de cuidado: frase corta, clara y en imperativo.',
     math:'Cuántos insectos hacen falta para polinizar: estimación sencilla con material.',
     english:'Bees help the flowers. Do not step on them.',
     art:'Cartel de cuidado con letra grande y un solo dibujo.',
     music:'Canción de los insectos para el vídeo.',
     pe:'Circuito de la polinización: llevar sin derramar.',
     tutoria:'Cuidar lo pequeño: por qué importa.'},
  10:{science:'Situaciones reales de aula con un insecto y qué respuestas caben; se elige el problema del prototipo.',
      social:'Se acuerda el protocolo de clase: qué hacemos cuando aparece uno.',
      math:'El plano del prototipo: tamaño, cuántas piezas y cuántas de cada una.',
      comunicacion:'Escribir el protocolo en pasos numerados.',
      english:'Do not touch it. Call the teacher. We need a box.',
      art:'Plano del prototipo dibujado por el equipo.',
      music:'Sintonía del protocolo para recordarlo.',
      pe:'Simulacro del protocolo: moverse sin correr.',
      tutoria:'Ponerse de acuerdo en equipo sin pelear.'},
  11:{science:'Se construye el prototipo con material reciclado siguiendo el plano y se comprueba si funciona.',
      art:'Construcción del prototipo y póster de cómo funciona.',
      comunicacion:'Presentación oral del prototipo y grabación del vídeo.',
      math:'Comprobar que las medidas del prototipo coinciden con el plano.',
      social:'El vídeo para la comunidad: a quién va dirigido y qué le pide.',
      english:'We made it with bottles. It works like this. It helps the ants.',
      music:'Música del vídeo final.',
      pe:'Presentación del prototipo en el patio.',
      tutoria:'Escuchar la mejora que propone otro equipo y aplicarla.'}
},

/* ================================================== 1.o · T2 · P3+P4 ==== */
'g1.t2': {
  1:{science:'Qué es un fenómeno natural y qué lo convierte en desastre: primeros casos.',
     social:'Los sucesos que han pasado aquí, puestos en orden en la línea de tiempo de la clase.',
     comunicacion:'Contar un suceso en orden: qué pasó primero y qué después.',
     math:'Los años en la recta numérica: antes y después, más cerca y más lejos.',
     english:'There was an earthquake. It happened in Lima.',
     art:'Ilustración de un suceso de la línea de tiempo.',
     music:'Sonidos de la naturaleza: escucha y clasificación.',
     pe:'Reacción rápida: juegos de parar y moverse a la señal.',
     tutoria:'Qué siento cuando tiembla y con quién lo hablo.'},
  2:{social:'Costa, sierra y selva: cómo es el suelo, el clima y qué crece o tiembla en cada una.',
     science:'Por qué en cada región pasa algo distinto: relieve, agua y clima.',
     comunicacion:'La ficha de región con las mismas cuatro casillas para las tres.',
     math:'Comparar temperaturas y alturas de las tres regiones: mayor y menor.',
     english:'It is hot in the jungle. It rains a lot.',
     art:'Las tres regiones en un mural colectivo.',
     music:'Una canción de cada región.',
     pe:'Juegos tradicionales de cada región.',
     tutoria:'De qué región viene mi familia.'},
  3:{science:'Antes, durante y después: qué se prepara, qué se hace y qué se revisa.',
     social:'La zona segura del colegio y quién avisa: el plan de todos.',
     comunicacion:'Escribir instrucciones en imperativo y en orden.',
     math:'Contar los pasos hasta la zona segura y cronometrarlos.',
     english:'Get under the table. Do not run. Go to the safe zone.',
     art:'Cartel de las recomendaciones, con pictogramas.',
     music:'Señal sonora del simulacro.',
     pe:'Ensayo del desplazamiento a la zona segura.',
     tutoria:'Mantener la calma: qué hago con mi miedo.'},
  4:{science:'Por qué unas construcciones aguantan y otras no: base, columnas y peso. El experimento de la columna.',
     math:'Formas y medidas del edificio: base ancha, altura y cuántas piezas.',
     art:'Construcción del edificio del equipo para la ciudad colaborativa.',
     social:'Qué necesita una ciudad para funcionar: qué edificio hace falta.',
     comunicacion:'El nombre del edificio y su cartel.',
     english:'Our building is strong. The base is wide.',
     music:'Ritmo de trabajo para construir en equipo.',
     pe:'Transportar material entre todos sin que se caiga.',
     tutoria:'Si mi edificio se cae, se cae la calle: responsabilidad compartida.'},
  5:{science:'Causa y prevención: qué provoca cada problema y qué lo evita.',
     social:'Qué podemos prevenir nosotros y qué no depende de nosotros.',
     comunicacion:'Fichas de causa y prevención, emparejadas.',
     math:'Clasificar las fichas en dos columnas y contar cuántas hay en cada una.',
     english:'The rubbish blocks the water. We can clean the drain.',
     art:'Diseño de las fichas para que se entiendan sin leer.',
     music:'Canción de prevención para el simulacro.',
     pe:'Circuito de prevención: obstáculos y decisiones.',
     tutoria:'Qué puedo hacer yo esta semana.'},
  6:{comunicacion:'El portafolio del periodo: elegir el mejor trabajo y decir por qué.',
     social:'Presentación del portafolio y del simulacro a la clase.',
     science:'Revisión de lo aprendido sobre la Tierra y las regiones.',
     math:'Contar y ordenar los trabajos del portafolio.',
     english:'This is my best work. I learned about the jungle.',
     art:'Portada del portafolio.',
     music:'Cierre musical del periodo.',
     pe:'Simulacro completo, cronometrado.',
     tutoria:'Autoevaluación con caritas.'},
  7:{science:'Arranca P4. De dónde sale la comida: la semilla, lo que necesita y el registro de germinación.',
     math:'Medir la planta cada día y anotar: registro y comparación.',
     comunicacion:'El registro diario escrito: día, qué veo, cuánto mide.',
     social:'Quién cultiva lo que comemos.',
     english:'Day 1: nothing. It is two centimetres. I gave it water.',
     art:'Dibujo de observación de la planta cada semana.',
     music:'Canción de la semilla.',
     pe:'Juego del crecimiento: de semilla a árbol.',
     tutoria:'Cuidar algo todos los días aunque no pase nada.'},
  8:{social:'Qué se cultiva en cada región y por qué: el mapa de región y cultivo.',
     science:'Qué necesita cada cultivo: clima, agua y suelo.',
     comunicacion:'Escribir en el mapa el nombre de cada alimento y su región.',
     math:'Contar cuántos alimentos hay por región y comparar.',
     english:'Rice grows on the coast. This banana is from the jungle.',
     art:'El mapa de Perú con los alimentos dibujados.',
     music:'Canción de los alimentos del Perú.',
     pe:'Juego de la cosecha por regiones.',
     tutoria:'Qué comida de otra región me gustaría probar.'},
  9:{social:'El viaje de la comida hasta el colegio: agricultor, camión, mercado, tienda y yo.',
     comunicacion:'La dramatización del mercado: quién soy y qué digo.',
     math:'Pagar y dar el vuelto con monedas de juguete.',
     science:'La cadena de frío: por qué unas cosas van en frío.',
     english:'I am the farmer. How much is it? Here you are.',
     art:'Decorado y carteles del mercado.',
     music:'Pregones del mercado, con ritmo.',
     pe:'Cargar y transportar en equipo.',
     tutoria:'Dar las gracias a quien nos trae la comida.'},
  10:{science:'Higiene de los alimentos: lavar, guardar en frío y mirar la fecha.',
      comunicacion:'El folleto de higiene en tres caras, con pasos numerados.',
      social:'Qué hace mi familia en casa con la comida.',
      math:'Las fechas del calendario: antes y después de la fecha de vencimiento.',
      english:'Wash the fruit. Put the milk in the fridge. Look at the date.',
      art:'Diseño del folleto para que se entienda sin leer.',
      music:'Canción del lavado de manos, cronometrada.',
      pe:'Rutina de higiene antes y después de la actividad física.',
      tutoria:'El folleto es para mi familia: a quién se lo doy.'},
  11:{science:'Qué me hace por dentro cada alimento: energía, crecimiento y protección.',
      math:'Repartir el plato en partes: la mitad y las porciones.',
      social:'La lonchera de mi casa y la de la clase.',
      comunicacion:'Explicar por qué elegí cada alimento de mi plato.',
      english:'Bread gives me energy. Fruit protects me. Milk makes me grow.',
      art:'El plato dibujado y etiquetado.',
      music:'Ensayo de la actuación de la feria.',
      pe:'Juego de la lonchera equilibrada.',
      tutoria:'Probar algo nuevo sin obligar a nadie.'},
  12:{social:'La Feria de Científicos de la Comida: montar el puesto y recibir a los visitantes.',
      comunicacion:'Las tres frases del puesto, aprendidas y dichas mirando al visitante.',
      science:'Explicar el viaje del alimento y su aporte a quien pregunte.',
      math:'La lonchera equilibrada: contar y repartir delante del visitante.',
      english:'Welcome to our stand. This potato comes from Puno. Would you like to try?',
      art:'Montaje del puesto y de la lonchera.',
      music:'Actuación de apertura de la feria.',
      pe:'Recorrido de la feria sin chocarse.',
      tutoria:'Recibir a un invitado: mirar, saludar y explicar.'}
}

};
})();
