# -*- coding: utf-8 -*-
"""Entrenador de vocabulario YLE (Ruta YLE 2026, Fase 3): construye yle/vocab/<level>.json
con las palabras de la lista oficial 2025 que NO aparecen en Fun for Nordic
(C:/Projects/yle-oficial/faltan_<level>.json), cada una con dibujo (emoji, o el mapa
de yle/fluent3d.js en la app), tema, frase de ejemplo dentro del vocabulario del nivel
y significado en español para la familia.

    python yle/tools/build_vocab.py            # escribe los tres JSON y avisa si falta alguna palabra

Formato de cada entrada: {"w": palabra, "e": emoji|null, "t": tema, "ex": ejemplo, "es": español,
                          "p": false si el dibujo es genérico (nombres, frases) y no sirve para
                          «elige el dibujo», "s": slug del audio (yle-audio/vocab/<level>/<s>.mp3)}
"""
import io, json, os, re, sys

AQUI = os.path.dirname(os.path.abspath(__file__))
RAIZ = os.path.dirname(os.path.dirname(AQUI))
FALTAN = r'C:\Projects\yle-oficial\faltan_%s.json'
OUT = os.path.join(RAIZ, 'yle', 'vocab')

THEMES = {
  'names': '🧒 Names', 'animals': '🐾 Animals', 'food': '🍎 Food & drink', 'home': '🏠 At home',
  'school': '🏫 School', 'sports': '⚽ Sports & hobbies', 'places': '🏙️ Places', 'family': '👪 Family & people',
  'body': '🩺 Body & health', 'transport': '🚌 Transport', 'world': '🌍 The world', 'time': '🕒 Time & numbers',
  'expressions': '💬 Useful phrases', 'describing': '🎨 Describing words', 'actions': '🏃 Action words',
  'tech': '💻 Technology', 'clothes': '👕 Clothes', 'work': '💼 Jobs & work', 'music': '🎵 Music',
}
GENERIC = {'💬', '👦', '👧', '🧒', '📅', '📍', '❓', '🙋', '🚫', '🔢', '⏱️', '⏳', '⏰'}

# Entradas de la lista oficial que vienen con dos formas: se separan o se limpian.
RENOMBRA = {
  'starters': {'ann/ anna': ['ann', 'anna'], 'take a photo/picture': ['take a photo'], 'television/tv': ['television (TV)'],
               'don\u2019t worry': ["don't worry"], 'let\u2019s': ["let's"]},
  'movers': {'t uesday': ['tuesday'], 'o\u2019clock': ["o'clock"]},
  'flyers': {'businessman/woman': ['businessman / businesswoman']},
}

# palabra: [emoji o None (= mapa de fluent3d), tema, ejemplo, español]
STARTERS = {
 "a lot of": ["💬","expressions","There are a lot of fish in the sea.","muchos, muchas"],
 "alex": ["🧒","names","Alex is seven years old.","Alex (nombre de niño o niña)"],
 "alice": ["👧","names","Alice has got a red bag.","Alice (nombre de niña)"],
 "alien": ["👽","world","The alien is green and has got three eyes.","extraterrestre"],
 "ann": ["👧","names","Ann is my sister.","Ann (nombre de niña)"],
 "anna": ["👧","names","Anna likes drawing.","Anna (nombre de niña)"],
 "armchair": ["🛋️","home","Grandpa is sleeping in the armchair.","sillón"],
 "badminton": ["🏸","sports","We play badminton in the garden.","bádminton"],
 "baseball": ["⚾","sports","Tom has got a new baseball.","béisbol"],
 "baseball cap": ["🧢","clothes","Put on your baseball cap. It's sunny!","gorra"],
 "bean": ["🫘","food","I don't like beans.","frijol, judía"],
 "bee": ["🐝","animals","The bee is on the flower.","abeja"],
 "ben": ["👦","names","Ben is playing football.","Ben (nombre de niño)"],
 "bill": ["👦","names","Bill has got a blue bike.","Bill (nombre de niño)"],
 "board game": ["🎲","sports","Let's play a board game!","juego de mesa"],
 "bookcase": ["📚","home","The books are in the bookcase.","estantería, librero"],
 "bookshop": ["🏪","places","Mum is buying a book in the bookshop.","librería"],
 "bounce": ["🏀","actions","Bounce the ball!","botar, rebotar"],
 "burger": [None,"food","I'd like a burger and some chips.","hamburguesa"],
 "bye": ["👋","expressions","Bye! See you tomorrow!","adiós"],
 "camera": [None,"tech","Dad has got a new camera.","cámara"],
 "classmate": ["🧑‍🤝‍🧑","school","Sam is my classmate.","compañero/a de clase"],
 "coconut": [None,"food","Monkeys like coconuts.","coco"],
 "computer": [None,"tech","I play games on the computer.","computadora"],
 "cool": ["😎","expressions","That's a cool T-shirt!","genial, guay"],
 "crocodile": [None,"animals","The crocodile is in the water.","cocodrilo"],
 "dan": ["👦","names","Dan is riding his bike.","Dan (nombre de niño)"],
 "dining room": ["🍽️","home","We eat lunch in the dining room.","comedor"],
 "donkey": [None,"animals","The donkey is eating an apple.","burro"],
 "don't worry": ["💬","expressions","Don't worry, it's OK!","no te preocupes"],
 "end": ["🏁","time","This is the end of the story.","fin, final"],
 "enjoy": ["😊","actions","Enjoy your lunch!","disfrutar"],
 "eva": ["👧","names","Eva is singing a song.","Eva (nombre de niña)"],
 "example": ["📝","school","Look at the example first.","ejemplo"],
 "eye": [None,"body","I've got two brown eyes.","ojo"],
 "fantastic": ["🤩","expressions","Fantastic! Well done!","fantástico"],
 "fishing": ["🎣","sports","Grandpa likes fishing.","pesca, ir a pescar"],
 "glasses": [None,"clothes","My teacher wears glasses.","lentes, gafas"],
 "go to bed": ["🛏️","actions","I go to bed at eight o'clock.","irse a la cama"],
 "go to sleep": ["😴","actions","The baby is going to sleep.","dormirse"],
 "grace": ["👧","names","Grace has got a cat.","Grace (nombre de niña)"],
 "grape": [None,"food","I like green grapes.","uva"],
 "guitar": [None,"music","Dad plays the guitar.","guitarra"],
 "hall": ["🚪","home","Your shoes are in the hall.","recibidor, pasillo"],
 "handbag": [None,"clothes","Mum's handbag is red.","bolso, cartera"],
 "helicopter": [None,"transport","Look! A helicopter in the sky!","helicóptero"],
 "hers": ["💬","expressions","This bag is hers.","suyo, suya (de ella)"],
 "hi": ["👋","expressions","Hi! I'm Lucy.","hola"],
 "hit": ["🏏","actions","Hit the ball with the bat.","golpear"],
 "hobby": ["🎨","sports","My hobby is drawing.","pasatiempo, afición"],
 "hockey": [None,"sports","We play hockey at school.","hockey"],
 "hugo": ["👦","names","Hugo is eating an ice cream.","Hugo (nombre de niño)"],
 "in front of": ["📍","expressions","The dog is in front of the house.","delante de"],
 "jeans": [None,"clothes","I'm wearing blue jeans.","jeans, vaqueros"],
 "jellyfish": [None,"animals","There's a jellyfish in the sea.","medusa"],
 "jill": ["👧","names","Jill is reading a book.","Jill (nombre de niña)"],
 "kid": ["🧒","family","The kids are in the playground.","niño, niña"],
 "kim": ["🧒","names","Kim is my friend.","Kim (nombre de niño o niña)"],
 "kiwi": ["🥝","food","Kiwis are green.","kiwi"],
 "let's": ["💬","expressions","Let's play football!","vamos a…"],
 "lime": ["🍋","food","This lime is very sour!","lima"],
 "line": ["〰️","school","Draw a line under the word.","línea"],
 "lizard": [None,"animals","The lizard is on the rock.","lagartija"],
 "lots": ["💬","expressions","Thanks a lot! I've got lots!","muchos, mucho"],
 "lots of": ["💬","expressions","There are lots of toys in the box.","muchos, muchas"],
 "lucy": ["👧","names","Lucy is wearing a hat.","Lucy (nombre de niña)"],
 "mark": ["👦","names","Mark has got a robot.","Mark (nombre de niño)"],
 "mat": ["🟫","home","The cat is on the mat.","tapete, alfombrilla"],
 "matt": ["👦","names","Matt likes tennis.","Matt (nombre de niño)"],
 "me too": ["💬","expressions","I like pizza. Me too!","yo también"],
 "meatballs": ["🍝","food","We are having meatballs for dinner.","albóndigas"],
 "mine": ["💬","expressions","This pencil is mine.","mío, mía"],
 "mirror": [None,"home","Look in the mirror!","espejo"],
 "monster": [None,"world","The monster is big and purple.","monstruo"],
 "nick": ["👦","names","Nick is playing the piano.","Nick (nombre de niño)"],
 "oh dear": ["💬","expressions","Oh dear! My ice cream!","¡vaya!, ¡ay!"],
 "ok": ["👌","expressions","OK, let's go!","vale, de acuerdo"],
 "onion": [None,"food","I don't like onions.","cebolla"],
 "ours": ["💬","expressions","That house is ours.","nuestro, nuestra"],
 "page": ["📄","school","Open your book at page ten.","página"],
 "pardon": ["💬","expressions","Pardon? Can you say that again?","¿perdón?, ¿cómo?"],
 "pea": ["🫛","food","Peas are small and green.","arveja, guisante"],
 "pear": [None,"food","I'm eating a pear.","pera"],
 "phone": [None,"tech","Mum is talking on the phone.","teléfono"],
 "piano": [None,"music","Alice plays the piano.","piano"],
 "pick up": ["🙌","actions","Pick up your pencil, please.","recoger, levantar"],
 "pie": ["🥧","food","Grandma is making an apple pie.","pastel, tarta"],
 "plane": [None,"transport","The plane is in the sky.","avión"],
 "polar bear": ["🐻‍❄️","animals","Polar bears are white.","oso polar"],
 "poster": ["🖼️","home","There's a poster on the wall.","póster, afiche"],
 "potato": [None,"food","We eat potatoes for lunch.","papa, patata"],
 "really": ["💬","expressions","Really? That's great!","¿de verdad?, realmente"],
 "sam": ["🧒","names","Sam is swimming.","Sam (nombre de niño o niña)"],
 "sausage": [None,"food","I like sausages and eggs.","salchicha"],
 "see you": ["👋","expressions","See you tomorrow!","nos vemos"],
 "skateboard": [None,"sports","My skateboard is red.","patineta, monopatín"],
 "skateboarding": ["🛹","sports","I love skateboarding.","andar en patineta"],
 "sock": [None,"clothes","Where is my blue sock?","calcetín, media"],
 "spider": [None,"animals","There's a spider on the wall!","araña"],
 "story": ["📖","school","Grandma is reading a story.","cuento, historia"],
 "sue": ["👧","names","Sue is drawing a horse.","Sue (nombre de niña)"],
 "table tennis": ["🏓","sports","We play table tennis after school.","tenis de mesa, ping-pong"],
 "tablet": ["📱","tech","I watch cartoons on the tablet.","tableta"],
 "take a photo": ["📸","actions","Can I take a photo of you?","tomar una foto"],
 "television (TV)": ["📺","home","We watch TV in the living room.","televisión"],
 "tennis racket": ["🎾","sports","This is my new tennis racket.","raqueta de tenis"],
 "theirs": ["💬","expressions","The ball is theirs.","suyo, suya (de ellos)"],
 "tom": ["👦","names","Tom is in the garden.","Tom (nombre de niño)"],
 "try": ["💪","actions","Try again!","intentar, probar"],
 "ugly": ["👹","describing","The monster is very ugly.","feo, fea"],
 "which": ["❓","expressions","Which one is your bag?","cuál"],
 "would like": ["💬","expressions","I would like an apple, please.","querría, me gustaría"],
 "yours": ["💬","expressions","Is this pencil yours?","tuyo, tuya"],
 "zebra": [None,"animals","A zebra is black and white.","cebra"],
}

MOVERS = {
 "afraid": ["😨","describing","I'm afraid of spiders.","asustado; tener miedo"],
 "all right": ["💬","expressions","Are you all right? Yes, I'm fine.","bien, de acuerdo"],
 "app": ["📲","tech","This app is for learning English.","aplicación"],
 "awake": ["👀","describing","The baby is awake.","despierto"],
 "bad": ["👎","describing","That was a bad idea.","malo"],
 "badly": ["😬","describing","He played badly today.","mal"],
 "basement": ["🪜","home","Our bikes are in the basement.","sótano"],
 "be called": ["💬","expressions","My dog is called Max.","llamarse"],
 "brave": ["🦸","describing","The firefighter is very brave.","valiente"],
 "break": ["💥","actions","Don't break the window!","romper"],
 "brilliant": ["🌟","expressions","Brilliant! You did it!","genial, brillante"],
 "building": ["🏢","places","That building is very tall.","edificio"],
 "bus station": ["🚏","places","We waited at the bus station.","estación de autobuses"],
 "bus stop": ["🚏","places","The bus stop is near my house.","paradero, parada de autobús"],
 "cage": ["🐹","animals","The rabbit is in its cage.","jaula"],
 "car park": ["🅿️","places","Dad parked in the car park.","estacionamiento"],
 "cd": ["💿","tech","Grandma listens to music on a CD.","CD"],
 "charlie": ["👦","names","Charlie is my cousin.","Charlie (nombre de niño)"],
 "circus": ["🎪","places","We went to the circus on Saturday.","circo"],
 "clare": ["👧","names","Clare is good at swimming.","Clare (nombre de niña)"],
 "coffee": [None,"food","Mum drinks coffee in the morning.","café"],
 "come on": ["💬","expressions","Come on! We're late!","¡vamos!, ¡venga!"],
 "comic": ["📰","school","I read a comic every week.","cómic, historieta"],
 "comic book": ["📚","school","This comic book is funny.","libro de cómics"],
 "country": ["🌍","world","Peru is a big country.","país"],
 "daisy": ["👧","names","Daisy is wearing a yellow dress.","Daisy (nombre de niña)"],
 "daughter": ["👧","family","Mrs Brown has got one daughter.","hija"],
 "difference": ["🔍","school","Find the differences between the two pictures.","diferencia"],
 "downstairs": ["⬇️","home","The kitchen is downstairs.","abajo, en el piso de abajo"],
 "dress up": ["🎭","actions","We dressed up as pirates.","disfrazarse"],
 "drive": ["🚗","actions","My dad drives a red car.","conducir, manejar"],
 "drop": ["💧","actions","Don't drop the glass!","dejar caer"],
 "dvd": ["📀","tech","Let's watch a DVD tonight.","DVD"],
 "e-book": ["📱","tech","I read an e-book on the tablet.","libro electrónico"],
 "earache": ["🤕","body","Jim has got earache.","dolor de oído"],
 "email": ["📧","tech","Grandpa sent me an email.","correo electrónico"],
 "excuse me": ["💬","expressions","Excuse me, where is the station?","disculpe, perdón"],
 "fair": ["🎡","places","There is a fair in the park today.","feria"],
 "farmer": [None,"work","The farmer is feeding the cows.","granjero"],
 "fat": ["🐷","describing","The cat is very fat.","gordo"],
 "fine": ["👍","expressions","How are you? I'm fine, thanks.","bien"],
 "fix": ["🔧","actions","Dad can fix my bike.","arreglar"],
 "fred": ["👦","names","Fred has got a new kite.","Fred (nombre de niño)"],
 "frightened": ["😱","describing","The children were frightened of the storm.","asustado"],
 "get off": ["🚌","actions","We get off the bus at the school.","bajarse (del bus)"],
 "get undressed": ["🩳","actions","Get undressed and put on your pyjamas.","desvestirse"],
 "go shopping": ["🛍️","actions","We go shopping on Saturdays.","ir de compras"],
 "granddaughter": ["👧","family","Grandma is with her granddaughter.","nieta"],
 "grandparent": ["👴","family","My grandparents live in the countryside.","abuelo, abuela"],
 "grandson": ["👦","family","Grandpa is playing with his grandson.","nieto"],
 "ground": ["🟤","world","The ball is on the ground.","suelo, tierra"],
 "grown-up": ["🧑","family","Grown-ups drink coffee.","adulto, persona mayor"],
 "helmet": [None,"clothes","Wear a helmet on your bike.","casco"],
 "how often": ["🗓️","expressions","How often do you play tennis?","con qué frecuencia"],
 "hurt": ["🤕","body","I fell and hurt my knee.","doler; hacerse daño"],
 "ice skates": ["⛸️","sports","I got new ice skates for my birthday.","patines de hielo"],
 "ice skating": ["⛸️","sports","We went ice skating in winter.","patinaje sobre hielo"],
 "internet": ["🌐","tech","I look for pictures on the internet.","internet"],
 "jack": ["👦","names","Jack is climbing the tree.","Jack (nombre de niño)"],
 "jane": ["👧","names","Jane is cooking with her mum.","Jane (nombre de niña)"],
 "jim": ["👦","names","Jim has got a toothache.","Jim (nombre de niño)"],
 "julia": ["👧","names","Julia is riding a horse.","Julia (nombre de niña)"],
 "laptop": ["💻","tech","Mum works on her laptop.","laptop, portátil"],
 "lily": ["👧","names","Lily is at the circus.","Lily (nombre de niña)"],
 "lose": ["😢","actions","Don't lose your keys!","perder"],
 "mary": ["👧","names","Mary is younger than me.","Mary (nombre de niña)"],
 "model": ["🚢","sports","Peter makes model planes.","maqueta, modelo"],
 "moon": [None,"world","The moon is bright tonight.","luna"],
 "moustache": ["👨","body","My uncle has got a moustache.","bigote"],
 "naughty": ["😈","describing","The naughty dog ate my sandwich!","travieso"],
 "net": ["🥅","sports","The ball is in the net!","red"],
 "noodles": ["🍜","food","I love noodles with vegetables.","fideos"],
 "o'clock": ["🕔","time","School starts at eight o'clock.","en punto"],
 "parent": ["👪","family","My parents are teachers.","padre, madre"],
 "paul": ["👦","names","Paul is a good singer.","Paul (nombre de niño)"],
 "peter": ["👦","names","Peter can skip very fast.","Peter (nombre de niño)"],
 "pop star": ["🎤","music","She wants to be a pop star.","estrella del pop"],
 "practise": ["🎹","actions","I practise the piano every day.","practicar"],
 "quick": ["⚡","describing","Be quick! The bus is coming.","rápido"],
 "road": ["🛣️","places","Look both ways before you cross the road.","carretera, calle"],
 "roller skates": ["🛼","sports","Sally has got new roller skates.","patines de ruedas"],
 "roller skating": ["🛼","sports","We went roller skating in the park.","patinaje sobre ruedas"],
 "sail": ["⛵","actions","We sailed on the lake.","navegar"],
 "sally": ["👧","names","Sally is my best friend.","Sally (nombre de niña)"],
 "sauce": ["🥫","food","I like tomato sauce on my pasta.","salsa"],
 "shall": ["💬","expressions","Shall I help you?","¿…? (para ofrecer ayuda)"],
 "shoulder": [None,"body","The parrot is on his shoulder.","hombro"],
 "shower": [None,"home","I have a shower every morning.","ducha"],
 "skip": ["🪢","actions","The girls are skipping in the playground.","saltar la cuerda"],
 "son": ["👦","family","Mr Green has got two sons.","hijo"],
 "swimsuit": ["🩱","clothes","Don't forget your swimsuit!","traje de baño"],
 "tuesday": ["📅","time","We have music on Tuesday.","martes"],
 "terrible": ["😖","describing","The weather was terrible yesterday.","terrible"],
 "thin": ["🥢","describing","The cat is thin, not fat.","delgado"],
 "thirsty": ["🥤","body","I'm thirsty. Can I have some water?","sediento; tener sed"],
 "toothache": ["🦷","body","Jim has got toothache.","dolor de muelas"],
 "toothpaste": ["🪥","home","Put some toothpaste on your toothbrush.","pasta de dientes"],
 "tractor": [None,"transport","The farmer drives a tractor.","tractor"],
 "vicky": ["👧","names","Vicky helps at home.","Vicky (nombre de niña)"],
 "waterfall": ["🏞️","world","We saw a beautiful waterfall.","cascada, catarata"],
 "weak": ["😩","describing","I feel weak when I'm ill.","débil"],
 "website": ["🌐","tech","This website has got good games.","sitio web"],
 "worse": ["📉","describing","My cold is worse today.","peor"],
 "worst": ["📉","describing","That was the worst film ever!","el peor"],
 "wrong": ["❌","describing","That answer is wrong.","incorrecto, equivocado"],
 "zoe": ["👧","names","Zoe is at the bus stop.","Zoe (nombre de niña)"],
}

FLYERS = {
 "a few": ["💬","expressions","I've got a few coins in my pocket.","unos pocos"],
 "actor": ["🎭","work","My uncle is an actor.","actor"],
 "anywhere": ["🗺️","expressions","I can't find my glove anywhere.","en ningún sitio; en cualquier sitio"],
 "at the moment": ["⏱️","time","I'm doing my homework at the moment.","en este momento"],
 "bandage": ["🩹","body","The nurse put a bandage on my arm.","venda"],
 "beetle": ["🪲","animals","A beetle is walking on the leaf.","escarabajo"],
 "betty": ["👧","names","Betty is my grandmother.","Betty (nombre de mujer)"],
 "bin": ["🗑️","home","Put the paper in the bin.","tacho, papelera"],
 "bracelet": ["📿","clothes","Emma is wearing a silver bracelet.","pulsera"],
 "burn": ["🔥","actions","Be careful! Don't burn your hand.","quemar"],
 "business": ["💼","work","My aunt has got her own business.","negocio, empresa"],
 "businessman / businesswoman": ["👔","work","A businessman works in an office.","empresario / empresaria"],
 "by myself": ["🙋","expressions","I made this cake by myself.","yo solo, yo sola"],
 "by yourself": ["🙋","expressions","Did you do it by yourself?","tú solo, tú sola"],
 "calendar": ["📅","time","Write the date on the calendar.","calendario"],
 "chat": ["💬","actions","We chat online after school.","charlar, chatear"],
 "chopsticks": ["🥢","food","Can you eat noodles with chopsticks?","palillos"],
 "college": ["🎓","school","My sister is at college.","instituto superior, universidad"],
 "cooker": ["🍳","home","The soup is on the cooker.","cocina (el aparato)"],
 "costume": ["🦸","clothes","I wore a pirate costume to the party.","disfraz"],
 "creature": ["🐉","world","What is that strange creature?","criatura"],
 "cushion": ["🛋️","home","There are two cushions on the sofa.","cojín"],
 "cycle": ["🚴","actions","We cycle to school every day.","ir en bicicleta"],
 "david": ["👦","names","David is the photographer.","David (nombre de niño)"],
 "disappear": ["🫥","actions","The rabbit disappeared into the hat!","desaparecer"],
 "eagle": ["🦅","animals","An eagle is flying over the mountains.","águila"],
 "emma": ["👧","names","Emma is learning to ski.","Emma (nombre de niña)"],
 "environment": ["🌱","world","We must look after the environment.","medio ambiente"],
 "exit": ["🚪","places","The exit is next to the shop.","salida"],
 "extinct": ["🦕","world","Dinosaurs are extinct.","extinto"],
 "factory": ["🏭","places","My father works in a factory.","fábrica"],
 "fall over": ["🤸","actions","I fell over on the ice.","caerse"],
 "fetch": ["🐕","actions","The dog can fetch the ball.","ir a buscar, traer"],
 "fire fighter": ["🧑‍🚒","work","The fire fighter climbed the ladder.","bombero"],
 "fire station": ["🚒","places","The fire station is on this road.","estación de bomberos"],
 "foggy": ["🌫️","world","It's foggy this morning.","con niebla"],
 "fork": ["🍴","food","We eat pasta with a fork.","tenedor"],
 "frank": ["👦","names","Frank is a mechanic.","Frank (nombre de niño)"],
 "frightening": ["👻","describing","That film was frightening!","aterrador"],
 "fur": ["🐻","animals","The bear has got thick brown fur.","pelaje"],
 "furry": ["🐹","describing","My hamster is small and furry.","peludo"],
 "george": ["👦","names","George is at the post office.","George (nombre de niño)"],
 "get to": ["🏁","actions","How do you get to school?","llegar a"],
 "glove": ["🧤","clothes","I lost one glove in the snow.","guante"],
 "glue": ["🧴","school","Use glue to stick the paper.","pegamento"],
 "go away": ["🚶","actions","Go away! I'm reading.","irse, marcharse"],
 "harry": ["👦","names","Harry built a snowman.","Harry (nombre de niño)"],
 "hate": ["😠","describing","I hate cold weather.","odiar"],
 "helen": ["👧","names","Helen is a nurse.","Helen (nombre de mujer)"],
 "holly": ["👧","names","Holly plays the violin.","Holly (nombre de niña)"],
 "hope": ["🤞","expressions","I hope it's sunny tomorrow.","esperar (tener esperanza)"],
 "horrible": ["🤢","describing","This soup tastes horrible!","horrible"],
 "husband": ["👨","family","Mrs Brown's husband is a doctor.","esposo, marido"],
 "if you want": ["💬","expressions","You can come with us if you want.","si quieres"],
 "improve": ["📈","actions","I want to improve my English.","mejorar"],
 "in a minute": ["⏳","time","I'll be there in a minute.","en un minuto"],
 "information": ["ℹ️","school","Where can we get information about the museum?","información"],
 "insect": ["🐜","animals","A bee is an insect.","insecto"],
 "instrument": ["🎻","music","Which instrument do you play?","instrumento"],
 "interested": ["🤔","describing","I'm interested in dinosaurs.","interesado"],
 "invitation": ["💌","school","I got an invitation to Sarah's party.","invitación"],
 "knife": ["🔪","food","Cut the bread with a knife.","cuchillo"],
 "language": ["🗣️","school","English is a language.","idioma, lengua"],
 "large": ["🐘","describing","An elephant is a large animal.","grande"],
 "look after": ["🧑‍⚕️","actions","I look after my little brother.","cuidar"],
 "magazine": ["📰","school","Mum is reading a magazine.","revista"],
 "make sure": ["✅","expressions","Make sure you close the door.","asegurarse"],
 "married": ["💍","family","My aunt got married last year.","casado"],
 "mechanic": ["🧑‍🔧","work","The mechanic is repairing the car.","mecánico"],
 "member": ["🪪","family","I'm a member of the chess club.","miembro"],
 "michael": ["👦","names","Michael is the tallest boy in the class.","Michael (nombre de niño)"],
 "mind": ["💬","expressions","Do you mind if I open the window?","importar; molestar"],
 "no problem": ["💬","expressions","Can you help me? No problem!","sin problema"],
 "no-one": ["🚫","expressions","No-one is at home.","nadie"],
 "november": ["📅","time","My birthday is in November.","noviembre"],
 "nowhere": ["🚫","expressions","There is nowhere to sit.","en ningún sitio"],
 "octopus": ["🐙","animals","An octopus has got eight arms.","pulpo"],
 "office": ["🏢","work","Mum works in an office.","oficina"],
 "online": ["🌐","tech","We play games online.","en línea"],
 "passenger": ["🧳","transport","The passengers are getting on the train.","pasajero"],
 "photographer": ["📷","work","The photographer took our picture.","fotógrafo"],
 "piece": ["🍰","food","Can I have a piece of cake?","trozo, pedazo"],
 "pleased": ["😊","describing","I'm pleased to meet you.","contento, encantado"],
 "pond": ["🦆","world","There are ducks on the pond.","estanque"],
 "poor": ["🪙","describing","The poor man had no money.","pobre"],
 "pop music": ["🎵","music","I listen to pop music.","música pop"],
 "popular": ["⭐","describing","Football is popular in my country.","popular"],
 "post office": ["📮","places","I bought stamps at the post office.","oficina de correos"],
 "pull": ["🪢","actions","Pull the rope!","tirar, jalar"],
 "push": ["🛒","actions","Push the door to open it.","empujar"],
 "pyramid": ["🔺","world","We saw the pyramids in Egypt.","pirámide"],
 "repair": ["🔧","actions","Dad repaired my bike.","reparar"],
 "repeat": ["🔁","actions","Can you repeat that, please?","repetir"],
 "rich": ["💰","describing","The king was very rich.","rico"],
 "richard": ["👦","names","Richard is a businessman.","Richard (nombre de niño)"],
 "robert": ["👦","names","Robert lives near the fire station.","Robert (nombre de niño)"],
 "rock music": ["🎸","music","My brother likes rock music.","música rock"],
 "sarah": ["👧","names","Sarah is having a party.","Sarah (nombre de niña)"],
 "save": ["🐖","actions","I'm saving money for a new bike.","ahorrar; salvar"],
 "search": ["🔎","actions","Search for the word online.","buscar"],
 "sell": ["🏷️","actions","They sell fruit at the market.","vender"],
 "september": ["📅","time","School starts in September.","septiembre"],
 "several": ["🔢","expressions","I've read several books this month.","varios"],
 "shampoo": ["🧴","home","Wash your hair with shampoo.","champú"],
 "ski": ["⛷️","sports","We ski in the mountains in winter.","esquiar"],
 "skyscraper": ["🏙️","places","There are skyscrapers in the city.","rascacielos"],
 "sledge": ["🛷","sports","We went down the hill on a sledge.","trineo"],
 "smell": ["👃","body","The flowers smell wonderful.","oler; olor"],
 "snowball": ["❄️","world","The boys are throwing snowballs.","bola de nieve"],
 "snowboard": ["🏂","sports","Harry has got a new snowboard.","tabla de snowboard"],
 "snowman": ["⛄","world","We made a snowman in the garden.","muñeco de nieve"],
 "soap": ["🧼","home","Wash your hands with soap.","jabón"],
 "soon": ["⏰","time","See you soon!","pronto"],
 "sophia": ["👧","names","Sophia is a member of the swimming club.","Sophia (nombre de niña)"],
 "sore": ["🤒","body","I've got a sore throat.","dolorido, irritado"],
 "speak": ["🗣️","actions","Do you speak English?","hablar"],
 "spotted": ["🐆","describing","The dog has got a spotted coat.","con manchas, moteado"],
 "stripe": ["🦓","describing","A zebra has got black and white stripes.","raya"],
 "striped": ["🦓","describing","He's wearing a striped T-shirt.","a rayas"],
 "such": ["💬","expressions","It was such a good film!","tan, tal"],
 "sunglasses": ["🕶️","clothes","Wear your sunglasses at the beach.","lentes de sol"],
 "surprise": ["🎁","expressions","What a surprise! A party for me!","sorpresa"],
 "swan": ["🦢","animals","A white swan is on the lake.","cisne"],
 "swing": ["🎠","sports","The children are playing on the swing.","columpio"],
 "tidy": ["🧹","describing","Keep your bedroom tidy!","ordenado; ordenar"],
 "toe": ["🦶","body","I hurt my toe on the rock.","dedo del pie"],
 "trainers": ["👟","clothes","I wear trainers for sport.","zapatillas"],
 "tune": ["🎶","music","She is singing a lovely tune.","melodía"],
 "turn off": ["🔌","actions","Turn off the TV, please.","apagar"],
 "turn on": ["💡","actions","Turn on the light.","encender"],
 "unfriendly": ["😒","describing","That dog looks unfriendly.","antipático"],
 "unhappy": ["😞","describing","Why are you unhappy?","triste, infeliz"],
 "unkind": ["😠","describing","Don't be unkind to your sister.","poco amable, cruel"],
 "untidy": ["🧺","describing","Your desk is very untidy.","desordenado"],
 "unusual": ["🦄","describing","What an unusual creature!","poco común, raro"],
 "whisper": ["🤫","actions","Whisper! The baby is sleeping.","susurrar"],
 "wife": ["👩","family","Mr Green's wife is a photographer.","esposa"],
 "wifi": ["📶","tech","Is there wifi in the hotel?","wifi"],
 "william": ["👦","names","William is good at chess.","William (nombre de niño)"],
 "wonderful": ["🌈","expressions","What a wonderful day!","maravilloso"],
 "zero": ["0️⃣","time","Ten minus ten is zero.","cero"],
}

DATA = {'starters': STARTERS, 'movers': MOVERS, 'flyers': FLYERS}


def slug(w):
    return re.sub(r'[^a-z0-9]+', '_', w.lower()).strip('_')


def titulo(w):
    # nombres propios con mayúscula, días y meses también
    return w[0].upper() + w[1:] if w and w[0].isalpha() else w


def build(level):
    faltan = json.load(io.open(FALTAN % level, encoding='utf-8'))
    ren = RENOMBRA.get(level, {})
    palabras = []
    for w in faltan:
        palabras.extend(ren.get(w, [w]))
    d = DATA[level]
    faltantes = [w for w in palabras if w not in d]
    sobran = [w for w in d if w not in palabras]
    if faltantes or sobran:
        print('%s: SIN DEFINIR %s | SOBRAN %s' % (level, faltantes, sobran))
    out = []
    for w in palabras:
        if w not in d: continue
        e, t, ex, es = d[w]
        assert t in THEMES, (w, t)
        mostrar = titulo(w) if t in ('names', 'time') and w not in ("o'clock", 'zero', 'soon', 'end', 'at the moment', 'in a minute') else w
        row = {'w': mostrar, 'k': w, 'e': e, 't': t, 'ex': ex, 'es': es, 's': slug(w)}
        if e in GENERIC or t in ('names', 'expressions'): row['p'] = False
        out.append(row)
    os.makedirs(OUT, exist_ok=True)
    io.open(os.path.join(OUT, level + '.json'), 'w', encoding='utf-8').write(json.dumps({'level': level, 'themes': THEMES, 'words': out}, ensure_ascii=False, indent=0))
    con = sum(1 for r in out if r.get('p') is not False)
    print('%s: %d palabras (%d con dibujo para elegir) -> yle/vocab/%s.json' % (level, len(out), con, level))


if __name__ == '__main__':
    for lv in ['starters', 'movers', 'flyers']:
        build(lv)
