# -*- coding: utf-8 -*-
"""Las palabras de la lista oficial 2025 que solo ensenaba Fun for Nordic.

Companero de vocab_huecos.py. Aquel cubrio las 471 que no ensenaba nadie; estas son
las otras 551 (230 de Starters, 122 de Movers, 199 de Flyers): las que el curso de
primaria SI declara en la wordlist de alguna unidad, y que por eso hueco() dejaba
fuera del entrenador.

Fuera del portal del colegio ese descuento no vale. cohasset.pe no tiene Fun for
Nordic —es la web del centro de idiomas—, asi que alli el entrenador prometia la
lista de 2025 y entregaba dos tercios: 265 de las 495 de Starters, 259 de 381 en
Movers, 305 de 504 en Flyers. Y el pie de la pagina lo decia sin enterarse: «N words
here, M in the Fun for Nordic course», nombrando un curso que en esa web no existe.

Con estas tablas el entrenador cubre la lista entera en las dos webs y el JSON sigue
siendo uno solo por nivel, byte-identico entre los dos repos. Las que el curso ya
ensena viajan marcadas con "c": true, y el front las separa en «ya vistas en clase»:
en NIS son repaso declarado, no relleno.

Cada entrada: palabra -> [emoji, tema, frase de ejemplo, significado en espanol].
Las claves se escriben como las escribe yle/wordlist-2025.json, salvo las de barra,
que van con espacios («child / children»): clave() las normaliza igual, y asi el TTS
lee «child» y no la barra. Las frases se quedan dentro del vocabulario del nivel; lo
comprueba yle/tools/valida_vocab.py con el mismo filtro que valida los examenes.
"""

# --------------------------------------------------------------------- STARTERS
STARTERS = {
 "a": ["💬","grammar","This is a cat.","un, una"],
 "afternoon": ["🌇","time","Good afternoon, class!","tarde"],
 "again": ["🔁","expressions","Sing the song again!","otra vez"],
 "alphabet": ["🔤","school","We are learning the alphabet.","abecedario"],
 "angry": ["😠","describing","Dad is angry with the dog.","enfadado, molesto"],
 "answer": ["🙋","school","What is the answer? Ten!","respuesta, responder"],
 "apple": ["🍎","food","I've got a big red apple.","manzana"],
 "arm": ["💪","body","My arm is long.","brazo"],
 "ask": ["❓","actions","Ask your teacher!","preguntar, pedir"],
 "baby": ["👶","family","The baby is sleeping.","bebé"],
 "bag": ["🎒","school","My books are in my bag.","bolsa, mochila"],
 "ball": ["⚽","sports","Throw the ball to me!","pelota, balón"],
 "balloon": ["🎈","sports","I've got a big red balloon.","globo"],
 "banana": ["🍌","food","Monkeys like bananas.","plátano, banana"],
 "basketball": ["🏀","sports","We play basketball in the park.","básquetbol"],
 "bathroom": ["🛁","home","The bathroom is next to my bedroom.","baño, cuarto de baño"],
 "beach": ["🏖️","places","We are playing on the beach.","playa"],
 "bear": ["🐻","animals","The bear is very big.","oso"],
 "beautiful": ["🌸","describing","What a beautiful flower!","hermoso, bonito"],
 "bed": ["🛏️","home","My teddy is on the bed.","cama"],
 "bedroom": ["🛏️","home","There are two beds in my bedroom.","dormitorio"],
 "big": ["🐘","describing","An elephant is very big.","grande"],
 "bike": ["🚲","transport","I can ride my bike.","bicicleta"],
 "bird": ["🐦","animals","The bird is in the tree.","pájaro, ave"],
 "birthday": ["🎂","time","Happy birthday, Grandma!","cumpleaños"],
 "black": ["⚫","describing","My cat is black.","negro"],
 "blue": ["🔵","describing","The sea is blue.","azul"],
 "board": ["📋","school","Look at the board, please.","pizarra"],
 "boat": ["⛵","transport","There is a boat on the water.","barco, bote"],
 "body": ["🧍","body","Point to your body!","cuerpo"],
 "book": ["📘","school","This book is about animals.","libro"],
 "box": ["📦","home","What is in the box?","caja"],
 "boy": ["👦","family","That boy is my brother.","niño, chico"],
 "bread": ["🍞","food","I eat bread for breakfast.","pan"],
 "breakfast": ["🥞","food","We have breakfast at seven.","desayuno"],
 "brother": ["👦","family","My brother is ten.","hermano"],
 "brown": ["🟤","describing","The horse is brown.","marrón, café"],
 "bus": ["🚌","transport","I go to school on the bus.","autobús, bus"],
 "cake": ["🎂","food","This cake is for my birthday.","pastel, torta"],
 "can": ["💬","grammar","I can swim!","poder, saber (hacer algo)"],
 "car": ["🚗","transport","Dad's car is red.","carro, coche"],
 "carrot": ["🥕","food","The carrot is orange.","zanahoria"],
 "cat": ["🐱","animals","My cat is sleeping on the sofa.","gato"],
 "chair": ["🪑","home","Sit on the chair, please.","silla"],
 "chicken": ["🐔","animals","The chicken is in the garden.","pollo, gallina"],
 "child / children": ["🧒","family","There are ten children in my class.","niño / niños"],
 "clap": ["👏","actions","Clap your hands!","aplaudir"],
 "clean": ["🧽","describing","My hands are clean now.","limpio, limpiar"],
 "clock": ["🕐","time","The clock is on the wall.","reloj (de pared)"],
 "close": ["🚪","actions","Close the door, please.","cerrar"],
 "correct": ["✅","school","Yes, that's correct!","correcto"],
 "count": ["🔢","school","Count the apples: one, two, three!","contar"],
 "cow": ["🐮","animals","The cow is black and white.","vaca"],
 "crayon": ["🖍️","school","Draw the sun with a yellow crayon.","crayón, lápiz de color"],
 "cross": ["❌","school","Write a cross next to the picture.","cruz, tachar"],
 "cupboard": ["🚪","home","The cupboard is in the kitchen.","armario, alacena"],
 "dad": ["👨","family","My dad is driving the car.","papá"],
 "dirty": ["🧼","describing","Your shoes are very dirty!","sucio"],
 "dog": ["🐶","animals","The dog is playing with the ball.","perro"],
 "doll": ["🪆","sports","My sister has got a new doll.","muñeca"],
 "door": ["🚪","home","Open the door, please.","puerta"],
 "draw": ["🖌️","actions","Draw a big yellow sun.","dibujar"],
 "dress": ["👗","clothes","Her dress is pink.","vestido"],
 "drink": ["🥤","actions","Drink your milk!","beber, tomar"],
 "duck": ["🦆","animals","The duck is on the water.","pato"],
 "egg": ["🥚","food","I eat two eggs for breakfast.","huevo"],
 "elephant": ["🐘","animals","The elephant has got a long nose.","elefante"],
 "eraser (UK rubber)": ["🧽","school","Can I have your eraser, please?","borrador, goma"],
 "evening": ["🌆","time","Good evening, Mum!","tarde, noche"],
 "face": ["😀","body","Look at my funny face!","cara"],
 "family": ["👪","family","This is a photo of my family.","familia"],
 "father": ["👨","family","My father is a teacher.","padre"],
 "fish (s + pl)": ["🐟","animals","There are ten fish in the water.","pez, pescado"],
 "floor": ["🧹","home","Your books are on the floor!","suelo, piso"],
 "flower": ["🌼","world","This flower is beautiful.","flor"],
 "fly": ["🦋","actions","Look! The bird can fly.","volar"],
 "foot / feet": ["🦶","body","I've got two feet.","pie / pies"],
 "football (US soccer)": ["⚽","sports","My brother plays football at school.","fútbol"],
 "friend": ["🧑‍🤝‍🧑","family","Sam is my friend.","amigo, amiga"],
 "fruit": ["🍎","food","I like fruit: apples, bananas and pears.","fruta"],
 "fun": ["🎉","expressions","This game is fun!","divertido, diversión"],
 "funny": ["😂","describing","That monkey is very funny!","gracioso, chistoso"],
 "game": ["🎲","sports","Let's play a game!","juego"],
 "garden": ["🏡","home","We are playing in the garden.","jardín"],
 "giraffe": ["🦒","animals","The giraffe is very big.","jirafa"],
 "girl": ["👧","family","That girl is my sister.","niña, chica"],
 "goat": ["🐐","animals","The goat is eating my hat!","cabra"],
 "goodbye": ["👋","expressions","Goodbye, Mum! See you!","adiós"],
 "grandma": ["👵","family","My grandma makes very good cakes.","abuela"],
 "grandpa": ["👴","family","Grandpa is reading in the armchair.","abuelo"],
 "green": ["🟢","describing","The tree is green.","verde"],
 "hair": ["🦱","body","Her hair is long and black.","cabello, pelo"],
 "hand": ["✋","body","Put up your hand!","mano"],
 "happy": ["😊","describing","I'm very happy today!","feliz, contento"],
 "hat": ["🎩","clothes","Grandpa's hat is brown.","sombrero"],
 "he": ["💬","grammar","This is my brother. He is nine.","él"],
 "head": ["🧠","body","Put your hands on your head.","cabeza"],
 "hello": ["👋","expressions","Hello! What's your name?","hola"],
 "her": ["💬","grammar","This is Anna and her cat.","su, de ella"],
 "here": ["📍","grammar","Come here, please!","aquí"],
 "hippo": ["🦛","animals","The hippo is in the water.","hipopótamo"],
 "his": ["💬","grammar","This is Tom and his dog.","su, de él"],
 "hooray": ["🎉","expressions","Hooray! We are going to the beach!","¡bravo!, ¡hurra!"],
 "horse": ["🐴","animals","The horse is running.","caballo"],
 "house": ["🏠","home","Our house is white and blue.","casa"],
 "ice cream": ["🍨","food","I'd like an ice cream, please.","helado"],
 "in": ["💬","grammar","The cat is in the box.","en, dentro de"],
 "it": ["💬","grammar","Look at the bird! It is very small.","ello, lo (para cosas)"],
 "jacket": ["🧥","clothes","Put on your jacket!","chaqueta, casaca"],
 "juice": ["🧃","food","Would you like some apple juice?","jugo, zumo"],
 "jump": ["🤸","actions","Jump! One, two, three!","saltar"],
 "kitchen": ["🍽️","home","Mum is in the kitchen.","cocina"],
 "kite": ["🪁","sports","My kite is red and yellow.","cometa, papalote"],
 "lamp": ["💡","home","The lamp is next to my bed.","lámpara"],
 "learn": ["📖","school","We learn English at school.","aprender"],
 "leg": ["🦵","body","A spider has got eight legs.","pierna, pata"],
 "lemonade": ["🧃","food","Would you like some lemonade?","limonada"],
 "letter (as in alphabet)": ["🔤","school","What letter is this? It's a B!","letra"],
 "listen": ["👂","actions","Listen to the song!","escuchar"],
 "living room": ["🛋️","home","We watch TV in the living room.","sala, salón"],
 "long": ["📏","describing","The snake is very long.","largo"],
 "look": ["👀","actions","Look at the picture!","mirar"],
 "lorry (US truck)": ["🚚","transport","The lorry is very big.","camión"],
 "man / men": ["👨","family","That man is my father.","hombre / hombres"],
 "mango": ["🥭","food","I like mango ice cream.","mango"],
 "meat": ["🍖","food","The dog is eating meat.","carne"],
 "milk": ["🥛","food","Drink your milk!","leche"],
 "monkey": ["🐵","animals","The monkey is in the tree.","mono"],
 "morning": ["🌅","time","Good morning, children!","mañana"],
 "mother": ["👩","family","My mother is making a cake.","madre"],
 "motorbike": ["🏍️","transport","Dad has got a big motorbike.","moto, motocicleta"],
 "mouse (computer)": ["🖱️","tech","The mouse is next to the computer.","ratón (de computadora)"],
 "mouse / mice": ["🐭","animals","There are two mice under the table.","ratón / ratones"],
 "mouth": ["👄","body","Open your mouth!","boca"],
 "mum": ["👩","family","My mum is making a cake.","mamá"],
 "name": ["📛","expressions","What's your name? I'm Ben.","nombre"],
 "new": ["✨","describing","I've got a new bike!","nuevo"],
 "next to": ["💬","grammar","The chair is next to the table.","al lado de"],
 "night": ["🌙","time","Good night! Sleep well.","noche"],
 "nose": ["👃","body","The elephant has got a long nose.","nariz"],
 "old": ["👴","describing","My grandpa is very old.","viejo, mayor"],
 "on": ["💬","grammar","The book is on the table.","sobre, encima de"],
 "one": ["1️⃣","time","I've got one brother and two sisters.","uno"],
 "open": ["🚪","actions","Open your books, please.","abrir, abierto"],
 "orange": ["🍊","food","I'd like an orange, please.","naranja"],
 "paint": ["🎨","actions","Let's paint a big blue boat!","pintar, pintura"],
 "park": ["🌳","places","We play football in the park.","parque"],
 "pen": ["🖊️","school","Write with a blue pen.","bolígrafo, lapicero"],
 "pencil": ["✏️","school","My pencil is on the desk.","lápiz"],
 "person / people": ["🧑","family","There are ten people in the shop.","persona / personas"],
 "pet": ["🐾","animals","My pet is a small brown dog.","mascota"],
 "picture": ["🖼️","school","Look at the picture and say the word.","dibujo, foto"],
 "pineapple": ["🍍","food","This pineapple is very big.","piña, ananá"],
 "pink": ["🩷","describing","Her dress is pink.","rosado, rosa"],
 "play": ["🧸","actions","Let's play in the garden!","jugar, tocar (música)"],
 "point": ["☝️","actions","Point to the red car!","señalar"],
 "purple": ["🟣","describing","I've got a purple pen.","morado, lila"],
 "read": ["📖","actions","I read a book at night.","leer"],
 "red": ["🔴","describing","My bike is red.","rojo"],
 "rice": ["🍚","food","We eat rice with chicken.","arroz"],
 "rubber (US eraser)": ["🧽","school","Can I have your rubber, please?","borrador, goma"],
 "rug": ["🧶","home","The cat is sleeping on the rug.","alfombra, tapete"],
 "ruler": ["📏","school","Draw the line with a ruler.","regla"],
 "run": ["🏃","actions","Run! The bus is here!","correr"],
 "sad": ["😢","describing","My sister is sad today.","triste"],
 "sand": ["🏖️","world","We are playing in the sand.","arena"],
 "scary": ["👻","describing","That story is very scary!","que da miedo"],
 "school": ["🏫","school","I go to school with my brother.","colegio, escuela"],
 "sea": ["🌊","world","There are a lot of fish in the sea.","mar"],
 "she": ["💬","grammar","This is my sister. She is six.","ella"],
 "sheep (s + pl)": ["🐑","animals","There are ten sheep in the garden.","oveja, ovejas"],
 "shell": ["🐚","world","Look at this beautiful shell!","concha, caracol"],
 "shop (US store)": ["🏬","places","The shop is next to my house.","tienda"],
 "short": ["📏","describing","My hair is short.","corto, bajo"],
 "shorts": ["🩳","clothes","My shorts are green.","pantalones cortos, shorts"],
 "sing": ["🎤","actions","Let's sing a song!","cantar"],
 "sister": ["👧","family","My sister is four.","hermana"],
 "sit": ["🪑","actions","Sit next to me, please.","sentarse"],
 "skirt": ["👘","clothes","Her skirt is blue and white.","falda"],
 "sleep": ["😴","actions","The baby is sleeping.","dormir"],
 "small": ["🐭","describing","A mouse is very small.","pequeño"],
 "smile": ["😊","actions","Smile! I'm taking a photo.","sonreír, sonrisa"],
 "snake": ["🐍","animals","The snake is long and green.","serpiente, culebra"],
 "soccer (UK football)": ["⚽","sports","We play soccer in the park.","fútbol"],
 "sofa": ["🛋️","home","The cat is on the sofa.","sofá"],
 "spell": ["🔤","school","How do you spell your name?","deletrear"],
 "stand": ["🧍","actions","Stand up, please!","estar de pie, ponerse de pie"],
 "stop": ["🚫","actions","Stop! Don't run!","parar, detenerse"],
 "store (UK shop)": ["🏬","places","There is a new store in my street.","tienda"],
 "street": ["🏙️","places","My house is in this street.","calle"],
 "sun": ["☀️","world","The sun is big and yellow.","sol"],
 "sweets (US candy)": ["🍬","food","I've got two sweets for you.","dulces, caramelos"],
 "swim": ["🏊","actions","I can swim in the sea.","nadar"],
 "T-shirt": ["👕","clothes","My T-shirt is yellow.","polo, camiseta"],
 "table": ["🍽️","home","The bread is on the table.","mesa"],
 "tail": ["🐈","animals","My cat has got a long tail.","cola, rabo"],
 "teacher": ["🧑‍🏫","school","My teacher is very funny.","profesor, maestra"],
 "teddy (bear)": ["🧸","sports","I sleep with my teddy bear.","osito de peluche"],
 "tennis": ["🎾","sports","Let's play tennis!","tenis"],
 "thank you": ["💬","expressions","Thank you, Grandma!","gracias"],
 "that": ["💬","grammar","What's that? It's a kite.","ese, aquel"],
 "there": ["📍","grammar","Look! There is a bird in the tree.","allí, ahí"],
 "these": ["💬","grammar","These are my new shoes.","estos, estas"],
 "this": ["💬","grammar","This is my dog.","este, esta"],
 "those": ["💬","grammar","Those are my friends.","esos, aquellos"],
 "tiger": ["🐯","animals","The tiger is orange and black.","tigre"],
 "today": ["📅","time","Today is my birthday!","hoy"],
 "train": ["🚆","transport","The train is going to the beach.","tren"],
 "tree": ["🌳","world","There is a bird in the tree.","árbol"],
 "trousers": ["👖","clothes","My trousers are black.","pantalones"],
 "truck (UK lorry)": ["🚚","transport","There are two trucks in the street.","camión"],
 "under": ["💬","grammar","The ball is under the chair.","debajo de"],
 "walk": ["🚶","actions","Let's walk to the park.","caminar, andar"],
 "wall": ["🧱","home","The picture is on the wall.","pared, muro"],
 "water": ["💧","food","Drink some water!","agua"],
 "watermelon": ["🍉","food","This watermelon is very big.","sandía"],
 "wave": ["👋","actions","Wave goodbye to Grandma!","saludar con la mano, ola"],
 "wear": ["👕","actions","I wear a blue T-shirt at school.","llevar puesto, usar"],
 "well done": ["💬","expressions","Well done! That's correct.","¡muy bien!, ¡bien hecho!"],
 "what": ["❓","grammar","What's this? It's a lamp.","qué"],
 "where": ["❓","grammar","Where is my bag?","dónde"],
 "white": ["⚪","describing","The sheep is white.","blanco"],
 "window": ["🪟","home","Open the window, please.","ventana"],
 "woman / women": ["👩","family","That woman is my mother.","mujer / mujeres"],
 "word": ["🔤","school","Read the word and write it.","palabra"],
 "write": ["✍️","actions","Write your name here.","escribir"],
 "yellow": ["🟡","describing","The sun is yellow.","amarillo"],
 "young": ["👶","describing","My sister is very young.","joven, pequeño"],
 "zoo": ["🦁","places","There are two tigers at the zoo.","zoológico"],
}

# ----------------------------------------------------------------------- MOVERS
MOVERS = {
 "above": ["💬","grammar","The clock is above the door.","encima de, sobre"],
 "bat": ["🦇","animals","Bats sleep in the day and fly at night.","murciélago"],
 "beard": ["🧔","body","My grandpa has got a white beard.","barba"],
 "better": ["👍","describing","I'm better at tennis than my brother.","mejor"],
 "blanket": ["🛏️","home","There is a blanket on my bed.","manta, frazada"],
 "boring": ["😑","describing","This film is boring!","aburrido"],
 "bottle": ["🍼","food","There is a bottle of water in my bag.","botella"],
 "café": ["☕","places","We had a milkshake in the café.","cafetería, café"],
 "catch (e.g. a bus)": ["🚌","actions","We catch the bus at eight o'clock.","tomar, coger (el bus)"],
 "cheese": ["🧀","food","I'd like a cheese sandwich, please.","queso"],
 "cinema": ["🎬","places","We are going to the cinema on Saturday.","cine"],
 "clever": ["🧠","describing","My sister is very clever at school.","listo, inteligente"],
 "climb": ["🧗","actions","The monkey can climb the tree.","trepar, escalar"],
 "cloud": ["☁️","world","There is a big grey cloud in the sky.","nube"],
 "cloudy": ["☁️","world","It's cloudy today, but it isn't raining.","nublado"],
 "coat": ["🧥","clothes","Put on your coat. It's cold outside!","abrigo"],
 "cold": ["🥶","describing","The water in the lake is very cold.","frío"],
 "cough": ["🤧","body","I've got a bad cough today.","tos, toser"],
 "curly": ["🦱","describing","She has got long curly hair.","rizado, crespo"],
 "dance": ["💃","actions","Let's dance to this song!","bailar"],
 "dangerous": ["⚠️","describing","Sharks are dangerous animals.","peligroso"],
 "dentist": ["🦷","work","The dentist is looking at my teeth.","dentista"],
 "difficult": ["😖","describing","This game is very difficult.","difícil"],
 "doctor": ["🧑‍⚕️","work","The doctor helps people who are ill.","doctor, médica"],
 "dolphin": ["🐬","animals","Dolphins can swim and jump.","delfín"],
 "driver": ["🚌","work","The bus driver is very friendly.","conductor, chofer"],
 "easy": ["😀","describing","This word is easy to spell.","fácil"],
 "feed": ["🍼","actions","I feed my rabbit every morning.","dar de comer, alimentar"],
 "field": ["🌾","places","There are ten sheep in the garden.","campo, prado"],
 "first": ["1️⃣","time","Read the first word on the page.","primero"],
 "fish": ["🐟","food","We eat fish and rice on Fridays.","pescado"],
 "forest": ["🌲","places","There are a lot of trees in the forest.","bosque"],
 "Friday": ["📅","time","We play football on Friday.","viernes"],
 "funfair": ["🎪","places","We went to the funfair on Saturday.","feria, parque de diversiones"],
 "get dressed": ["👕","actions","I get dressed after breakfast.","vestirse"],
 "get up": ["⏰","actions","I get up at seven o'clock.","levantarse"],
 "grass": ["🌱","world","The cows are eating grass.","pasto, hierba"],
 "grow": ["🌱","actions","These flowers grow very quickly.","crecer, cultivar"],
 "headache": ["🤕","body","I've got a headache. Can I have some water?","dolor de cabeza"],
 "help": ["🤝","actions","Can you help me, please?","ayudar, ayuda"],
 "hide": ["🙈","actions","Let's hide behind the tree!","esconderse, esconder"],
 "hop": ["🐰","actions","Rabbits hop on their long legs.","brincar, saltar"],
 "hospital": ["🏥","places","My mother works in a hospital.","hospital"],
 "hot": ["🔥","describing","Don't drink it! The soup is very hot.","caliente, caluroso"],
 "hungry": ["🍽️","describing","I'm hungry. Can I have a sandwich?","hambriento, con hambre"],
 "ill": ["🤒","body","Tom is ill today, so he isn't at school.","enfermo"],
 "invite": ["💌","actions","I want to invite all my friends to the party.","invitar"],
 "jungle": ["🌴","places","Tigers and monkeys live in the jungle.","selva, jungla"],
 "kangaroo": ["🦘","animals","Kangaroos can jump and run.","canguro"],
 "lake": ["🏞️","places","There are ducks on the lake.","lago"],
 "leaf / leaves": ["🍂","world","The leaves on this tree are green.","hoja / hojas"],
 "library": ["📚","places","I read books in the library.","biblioteca"],
 "lion": ["🦁","animals","The lion is sleeping under a tree.","león"],
 "little": ["🐭","describing","My little sister is only two.","pequeño, poquito"],
 "map": ["🗺️","places","Look at the map. Where is the lake?","mapa"],
 "market": ["🏪","places","We buy fruit at the market.","mercado"],
 "milkshake": ["🥤","food","I'd like a banana milkshake, please.","batido, malteada"],
 "Monday": ["📅","time","We have English on Monday.","lunes"],
 "mountain": ["⛰️","world","That mountain is very big.","montaña"],
 "nurse": ["🧑‍⚕️","work","The nurse is helping the doctor.","enfermero, enfermera"],
 "opposite": ["↔️","grammar","The shop is opposite the library.","enfrente de, contrario"],
 "outside": ["🌳","grammar","It's sunny. Let's play outside!","afuera, fuera"],
 "pair": ["👟","clothes","I've got a new pair of shoes.","par"],
 "panda": ["🐼","animals","The panda is eating.","panda"],
 "parrot": ["🦜","animals","My parrot can say my name!","loro, perico"],
 "party": ["🎉","time","There are twenty children at the party.","fiesta"],
 "pasta": ["🍝","food","We have pasta for dinner on Mondays.","pasta, fideos"],
 "penguin": ["🐧","animals","Penguins can't fly, but they can swim.","pingüino"],
 "picnic": ["🧺","sports","We had a picnic in the park.","picnic"],
 "plant": ["🪴","world","There is a green plant next to the window.","planta, plantar"],
 "present": ["🎁","time","This present is for your birthday.","regalo"],
 "pretty": ["🌸","describing","What a pretty dress!","bonito, lindo"],
 "put on": ["🧥","actions","Put on your coat before you go outside.","ponerse"],
 "quiet": ["🤫","describing","Be quiet! The baby is sleeping.","callado, silencioso"],
 "rabbit": ["🐇","animals","My rabbit likes carrots.","conejo"],
 "rainbow": ["🌈","world","Look at the rainbow in the sky!","arcoíris"],
 "river": ["🏞️","world","There are a lot of fish in the river.","río"],
 "rock": ["🪨","world","The bird is sitting on a big rock.","roca, piedra"],
 "salad": ["🥗","food","I'd like a salad with my chicken.","ensalada"],
 "sandwich": ["🥪","food","I've got a cheese sandwich for lunch.","sándwich, emparedado"],
 "Saturday": ["📅","time","On Saturday we go to the beach.","sábado"],
 "scarf": ["🧣","clothes","My scarf is red and very long.","bufanda"],
 "seat": ["🪑","transport","Is this your seat?","asiento"],
 "send": ["📩","actions","I want to send this letter to my grandma.","enviar, mandar"],
 "shark": ["🦈","animals","Sharks live in the sea.","tiburón"],
 "shop": ["🏬","places","There is a new shop in our street.","tienda"],
 "shout": ["📢","actions","Don't shout! The baby is sleeping.","gritar"],
 "sick": ["🤢","body","I'm sick today, so I'm not at school.","mareado, con náuseas"],
 "snail": ["🐌","animals","The snail is on the leaf.","caracol"],
 "snow": ["❄️","world","There is snow on the mountain.","nieve, nevar"],
 "soup": ["🍜","food","This soup is very hot!","sopa"],
 "sports centre (US center)": ["🏟️","places","We play basketball at the sports centre.","polideportivo, centro deportivo"],
 "star": ["⭐","world","Look at the stars in the sky!","estrella"],
 "stomach-ache": ["🤕","body","I've got a stomach-ache. I ate too much cake.","dolor de estómago"],
 "straight": ["📏","describing","She has got long straight hair.","liso, recto"],
 "strong": ["💪","describing","Elephants are very strong animals.","fuerte"],
 "Sunday": ["📅","time","On Sunday we don't go to school.","domingo"],
 "sunny": ["☀️","world","It's a sunny day. Let's go to the beach!","soleado"],
 "supermarket": ["🏬","places","Mum is buying eggs at the supermarket.","supermercado"],
 "surprised": ["😲","describing","Grandma was surprised when she saw her present.","sorprendido"],
 "sweater": ["🧶","clothes","Put on your sweater. It's cold.","suéter, chompa"],
 "swimming pool": ["🏊","sports","There is a swimming pool at the sports centre.","piscina, alberca"],
 "take off (i.e. get undressed)": ["🧥","actions","Take off your wet coat, please.","quitarse"],
 "temperature": ["🌡️","body","The doctor is taking my temperature.","temperatura, fiebre"],
 "than": ["💬","grammar","My brother is taller than me.","que (en comparaciones)"],
 "Thursday": ["📅","time","We have music on Thursday.","jueves"],
 "ticket": ["🎫","transport","I've got two tickets for the train.","boleto, entrada"],
 "tooth / teeth": ["🦷","body","Clean your teeth after breakfast!","diente / dientes"],
 "toothbrush": ["🪥","home","My toothbrush is blue and white.","cepillo de dientes"],
 "towel": ["🏖️","home","Take a towel to the swimming pool.","toalla"],
 "treasure": ["💎","world","They found treasure under the old tree.","tesoro"],
 "village": ["🏘️","places","My grandpa lives in a small village.","pueblo, aldea"],
 "wait": ["⏳","actions","Wait for me! I'm coming.","esperar"],
 "wash": ["🧼","actions","Wash your hands before dinner.","lavar, lavarse"],
 "weather": ["🌤️","world","What's the weather like today?","clima, tiempo"],
 "Wednesday": ["📅","time","On Wednesday we have sport.","miércoles"],
 "weekend": ["📅","time","At the weekend we go to my grandma's house.","fin de semana"],
 "whale": ["🐳","animals","Whales are the biggest animals in the sea.","ballena"],
 "wind": ["💨","world","The wind is taking my kite up!","viento"],
 "windy": ["💨","world","It's windy today. Let's fly our kites!","ventoso, con viento"],
 "yesterday": ["📅","time","Yesterday we played football in the park.","ayer"],
}

# ----------------------------------------------------------------------- FLYERS
FLYERS = {
 "adventure": ["🗺️","world","Their journey to the cave was a great adventure.","aventura"],
 "agree": ["🤝","actions","I agree with you. That's the best answer.","estar de acuerdo"],
 "airport": ["🛫","places","We arrived at the airport two hours early.","aeropuerto"],
 "already": ["💬","grammar","I've already finished my homework.","ya"],
 "ambulance": ["🚑","transport","The ambulance took the man to hospital.","ambulancia"],
 "April": ["📅","time","My birthday is in April.","abril"],
 "arrive": ["🚉","actions","The train arrives at midday.","llegar"],
 "art": ["🎨","school","Art is my favourite subject at school.","arte, plástica"],
 "artist": ["🧑‍🎨","work","The artist is painting a picture of the sea.","artista"],
 "astronaut": ["🧑‍🚀","work","The astronaut went into space in a rocket.","astronauta"],
 "August": ["📅","time","We go to the beach in August.","agosto"],
 "autumn (US fall)": ["🍂","time","In autumn the leaves fall from the trees.","otoño"],
 "belt": ["🧵","clothes","My trousers are too big without a belt.","cinturón, correa"],
 "bicycle": ["🚲","transport","I go to school on my bicycle.","bicicleta"],
 "bored": ["😑","describing","I'm bored. Let's play a game!","aburrido"],
 "bridge": ["🌉","places","We walked over the bridge to the village.","puente"],
 "broken": ["🔧","describing","My watch is broken. It doesn't work.","roto, averiado"],
 "butter": ["🧈","food","I'd like some bread and butter, please.","mantequilla"],
 "card": ["💌","time","I'm sending my grandma a birthday card.","tarjeta"],
 "cartoon": ["📺","expressions","My little brother watches cartoons after school.","dibujos animados"],
 "castle": ["🏰","places","The old castle is on top of the hill.","castillo"],
 "cave": ["🕳️","world","They found treasure in a dark cave.","cueva, caverna"],
 "century": ["🕰️","time","This castle is more than a century old.","siglo"],
 "cereal": ["🥣","food","I have cereal and milk for breakfast.","cereal"],
 "channel": ["📺","tech","Can you change the channel? This programme is boring.","canal"],
 "cheap": ["💰","describing","These shoes are cheap. They aren't expensive.","barato"],
 "chess": ["♟️","sports","My grandpa taught me to play chess.","ajedrez"],
 "club": ["🎽","sports","I go to the chess club on Thursdays.","club"],
 "collect": ["📦","actions","My sister collects stamps from other countries.","coleccionar, recoger"],
 "corner": ["📐","places","The shop is on the corner of my street.","esquina, rincón"],
 "cut": ["✂️","actions","Cut the paper with these scissors.","cortar"],
 "dark": ["🌑","describing","It's dark outside. Turn on the light!","oscuro"],
 "December": ["📅","time","It snows here in December.","diciembre"],
 "deep": ["🌊","describing","Don't swim there. The water is very deep.","profundo, hondo"],
 "designer": ["🧑‍🎨","work","My aunt is a designer. She makes clothes.","diseñador, diseñadora"],
 "dictionary": ["📖","school","Look up the new word in your dictionary.","diccionario"],
 "early": ["⏰","time","We got up early to catch the first train.","temprano"],
 "Earth": ["🌍","world","The Earth goes round the sun.","la Tierra"],
 "east": ["🧭","world","The sun comes up in the east.","este, oriente"],
 "elbow": ["🦾","body","I fell off my bike and hurt my elbow.","codo"],
 "empty": ["🫙","describing","The bottle is empty. There's no water in it.","vacío"],
 "engineer": ["🔧","work","The engineer is building a new bridge.","ingeniero, ingeniera"],
 "enough": ["💬","grammar","We haven't got enough chairs for all the children.","suficiente, bastante"],
 "envelope": ["📩","school","Put the letter in the envelope and send it.","sobre"],
 "ever": ["💬","grammar","Have you ever been to the mountains?","alguna vez"],
 "excited": ["🤩","describing","The children are excited about the journey.","emocionado, entusiasmado"],
 "expensive": ["💰","describing","That camera is too expensive for me.","caro, costoso"],
 "fall (UK autumn)": ["🍂","time","In fall the weather gets colder.","otoño"],
 "February": ["📅","time","February is the shortest month of the year.","febrero"],
 "festival": ["🎪","time","There is a music festival in our town in May.","festival"],
 "finger": ["☝️","body","I've got five fingers on each hand.","dedo (de la mano)"],
 "finish": ["🏁","actions","I finish my homework before dinner.","terminar, acabar"],
 "fire": ["🔥","world","They cooked their dinner on the fire.","fuego, incendio"],
 "fire engine (US fire truck)": ["🚒","transport","The fire engine arrived very quickly.","camión de bomberos"],
 "flour": ["🥖","food","You need flour and eggs to make a cake.","harina"],
 "fog": ["🌫️","world","We couldn't see the mountain because of the fog.","niebla, neblina"],
 "forget": ["🤔","actions","Don't forget your ticket!","olvidar"],
 "fridge": ["🧊","home","Put the milk in the fridge, please.","refrigeradora, nevera"],
 "friendly": ["😊","describing","Our new teacher is very friendly.","amable, simpático"],
 "future": ["🔮","time","In the future I want to be a pilot.","futuro"],
 "gate": ["🚧","home","Please close the gate so the dog can't get out.","reja, portón"],
 "geography": ["🌍","school","In geography we are learning about mountains and rivers.","geografía"],
 "glass": ["🥛","food","Can I have a glass of water, please?","vaso, vidrio"],
 "gold": ["🥇","describing","They found gold in the old cave.","oro, dorado"],
 "golf": ["⛳","sports","My uncle plays golf every Sunday.","golf"],
 "guess": ["🤔","actions","Guess what's in my bag!","adivinar"],
 "gym": ["🏋️","places","We play basketball in the school gym.","gimnasio"],
 "heavy": ["🏋️","describing","This suitcase is too heavy to carry.","pesado"],
 "hill": ["⛰️","world","Our house is at the top of the hill.","colina, cerro"],
 "history": ["🕰️","school","In history we learn about castles.","historia"],
 "honey": ["🍯","food","I like honey on my bread.","miel"],
 "hotel": ["🏨","places","We stayed in a hotel near the beach.","hotel"],
 "hurry": ["🏃","actions","Hurry up! The film starts in ten minutes.","apurarse, darse prisa"],
 "if": ["💬","grammar","If it rains, we'll stay at home.","si"],
 "instead": ["💬","grammar","There isn't any juice, so drink water instead.","en lugar de eso"],
 "jam": ["🍓","food","I have bread and jam for breakfast.","mermelada"],
 "January": ["📅","time","The new year starts in January.","enero"],
 "join (a club)": ["🎽","actions","I want to join the swimming club.","apuntarse, unirse a"],
 "journalist": ["📰","work","The journalist is writing about the festival.","periodista"],
 "journey": ["🧳","transport","The journey to the mountains takes three hours.","viaje, trayecto"],
 "just": ["💬","grammar","I've just finished my homework.","acabar de, solo"],
 "kilometre (US kilometer)": ["📏","time","The lake is two kilometres from our hotel.","kilómetro"],
 "knee": ["🦵","body","I fell over and hurt my knee.","rodilla"],
 "late": ["⏰","time","Hurry up, or we'll be late for school!","tarde, atrasado"],
 "later": ["⏰","time","I'll do my homework later, after dinner.","después, más tarde"],
 "lazy": ["😴","describing","My cat is very lazy. It sleeps all day.","perezoso, flojo"],
 "leave": ["🚪","actions","We leave the house at eight o'clock.","salir de, dejar"],
 "left (as in direction)": ["⬅️","places","Turn left at the corner.","izquierda"],
 "letter (as in mail)": ["💌","school","I wrote a letter to my cousin.","carta"],
 "lift": ["🛗","home","Our flat is on the tenth floor, so we take the lift.","ascensor, elevador"],
 "lift (ride)": ["🚗","transport","Dad gave me a lift to the station.","aventón, llevar en carro"],
 "light": ["💡","home","Turn on the light. It's dark in here.","luz, ligero"],
 "manager": ["💼","work","My mother is the manager of a hotel.","gerente, jefa"],
 "March": ["📅","time","It's often windy in March.","marzo"],
 "maths (US math)": ["🔢","school","We have maths after break.","matemáticas"],
 "May": ["📅","time","The festival is in May.","mayo"],
 "medicine": ["💊","body","Take this medicine and you'll feel better.","medicina, medicamento"],
 "meet": ["🤝","actions","Let's meet at the cinema at six.","encontrarse, conocer"],
 "metal": ["🔩","describing","The gate is made of metal.","metal"],
 "midday": ["🕛","time","We have lunch at midday.","mediodía"],
 "midnight": ["🕛","time","The party finished at midnight.","medianoche"],
 "might": ["💬","grammar","It might rain later. Take your umbrella.","podría, quizá"],
 "minute": ["⏱️","time","Wait a minute! I'm coming.","minuto"],
 "mix": ["🥣","actions","Mix the flour and the eggs in a bowl.","mezclar"],
 "motorway": ["🛣️","transport","There is a lot of traffic on the motorway.","autopista"],
 "museum": ["🏛️","places","We saw an old spaceship at the museum.","museo"],
 "news": ["📰","tech","My parents watch the news after dinner.","noticias"],
 "noisy": ["📢","describing","The classroom is very noisy today.","ruidoso"],
 "north": ["🧭","world","It's colder in the north of the country.","norte"],
 "ocean": ["🌊","world","Whales and sharks live in the ocean.","océano"],
 "October": ["📅","time","School starts again in October.","octubre"],
 "olives": ["🫒","food","I like olives on my pizza.","aceitunas"],
 "once": ["💬","grammar","I go swimming once a week.","una vez"],
 "oven": ["🍳","home","The cake is in the oven.","horno"],
 "over": ["💬","grammar","The plane flew over the mountains.","sobre, por encima de"],
 "past": ["🕰️","time","It's half past four.","y (la hora), pasado"],
 "path": ["🥾","places","Follow this path through the forest.","sendero, camino"],
 "pepper": ["🫑","food","Put some salt and pepper on your salad.","pimienta, pimiento"],
 "perhaps": ["💬","grammar","Perhaps we'll go to the beach on Sunday.","quizá, tal vez"],
 "pilot": ["🧑‍✈️","work","The pilot flies the plane.","piloto"],
 "planet": ["🪐","world","The Earth is a planet.","planeta"],
 "plastic": ["♻️","describing","This bottle is made of plastic.","plástico"],
 "platform": ["🚉","transport","Our train leaves from platform two.","andén"],
 "pocket": ["👕","clothes","My keys are in my jacket pocket.","bolsillo"],
 "police officer": ["👮","work","The police officer helped us find our hotel.","policía"],
 "police station": ["🏢","places","We took the lost bag to the police station.","comisaría"],
 "postcard": ["📮","time","I sent my friend a postcard from the beach.","postal"],
 "prefer": ["👍","actions","I prefer tennis to golf.","preferir"],
 "prize": ["🏆","sports","Our team won first prize in the race.","premio"],
 "programme (US program)": ["📺","tech","This programme about dolphins is very good.","programa"],
 "puzzle": ["🧩","sports","This puzzle has got a thousand pieces.","rompecabezas"],
 "quarter": ["🕒","time","I get up at a quarter past seven.","cuarto"],
 "race": ["🏁","sports","My brother won the race yesterday.","carrera"],
 "railway": ["🛤️","transport","The railway goes through the mountains.","ferrocarril, vía férrea"],
 "ready": ["✅","describing","Are you ready? The bus is here!","listo, preparado"],
 "remember": ["🧠","actions","Remember to take your umbrella!","recordar, acordarse"],
 "restaurant": ["🍽️","places","We had dinner in a restaurant near the river.","restaurante"],
 "right (as in direction)": ["➡️","places","Turn right after the bridge.","derecha"],
 "ring": ["💍","clothes","My grandma has got a gold ring.","anillo, sonar"],
 "rocket": ["🚀","transport","The rocket took the astronauts into space.","cohete"],
 "salt": ["🧂","food","There's too much salt in this soup.","sal"],
 "science": ["🔬","school","In science we are learning about planets.","ciencias"],
 "score": ["🥅","sports","Our team scored three goals.","marcar, puntuación"],
 "screen": ["🖥️","tech","The words are on the computer screen.","pantalla"],
 "secret": ["🤫","expressions","Don't tell anyone! It's a secret.","secreto"],
 "shelf": ["📚","home","The dictionary is on the top shelf.","estante, repisa"],
 "silver": ["🥈","describing","She's wearing a silver ring.","plata, plateado"],
 "singer": ["🧑‍🎤","music","My favourite singer is coming to our town.","cantante"],
 "snack": ["🍪","food","I have a snack after school.","refrigerio, tentempié"],
 "snowboarding": ["🏂","sports","We went snowboarding in the mountains.","snowboard"],
 "sound": ["🔊","music","What's that sound? Is it a bird?","sonido"],
 "south": ["🧭","world","It's hotter in the south.","sur"],
 "space": ["🌌","world","The astronaut looked at the Earth from space.","espacio"],
 "spaceship": ["🛸","transport","The spaceship is flying to another planet.","nave espacial"],
 "spring": ["🌸","time","The flowers grow in spring.","primavera"],
 "stadium": ["🏟️","places","There were thirty thousand people in the stadium.","estadio"],
 "stage (theatre)": ["🎭","music","The singer is on the stage.","escenario"],
 "stamp": ["📮","school","Put a stamp on the envelope before you send it.","sello, estampilla"],
 "stay": ["🏨","actions","We stayed with my grandparents for a week.","quedarse, alojarse"],
 "step": ["🪜","actions","Be careful! There's a step here.","escalón, paso"],
 "still": ["💬","grammar","It's ten o'clock and my brother is still asleep.","todavía, aún"],
 "stone": ["🪨","world","The old bridge is made of stone.","piedra"],
 "storm": ["⛈️","world","We stayed at home because of the storm.","tormenta"],
 "straight on": ["⬆️","places","Go straight on and you'll see the museum.","todo recto, de frente"],
 "stream": ["🏞️","world","There are little fish in the stream.","arroyo, riachuelo"],
 "subject": ["📚","school","My favourite subject is geography.","asignatura, materia"],
 "suddenly": ["💥","grammar","Suddenly, the lights went off.","de repente"],
 "sugar": ["🍬","food","I don't take sugar in my tea.","azúcar"],
 "suitcase": ["🧳","transport","My suitcase is very heavy.","maleta"],
 "sure": ["✅","expressions","Are you sure this is the right way?","seguro"],
 "surname": ["📛","expressions","What's your surname? How do you spell it?","apellido"],
 "taxi": ["🚕","transport","We took a taxi to the airport.","taxi"],
 "team": ["🏅","sports","There are eleven players in a football team.","equipo"],
 "tent": ["⛺","sports","We slept in a tent next to the lake.","carpa, tienda de campaña"],
 "theatre (US theater)": ["🎭","places","We saw a play at the theatre.","teatro"],
 "through": ["💬","grammar","The train went through the mountains.","a través de, por"],
 "time": ["🕒","time","What time does the film start?","hora, tiempo, vez"],
 "timetable": ["📅","school","Look at the timetable. We have science on Monday.","horario"],
 "together": ["🤝","grammar","We did our homework together.","juntos"],
 "traffic": ["🚦","transport","There was a lot of traffic this morning.","tráfico"],
 "twice": ["💬","grammar","I go swimming twice a week.","dos veces"],
 "umbrella": ["☂️","clothes","Take your umbrella. It's going to rain.","paraguas"],
 "uniform": ["👔","clothes","We wear a blue school uniform.","uniforme"],
 "university": ["🎓","places","My cousin studies science at university.","universidad"],
 "usually": ["💬","grammar","I usually get up at seven o'clock.","normalmente, suele"],
 "view": ["🏞️","world","There's a beautiful view from the top of the hill.","vista"],
 "visit": ["🚶","actions","We visit my grandparents every weekend.","visitar"],
 "volleyball": ["🏐","sports","We played volleyball on the beach.","vóleibol"],
 "waiter": ["🧑‍🍽️","work","The waiter brought us our soup.","mesero, camarero"],
 "west": ["🧭","world","The sun goes down in the west.","oeste"],
 "whistle": ["🎣","sports","The teacher has got a whistle for the race.","silbato, silbar"],
 "winner": ["🏆","sports","The winner of the race got a prize.","ganador, ganadora"],
 "wish": ["🌠","actions","Close your eyes and make a wish!","deseo, desear"],
 "wood": ["🪵","describing","This table is made of wood.","madera, bosque"],
 "wool": ["🧶","clothes","My sweater is made of wool.","lana"],
 "worried": ["😟","describing","Mum was worried because we were late.","preocupado"],
 "x-ray": ["🩻","body","The doctor took an x-ray of my knee.","radiografía"],
 "yet": ["💬","grammar","I haven't finished my homework yet.","todavía, aún"],
 "yoghurt": ["🥣","food","I have yoghurt and fruit for breakfast.","yogur"],
}
