# -*- coding: utf-8 -*-
"""Las palabras de la lista oficial 2025 que no ensenaba nadie.

El entrenador se construia desde C:/Projects/yle-oficial/faltan_<level>.json, y ese
archivo daba por cubierta cualquier palabra que apareciera EN ALGUN TEXTO del curso.
Una palabra que sale una vez dentro de un cuento no esta ensenada: nadie le dice al
alumno que la aprenda, no esta en la lista de la unidad y no la practica.

Con el criterio bueno —o esta en el entrenador, o alguna unidad la declara en su
wordlist— y normalizando las entradas con variantes de la lista oficial («eraser (UK
rubber)», «fish (s + pl)», «child/children»), el hueco real eran 471 palabras:
154 de Starters, 156 de Movers y 161 de Flyers. Son estas.

Cada entrada: palabra -> [emoji, tema, frase de ejemplo, significado en espanol].
El emoji puede ser None: entonces lo pone el mapa de yle/fluent3d.js en la app.
Las frases estan dentro del vocabulario del nivel; lo comprueba build_vocab.py con
el mismo filtro que valida los examenes.

Las palabras gramaticales (and, but, some, very...) van al tema «grammar»: tambien
son de la lista oficial y el alumno tiene que reconocerlas, pero no se puede elegir
un dibujo para «and», asi que quedan fuera de ese modo.
"""

# --------------------------------------------------------------------- STARTERS
STARTERS = {
 "a lot": ["💬","grammar","Pip eats a lot!","mucho"],
 "add": ["➕","actions","Add two eggs to the cake.","añadir"],
 "an": ["💬","grammar","This is an apple.","un, una (antes de a, e, i, o, u)"],
 "and": ["💬","grammar","I've got a pen and a pencil.","y"],
 "animal": ["🐾","animals","A cat is my favourite animal.","animal"],
 "apartment (UK flat)": ["🏢","home","Their apartment is very big.","apartamento, piso"],
 "at": ["💬","grammar","We are at school.","en"],
 "bat (as sports equipment)": ["🏏","sports","Hit the ball with the bat!","bate"],
 "bath": ["🛁","home","Pip is in the bath!","baño, bañera"],
 "be": ["💬","grammar","Be happy!","ser, estar"],
 "behind": ["💬","grammar","The ball is behind the door.","detrás de"],
 "between": ["💬","grammar","The cat is between the two chairs.","entre"],
 "boots": ["🥾","clothes","My new boots are red.","botas"],
 "but": ["💬","grammar","I like fish but I don't like eggs.","pero"],
 "candy (UK sweet(s))": ["🍬","food","I've got two candies for you.","caramelo, dulce"],
 "catch (e.g. a ball)": ["🤾","actions","Catch the ball!","atrapar, coger"],
 "chips (US fries)": ["🍟","food","I like chips with my chicken.","patatas fritas"],
 "chocolate": ["🍫","food","I love chocolate cake!","chocolate"],
 "choose": ["👉","actions","Choose a colour: red, blue or green?","elegir"],
 "class": ["🧑‍🏫","school","There are ten children in my class.","clase (grupo)"],
 "classroom": ["🏫","school","Our classroom has got a big board.","aula, salón de clase"],
 "closed": ["🚪","describing","The door is closed.","cerrado"],
 "clothes": ["👕","clothes","My clothes are in the bedroom.","ropa"],
 "colour (US color)": ["🎨","describing","What colour is your bag?","color"],
 "come": ["🚶","actions","Come here, Pip!","venir"],
 "complete": ["✅","school","Complete the word and write it.","completar"],
 "cousin": ["🧑","family","My cousin is eight.","primo, prima"],
 "day": ["📅","time","Today is a happy day!","día"],
 "desk": ["🪑","school","My book is on the desk.","pupitre, escritorio"],
 "dinner": ["🍽️","food","We have dinner at seven.","cena"],
 "do": ["💬","grammar","Do you like cake?","hacer (y para preguntar)"],
 "don’t worry": ["💬","expressions","Don't worry! It's OK.","no te preocupes"],
 "double": ["2️⃣","describing","Sam has got a double bed.","doble"],
 "drawing": ["🖌️","school","Freya is drawing a big boat.","dibujando, dibujo"],
 "drive": ["🚗","transport","Dad can drive the car.","conducir, manejar"],
 "ear": ["👂","body","You listen with your ears.","oreja, oído"],
 "eat": ["🍽️","actions","I eat rice for lunch.","comer"],
 "English": ["🇬🇧","school","Say it in English!","inglés"],
 "favourite (US favorite)": ["⭐","describing","My favourite colour is orange.","favorito, preferido"],
 "find": ["🔍","actions","Find the red ball!","encontrar"],
 "flat (US apartment)": ["🏢","home","Their flat is on the third floor.","piso, apartamento"],
 "food": ["🍎","food","There is a lot of food on the table.","comida"],
 "for": ["💬","grammar","This cake is for you.","para, por"],
 "fries (UK chips)": ["🍟","food","Can I have fries, please?","patatas fritas"],
 "frog": ["🐸","animals","The frog is green and it can jump.","rana"],
 "from": ["💬","grammar","I'm from Peru.","de, desde"],
 "get": ["🎁","actions","I get a new bike on my birthday.","conseguir, recibir"],
 "give": ["🤲","actions","Give me your hand.","dar"],
 "go": ["🏃","actions","Let's go to the park!","ir"],
 "good": ["👍","describing","This is a good book.","bueno"],
 "grandfather": ["👴","family","My grandfather is eighty.","abuelo"],
 "grandmother": ["👵","family","My grandmother makes good cakes.","abuela"],
 "gray (UK grey)": ["🩶","describing","The elephant is gray.","gris"],
 "great": ["🎉","describing","Great! Your picture is beautiful.","genial, estupendo"],
 "grey (US gray)": ["🩶","describing","It is very big and grey.","gris"],
 "have": ["💬","grammar","I have a book to read.","tener"],
 "have got": ["💬","grammar","She has got a red bike.","tener"],
 "him": ["💬","grammar","Look at him!","lo, le, a él"],
 "hold": ["✋","actions","Hold my hand, please.","sostener, agarrar"],
 "home": ["🏠","home","Pip is sleeping at home.","casa, hogar"],
 "how": ["💬","grammar","How are you?","cómo"],
 "how many": ["🔢","grammar","How many pencils have you got?","cuántos, cuántas"],
 "how old": ["🎂","grammar","How old are you? I'm seven.","cuántos años"],
 "I": ["💬","grammar","I like ice cream.","yo"],
 "its": ["💬","grammar","The dog is in its house.","su (de un animal o cosa)"],
 "keyboard (computer)": ["⌨️","tech","I write on the keyboard of the computer.","teclado"],
 "kick": ["🦵","sports","Kick the ball to me!","patear, dar una patada"],
 "know": ["🧠","actions","I know the answer!","saber, conocer"],
 "lemon": ["🍋","food","The lemon is yellow.","limón"],
 "lesson": ["🏫","school","We've got an English lesson now.","clase, lección"],
 "let’s": ["💬","expressions","Let's play football!","vamos a…"],
 "like": ["😀","actions","I like bananas.","gustar"],
 "live": ["🏠","actions","Birds live in the tree.","vivir"],
 "look at": ["👀","actions","Look at the big fish!","mirar"],
 "love": ["❤️","actions","I love my family.","querer mucho, encantar"],
 "lunch": ["🥪","food","I eat rice and fish for lunch.","almuerzo, comida"],
 "make": ["🛠️","actions","Let's make a cake!","hacer"],
 "many": ["💬","grammar","There are many flowers in the garden.","muchos, muchas"],
 "May (as in girl’s name)": ["👧","names","May has got a new kite.","May (nombre de niña)"],
 "me": ["💬","grammar","Show me your book.","me, a mí"],
 "Miss": ["👩‍🏫","names","Good morning, Miss Green!","señorita (para la profesora)"],
 "Mr": ["👨","names","Mr Brown is my teacher.","señor"],
 "Mrs": ["👩","names","Mrs Green has got two cats.","señora"],
 "music": ["🎵","music","I like music. Let's sing!","música"],
 "my": ["💬","grammar","This is my bag.","mi"],
 "nice": ["🙂","describing","She has got a nice smile.","simpático, bonito"],
 "no": ["💬","grammar","No, thank you.","no"],
 "not": ["💬","grammar","It is not a cat. It is a dog!","no"],
 "now": ["⏰","time","Come here now, please!","ahora"],
 "number": ["🔢","time","What number is on the door?","número"],
 "of": ["💬","grammar","This is the bag of my sister.","de"],
 "oh": ["💬","expressions","Oh! Look at that bird!","¡oh!, ¡ah!"],
 "or": ["💬","grammar","Do you want milk or juice?","o"],
 "our": ["💬","grammar","This is our classroom.","nuestro, nuestra"],
 "painting": ["🎨","school","Astrid is painting a big sun.","pintando, pintura"],
 "paper": ["📄","school","Draw a house on this paper.","papel"],
 "part": ["🧩","school","Draw one part of the picture.","parte"],
 "Pat": ["🧒","names","Pat has got six mice!","Pat (nombre de niño o niña)"],
 "photo": ["📷","school","Look at this photo of my family!","foto"],
 "playground": ["🛝","places","We play in the playground at school.","patio de recreo"],
 "please": ["🙏","expressions","Can I have some water, please?","por favor"],
 "put": ["📥","actions","Put your book in your bag.","poner"],
 "question": ["❓","school","I've got a question for you.","pregunta"],
 "radio": ["📻","home","Mum is listening to the radio.","radio"],
 "ride": ["🚲","actions","I can ride a bike!","montar"],
 "right": ["👉","describing","Your right hand, not your left!","derecha"],
 "right (as in correct)": ["✅","describing","Yes! That's the right answer.","correcto"],
 "robot": ["🤖","tech","The robot can walk and talk.","robot"],
 "room": ["🚪","home","There are four rooms in my house.","habitación, cuarto"],
 "say": ["💬","actions","Say hello to Pip!","decir"],
 "see": ["👀","actions","I can see three birds.","ver"],
 "sentence": ["📝","school","Write one sentence about your cat.","frase, oración"],
 "ship": ["🚢","transport","That big boat is a ship!","barco grande"],
 "shirt": ["👕","clothes","Nico is wearing a blue shirt.","camisa"],
 "shoe": ["👟","clothes","Put a shoe on your foot!","zapato"],
 "show": ["👉","actions","Show me your new toy!","enseñar, mostrar"],
 "silly": ["🤪","describing","Silly Pip! That's not a fish.","tonto, bobo"],
 "so": ["💬","grammar","I like football. So do I!","así que, tan"],
 "some": ["💬","grammar","I want some milk.","algo de, unos"],
 "song": ["🎵","music","Let's sing my favourite song!","canción"],
 "sorry": ["😔","expressions","Sorry! I can't come today.","lo siento, perdón"],
 "sport": ["⚽","sports","What sport do you play?","deporte"],
 "start": ["🚦","actions","Let's start the game!","empezar"],
 "talk": ["🗣️","actions","You talk with your mouth.","hablar"],
 "television/TV": ["📺","home","There is a big television in the living room.","televisión, tele"],
 "tell": ["🗣️","actions","Tell me your name, please.","contar, decir"],
 "thanks": ["🙏","expressions","Thanks! You are very nice.","gracias"],
 "the": ["💬","grammar","The cat is on the table.","el, la, los, las"],
 "their": ["💬","grammar","The children are in their classroom.","su (de ellos)"],
 "them": ["💬","grammar","You see with them.","los, las, les"],
 "then": ["⏰","time","First we eat, then we play.","luego, entonces"],
 "they": ["💬","grammar","They are my friends.","ellos, ellas"],
 "thing": ["📦","home","What is that thing in your bag?","cosa"],
 "throw": ["🤾","sports","Throw the ball to Tomás!","lanzar, tirar"],
 "tick": ["✔️","school","Tick the correct picture.","marcar con una palomita"],
 "to": ["💬","grammar","Come to my house!","a, hacia"],
 "tomato": ["🍅","food","The tomato is red. I like tomatoes!","tomate"],
 "too": ["💬","grammar","I like cake. Me too!","también"],
 "toy": ["🧸","home","My toy box is red.","juguete"],
 "TV/television": ["📺","home","Can I watch TV, please?","tele, televisión"],
 "understand": ["🧠","actions","I don't understand. Say it again, please.","entender"],
 "us": ["💬","grammar","Show us your picture, Nico!","nos, a nosotros"],
 "very": ["💬","grammar","The kite is very big!","muy"],
 "want": ["🙋","actions","I want an ice cream.","querer"],
 "watch": ["⌚","time","My watch is new.","reloj (de pulsera)"],
 "we": ["💬","grammar","We are in the park.","nosotros"],
 "well": ["👍","describing","Astrid sings very well.","bien"],
 "who": ["💬","grammar","Who is that man?","quién"],
 "whose": ["💬","grammar","Whose bag is this?","de quién"],
 "with": ["💬","grammar","I live with my mother and father.","con"],
 "wow": ["😮","expressions","Wow! That's a big cake!","¡guau!"],
 "year": ["📅","time","Pip is one year old!","año"],
 "yes": ["💬","grammar","Yes, please!","sí"],
 "you": ["💬","grammar","How old are you?","tú, usted"],
 "your": ["💬","grammar","Where is your book?","tu"],
}

# ----------------------------------------------------------------------- MOVERS
MOVERS = {
 "address": ["✉️","home","Write your name and address on the letter.","dirección"],
 "after": ["💬","grammar","What do you do after school?","después de"],
 "age": ["🎂","time","What age are you? I'm nine.","edad"],
 "all": ["💬","grammar","All the children are in the playground.","todos, todas"],
 "along": ["💬","grammar","We walked along the river.","a lo largo de, por"],
 "always": ["💬","grammar","Erik always eats bread for breakfast.","siempre"],
 "another": ["💬","grammar","Would you like another apple?","otro, otra"],
 "any": ["💬","grammar","Have you got any brothers?","algún, alguno"],
 "around": ["💬","grammar","Look around the room!","alrededor, a la vuelta"],
 "asleep": ["😴","describing","The baby is asleep. Be quiet!","dormido"],
 "aunt": ["👩","family","My aunt lives in the countryside.","tía"],
 "back": ["🔙","body","My back hurts after the long walk.","espalda; de vuelta"],
 "balcony": ["🏢","home","There are flowers on our balcony.","balcón"],
 "band (music)": ["🎸","music","My brother plays in a band.","banda, grupo de música"],
 "because": ["💬","grammar","I went home because I was tired.","porque"],
 "before": ["💬","grammar","Sunday comes before Monday.","antes de"],
 "below": ["💬","grammar","The fish are below the boat.","debajo de"],
 "best": ["🏆","describing","Anna is my best friend.","el mejor"],
 "blond(e)": ["👱","describing","Sofía has got long blonde hair.","rubio, rubia"],
 "both": ["💬","grammar","Both my brothers play football.","los dos, ambos"],
 "bottom": ["⬇️","describing","My name is at the bottom of the page.","el fondo, la parte de abajo"],
 "bowl": ["🥣","food","There is soup in the bowl.","cuenco, tazón"],
 "bring": ["🎁","actions","Bring your coloured pencils to school.","traer"],
 "build": ["🧱","actions","Erik wants to build a robot.","construir"],
 "busy": ["🏃","describing","Mum is very busy today.","ocupado"],
 "buy": ["🛒","actions","We buy fruit at the market.","comprar"],
 "by": ["💬","grammar","I go to school by bus.","en (transporte); por"],
 "call": ["📞","actions","Please call me after school.","llamar"],
 "careful": ["⚠️","describing","Be careful! The floor is wet.","cuidadoso, con cuidado"],
 "carefully": ["👂","describing","Listen carefully and write the answer.","con atención"],
 "carry": ["🎒","actions","Can you carry my bag, please?","llevar, cargar"],
 "centre (US center)": ["🎯","places","The shops are in the centre of the town.","centro"],
 "change": ["🔄","actions","I want to change my seat.","cambiar"],
 "circle": ["⭕","describing","Draw a circle round the correct word.","círculo"],
 "city": ["🏙️","places","Lima is a very big city.","ciudad"],
 "city/town centre (US center)": ["🏙️","places","We took the bus to the city centre.","centro de la ciudad"],
 "clown": ["🤡","work","The clown has got a red nose.","payaso"],
 "cook": ["🧑‍🍳","actions","Dad can cook fish and rice.","cocinar; cocinero"],
 "could (as in past of can for ability)": ["💬","grammar","I could see some birds in the tree.","podía, pude"],
 "countryside": ["🌾","world","My grandparents live in the countryside.","el campo"],
 "cry": ["😢","actions","Don't cry! I can help you.","llorar"],
 "cup": ["☕","food","There is a cup of tea on the table.","taza"],
 "different": ["🔀","describing","These two pictures are different.","diferente"],
 "down": ["💬","grammar","Sit down, please.","abajo"],
 "dream": ["💭","actions","I had a funny dream about a flying cat.","sueño; soñar"],
 "dry": ["🌵","describing","My shoes are dry now.","seco"],
 "elevator (UK lift)": ["🛗","home","We took the elevator to the top floor.","ascensor"],
 "every": ["💬","grammar","I clean my room every Saturday.","cada, todos los"],
 "everyone": ["👥","grammar","Everyone is happy today!","todo el mundo"],
 "everything": ["📦","grammar","Erik put everything in his bag.","todo"],
 "exciting": ["🎉","describing","The film was very exciting!","emocionante"],
 "fall": ["🍂","actions","Be careful — don't fall!","caer, caerse"],
 "famous": ["⭐","describing","She is a famous singer.","famoso"],
 "farm": ["🚜","places","There are cows and sheep on the farm.","granja"],
 "film (US movie)": ["🎬","music","We watched a funny film on Sunday.","película"],
 "film (US movie) star": ["🌟","work","She wants to be a film star.","estrella de cine"],
 "floor (e.g. ground, 1st, etc.)": ["🏢","home","Their flat is on the second floor.","piso, planta"],
 "get on": ["🚌","transport","Show your ticket when you get on the bus.","subir (a un vehículo)"],
 "goal": ["🥅","sports","Daisy kicked the ball and got a goal!","gol"],
 "have (got) to": ["💬","grammar","I have to clean my room before lunch.","tener que"],
 "holiday": ["🏖️","time","We go to the beach in the holidays.","vacaciones"],
 "homework": ["📚","school","I do my homework after dinner.","deberes, tarea"],
 "how much": ["💬","grammar","How much water do you drink?","cuánto"],
 "huge": ["🐘","describing","The elephant was huge!","enorme"],
 "hundred": ["💯","time","There are a hundred children in our school.","cien"],
 "ice": ["🧊","food","Put some ice in my drink, please.","hielo"],
 "idea": ["💡","school","Good idea! Let's do that.","idea"],
 "inside": ["💬","grammar","It's raining. Let's play inside.","dentro"],
 "into": ["💬","grammar","The cat jumped into the box.","dentro de, a"],
 "island": ["🏝️","world","There are birds on the small island.","isla"],
 "kind": ["🤗","describing","Valentina is very kind to her friends.","amable; tipo, clase"],
 "kitten": ["🐱","animals","Our cat has got four kittens.","gatito"],
 "last": ["⏮️","time","We went to the farm last Tuesday.","último; pasado"],
 "laugh": ["😄","actions","The children laugh at the clown.","reír"],
 "lift (US elevator)": ["🛗","home","The lift is broken, so we walked upstairs.","ascensor"],
 "look for": ["🔍","actions","Sofía is looking for her lost dog.","buscar"],
 "loud": ["🔊","describing","That music is too loud!","alto, ruidoso"],
 "loudly": ["📢","describing","He sang loudly and the class laughed.","en voz alta"],
 "machine": ["⚙️","tech","Erik built a machine that makes noise.","máquina"],
 "matter": ["❓","expressions","What's the matter? Have you got a headache?","asunto; ¿qué pasa?"],
 "mean": ["💬","actions","What does this word mean?","significar"],
 "message": ["✉️","tech","I write a message to my friend.","mensaje"],
 "mistake": ["❌","school","Sorry, that was my mistake.","error"],
 "more": ["💬","grammar","Would you like some more rice?","más"],
 "most": ["💬","grammar","Luna is the most beautiful dog in town.","el más"],
 "move": ["➡️","actions","Don't move! There is a bee on your hat.","mover, moverse"],
 "movie (UK film)": ["🎬","music","Let's watch a movie after dinner.","película"],
 "must": ["💬","grammar","You must do your homework before you play.","deber, tener que"],
 "near": ["💬","grammar","The shop is near my house.","cerca de"],
 "neck": ["🧣","body","You wear a scarf round your neck.","cuello"],
 "need": ["🙋","actions","You need a coat today. It is cold.","necesitar"],
 "never": ["💬","grammar","She never eats meat.","nunca"],
 "noise": ["📢","describing","There is a lot of noise in the street.","ruido"],
 "nothing": ["💬","grammar","There is nothing in the box.","nada"],
 "off": ["💬","grammar","Take off your coat. It is hot inside.","fuera, quitar(se)"],
 "often": ["💬","grammar","We often go swimming on Saturdays.","a menudo"],
 "only": ["💬","grammar","I have got only one apple.","solo"],
 "out": ["💬","grammar","Erik is out. He is playing in the garden.","fuera"],
 "out of": ["💬","grammar","Look out of the window!","por, fuera de"],
 "o’clock": ["🕒","time","School starts at eight o'clock.","en punto"],
 "pancake": ["🥞","food","We eat pancakes on Saturday morning.","panqueque, crepe"],
 "pirate": ["🏴","world","The pirate has got a map and a parrot.","pirata"],
 "place": ["📍","places","The library is a quiet place.","lugar, sitio"],
 "plate": ["🍽️","food","There is bread and cheese on my plate.","plato"],
 "player": ["⚽","sports","Every player has got a number.","jugador"],
 "pool": ["🏊","sports","We swim in the pool every Friday.","piscina"],
 "practice": ["🎹","school","Piano practice is at four o'clock.","práctica, ensayo"],
 "puppy": ["🐶","animals","Luna was a very small puppy.","cachorro"],
 "quickly": ["⚡","describing","Jim swam very quickly.","rápidamente"],
 "quietly": ["🤫","describing","Please close the door quietly.","en silencio"],
 "rain": ["🌧️","world","We saw a rainbow after the rain.","lluvia"],
 "roof": ["🏠","home","There is a bird on the roof.","tejado, techo"],
 "round": ["⭕","describing","He wears round glasses.","redondo; alrededor de"],
 "safe": ["🦺","describing","Wear your helmet. Then you are safe.","seguro, a salvo"],
 "second": ["⏱️","time","Wait a second! I am coming.","segundo"],
 "shape": ["🔷","describing","This box has got the shape of a circle.","forma"],
 "shopping": ["🛍️","actions","Mum is doing the shopping at the market.","las compras"],
 "shopping centre (US center)": ["🏬","places","There are twenty shops in the shopping centre.","centro comercial"],
 "skate": ["⛸️","sports","Valentina can skate very well.","patinar"],
 "sky": ["☁️","world","There are seven colours in the sky after rain.","cielo"],
 "slow": ["🐌","describing","The bus is very slow today.","lento"],
 "slowly": ["🐢","describing","Please read slowly. I do not understand.","despacio"],
 "someone": ["🙋","grammar","Someone is at the door.","alguien"],
 "something": ["📦","grammar","There is something in my shoe!","algo"],
 "sometimes": ["💬","grammar","Sometimes we walk to school.","a veces"],
 "square": ["⬜","places","We play football in the square.","plaza; cuadrado"],
 "stair(s)": ["🪜","home","Go up the stairs to the bedroom.","escaleras"],
 "station": ["🚉","transport","The train leaves the station at six.","estación"],
 "stomach": ["🩺","body","I have got a stomach-ache. I ate too much cake!","estómago, barriga"],
 "sweet": ["🍬","food","This orange is very sweet.","dulce"],
 "take": ["🎒","actions","Take your bag and come with me.","tomar, llevar"],
 "tall": ["📏","describing","My brother is very tall.","alto"],
 "tea": ["🍵","food","Grandma drinks tea in the afternoon.","té"],
 "teach": ["🧑‍🏫","actions","Can you teach me to skate?","enseñar"],
 "text": ["📱","tech","I write a text to my cousin.","mensaje de texto"],
 "think": ["🤔","actions","I think the cat won this game.","pensar, creer"],
 "third": ["3️⃣","time","Jim came third in the swimming.","tercero"],
 "tired": ["😪","describing","We came home tired and happy.","cansado"],
 "top": ["⬆️","describing","The bird is at the top of the tree.","la parte de arriba"],
 "town": ["🏘️","places","There are two schools in our town.","pueblo, ciudad pequeña"],
 "town/city centre (US center)": ["🏙️","places","We walked to the town centre.","centro del pueblo"],
 "travel": ["✈️","transport","We travel to the mountains by train.","viajar"],
 "trip": ["🚌","transport","The class trip is on Friday.","excursión, viaje"],
 "uncle": ["👨","family","It was my uncle's farm.","tío"],
 "up": ["💬","grammar","Stand up, please!","arriba"],
 "upstairs": ["🪜","home","The bedrooms are upstairs.","arriba, en el piso de arriba"],
 "vegetable": ["🥕","food","A carrot is a long orange vegetable.","verdura, vegetal"],
 "video": ["📹","tech","We watched a video about sea animals.","video"],
 "wake (up)": ["⏰","actions","I wake up at seven every morning.","despertarse"],
 "week": ["📅","time","There are seven days in a week.","semana"],
 "wet": ["💧","describing","My hair is wet after swimming.","mojado"],
 "when": ["💬","grammar","When does school start?","cuándo"],
 "why": ["💬","grammar","Why is he laughing?","por qué"],
 "work": ["💼","work","My mother works in a hospital.","trabajar; trabajo"],
 "world": ["🌍","world","There are many countries in the world.","mundo"],
 "would": ["💬","grammar","What would you like to drink?","(condicional)"],
}


# ----------------------------------------------------------------------- FLYERS
FLYERS = {
 "a little": ["💬","grammar","There is only a little milk left.","un poco"],
 "across": ["💬","grammar","We walked across the bridge.","al otro lado de, a través de"],
 "act": ["🎭","actions","She wants to act in a film.","actuar"],
 "actually": ["💬","grammar","Actually, my birthday is in July, not June.","en realidad"],
 "ago": ["⏪","time","We moved here two years ago.","hace (tiempo)"],
 "air": ["💨","world","Whales come up for air.","aire"],
 "alone": ["🧍","describing","He walked home alone.","solo"],
 "also": ["💬","grammar","Oliver has also got a headache.","también"],
 "amazing": ["🤩","describing","The waterfall was amazing!","asombroso, increíble"],
 "anyone": ["🙋","grammar","Is anyone in the kitchen?","alguien"],
 "anything": ["📦","grammar","He did not say anything about it.","algo, nada"],
 "appear": ["👀","actions","A rainbow can appear after the rain.","aparecer"],
 "as": ["💬","grammar","He works as a doctor in the hospital.","como"],
 "as … as": ["💬","grammar","Our snowman is as tall as my sister.","tan… como"],
 "away": ["💬","grammar","The bird flew away.","lejos, fuera"],
 "backpack (UK rucksack)": ["🎒","clothes","My backpack is full of books.","mochila"],
 "bank": ["🏦","places","Mum keeps her money in the bank.","banco"],
 "begin": ["🚦","actions","The film begins at eight.","empezar"],
 "believe": ["🤔","actions","You will not believe this story!","creer"],
 "biscuit (US cookie)": ["🍪","food","Would you like a biscuit with your tea?","galleta"],
 "bit": ["💬","grammar","It is a bit dark in here.","un poco"],
 "borrow": ["📚","actions","Can I borrow your pencil, please?","pedir prestado"],
 "brush": ["🪮","home","Brush your hair before school.","cepillo; cepillar"],
 "businessman/woman": ["💼","work","My uncle is a businessman in the city.","hombre / mujer de negocios"],
 "butterfly": ["🦋","animals","A butterfly landed on the flower.","mariposa"],
 "camel": ["🐪","animals","A camel can live in the desert.","camello"],
 "camp": ["⛺","places","Our camp is next to the waterfall.","campamento"],
 "chemist('s)": ["💊","places","Buy the medicine at the chemist’s.","farmacia"],
 "comb": ["💇","home","Use a comb for your hair.","peine"],
 "competition": ["🏆","sports","We have won the competition!","concurso, competición"],
 "concert": ["🎼","music","The concert starts at seven.","concierto"],
 "conversation": ["🗣️","school","We had a long conversation about animals.","conversación"],
 "cookie (UK biscuit)": ["🍪","food","Grandma made chocolate cookies.","galleta"],
 "could (for possibility)": ["💬","grammar","You could invite Robert to the game.","podrías"],
 "crown": ["👑","world","The queen is wearing a gold crown.","corona"],
 "date (as in time)": ["📅","time","What is the date today?","fecha"],
 "dear (as in Dear Harry)": ["💌","expressions","Dear Grandma, we are all well.","querido, querida"],
 "decide": ["🤔","actions","Let us decide before lunch.","decidir"],
 "delicious": ["😋","describing","This soup is delicious!","delicioso"],
 "desert": ["🏜️","world","Camels live in the desert.","desierto"],
 "design": ["✏️","actions","Design a poster for the show.","diseñar"],
 "diary": ["📓","school","I write in my diary every night.","diario, agenda"],
 "dinosaur": ["🦖","animals","There is a new dinosaur room in the museum.","dinosaurio"],
 "drum": ["🥁","music","He plays the drums in a band.","tambor"],
 "during": ["💬","grammar","It rained during the match.","durante"],
 "each": ["💬","grammar","Two people each, please.","cada uno"],
 "else": ["💬","grammar","What else would you like to draw?","más, otra cosa"],
 "enormous": ["🐘","describing","What an enormous rocket!","enorme"],
 "enter (a competition)": ["🏅","sports","Will you enter the swimming competition?","participar en"],
 "entrance": ["🚪","places","Maya is waiting at the school entrance.","entrada"],
 "everywhere": ["🌍","grammar","There were leaves everywhere.","por todas partes"],
 "excellent": ["⭐","describing","I make excellent banana pancakes.","excelente"],
 "explain": ["🗣️","actions","Can you explain it again, please?","explicar"],
 "explore": ["🧭","actions","We want to explore the island.","explorar"],
 "far": ["💬","grammar","The beach is not far from our house.","lejos"],
 "fast": ["⚡","describing","The song is just too fast.","rápido"],
 "feel": ["🫀","actions","How do you feel today?","sentirse"],
 "find out": ["🔎","actions","Let us find out who won!","averiguar"],
 "flag": ["🏳️","world","There is a flag on top of the building.","bandera"],
 "flashlight (UK torch)": ["🔦","home","Take a flashlight into the cave.","linterna"],
 "follow": ["👣","actions","Follow me to the museum!","seguir"],
 "front": ["💬","grammar","Maya is at the front of the school.","el frente, delante"],
 "full": ["🧳","describing","My backpack is full of books.","lleno"],
 "go out": ["🚪","actions","We go out for a walk after dinner.","salir"],
 "group": ["👥","school","A group of players who play together.","grupo"],
 "half": ["🕐","time","We meet at half past two.","media, mitad"],
 "happen": ["❓","actions","What happened after the storm?","pasar, ocurrir"],
 "hard": ["🪨","describing","This question is very hard.","difícil; duro"],
 "hear": ["👂","actions","I cannot hear you. Speak louder!","oír"],
 "high": ["⬆️","describing","The kite is very high in the sky.","alto"],
 "hole": ["🕳️","world","There is a dark hole in the mountain.","agujero"],
 "hour": ["⏱️","time","The journey takes one hour.","hora"],
 "how long": ["💬","grammar","How long does the film take?","cuánto tiempo"],
 "important": ["❗","describing","This is important news.","importante"],
 "interesting": ["🧐","describing","Choose interesting questions!","interesante"],
 "invent": ["💡","actions","Erik wants to invent a new machine.","inventar"],
 "job": ["💼","work","My father has got a new job in the city.","trabajo, oficio"],
 "July": ["📅","time","We go to the beach in July.","julio"],
 "June": ["📅","time","My birthday was in June.","junio"],
 "Katy": ["👧","names","Her name is Katy, K-A-T-Y.","Katy (nombre de niña)"],
 "keep": ["📦","actions","Keep the score on this paper.","guardar, quedarse con"],
 "key": ["🔑","home","I cannot find the key to the front door.","llave"],
 "king": ["🤴","world","The king lived in a castle.","rey"],
 "land": ["✈️","actions","Where did the plane land?","aterrizar; tierra"],
 "let": ["💬","grammar","Let me help you with that bag.","dejar, permitir"],
 "lie (as in lie down)": ["🛏️","actions","Lie down and close your eyes.","tumbarse, acostarse"],
 "London": ["🇬🇧","places","My cousin lives in London.","Londres"],
 "look like": ["👀","describing","What does your new teacher look like?","parecerse a"],
 "lovely": ["😊","describing","What a lovely garden!","precioso, encantador"],
 "low": ["⬇️","describing","A low white cloud sat on the hill.","bajo"],
 "lucky": ["🍀","describing","You are lucky! You won the game.","con suerte, afortunado"],
 "match (football)": ["⚽","sports","Did they win the match?","partido"],
 "meal": ["🍽️","food","Dinner is my favourite meal.","comida (del día)"],
 "meeting": ["👥","work","The meeting is closed. See you tomorrow!","reunión"],
 "middle": ["💬","grammar","It started to rain in the middle of our song.","en medio de"],
 "million": ["💯","time","There are a million stars in the sky.","millón"],
 "missing": ["❓","describing","One page of the book is missing.","que falta, perdido"],
 "money": ["💰","work","I keep my money in my pocket.","dinero"],
 "month": ["📅","time","March is the third month.","mes"],
 "much": ["💬","grammar","Much better, thanks!","mucho"],
 "necklace": ["📿","clothes","She is wearing a gold necklace.","collar"],
 "nest": ["🪹","animals","There are three eggs in the nest.","nido"],
 "newspaper": ["📰","school","Dad reads the newspaper at breakfast.","periódico"],
 "next": ["💬","grammar","The bank is next to the museum.","al lado de; siguiente"],
 "of course": ["💬","expressions","Of course you can come with us!","por supuesto"],
 "Oliver": ["👦","names","This guitar is Oliver’s.","Oliver (nombre de niño)"],
 "other": ["💬","grammar","Do you agree with each other?","otro"],
 "pajamas (UK pyjamas)": ["🛌","clothes","He was still in his pajamas at ten!","pijama"],
 "pizza": ["🍕","food","What do you put on your pizza?","pizza"],
 "post": ["📮","tech","Kili brings the post every morning.","correo; enviar"],
 "prepare": ["🍳","actions","We prepare the picnic on Friday night.","preparar"],
 "problem": ["❗","school","We have got a small problem with the bus.","problema"],
 "project": ["📐","school","Our class project is about the sea.","proyecto"],
 "pyjamas (US pajamas)": ["🛌","clothes","Put on your pyjamas and go to bed.","pijama"],
 "queen": ["👸","world","The queen lived in the old castle.","reina"],
 "quite": ["💬","grammar","The film was quite good.","bastante"],
 "quiz": ["❓","school","Quiz time! Six questions each.","concurso de preguntas"],
 "racing (car; bike)": ["🏎️","sports","He has got a red racing bike.","de carreras"],
 "rucksack (US backpack)": ["🎒","clothes","You carry a rucksack on your back.","mochila"],
 "same": ["💬","grammar","We have got the same jacket!","el mismo, igual"],
 "scissors": ["✂️","school","Cut the paper with the scissors.","tijeras"],
 "should": ["💬","grammar","Should we take a towel to the pool?","debería"],
 "since": ["💬","grammar","I have lived here since I was five.","desde"],
 "soft": ["🪶","describing","This blanket is very soft.","suave, blando"],
 "somewhere": ["📍","grammar","I put my key somewhere in this room!","en alguna parte"],
 "special": ["⭐","describing","Today is a special day: it is my birthday!","especial"],
 "spend": ["💸","actions","I spend my money on books.","gastar; pasar (tiempo)"],
 "spoon": ["🥄","food","Add a small spoon of salt.","cuchara"],
 "spot": ["🟤","describing","This dog has got black spots.","mancha, lunar"],
 "strange": ["👽","describing","What a strange dream!","extraño, raro"],
 "strawberry": ["🍓","food","Sometimes I have strawberry jam.","fresa"],
 "student": ["🧑‍🎓","school","Every student in my class has got a diary.","alumno, estudiante"],
 "study": ["📖","school","I study English every evening.","estudiar"],
 "summer": ["☀️","time","In summer the days are long.","verano"],
 "take (as in time, e.g. it takes 20 minutes)": ["⏱️","time","The journey takes twenty minutes.","tardar, llevar"],
 "taste": ["👅","actions","This soup does not taste like fish.","saborear; sabor"],
 "telephone": ["☎️","tech","Can I use your telephone, please?","teléfono"],
 "thank": ["🙏","expressions","Thank you, Maya!","dar las gracias"],
 "thousand": ["🔢","time","A thousand people came to the concert.","mil"],
 "tomorrow": ["📅","time","Will it rain tomorrow?","mañana"],
 "tonight": ["🌙","time","I will tell you tonight.","esta noche"],
 "torch (US flashlight)": ["🔦","home","I have already put in my torch and my camera.","linterna"],
 "tortoise": ["🐢","animals","The tortoise walks very slowly.","tortuga"],
 "touch": ["☝️","actions","You can touch it! It is soft.","tocar"],
 "tour": ["🗺️","transport","We went on a tour of the old town.","recorrido, gira"],
 "turn": ["↪️","actions","Turn left at the bridge.","girar; turno"],
 "tyre (US tire)": ["🛞","transport","My bike has got a flat tyre.","neumático, llanta"],
 "until": ["💬","grammar","We waited until four o'clock.","hasta"],
 "use": ["🔧","actions","Use a spoon for the soup.","usar"],
 "violin": ["🎻","music","She plays the violin in the school concert.","violín"],
 "warm": ["🧣","describing","This coat is warm. Put it on!","cálido, abrigado"],
 "way": ["💬","grammar","Which way is the museum?","camino, manera"],
 "wheel": ["🎡","transport","I rode the big wheel three times!","rueda"],
 "while": ["💬","grammar","He often sings while he flies.","mientras"],
 "wild": ["🐅","animals","Tigers are wild animals.","salvaje"],
 "will": ["💬","grammar","Will you do your homework this evening?","(futuro)"],
 "win": ["🏆","sports","Did they win the match?","ganar"],
 "wing": ["🪶","animals","The bird hurt its wing.","ala"],
 "winter": ["❄️","time","She wears this coat every winter.","invierno"],
 "without": ["💬","grammar","She cannot read without her glasses.","sin"],
 "you’re welcome": ["🙏","expressions","Thank you! — You’re welcome.","de nada"],
}
